### ISSUE TITLE
Data Mapping

### ISSUE THREAD

**Issue by ctatineni** [spring-projects/spring-integration#1724]
Are there any data Mapping tools available for Spring Integration?

**Comment by artembilan** [comment]
Hello, @ctatineni !

Please, be more specific in the subject.

Shortly: no, Spring Integration don't have any Data Mapping tool.
But from other hand: should it?

The purpose of the Data Mapping tool (from big height) is to provide some visual designer which allows via drag-and-drop feature to build some template to map data type from the left to data type on the right.

But... Is that a responsibility of Spring Integration, which implements (EIP)[http://www.enterpriseintegrationpatterns.com/]?

Right, Spring Integration can use the result of such a tool from its Transformers or Service Activator, but the tool is really out of Spring Integration scope.

Or we talk about different topics...
