### ISSUE TITLE
Gateway for High volume applications

### ISSUE THREAD

**Issue by ctatineni** [spring-projects/spring-integration#1732]
Is it recommended to use outbound gateway with Cached connection factory for high volume applications?

**Comment by artembilan** [comment]
Hello, @ctatineni !

Looks like it is a question, not an issue with the Framework, or not even improvement suggestion.

for similar cases it would be better to ask questions on the [StackOverflow](http://stackoverflow.com).

And please, provide as much details and context for the problem as possible.
Right now your question is fully unclear.

Closing as invalid.

Thanks for your patience!
