### ISSUE TITLE
Code style conventions defining 

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration#1757]
At this moment code style conventions are defined at `Mind the whitespace` and `Add Apache license header to all new classes` chapters here
https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc
and here
https://github.com/spring-projects/spring-integration-extensions/wiki/Contributor-Guidelines
May be another Spring projects have them separately too.

So,

1. Add to this documentation links to code conventions for [InteglliJ IDEA](https://github.com/spring-projects/spring-framework/tree/master/src/idea) and [Eclipse](https://github.com/spring-projects/spring-framework/tree/master/src/eclipse)

2. Add import optimization rules to default settings' files
![393c7440-f828-11e5-802b-e75139f9a5a9](https://cloud.githubusercontent.com/assets/1883572/14324946/1c1c1a66-fbf5-11e5-9ddc-b9f2bc6a8cc3.jpg)

3. Add convention to have empty line at the end of any source files

3. (optionally) Use InteglliJ IDEA ability to host and share centralized source of conventions and settings (see [Settings Repository](https://www.jetbrains.com/help/idea/2016.1/settings-repository.html) feature). So any change of the rules will affect InteglliJ IDEA IDEs automatically.

**Comment by englishman** [comment]
Also field value **Code Style/Java/General/Names count to use static import with '*'** is 1. It's incorrect due to https://github.com/spring-projects/spring-integration-extensions/pull/159#discussion_r58327115

**Comment by artembilan** [comment]
See #1758 and https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-Framework-Code-Style.

I have took a look briefly to the IDEA Settings Repository feature. And the result is here: https://github.com/artembilan/IDEA-Settings.
Not sure that I would like to share that my "hell" with the community...

That's all.
Cheers!

**Comment by artembilan** [comment]
> Also field value Code Style/Java/General/Names count to use static import with '*' 

That is an IDEA specific option. I'm sure in the Eclipse it's something different.
I have just added a general note in the target Code Style Doc:

> Plus no one asterisk (*) import is allowed.
