### ISSUE TITLE
Provide the ability to configure allowed origins in ServerWebSocketContainer

### ISSUE THREAD

**Issue by DzmitryShylovich** [spring-projects/spring-integration#1813]
There is no way to intercept creation of WebSocketHandlerRegistration inside `registerWebSocketHandlers()` method and configure allowed origins as described [here](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-server-allowed-origins), so clients on another host/port cannot connect to the server and receive messages.

https://github.com/spring-projects/spring-integration/blob/master/spring-integration-websocket/src/main/java/org/springframework/integration/websocket/ServerWebSocketContainer.java#L119

```
@Override
	public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
		WebSocketHandler webSocketHandler = this.webSocketHandler;

		if (this.decoratorFactories != null) {
			for (WebSocketHandlerDecoratorFactory factory : this.decoratorFactories) {
				webSocketHandler = factory.decorate(webSocketHandler);
			}
		}

		WebSocketHandlerRegistration registration = registry.addHandler(webSocketHandler, this.paths)
				.setHandshakeHandler(this.handshakeHandler)
				.addInterceptors(this.interceptors);
}
```

Possible solutions might be to create method `setAllowedOrigins(String ...origins)` or create WebSocketHandlerRegistrationDecorator.

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/INT-4039
