### ISSUE TITLE
WebSocketStompSessionManager calls incorrect method on WebSocketStompClient

### ISSUE THREAD

**Issue by seanmmills** [spring-projects/spring-integration#1820]
The WebSocketStompSessionManager.connect is dispatching to the wrong method on the WebSocketStompClient.  It's not failing compile because of a method signature with a variable-length argument list of Object.  It is resolving to the method:

`public ListenableFuture<StompSession> connect(String url, StompSessionHandler handler, Object... uriVars) {`

However, it should resolve to the method:

`public ListenableFuture<StompSession> connect(String url, WebSocketHttpHeaders handshakeHeaders, StompHeaders connectHeaders, StompSessionHandler handler, Object... uriVariables) {`

**Comment by artembilan** [comment]
https://jira.spring.io/browse/INT-4044 for the history and tracking.
