### ISSUE TITLE
README says Eclipse can open all the projects but spring-integration-test is broken for me

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-integration#1824]
There's an access problem with the heap dumper and Eclipse won't build spring-integration-test until I explicitly tell it to ignore access violations (in the compiler config preferences).

**Comment by garyrussell** [comment]
Yeah - I saw that recently - I am leaning towards removing it, or commenting it out rather than spending a lot of time/energy trying to figure out how to "fix" it.
