### ISSUE TITLE
Spring Mail inline images doesn't work in Mac Mail

### ISSUE THREAD

**Issue by yanshuai** [spring-projects/spring-integration#1826]
When I use Spring to send mail inline images, I found it doesn't show image in Mac Mail App, but it shows it in web Zimbra. My code is as follows, what's wrong with it?
```java
JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
mailSender.setDefaultEncoding("UTF-8");
mailSender.setHost(Consts.MAIL_HOST);
mailSender.setUsername(Consts.MAIL_USER);
mailSender.setPassword(Consts.MAIL_PASSWORD);
MimeMessage msg = mailSender.createMimeMessage();
MimeMessageHelper helper = new MimeMessageHelper(msg, true, "UTF-8");
helper.setFrom(mailSender.getUsername());
InternetAddress[] addresses = InternetAddress.parse("sartisty@gmail.com");
helper.setTo(addresses);
helper.setSubject("test");
helper.setText("<html><body><img src='cid:identifier1234'></body></html>", true);
FileSystemResource res = new FileSystemResource(new File("/Users/yanshuai/widget-ca3dc599-9c30-43de-9a2d-b62903301b59.png"));
helper.addInline("identifier1234", res);
mailSender.send(msg);
```

**Comment by artembilan** [comment]
I don't find that it is Spring Integration problem.
Please, be sure that you don't have any problem with your Mac Mail App.
Check this forum, for example: https://discussions.apple.com/message/22622495#22622495

I found there some answer like:
> Sorted.

> Quit Mail

> Open Terminal.

>paste this in and press return

> `defaults write com.apple.mail DisableInlineAttachmentViewing -bool NO`

Look! There is nothing about Spring Integration.

Let us know how it is going and we'll close the issue as an invalid.

**Comment by artembilan** [comment]
Closed as non-related to Spring Integration and with the lack of reported response.
