### ISSUE TITLE
Problems with Thread State Propagation when using a publish subscribe channel with apply sequence = true

### ISSUE THREAD

**Issue by alejandroMartin** [spring-projects/spring-integration#1847]
Hi,

We are using spring integration and we would like to propagate thread state with publish subscribe channel, but unfortunately we cannot make it work. We use a `PublishSubscribe` channel with `Executors.newCachedThreadPool()`.

`ThreadStatePropagationChannelInterceptor` creates a `MessageWithThreadState` object with the custom thread context data, but it seems that the `BroadcastingDispatcher` instances a new `GenericMessage` using the `1MessageBuilder`. So, the `threadStatePropagationChannelInterceptor` cannot populate the new thread context because it does not recognize the new `GenericMessage`.

If we use apply `sequence = false`, it works correctly.

**Comment by artembilan** [comment]
Looks like a bug, but would you mind to share some config and test-case to play from our side.

Thank you!

**Comment by alejandroMartin** [comment]
I have developed an integration test that shows the problem using the SecurityContext  https://github.com/serenity-devstack/spring-integration/commit/0863239252f05ff869bee994a0f75fe1f0ef3b21

**Comment by artembilan** [comment]
Confirmed. 
See https://jira.spring.io/browse/INT-4072
Thank you for catching that!
