### ISSUE TITLE
The controlEncoding setting in AbstractFtpSessionFactory is not effective

### ISSUE THREAD

**Issue by GodIsDevil** [spring-projects/spring-integration#1915]
The controlEncoding setting in AbstractFtpSessionFactory happens after the ftp client connects to it's server.But in the docs of  org.apache.commons.net.ftp.FTP it says that this has to be set before the connection is established.
![ftp](https://cloud.githubusercontent.com/assets/16829588/18946805/206a6700-8663-11e6-9419-a73f0ad781d8.png)

**Comment by garyrussell** [comment]
Thanks; I opened a [JIRA Issue](https://jira.spring.io/browse/INT-4128) for this.
