### ISSUE TITLE
jdbc inbound adapter with 'role' attribute should not auto-start

### ISSUE THREAD

**Issue by bliessens** [spring-projects/spring-integration#1928]
Hi,

I have an application with a jdbc inboud channel adapter. The app is clustered and the <int-jdbc:inbound-channel-adapter/> should only be executed on 1 instance at any time. So I have added the role="integrator" attribute and I added SI Zookeeper to the app to perform leadership election. 
Now it seems all the <int-jdbc:inbound-channel-adapter/> ais started even before leadership election is performed. I would have expected the role attribute would imply auto-start="false" but it doesn't. Either this is a bug or a least something that should be documented.

**Comment by garyrussell** [comment]
Hi, yes, `autoStart` is completely independent of the role; in fact, the adapter doesn't even know anything about the role it is in.

I agree that we should make that clear in the documentation.
