### ISSUE TITLE
imap-idle-channel-adapter with mail-filter-expression doesn't mark messages as RECENT

### ISSUE THREAD

**Issue by cyterdan** [spring-projects/spring-integration#1935]
I'm looking to filter email messages containing '+' in the recipient address.
I have setup this adapter  : 
```
    <int-mail:imap-idle-channel-adapter id="gmailAdapter"
                                        store-uri="${gmail.protocole}://${gmail.account}:${gmail.password}@${gmail.imap.server}:${gmail.imap.port}/inbox"
                                        channel="mailbox-receive"
                                        auto-startup="false"
                                        should-delete-messages="false"
                                        should-mark-messages-as-read="true"
                                        java-mail-properties="javaMailProperties"
                                        mail-filter-expression="allRecipients[0].address matches '.*+.*@.*'"

    >
```

according to the documentation (http://docs.spring.io/spring-integration/reference/html/mail.html#mail-filtering) , messages who are not filtered, should have the RECENT flag unset. 

The filter works correctly but I see in the logs the adapter keeps polling the inbox every 2 secondes if a new message doesn't match the filter

**Comment by artembilan** [comment]
You should be sure that your mail server support `RECENT` flag on the folder:

> Another reasonable question is what happens on the next poll, or idle event, or what happens when such adapter is restarted. Will there be a potential duplication of massages to be filtered? In other words if on the last retrieval where you had 5 new messages and only 1 passed the filter what would happen with the other 4. Would they go through the filtering logic again on the next poll or idle? After all they were not marked as SEEN. The actual answer is no. They would not be subject of duplicate processing due to another flag (RECENT) that is set by the Email server and is used by Spring Integration mail search filter. Folder implementations set this flag to indicate that this message is new to this folder, that is, it has arrived since the last time this folder was opened. In other while our adapter may peek at the email it also lets the email server know that such email was touched and therefore will be marked as RECENT by the email server.

Do you see something like this in your logs:
```
if (folder.getPermanentFlags().contains(Flags.Flag.USER)) {
	logger.debug("This email server does not support RECENT flag, but it does support " +
			"USER flags which will be used to prevent duplicates during email fetch." +
			" This receiver instance uses flag: " + getUserFlag());
	Flags siFlags = new Flags();
	siFlags.add(getUserFlag());
	notFlagged = new NotTerm(new FlagTerm(siFlags, true));
}
else {
	logger.debug("This email server does not support RECENT or USER flags. " +
			"System flag 'Flag.FLAGGED' will be used to prevent duplicates during email fetch.");
			notFlagged = new NotTerm(new FlagTerm(new Flags(Flags.Flag.FLAGGED), true));
}
```
Of course you should switch on `DEBUG` for the `org.springframework.integration` category.

**Comment by cyterdan** [comment]
I see the first log(I'm using gmail so the RECENT flag is not supported, only the USER flags).

Is the user flag set only after filtering ?

**Comment by cyterdan** [comment]
Ended up adding another adapter to move messages not handled by the first filter. closing as this is not a bug.
