### ISSUE TITLE
ArrayStoreException when using @ServiceActivator and nested object in payload

### ISSUE THREAD

**Issue by Kavenon** [spring-projects/spring-integration#1954]
What I'm trying to achieve is to send object BeaconDiscoverEvent to queue, then receive it in consumer.
BeaconDiscoverEvent looks like this:
`private String uuid;  
private Beacon beacon;`

Beacon is also POJO object, that contains only integers and strings.

When I send this object, I get ArrayStoreException while executing toString method of BeaconDiscoverEvent (inside consumer). I think there's some recursion problem (see screenshot), because uuid is supposed to be string.

![image](https://cloud.githubusercontent.com/assets/7526374/19835261/a6c9de18-9e80-11e6-9fac-89c5c9bdb334.png)

Funny thing is, that if I remove uuid field from event, everything works. Also if I keep uuid field and remove beacon field it works too.

For now I've changed `@ServiceActivator` to `@StreamListener`, added contentType: application/json in producer and now it's working, but kryo is not used, so just plain json is sent.

Spring Boot: 1.4.1.RELEASE
BOM: Camden.RELEASE

**Comment by artembilan** [comment]
Would be better to have some simple Boot application to play from our side. Or at least have some config and a full stack trace to analyze.

Such a description doesn't prove that there is some problem in Spring Integration...

**Comment by Kavenon** [comment]
Well.. I'm sorry for bothering you.
I tried to create much simpler project to show you the problem. It turned out that, object being sent to queue has to have exacly the same fields in the consumer (in my case object inside consumer had less fields than in producer). 

This is my bad. Next time I'll start with creating simple application.

**Comment by garyrussell** [comment]
No problem; thanks for following up!
