### ISSUE TITLE
SerializingHttpMessageConverter ignores setSupportedMediaTypes

### ISSUE THREAD

**Issue by eahamada** [spring-projects/spring-integration#1982]
Hello,

It seems in RestTemplate.HttpEntityRequestCallback.doWithRequest(ClientHttpRequest httpRequest), SerializingHttpMessageConverter.canWrite(Class<?> clazz, MediaType mediaType) is called and throws RestClientException("no suitable converter ..."), even though I added MediaType using setSupportedMediaTypes.

As of spring-integration-http-4.3.4, canWrite ignores setSupportedMediaTypes and only checks mediaType is included in APPLICATION_JAVA_SERIALIZED_OBJECT : 
```java
@Override
public boolean canWrite(Class<?> clazz, MediaType mediaType) {
  return (Serializable.class.isAssignableFrom(clazz) && APPLICATION_JAVA_SERIALIZED_OBJECT.includes(mediaType));
}
```

I suggest this workaround :
```java
  @Override
  public boolean canWrite(Class<?> clazz, MediaType mediaType) {
    if (Serializable.class.isAssignableFrom(clazz)) {
      for (MediaType mt : getSupportedMediaTypes()) {
        if (mt.includes(mediaType)) {
          return true;
        }
      }
    }
    return false;
  }
```

**Comment by garyrussell** [comment]
Can you explain what media type you are setting? This converter is intended to support `application/x-java-serialized-object` only.

Since it only supports java serialization, I suppose it could/should have rejected your attempt to add a different contentType; are you using some non-standard contentType which actually means it's still java deserialization that's required?

**Comment by eahamada** [comment]
unfortunately, I dont control expected contentType, which is "application/octet-stream".

**Comment by eahamada** [comment]
That's what I meant. 
It is odd indeed. I did customize the converter and override canWrite().
I just found it odd that you can `setSupportedMediaTypes` but cannot write entity.
Please close issue until someone finds more convincing arguments :)

**Comment by garyrussell** [comment]
Thanks; closed in favor of [INT-4172](https://jira.spring.io/browse/INT-4172).
