### ISSUE TITLE
how to use .done to read file in diractory?

### ISSUE THREAD

**Issue by opticaline** [spring-projects/spring-integration#1998]
i have test.txt in diractory,
only when test.txt.done or test.done file in diractory start reading test.txt.

**Comment by artembilan** [comment]
I'm not sure in what context you mean.

Would you mind to shad more light what's going on? 

OTOH the StackOverflow is a place for similar questions. 

GH issues and JIRA are for bug tickets or new requests.

**Comment by garyrussell** [comment]
You need to use a custom `FileListFilter` that filters files that don't have the appropriate `.done` file present.

**Comment by opticaline** [comment]
@garyrussell 
Hi, this is my filter.
`
private final AntPathMatcher matcher = new AntPathMatcher();

    private String doneFile = ".done";
    private String pattern;

    public DoneFileFilter(String pattern, String doneFile) {
        this.pattern = pattern;
        this.doneFile = doneFile.startsWith(".") ? doneFile : "." + doneFile;
    }

    @Override
    public List<File> filterFiles(File[] files) {
        List<File> fileList = new ArrayList<>();
        for (File file : files) {
            System.out.println(file);
            String name = file.getName();
            if (matcher.match(pattern, name)) {
                File f = new File(file.getParent(), name + doneFile);
                if (f.exists()) {
                    fileList.add(f);
                }
            }
        }
        System.out.println(fileList);
        return null;
    }
`

but is now working.
Is there anything I do wrong?

**Comment by garyrussell** [comment]
I assume you mean __not__ not __now__.

On the face of it, it looks ok to me; you need to debug it. If you can't figure it out, you need to show all your configuration.

**Comment by opticaline** [comment]
@garyrussell 
Hi, this is my full configuration.

```
@SpringBootApplication
public class FileReadingJavaApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(FileReadingJavaApplication.class)
                .web(false)
                .run(args);
    }

    @Bean
    public IntegrationFlow fileReadingFlow() {
        return IntegrationFlows
                .from(s -> s.file(new File("D:\\data\\input"))
                                .useWatchService(true).watchEvents(FileReadingMessageSource.WatchEventType.CREATE)
                                .filter(new DoneFileFilter("*.txt", "ok")),
                        e -> e.poller(Pollers.fixedDelay(1000)))
                .split(new FileSplitter(true))
                .handle(new GenericHandler<Object>() {
                    @Override
                    public Object handle(Object payload, Map<String, Object> headers) {
                        System.out.println(payload.getClass());
                        System.out.println(payload);
                        return null;
                    }
                })
                .get();
    }
}
```
It looks like it ignores the return value contained in the non-passed parameter of the filter.

**Comment by artembilan** [comment]
Would you mind explaining why your filter returns `null` but not `fileList`?

**Comment by garyrussell** [comment]
Good catch, @artembilan I didn't notice that.

**Comment by opticaline** [comment]
@artembilan @garyrussell 
Sorry, i put a test version on this, i change the comment already. but is't still now work.
When directory has file 1.txt, i start app.console output like this.

D:\data\input\1.txt
[]
 _**// put file 1.txt.ok in directory**_ 
D:\data\input\1.txt.ok
[D:\data\input\1.txt]
[]
[]

**Comment by garyrussell** [comment]
By default, your filter is added to a `CompositeFileListFilter`, along with an `AcceptOnceFileListFilter`.

Add `.preventDuplicates()` to the file adapter spec to disable this, but unless you remove the files after processing, it will be processed again on the next poll.

**Comment by artembilan** [comment]
> along with an AcceptOnceFileListFilter

No, it isn't.

I've just tested your use-case and the problem looks like is tied with the `FileReadingMessageSource.WatchEventType.CREATE`

**Comment by garyrussell** [comment]
Ah - didn't notice he was using watch events.

You should be able to change you pattern to pass the `.ok` file and use its event to populate the result with the plain file.

**Comment by artembilan** [comment]
Looks like it won't help, Gary. Look into `CompositeFileListFilter` logic around `retain`.

**Comment by artembilan** [comment]
I think you really have to care about `FileReadingMessageSource.WatchEventType.MODIFY` event type as well.

Since logically `.done` file appears only after the final modification to the original file, that would be correct to track such an event as well to let `CompositeFileListFilter` to pass the original file together with the `.done`.
OTOH the regular `FileReadingMessageSource` (without `WatchService`) should work as is.

**Comment by garyrussell** [comment]
I don't think you can rely on that - there's a race condition between the last modify and the arrival of the `.done` file. I don't think using the watch service will work reliably here.

**Comment by opticaline** [comment]
i remove watch service and append preventDuplicates, but still now working.
```
@Bean
    public IntegrationFlow fileReadingFlow() {
        return IntegrationFlows
                .from(s -> s.file(new File("D:\\data\\input"))
                                .preventDuplicates(true)
                                .filter(new DoneFileFilter("*.txt", "ok")),
                        e -> e.poller(Pollers.fixedDelay(1000)))
                .split(new FileSplitter(true))
                .handle(new GenericHandler<Object>() {
                    @Override
                    public Object handle(Object payload, Map<String, Object> headers) {
                        System.out.println(payload.getClass());
                        System.out.println(payload);
                        return null;
                    }
                })
                .get();
    }
```

**Comment by artembilan** [comment]
Eh... I see sorry.
You have to do something like this:
````java
	@Bean
	public IntegrationFlow fileReadingFlow() {
		AcceptOnceFileListFilter<File> acceptOnceFileListFilter = new AcceptOnceFileListFilter<>();
		CompositeFileListFilter<File> compositeFileListFilter = new CompositeFileListFilter<>(
				Arrays.asList(acceptOnceFileListFilter,
						new DoneFileFilter("*.txt", "ok", acceptOnceFileListFilter)));
		return IntegrationFlows
				.from(s -> s.file(new File("/tmp/in"))
						.filter(compositeFileListFilter),
						e -> e.poller(Pollers.fixedDelay(1000)))
				.split(Files.splitter())
				.handle(System.out::println)
				.get();
	}

	private static class DoneFileFilter implements FileListFilter<File> {

		private final AntPathMatcher matcher = new AntPathMatcher();

		private String doneFile;

		private final ResettableFileListFilter<File> resettableFileListFilter;

		private String pattern;

		public DoneFileFilter(String pattern, String doneFile,
				ResettableFileListFilter<File> resettableFileListFilter) {
			this.pattern = pattern;
			this.doneFile = doneFile.startsWith(".") ? doneFile : "." + doneFile;
			this.resettableFileListFilter = resettableFileListFilter;
		}

		@Override
		public List<File> filterFiles(File[] files) {
			List<File> fileList = new ArrayList<>();
			for (File file : files) {
				String name = file.getName();
				if (matcher.match(pattern, name)) {
					File f = new File(file.getParent(), name + doneFile);
					if (f.exists()) {
						fileList.add(file);
					}
					else {
						this.resettableFileListFilter.remove(file);
					}
				}
			}
			System.out.println(fileList);
			return fileList;
		}

	}
````
Pay attention how I create a `compositeFileListFilter` and how I use `this.resettableFileListFilter.remove(file);` in the `DoneFileFilter`.

The problem with those filter combination that `CompositeFileListFilter` doesn't care about each filter result during iteration:
```
public List<F> filterFiles(F[] files) {
		Assert.notNull(files, "'files' should not be null");
		List<F> results = new ArrayList<F>(Arrays.asList(files));
		for (FileListFilter<F> fileFilter : this.fileFilters) {
			List<F> currentResults = fileFilter.filterFiles(files);
			results.retainAll(currentResults);
		}
		return results;
	}
```
Pay attention how it `retainAll()` from the original `files`. That's how any new file from the filter doesn't help, because we can't retain it in the result - nothing to retain for it. Therefore all the original files are removed.

Another concern which is pretty visible with the `AcceptOnceFileListFilter` involved, that `CompositeFileListFilter` don't care about previous filter result and just passes all original files to the next filter. In this case `AcceptOnceFileListFilter` just stores it in its internal cache, but doesn't pass to the output because of previous `retainAll()`.

I find this logic as a bit useless and wonder if we can reconsider it to a chain process when the next one does the stuff on the result of the previous one. This way we really combine filters logic to one valuable unit of work. 

@garyrussell , WDYT?

**Comment by garyrussell** [comment]
Yes, agreed, at least as an option.

**Comment by artembilan** [comment]
Well, something new `ChainFileListFilter` ? 😄

**Comment by artembilan** [comment]
The JIRA with similar problem: https://jira.spring.io/browse/INT-4215
