### ISSUE TITLE
DefaultSftpSessionFactory Seems Not Work, No Error, No Response

### ISSUE THREAD

**Issue by kexiuru** [spring-projects/spring-integration#2024]
**Using Version:** spring-integration-sftp-4.3.0.RELEASE
**Configuration as below:**

```
<bean id="defaultSessionFactory" class="org.springframework.integration.sftp.session.DefaultSftpSessionFactory">
		<property name="host" value="${sftp.host}" />
		<property name="privateKey" value="classpath:id_rsa" />
		<property name="user" value="${sftp.username}" />
		<property name="allowUnknownKeys" value="true" />
	</bean>
	<bean id="sftpSessionFactory" class="org.springframework.integration.file.remote.session.CachingSessionFactory">
		<constructor-arg ref="defaultSessionFactory" />
	</bean>
	<bean id="acceptOnceFilter" class="org.springframework.integration.file.filters.AcceptOnceFileListFilter" />
	
	
	<int:channel id="receiveChannel">
		<int:queue />
	</int:channel>
	
	<int-sftp:inbound-channel-adapter id="sftpInboundAdapter"
		auto-startup="true"
		channel="receiveChannel"
		session-factory="sftpSessionFactory" 
		remote-directory="${sftp.remote.input.dir}"
		filename-pattern="*.csv"
		local-directory="${sftp.local.ouput.dir}"
		local-filter="acceptOnceFilter">
		<int:poller fixed-rate="100"></int:poller>
	</int-sftp:inbound-channel-adapter>
```

Test Case code as below:

```
public class IntBatchTest  extends AbstractBatchTest {
	
	@Autowired
	private ApplicationContext context;

	@Test
	public void testBatchIntegration() {
		System.out.println("Start");
		PollableChannel receiveChannel = context.getBean("receiveChannel", PollableChannel.class);
		//SourcePollingChannelAdapter adapter = context.getBean(SourcePollingChannelAdapter.class);
		//adapter.start();
		
		System.out.println("ReceiveChannel:" + receiveChannel);
		receiveChannel.receive();
		System.out.println("End");
	}
}
```

When run this test case, no any error, no response, but keep running until you stop the process.

May I know if there is any configuration incorrect or the root cause?

**Comment by garyrussell** [comment]
If you enable DEBUG logging for `org.springframework.integration` you will get diagnostic log messages showing all activity.

If that doesn't help (for example, you see the polls, but no files are retrieved), enable logging for `Jsch` as well, as [explained in the documentation](http://docs.spring.io/spring-integration/reference/html/sftp.html#sftp-jsch-logging).

**Comment by artembilan** [comment]
Your program is blocked on the `receiveChannel.receive();`:
```
	/**
	 * Receive a message from this channel, blocking indefinitely if necessary.
	 * @return the next available {@link Message} or {@code null} if interrupted
	 */
	Message<?> receive();
```
So, if there is no any files on the remote dir, you don't have any messages to emit into the `receiveChannel`. And therefore nothing happens in your program.

The DEBUG is really your friend, as Gary pointed out already.

OTOH this kind of questions are subject for StackOverflow: http://stackoverflow.com/questions/tagged/spring-integration. 

GitHub and JIRA are really for confirmed bugs and new features or improvements requests.

**Comment by artembilan** [comment]
Closed with guidance above and with a lack of responsiveness from the reporter.
