### ISSUE TITLE
HTTP HEAD requests should not attempt to send payload

### ISSUE THREAD

**Issue by bkeyser** [spring-projects/spring-integration#2085]
When using an outbound channel adapter and the HTTP HEAD method, the HttpRequestExecutingMessageHandler through the AbstractHttpRequestExecutingMessageHandler is attempting to send the payload.  The shouldIncludeRequestBody() method should be updated to include a check for the HEAD method

```java
return !(HttpMethod.GET.equals(httpMethod) || HttpMethod.HEAD.equals(httpMethod))
```

**Comment by artembilan** [comment]
Why can't we do that?
What is the premise of such a limitation?
Is there some exception on the matter?

Just curious what made you to come to us with the issue.

Thanks

**Comment by bkeyser** [comment]
The problem I am trying to solve is to test the validity of a resource at an endpoint.  And perhaps my premise is wrong given the messaging construct?  I am very new to Spring Integration and so apologize in advance for any misunderstandings.

From the W3 HTTP specification

> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification.

Thus, if a HEAD request is supposed to be similar to a GET then the request should not have a body as part of the request.  While creating an integration test to test an IntegrationFlow the following error was generated

> org.springframework.web.client.RestClientException: Could not write request: no suitable HttpMessageConverter found for request type ...
	at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:892)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:650)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:549)
	at org.springframework.integration.http.outbound.HttpRequestExecutingMessageHandler.handleRequestMessage(HttpRequestExecutingMessageHandler.java:382)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)

...

**Comment by artembilan** [comment]
??? 
Some inconsistency in your expectations and what you provide.

From spec.
> that the server MUST NOT return a message-body in the response.

And your words:

>  then the request should not have a body as part of the request.

Your exception only says:

> no suitable HttpMessageConverter found for request type

I don't see any message there that HEAD can't have request body.

Your turn!

**Comment by garyrussell** [comment]
@artembilan HEAD is like GET, but only returns the headers.

[RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)

While the spec doesn't prohibit a GET (and hence HEAD) from containing a body; it doesn't really make sense. This [SO Answer](http://stackoverflow.com/questions/978061/http-get-with-request-body/983458#983458) is helpful.

**Comment by bkeyser** [comment]
While my language was not precise, @garyrussell reference explains the issue.  While a HEAD or GET request may have a body it is meaningless.  If meaningless, then an argument could be made that it should not be included.  Thanks for considering the request.

**Comment by artembilan** [comment]
Good.

Thank you both!
That is exactly what would be great to have from the beginning.
There must be some arguments to make a change.

Although I consider it as a bug, I don't think that we should backport to previous version because there might be some solutions relied on this bug.

Feel free, @bkeyser , to come back to us with the [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc)!

**Comment by garyrussell** [comment]
[INT-4242](https://jira.spring.io/browse/INT-4242).
