### ISSUE TITLE
TX bridge

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-integration#2106]
Could we add transactional property on bridge that would keep messages in transaction and forward it only on commit? Something like:

	public class StoreAndForward {
	
		private MessageChannel outputChannel;
	
		private TransactionSynchronization synchronization = new TransactionSynchronizationAdapter() {
			@Override
			@SuppressWarnings("unchecked")
			public void afterCommit() {
				Queue<Message<?>> messageQueue = (Queue<Message<?>>)TransactionSynchronizationManager.getResource(this);
				TransactionSynchronizationManager.unbindResource(this);
				while(!messageQueue.isEmpty()) {
					dispatch(messageQueue.poll());
				}
			}
		};
	
		public StoreAndForward(MessageChannel outputChannel){
			Assert.notNull(outputChannel, "'outputChannel' must not be null.");
			this.outputChannel = outputChannel;
		}
	
		@ServiceActivator
		public Message<?> storeAndForward(Message<?> message){
			if(TransactionSynchronizationManager.isActualTransactionActive()) {
				System.out.println("Active transaction, so schedule message release on commit.");
				storeAndScheduleForSendingAfterCommit(MessageBuilder.withPayload("Message").build());
				return null;	//return nothing as scheduled on commit
			}
			else{
				System.out.println("No active transaction - dispatch immediately.");
				return message;
			}
		}
	
		private void storeAndScheduleForSendingAfterCommit(Message<?> message){
			Queue<Message<?>> messageQueue = bindOrGetMessageQueue();
			messageQueue.add(message);
			TransactionSynchronizationManager.registerSynchronization(synchronization);
		}
	
		@SuppressWarnings("unchecked")
		private Queue<Message<?>> bindOrGetMessageQueue() {
			Queue<Message<?>> messageQueue = new LinkedList<>();
			if(TransactionSynchronizationManager.hasResource(synchronization)){
				messageQueue = (Queue<Message<?>>)TransactionSynchronizationManager.getResource(synchronization);
			}
			else {
				TransactionSynchronizationManager.bindResource(synchronization, messageQueue);
			}
			return messageQueue;
		}
	
		private void dispatch(Message<?> message){
			outputChannel.send(message);
		}
	}
and usage

	<int:channel id="post-demarc" />
	<bean id="storeAndForward" class="com.smth.StoreAndForward">
	    <constructor-arg ref="post-demarc" />
	</bean>
	
	<int:chain order="2" input-channel="demarcation" output-channel="post-demarc">
	    <int:service-activator ref="storeAndForward" />
	</int:chain>
	
	<int-amqp:outbound-channel-adapter channel="post-demarc" ...

**Comment by artembilan** [comment]
@bojanv55 ,

I just don't feel your requirements. So, my current answer "No".
Please, provide more info what is the purpose of such a buffer.

Maybe simple transactional thread around that `<int-amqp:outbound-channel-adapter>` is enough?

I just can't compute how it can be possible. Imagine the situation when your flow is long enough and there are many endpoints and logic after this "buffer". So, all of them will be invoked only during `afterCommit()`. Even if it is possible, that doesn't look like correct pattern to interfere into transaction.

Typically we rely on the `afterCommit()` only in case of target transactional resource: JMS, JDBC etc.. But it is really in the end of our call (COMMIT) and doesn't impact to the entire flow. I mean after performing INSERT we still can go ahead and do some other logic independently that real commit is done in the end of TX.

I can suggest for your some working pattern like Transactional Persistent QueueChannel. You send messages to it, but they will be visible for polling on another side really only after TX commit.

We recently added `TransactionHandleMessageAdvice` which can be applied in the middle of the flow for any endpoint and all the downstream flow (the same Thread) becomes transactional. But that is different story anyway. Just some more info for your to investigate.

**Comment by bojanv55** [comment]
So If I understood you correctly, there is another way to have amqp message delivered to inbound-channel-adapter, do processing of it in transaction and after saving to DB (in transaction) some output message can be sent to amqp outbound-channel-adapter after commit (and only if commit is successful) in a same thread (without polling etc.)? Basically my requirement is to send resulting AMQP message only after changes are really preserved to DB. If this can be done with this new thread around outbound-channel-adapter - is there any performance difference than doing it in same thread?

**Comment by artembilan** [comment]
If you would like to send confirmation after successful TX commit, consider `TransactionSynchronizationFactory`: http://docs.spring.io/spring-integration/reference/html/transactions.html#transaction-synchronization.

I just don't understand your original scenario.
And you still don't provide more info to determine what is the business requirements...

**Comment by artembilan** [comment]
@bojanv55 ,

since you are here around with your amazing work for the `JdbcMetadataStore`, maybe you'll consider to come to us with this one and provide more info what you have to do on the matter and we might help you somehow. And, finally, together we will figure out with which conclusion to close this issue.

Thanks

**Comment by bojanv55** [comment]
@artembilan  I forgot why I needed this at that time. I think that I needed it for some kind of transactional support when I was implementing idempotent receiver. Anyway, for now you can close this issue.

**Comment by artembilan** [comment]
Thank you for the answer, @bojanv55, anyway!

FYI there **is** out-of-the-box [Idempotent Receiver](http://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#idempotent-receiver). And right, your `JdbcMetadataStore` can be used there as well. And together with the `TransactionHandleMessageAdvice` they will do a good tandem do not store anything in DB until commit. Ultimate idempotency! 😄 

Closing as we agreed...
