### ISSUE TITLE
Invalid information in RedisMessageStore documentation

### ISSUE THREAD

**Issue by urgelacko** [spring-projects/spring-integration#2110]
According to the documentation's last sentence below it should be possible to configure the RedisMessageStore to serialize messages in Jackson: http://docs.spring.io/spring-integration/reference/html/redis.html#redis-message-store

I couldn't manage to do it and I think it is impossible right now because of the following reasons:

- I should provide a valueSerializer which uses Jackson to serialize objects
- *RedisMessageStore* extends *AbstractKeyValueMessageStore *
- *AbstractKeyValueMessageStore * uses redisTemplate and the previously configured serializers for example for the following call: https://github.com/spring-projects/spring-integration/blob/v4.3.8.RELEASE/spring-integration-core/src/main/java/org/springframework/integration/store/AbstractKeyValueMessageStore.java#L114
- This means the Jackson serializer should deserialize to a MessageGroupMetadata but it is impossible since the MessageGroupMetadata class has no default constructor and the one accepts an object which shouldn't be serialized at all (MessageGroup). Additionally that argument is not needed in case of deserialization at all.
- Since MessageGroupMetadata is not an interface I can't provide my own implementation as a result of deserialization

I think if this is a known limitation or it is intended the documentation should be more precise about these limitations.

**Comment by artembilan** [comment]
Well, I agreed and don't have a quick answer how to proceed.
On the one hand that document doesn't claim to use Jackson for (de)serialization.
But on the other one, even if we add default ctor to the `MessageGroupMetadata`, the `Message<?>` implementations are still stay non-compatible for JSON deserializaiton, because of several ctors there.

I don't want to drop that functionality since it promises some flexibility, but that really becomes useless in case of Jackson...

Any ideas besides dropping `setValueSerializer()` and polishing Docs for limitations?

Thanks

**Comment by urgelacko** [comment]
Thank you for your quick response @artembilan 
As I see the biggest problem with serializing `MessageGroupMetadata `is the `groupId `field. However according to a call hierarchy check the `getGroupId()` method is never used in the framework nor in the class itself. So it seems a bit useless for me currently but maybe I do not understand something happening under the hood.

Actually if we skip the `groupId `field problem above the `MessageGroupMetadata `class needs minor modifications to make it serializable with out of the box *`GenericJackson2JsonRedisSerializer`* implementation.
I have created a JUnit test and it seems the followings are do the work:
- remove `final `modifiers from the fields
- introduce a private default constructor
- add a public `getMessageIds()` getter

While these modifications won't drop functionality maybe there was a reason behind hiding the `messageIds `list itself.

**Comment by artembilan** [comment]
@urgelacko ,

I would like to see your changes.
Maybe you even can provide PullRequest on the matter, please.
That way it would be much easier to follow with the requirements and fixes.

Yes, we don't use that `groupId` field, just because the `key` of the record in Redis contains it already.
The best guess from my side that `groupId` property is in the `value` to let distinguish it from others during data analysis. But, yeah, we really may just drop this field to decrease the network workload and, therefore, target store 😄

**Comment by artembilan** [comment]
Also see https://jira.spring.io/browse/INT-4267

**Comment by urgelacko** [comment]
@artembilan 
I have used a bit different solution, I will share it maybe it will be useful. Thanks again!

`/**
 * Mutable {@link Message} implementation representing which supports serialization with Jackson.<br>
 * Publishes default constructor for supporting serialization with Jackson.
 * <p>
 * Created by Laci on 08/11/2016.
 */
public class MutableMessage<T> implements Message<T> {

    private T payload;
    private MutableMessageHeaders headers;

    protected MutableMessage() {
        this(null, null);
    }

    protected MutableMessage(T payload, Map<String, Object> headers) {
        this(payload, new MutableMessageHeaders(headers));
    }

    protected MutableMessage(T payload, MutableMessageHeaders headers) {
        this.payload = payload;
        this.headers = headers;
    }

    @Override
    public T getPayload() {
        return payload;
    }

    @Override
    public MessageHeaders getHeaders() {
        return headers;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        com.falconsocial.facebook.processor.config.redis.MutableMessage that = (com.falconsocial.facebook.processor.config.redis.MutableMessage) o;

        if (!payload.equals(that.payload)) {
            return false;
        }
        return headers.equals(that.headers);
    }

    @Override
    public int hashCode() {
        int result = payload.hashCode();
        result = 31 * result + headers.hashCode();
        return result;
    }

    /**
     * Extension of {@link MessageHeaders} which publishes a default constructor for support Jackson serialization of {@link Message}
     */
    public static class MutableMessageHeaders extends MessageHeaders {

        public MutableMessageHeaders() {
            super(new HashMap<>());
        }

        public MutableMessageHeaders(Map<String, Object> headers) {
            super(headers, UUID.fromString(headers.get(ID).toString()), Long.parseLong(headers.get(TIMESTAMP).toString()));
        }

        @Override
        protected Map<String, Object> getRawHeaders() {
            return super.getRawHeaders();
        }

        @Override
        public void putAll(Map<? extends String, ? extends Object> map) {
            super.getRawHeaders().putAll(map);
        }

        @Override
        public Object put(String key, Object value) {
            return super.getRawHeaders().put(key, value);
        }

        @Override
        public void clear() {
            super.getRawHeaders().clear();
        }

        @Override
        public Object remove(Object key) {
            return super.getRawHeaders().remove(key);
        }
    }

}`

GenericMessageSerializer is our own abstraction but it is not important part.

`@Component
public class JacksonMessageRedisSerialize implements RedisSerializer<Message<?>>, GenericMessageSerializer {

    private ObjectMapper om;

    @Autowired
    public void setObjectMapper(ObjectMapper om) {
        this.om = om.copy().enableDefaultTyping(ObjectMapper.DefaultTyping.OBJECT_AND_NON_CONCRETE, JsonTypeInfo.As.PROPERTY);
    }

    @Override
    public byte[] serialize(Message<?> message) throws SerializationException {
        if (null == message) {
            return new byte[0];
        }
        try {
            MutableMessage<?> serializableMessage = new MutableMessage<>(message.getPayload(), message.getHeaders());
            return this.om.writeValueAsBytes(serializableMessage);
        } catch (Exception ex) {
            throw new SerializationException("Could not write JSON: " + ex.getMessage(), ex);
        }
    }

    @Override
    public Message<?> deserialize(byte[] bytes) throws SerializationException {
        if (isEmpty(bytes)) {
            return null;
        }
        try {
            return this.om.readValue(bytes, 0, bytes.length, MutableMessage.class);
        } catch (Exception ex) {
            throw new SerializationException("Could not read JSON: " + ex.getMessage(), ex);
        }
    }

    @Override
    public String serializeToString(Message<?> message) {
        return new String(serialize(message));
    }

    @Override
    public Message<?> deSerializeFromString(String stringValue) {
        return deserialize(stringValue.getBytes());
    }

    private boolean isEmpty(byte[] bytes) {
        return bytes == null || bytes.length == 0;
    }

}`

**Comment by artembilan** [comment]
@urgelacko,

That's great solution and it really can be applied for some use-case.
For example in tests we have this variant, too: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-redis/src/test/java/org/springframework/integration/redis/util/CustomJsonSerializer.java

But my goal with the complex solution to cover as much use-cases as possible with the ability to preserve the incoming type. When we serialize `GenericMessage` we would like to deserialize to this one as well.
The `ErrorMessage` has some extra logic as well. The `AdviceMessage` goes a bit further and has aditional `inputMessage` property which is of `Message` type as well.
