### ISSUE TITLE
How to use the RedisLockRegistry ?

### ISSUE THREAD

**Issue by gaojia0814** [spring-projects/spring-integration#2199]
How to use the RedisLockRegistry ? when should i run the expireUnusedOlderThan method?

**Comment by artembilan** [comment]
We don't handle questions in bug tracking tool. Please, consider to ask them on [StackOverflow](https://stackoverflow.com/).

Anyway let us know, why JavaDocs on the matter is not enough: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/support/locks/ExpirableLockRegistry.java ?

For general `LockRegistry` usage see Reference Manual: http://docs.spring.io/spring-integration/docs/4.3.10.RELEASE/reference/html/redis.html#redis-lock-registry

**Comment by gaojia0814** [comment]
thanks
