### ISSUE TITLE
Add real examples for spring-integration-security

### ISSUE THREAD

**Issue by hadrienk** [spring-projects/spring-integration#2221]
The spring-integration-security module is not very easy to get started with. Especially if you are using java configuration.

**Comment by garyrussell** [comment]
@hadrienk Did you see the Java Config example [in Appendix D](http://docs.spring.io/spring-integration/reference/html/security.html#securing-channels)?

If, yes, what else do you think is missing?

Thanks.

**Comment by artembilan** [comment]
Closed with the proper answer and a lack of feedback from the reporter.

Feel free to reopen if you still have some concerns on the matter!
