### ISSUE TITLE
AbstractCorrelatingMessageHandler loses spring SecurityContext

### ISSUE THREAD

**Issue by tstorck** [spring-projects/spring-integration#2223]
Hi,

We noticed that when a groupTimeout is configured on an aggregator, and a timeout occurs on the AggregatingMessageHandler, the messages that are forced to continue are executed in a newly scheduled thread, which no longer holds the spring SecurityContext. 

See org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.scheduleGroupToForceComplete(MessageGroup) where the new Runnable is scheduled.

Kind regards
Tom

**Comment by garyrussell** [comment]
There is no direct support for propagating the security context when a group timeout occurs (or when a group is expired by a `MessageGroupStoreReaper`).

If you attach the same security context to a header in each arriving message, it would be propagated to the outbound message and you could restore it to the context holder in a service activator downstream of the aggregator.

If, however, the calling thread might clear the context before the group expires, the header would need a clone of the context. In order for the output message to get the header, the inbound context must be the identical object on each message. The aggregator discards conflicting headers.

**Comment by tstorck** [comment]
Ok, good to know that this is not supported, we'll handle it in a different way. Thanks for your response and implementation suggestion. 
KR Tom

**Comment by artembilan** [comment]
OTOH if you worry only about `scheduleGroupToForceComplete(MessageGroup)`, you can consider to use Spring Security Concurrency utils: https://docs.spring.io/spring-security/site/docs/4.2.3.RELEASE/reference/html/concurrency.html. In particular I suggest to inject `ConcurrentTaskScheduler` into the `AbstractCorrelatingMessageHandler` with the `DelegatingSecurityContextScheduledExecutorService` as delegate. This way the main thread (or more over task initiator thread) will propagate the `SecurityContext` to that scheduled thread via:
```
public DelegatingSecurityContextRunnable(Runnable delegate) {
	this(delegate, SecurityContextHolder.getContext());
}
```
