### ISSUE TITLE
RedisQueueMessageDrivenEndpoint setReceiveTimeout(): Javadoc does not match code

### ISSUE THREAD

**Issue by matthjes** [spring-projects/spring-integration#2228]
Hi,

I want to use a `RedisQueueMessageDrivenEndpoint` that blocks until a new message arrives, so I would have expected to set the receive timeout to 0. This is also mentioned in the Javadoc:

> A timeout of zero can be used to block indefinitely. If not set explicitly the timeout value will default to {@code 1000}

However, in the code the first line asserts that receive timeout is > 0:

```java
public void setReceiveTimeout(long receiveTimeout) {
    Assert.isTrue(receiveTimeout > 0, "'receiveTimeout' must be > 0.");
    this.receiveTimeout = receiveTimeout;
}
```
The documentation for BLPOP also mentions that a timeout of 0 blocks indefinitely.

**Comment by artembilan** [comment]
@matthjes ,

I think this is a good catch and should be considered as a bug.

The `RedisQueueInboundGateway` suffers the same problem.

Would you mind coming back with the [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc) on the matter?

Thanks
