### ISSUE TITLE
Channel Adapter diagram in spring-integration reference documentation correction

### ISSUE THREAD

**Issue by pavankumarchaitanya** [spring-projects/spring-integration#2243]
I have attached the screenshot of the documentation for spring-integration, the channel adapter is supposed to convert a message to target understandable object, so the _Message_ object in green should be between _Message Channel_ and _Channel Adapter_(in Figure 3.6).
![screen shot 2017-09-19 at 3 50 33 pm](https://user-images.githubusercontent.com/1131854/30619330-afc34626-9d53-11e7-93b9-fa8d4b01ce84.png)

**Comment by artembilan** [comment]
Yeah... I think so. The Outbound Channel Adapter indeed connects to the Target system. That is its purpose.
And yes, the Message Consuming Endpoint definitely reads messages from the channel.

Absolutely agree with the concern.

Would you contribute the fix?

Thank you for the pointer!

**Comment by pavankumarchaitanya** [comment]
Sure Artembilan, is there a URL/guideline to creating images for spring integration documentation?

**Comment by artembilan** [comment]
Yeah, the file we are talking about is here: https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/images/target-endpoint.jpg. So, you are free to fork the project, fix the image and Pull Request it!

Well, I think that will be just enough to have that image created in any appropriate graphic editor. For example, I would use Paint on my Windows 😄 

Let's hear what @garyrussell thinks on the matter!

**Comment by pavankumarchaitanya** [comment]
Ok Artembilan, I will figure out the editing options while waiting for a reply from Garyrussell. The reason I asked was that I saw a shadow below each component in the image. I was wondering if there is an editor/tool/standard for spring-integration images.

**Comment by pavankumarchaitanya** [comment]
![spring-integration-figure-3 6 4](https://user-images.githubusercontent.com/1131854/30666120-2d765df6-9e08-11e7-8ed0-1526fc0c7d19.jpg)
I've gotten till here using draw.io 

Let me know if it's ok, for uniformity I can create one more image for figure 5.5

I have attached the zip file containing the image that I have attached as xml exported from draw.io

Feel free to make any changes to the xml/image and let me know if I can go ahead and raise a pull request for both images(figure 3.5 and 3.6) or direct me towards next steps. 

[Spring-integration-figure-3.6.zip](https://github.com/spring-projects/spring-integration/files/1319157/Spring-integration-figure-3.6.zip)

**Comment by artembilan** [comment]
Thank you, @pavankumarchaitanya , for the effort!

Well, look the pictures are definitely different and even if you change the second one, we still have a bunch of many other in the project. So, for we would need to change them all to align in the same style.
That what might not be good idea because of a lot of time to spend.

Some remarks to your picture (besides the different style):
1. Components must be connected, no spaces between them and arrows.
2. And the components should not be squahsed/fat 😄 

Just IMO...

Let's wait for the input from @garyrussell !

**Comment by artembilan** [comment]
I did this for my presentation:

![image](https://user-images.githubusercontent.com/1071590/33331601-09f0bb20-d430-11e7-8e29-05302f04b3fe.png)

Does it work for you and for the rest of our Docs?

Thanks

**Comment by garyrussell** [comment]
LGTM
