### ISSUE TITLE
spring-integration-mail : ImapMailReceiver(String url) fails when username contains "@"

### ISSUE THREAD

**Issue by pravinarr** [spring-projects/spring-integration#2245]
ImapMailReceiver(String url) - constructor to set the parameters for URLName object.

The paarseString function in URLName function will fail if the username contains "@". Hence failing functionality. If there is a constructor to set URLName object directly then it would be great.

**Comment by garyrussell** [comment]
You need to escape special characters in the URL (except the `@` before the host name); for example `@` becomes `%40`.

See [here](https://www.werockyourweb.com/url-escape-characters/).

**Comment by artembilan** [comment]
Would you mind to share some stack trace on the matter?
We have this test-code:
```
Mail.imapInboundAdapter("imap://user:pw@localhost:" + imapServer.getPort() + "/INBOX")
```
Which does exactly what you are explaining:
```
public static ImapMailInboundChannelAdapterSpec imapInboundAdapter(String url) {
	return new ImapMailInboundChannelAdapterSpec(url);
}

...

ImapMailInboundChannelAdapterSpec(String url) {
	super(new ImapMailReceiver(url), false);
}
...

public ImapMailReceiver(String url) {
		super(url);
     ...
}

...

public AbstractMailReceiver(String url) {
		if (url != null) {
			this.url = new URLName(url);
		}
    ...
}
```
So, looks like that `@` works as is and there is no need in any escaping.

**Comment by pravinarr** [comment]
Escape character worked @garyrussell   thank you for your help.

@artembilan  I was trying to use a g suite email account for which the URL would be 
like imaps://username@domain.com:pwd@imap.gmail.com:993/INBOX. "@" in the username waa the problem.

**Comment by artembilan** [comment]
Oh! Sure. The story is about `@` in the *username*.
Sorry for the noise 😄
