### ISSUE TITLE
Prevent recursive detection on local directory using SftpInboundFileSynchronizingMessageSource

### ISSUE THREAD

**Issue by chrisschauer** [spring-projects/spring-integration#2253]
Hi,
we are testing at the moment spring-integration 5.0.0.M7 in our project (it was 4.3.8-RELEASE before) and we had some trouble regarding recursive detection of files.

Our workflow
 * Synchronize files from remote via (S)FTP to a local folder
 * Process the file on local folder and using an /error and /done directory to save results. The results are kept for a configurable amount of days.

Configuration of inbound adapter:
```
    @Bean
    @InboundChannelAdapter(value = "fileInputChannel", autoStartup = "false", poller = @Poller(fixedDelay = "5000"))
    public SftpInboundFileSynchronizingMessageSource remoteSource() {
        // SFTP connection settings
        DefaultSftpSessionFactory sftpSessionFactory = new DefaultSftpSessionFactory();
        sftpSessionFactory.setUser(user);
        sftpSessionFactory.setHost(host);
        sftpSessionFactory.setPort(port);
        sftpSessionFactory.setPassword(password);
        sftpSessionFactory.setAllowUnknownKeys(true);

        CachingSessionFactory<ChannelSftp.LsEntry> cachingSessionFactory = new CachingSessionFactory<>(sftpSessionFactory);

        // synchronizer config
        SftpInboundFileSynchronizer sftpSynchronizer = new SftpInboundFileSynchronizer(cachingSessionFactory);
        sftpSynchronizer.setRemoteDirectory(remoteWatchDir);
        // remote filter
        sftpSynchronizer.setFilter(new SftpRegexPatternFileListFilter(filePattern));
        sftpSynchronizer.setPreserveTimestamp(true);
        sftpSynchronizer.setDeleteRemoteFiles(true);

        SftpInboundFileSynchronizingMessageSource sftpMessageSource = new SftpInboundFileSynchronizingMessageSource(sftpSynchronizer);
        sftpMessageSource.setAutoCreateLocalDirectory(true);
        sftpMessageSource.setLocalDirectory(new File(watchDir));
        sftpMessageSource.setLocalFilter(new RegexPatternFileListFilter(filePattern));

        return sftpMessageSource;
    }
```

The locale file structure:

```
/watchDir
   /done
   /error
```

How can we prevent re-processing saved files in /done and /error? There is a new 'RecursiveDirectoryScanner' which i tried to disable this by using

`        sftpMessageSource.setUseWatchService(true);
`
but without success. Any thoughts? Thx

**Comment by garyrussell** [comment]
That's odd; when `setUseWatchService(false)` (the default), the `DefaultDirectoryScanner` is used, which doesn't recurse at all.

Can you attach a DEBUG log?

**Comment by artembilan** [comment]
That's not too odd, Gary. We have introduced `RecursiveDirectoryScanner` in the `5.0`: https://jira.spring.io/browse/INT-4086. And now we use it by default in the `AbstractInboundFileSynchronizingMessageSource`.

The idea to have `RecursiveDirectoryScanner` there is to let to restore the remote tree in local dir.
If you're done with downloaded files, consider to move them to different root directory.

We have recently fixed it by the `public void setScanner(DirectoryScanner scanner)`: https://jira.spring.io/browse/INT-4334. So, this problem can easily be overcome `DefaultDirectoryScanner` injection.

Well, right now I even think that we may reinstate the `DefaultDirectoryScanner` by default and document that to restore the file tree you should inject `RecursiveDirectoryScanner`.

WDYT?

**Comment by garyrussell** [comment]
Oh; I forgot about that change; it's an important improvement, but this is an undesired side-effect.

It's not clear why we need a recursive scanner here since we still only fetch one directory from the server; we simply are building the local tree to match the remote one. A default directory scanner for the leaf directory would be enough, at least when the local filename generator always generates the same path. However, I can see cases where the local path might change on each poll - of course, that new path might be outside the current tree as well - but they're on their own if they play tricks like that.

Full support for recursion is achieved using a recursive MGET with an outbound channel adapter.

Perhaps we should add a new option to "opt-in" to the new behavior (or a flag to revert to the previous behavior and configure the default scanner).

**Comment by artembilan** [comment]
As I said: we still in Milestone. We can reinstate the previous behavior with the `DefaultDirectoryScanner`. And since we have `setScanner()` already as well, there would be just enough to document how to inject `RecursiveDirectoryScanner` in case of local tree.

**Comment by chrisschauer** [comment]
Thank you guys for addressing my problem. Is a debug log needed yet? Close the issue if you want, for me the solution is to switch back to stable release version.

**Comment by artembilan** [comment]
Hello, @chrisschauer !

Well, that's thanks to you!

When we introduced `RecursiveDirectoryScanner` and made it as default one we thought about one  use-case, but didn't count with many other. And now we have realized that restoring file tree is rather rare scenario than default one. So, reverting back to that `DefaultDirectoryScanner` feels much better. 

Not what debug log you are talking about though...

The issue will be closed automatically when related PR is merged.

**Comment by chrisschauer** [comment]
Garry requested a debug log, but I think it's not needed anymore :-)
Do you know if there will be a new milestone release including this fix

**Comment by artembilan** [comment]
Well, we have GA on November 7th. And somewhere in between we should have an RC1.
So, I guess the current M8 we will make the next week!

**Comment by garyrussell** [comment]
Initialization code...

			if (this.scannerExplicitlySet) {
				Assert.state(!this.fileSource.isUseWatchService(),
						"'useWatchService' and 'scanner' are mutually exclusive.");
				this.fileSource.getScanner().setFilter(filter);
			}
			else if (!this.fileSource.isUseWatchService()) {
				RecursiveDirectoryScanner directoryScanner = new RecursiveDirectoryScanner();
				directoryScanner.setFilter(filter);
				this.fileSource.setScanner(directoryScanner);
			}

**Comment by artembilan** [comment]
Gary, that's true, M8 hasn't been released yet: https://jira.spring.io/plugins/servlet/mobile#issue/INT-4334

**Comment by garyrussell** [comment]
Ah; ok; thanks.
