### ISSUE TITLE
ScatterGatherHandler.stop() calling GatherEndpoint.start instead of stop

### ISSUE THREAD

**Issue by abdulbeard** [spring-projects/spring-integration#2261]
https://github.com/spring-projects/spring-integration/blob/00807d47e2880e780b1430c3aba3a588490572da/spring-integration-core/src/main/java/org/springframework/integration/scattergather/ScatterGatherHandler.java#L164

**Comment by artembilan** [comment]
Great catch! 

Would you mind fixing the issue as contribution: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc ?

Thank you!

**Comment by abdulbeard** [comment]
https://github.com/spring-projects/spring-integration/pull/2262
