### ISSUE TITLE
MQTT Support: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage

### ISSUE THREAD

**Issue by yyguo1986** [spring-projects/spring-integration#2286]
I followed the section 23.2.2 (not using Spring boot) in the following doc to configure inbound adapter using Java configuration, but got an exception with "Dispatcher has no subscribers".  It seems service activator was not added as a subscriber to the channel. How to resolve this issue?

 __https://docs.spring.io/spring-integration/docs/4.3.12.RELEASE/reference/html/mqtt.html_

__Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=Published msg, headers={timestamp=1510713251102, id=0eb4434c-e187-cb77-0f5e-f6dfc5b7822b, mqtt_qos=0, mqtt_topic=spring/topic, mqtt_retained=false, mqtt_duplicate=false}]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:154)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
	... 10 more_

**Comment by artembilan** [comment]
I think you are missing the fact that there is a `@SpringBootApplication` annotation on the class. According to your explanation you don’t have it, neither you have an important for Spring Integration Java configuration `@EnableIntegration` annotation: https://docs.spring.io/spring-integration/docs/4.3.12.RELEASE/reference/html/overview.html#configuration-enable-integration

**Comment by yyguo1986** [comment]
Yes, it works after adding the @SpringBootApplication annotation on the class. Thanks.

But I have one more question: 
does it work only when adding a @SpringBootApplication annotation? Is there another config way without spring boot annotation?

**Comment by garyrussell** [comment]
Yes, as @artembilan said; `@EnableIntegration` (boot adds that annotation internally, a non-boot application has to add that to one of its `@Configuration` classes.

**Comment by artembilan** [comment]
This not that kind of issues we consider here on GitHub. Please, represent your questions on StackOverflow. We will let you know there if it is necessary to raise a bug report.

 But yeah, documentation is there for you. And I answered with the proper link...

**Comment by artembilan** [comment]
Closed as answered question.
Nothing really to fix from the code perspective.

**Comment by yyguo1986** [comment]
All works now, thanks.
