### ISSUE TITLE
Is it possible to synchronize all messages from inbox via spring-integration-mail?

### ISSUE THREAD

**Issue by sunandy3** [spring-projects/spring-integration#2293]
Is it possible to synchronize all messages from inbox via spring-integration-mail?
When the email address is bind, I want to synchronize all messages from inbox in first time, and then periodically receive the only new message. Can it be done by this integration package?

Thanks a lot.

**Comment by artembilan** [comment]
See documentation https://docs.spring.io/spring-integration/docs/4.3.12.RELEASE/reference/html/mail.html#mail-inbound and ask questions on public forums like StackOverflow.

We don’t support questions here on GitHub - only bug reports and feature requests.
