### ISSUE TITLE
[Spring-integration-mail] Provides a way to interact with ImapIdleChannelAdapter

### ISSUE THREAD

**Issue by M3lkior** [spring-projects/spring-integration#2294]
Hi,

I spent a lot of time to search how i can interact with ImapIdleChannelAdapter for a specific use case : 
* How i can play with the ImapMailReceiver to check the amount of unread email for example ?

It's possible thanks to Interceptor classes but only if a message in send or receive. How to do that on every poll ? 

I found a workaround by requesting the Folder object in a custom SearchTermStrategies class (which is apparently called in each poll) but i'm not all right with this implementation : 

```java
public class SearchTermStrategies implements SearchTermStrategy, ApplicationContextAware{
        private final static Logger logger = LoggerFactory.getLogger(SearchTermStrategies.class);

        ApplicationContext ac;
        @Override
        public SearchTerm generateSearchTerm(Flags supportedFlags, Folder folder) {

            try {
                if(folder.getUnreadMessageCount() == 0){
                    logger.info("No more mail to process, stoppping app");
                    SpringApplication.exit(ac,
                            () -> 0);                }
            } catch (MessagingException e) {
                logger.debug("Unable to get Folder content");
            }
            SearchTerm searchTerm = null;
            if (supportedFlags != null) {

                if (supportedFlags.contains(Flags.Flag.DELETED)) {
                    NotTerm notDeleted = new NotTerm(new FlagTerm(new Flags(Flags.Flag.DELETED), true));
                    if (searchTerm == null) {
                        searchTerm = notDeleted;
                    }
                    else {
                        searchTerm = new AndTerm(searchTerm, notDeleted);
                    }
                }
                if (supportedFlags.contains(Flags.Flag.SEEN)) {
                    NotTerm notSeen = new NotTerm(new FlagTerm(new Flags(Flags.Flag.SEEN), true));
                    if (searchTerm == null) {
                        searchTerm = notSeen;
                    }
                    else {
                        searchTerm = new AndTerm(searchTerm, notSeen);
                    }
                }
            }

            return searchTerm;
        }


```

Is it possible to provide a way to fully interact with the ImapIdleChannelAdapter configuration ?

```xml

	<int-mail:inbound-channel-adapter id="pollForEmail"
		channel="receiveChannel
		  store-uri="${app.incomingmail.store-uri}"
		search-term-strategy="searchTermStrategies"
		embedded-parts-as-bytes="true"
		 should-delete-messages="${app.incomingmail.should-delete-messages}"
		  should-mark-messages-as-read="${app.incomingmail.should-mark-as-read}"
			auto-startup="true"
		  java-mail-properties="javaMailProperties">

		<int:poller fixed-rate="5000" />

	</int-mail:inbound-channel-adapter>
...
```

Thanks

**Comment by artembilan** [comment]
We don't manage questions here on GitHub.
That is a matter of public forums, e.g. StackOverflow.

Anyway your question isn't clear. The `<int-mail:inbound-channel-adapter>` is about `MailReceivingMessageSource`, not `ImapIdleChannelAdapter`.

If need to get an access to the `Folder` backed by the `ImapMailReceiver`, you should populate `ImapIdleChannelAdapter` as a regular `<bean>` and inject a custom `ImapMailReceiver` with the `getFolder()` as `public`  method.

On the other hand it sounds like it isn't an `ImapIdleChannelAdapter`  responsibility to give you that functionality. You have to deal with `Folder`directly in your code using mail session object.

I'm closing this as it isn't bug neither feature request.

Feel free to reopen with more solid requirements.
