### ISSUE TITLE
unsubscribe and subscribe programatically

### ISSUE THREAD

**Issue by nitin02** [spring-projects/spring-integration#2296]
I'm using the `SubscribableChannel` for consuming messages from Kafka using the spring cloud stream implementation (1.1.0.RELEASE).

I can see in the interface definition that there are 2 methods to `subsribe` and unsubscribe to the `MessageHandler`. Can this be called programtically, to stop consumption and resume at run-time?

There pause/resume/seek functionality in spring cloud stream is currently not part of any stable release.

If yes, What's the best way to do this?

**Comment by artembilan** [comment]
The question isn't related to Spring Integration. At least by the premise.
You should consider to move it into the appropriate [Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream) project.

More over we don't handle them here on GitHub.

Really consider to ask questions on public forums, e.g. StackOverflow.

As far as I know you can't stop consumption in the current Spring Cloud Stream version.
