### ISSUE TITLE
WebFlux.outboundGateway has no way of producing Flux<Anything>

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-integration#2300]
In `WebFluxRequestExecutingMessageHandler`, I see the following:
```
if (expectedResponseType instanceof ParameterizedTypeReference<?>) {
  bodyMono = response.body(BodyExtractors.toMono((ParameterizedTypeReference<?>) expectedResponseType));
}
else if (expectedResponseType != null) {
	bodyMono = response.body(BodyExtractors.toMono((Class<?>) expectedResponseType));
}
```

What I'm expecting as response is `Flux<DataBuffer>` that I can do some processing on before sending to an output channel. However, the above code always forces the body to be converted to `Mono`.

The documentation for webflux support merely regurgitates what's in the code. 

> The WebClient exchange() operation returns a Mono<ClientResponse> which is mapped to the AbstractIntegrationMessageBuilder reactive support (using Mono.map()) as the output from the WebFluxRequestExecutingMessageHandler. Together with the ReactiveChannel as an outputChannel, the Mono<ClientResponse> evaluation is deferred until a downstream subscription is made. Otherwise, it is treated as an async mode and the Mono response is adapted to an SettableListenableFuture for an asynchronous reply from the WebFluxRequestExecutingMessageHandler.

It'd be nice to also see some examples for how to get a `Flux<UserDataType>`,  `Flux<DataBuffer>`, `Mono<ClientResponse>` etc. As with `RestTemplate`, where I've the option to get the `ResponseEntity` if I want to do the processing myself, I should also be able to get `Mono<ClientResponse>` should I so choose.

**Comment by artembilan** [comment]
Same here. The PR on the matter #2304

**Comment by artembilan** [comment]
Correct. That is not Spring Integration and Messaging architecture responsibility to expose such a low level resource. If you really need the access to it and do low-level logic around, consider to use `WebClient` directly in some POJO for the `@ServiceActivator`.

Anyway in this case we provide the body converted to the `payload` via provided `HttpMessageReader`s and HTTP headers are copied into the `MessageHeaders` according `HeaderMapper`. So, technically you have everything in the `Message` what you could get from the `ClientResponse` directly.

**Comment by asarkar** [comment]
>  you have everything in the Message what you could get from the ClientResponse directly.

That's not true. One example where that doesn't work is when the response is compressed. Your PR would produce a `Flux<DataBuffer>` which would be useless until the caller can reconstruct the `InputStream` and decompress it. Other examples might include not parsing the body at all if they see a particular header or something like that.

Point is, I don't understand why you'd force someone to write more code which can be supported by framework in the first place, and with little effort? Having a `Message<Mono<ClientResponse>>` is not breaking the messaging paradigm. The caller is in the best position to decide what should be in the message, not the framework author.

**Comment by artembilan** [comment]
Yeah... That existing status quo with all other channel adapters... 

@garyrussell , any thoughts since we always convert low-level response to our "convenient" representation?

I may suggest to let to inject something like `BodyExtractor` which simple can be like:
```
(inputMessage, context) -> inputMessage
```
Where that `inputMessage` is exactly `ClientResponse` and you will get the message with it downstream.

**Comment by garyrussell** [comment]
Sounds like a reasonable compromise. Maybe provide a canned `NoOpBodyExtractor` or at least document the lambda.

**Comment by artembilan** [comment]
@asarkar ,
let us know WDYT about previous discussion?
And let's move it to the PR already! That is much easier to comment on the code lines for the appropriate context.

For your `compressed` response use-case I would suggest to take a look into the `HttpMessageReader` abstraction which can be injected into the `WebClient` via its:
```
.exchangeStrategies(ExchangeStrategies.builder()
						.codecs(clientCodecConfigurer -> 
                                                                    clientCodecConfigurer.customCodecs()
                                                                                   .reader(...))
						.build())
```
