### ISSUE TITLE
cannot access CoreSubscriber when using Delayer

### ISSUE THREAD

**Issue by MALPI** [spring-projects/spring-integration#2317]
Hi there,

I am using Spring-Integration Core version 5.0.0.RELEASE in one of my projects.

When using the `DelayHandler` and compiling the code I am getting the following Exception by the compiler:

```
 gradle compileJava
:compileJava
/home/code/DelayerConfiguration.java:33: error: cannot access CoreSubscriber
    delayHandler.setDefaultDelay(DEFAULT_DELAY);
                ^
  class file for reactor.core.CoreSubscriber not found
1 error
:compileJava FAILED
```

Java version is:

```
java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

Seems like there is some version mismatch? After downgrading to `4.3.13.RELEASE` the issue disappears.

Best

**Comment by MALPI** [comment]
Seems like I got it fixed by adding the following dependency:

`'io.projectreactor:reactor-core:3.1.2.RELEASE'`

Though I am facing the next issue which seems to be introduced by Spring incompatibilities.

```
Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.integration.gateway.GatewayProxyFactoryBean]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.core.convert.support.DefaultConversionService.getSharedInstance()Lorg/springframework/core/convert/ConversionService;
```

**Comment by garyrussell** [comment]
Sounds like you have a __very__ old version of Spring Framework on the class path; that method was introduced in 4.3.5; Spring Integration 5 requires Spring Framework 5 (currently 5.0.2 is the latest).

What are you using for dependency management? All of these issues are best managed by maven or gradle.

If you are using Spring Boot 1.5.x; it is not compatible with SF/SI 5.x; boot 2.0 (currently at milestone 7) is compatible with the 5 series.

**Comment by artembilan** [comment]
Sounds more like [StackOverflow](https://stackoverflow.com/) question.

We manage here on GH only bug reports and feature requests.
Questions like this is better handled on the Community forums.

(I wonder if we should add some template here for issues to let people to know how it works from our side...)

**Comment by MALPI** [comment]
@artembilan @garyrussell , yes knowing this. It is rather a question for StackOverflow. Sorry to spam Issues for that but I thought that this is an issue related to the release...

I am using Spring Boot version 1.4.x I think. Spring Boot version 2.0 is not officially released yet therefore I didn't expect incompatibility with the latest *RELEASE* of Spring Integration. 

Thanks for your responses anyway.

**Comment by garyrussell** [comment]
The latest 1.4.x boot uses [spring.version 4.3.9](https://github.com/spring-projects/spring-boot/blob/1.4.x/spring-boot-dependencies/pom.xml#L148) so it's not clear why that method is not present but in any case Boots < 2.0 cannot be used with SI 5.x.

Boot 2.0 is not yet released but will be the first version that supports Spring Integration 5.x.

**Comment by garyrussell** [comment]
Correction; it appears you can use SI 5 with boot 1.4 but you have to override all the integration jars to 5.0.0.RELEASE and all spring framework jars to 5.0.2.RELEASE.

However, your mileage may vary - I only did a basic test.

You'd be better off using a boot milestone release (currently M7); AFAIK the release should be available in a couple of months or so.
