### ISSUE TITLE
WebFluxMessageHandlerSpec should support chaining

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-integration#2340]
[WebFluxMessageHandlerSpec.replyPayloadToFlux](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-webflux/src/main/java/org/springframework/integration/webflux/dsl/WebFluxMessageHandlerSpec.java#L70)

The workaround is to create a method like the following:
```
private WebFluxMessageHandlerSpec webFluxMessageHandlerSpec() {
    WebFluxMessageHandlerSpec spec = WebFlux.outboundGateway(m -> m.getPayload().toString(), webClient)
            .expectedResponseType(Whatever.class)
            .httpMethod(GET)
            .mappedRequestHeaders(ACCEPT);
    spec.replyPayloadToFlux(true);

    return spec;
}
```

@artembilan this is what we discussed on Twitter. Since I don't see the fix yet in the [repo](https://repo.spring.io/snapshot/org/springframework/integration/spring-integration-webflux/5.0.1.BUILD-SNAPSHOT/), I'm going to proceed with a PR myself.

**Comment by artembilan** [comment]
@asarkar ,

sorry, was side-tracked with other urgent stuff.

Yes, the workaround is correct. That definitely doesn't matter if we don't provide method chain support the things are not going to work.

Please, proceed with the PR and also consider to fix similar problem for the `bodyExtractor()` hook as well.

Thank you!

**Comment by asarkar** [comment]
Just made the PR (as indicated above by GH). Regarding `bodyExtractor`, you means the following should be changed too?
```
public void bodyExtractor(BodyExtractor<?, ClientHttpResponse> bodyExtractor) {
    this.target.setBodyExtractor(bodyExtractor);
}
```

**Comment by artembilan** [comment]
Right, that one should follow method chain design as well.
Thanks, I see a PR.

**Comment by asarkar** [comment]
Just updated it with the `bodyExtractor`. Now it has both fixes.
