### ISSUE TITLE
Allow ExecutorService to be injected

### ISSUE THREAD

**Issue by boaty82** [spring-projects/spring-integration#2354]
Please, please, please can this be injected through an overloaded constructor, and make the existing constructors chain on with a default value as per current defaulting logic.

I have need to use this class with another executorservice/threadfactory and it's looks like I'm going to have to now duplicate a lot of code

https://github.com/spring-projects/spring-integration/blob/e53e8941a18cb3bec30187abe32d66a14afa48ac/spring-integration-core/src/main/java/org/springframework/integration/support/leader/LockRegistryLeaderInitiator.java#L78-L79

**Comment by artembilan** [comment]
Yes, we can do that.

[CONTRIBUTING](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc) is welcome!

**Comment by boaty82** [comment]
Okie dokie I shall certainly do so!

**Comment by boaty82** [comment]
I did start refactoring the class too, to make it smaller and have a single responsibility, but felt I should possibly do this under another pull request.

May have some other feature requests (with PoCs) and some other helpful/reusable implementations I can submit

**Comment by artembilan** [comment]
I don't find that class too bad by design so we need to refactor it, but you are feel free to share your vision anyway. However right: let's do that in the separate PR!

**Comment by boaty82** [comment]
I just felt the class in particular didn’t follow the open/closed principle. It’s complexity is quite large too. But yes agree a different PR
