### ISSUE TITLE
int:json-to-object-transformer

### ISSUE THREAD

**Issue by prakashbxr85** [spring-projects/spring-integration#2416]
https://stackoverflow.com/questions/49746595/spring-integration-issue-with-json-to-object-transformer-json-argument-must-be

Spring Integration 5.0.4 Release

**Comment by garyrussell** [comment]
There is no need to post in two places; it wastes our time, and yours.

**Comment by artembilan** [comment]
Closed in favor of mentioned StackOverflow question.
GitHub and [JIRA](https://jira.spring.io/browse/INT) (we really prefer JIRA) are for bug reports and feature requests.

We handle questions (alongside with other community) through the StackOverflow.

If some issue is confirmed, we will reopen this ticket.

Thanks for understanding.
