### ISSUE TITLE
link to 1.x -> 2.0 migration broken

### ISSUE THREAD

**Issue by domdorn** [spring-projects/spring-integration#2456]
The link on 
https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-2.0-to-2.1-Migration-Guide
"Spring Integration 1.0 to 2.0 Migration Guide"

is broken. Where can I find information on how to migrate from 1.x -> 2.0 -> higher versions ?

**Comment by garyrussell** [comment]
Thanks for pointing this out; I am trying to locate that content. In the meantime there are a couple of links in the [2.0.GA release blog post](https://spring.io/blog/2010/11/23/spring-integration-2-0-ga-released/) that might be helpful. Also, see [this appendix in the reference manual](https://docs.spring.io/spring-integration/reference/html/history.html#migration-1.0-2.0).

**Comment by garyrussell** [comment]
I have located the content and added a new page to the [home page](https://github.com/spring-projects/spring-integration/wiki).

Thanks again.
