### ISSUE TITLE
JdbcLockRegistry should retry on DeadlockLoserDataAccessException 

### ISSUE THREAD

**Issue by brempusz** [spring-projects/spring-integration#2467]
I am using `LockRegistryLeaderInitiator`  with `JdbcLockRegistry`. It worked fine on 5.6.36 but after the migration to 5.7.19 I noticed flood of "leader granted/revoked" events when more than on instance of my service is running. After some debugging I noticed it is caused by `DeadlockLoserDataAccessException` not handled as "retry" in  `JdbcLockRegistry`.

MySql 5.7.15 introduced setting `innodb_deadlock_detect` (enabled by default, see https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_deadlock_detect).

When this setting is enabled exception will be thrown from MySql JDBC driver when deadlock is detected while accessing table row  (vendorCode=1213, SQLState=40001, message: Deadlock found when trying to get lock; try restarting transaction). It is then wrapped to spring exception `DeadlockLoserDataAccessException`. 

`JdbcLockRegistry` does not handle `DeadlockLoserDataAccessException` with "try again" action (as it does for `CannotSerializeTransactionException`, `TransactionTimedOutException`, `QueryTimeoutException`).

see https://github.com/spring-projects/spring-integration/blob/a2f3dbe5fb558359cc839a81b12a6161cd96cabf/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java#L218-L230

Spring Boot 1.5.13.RELEASE
Spring Integration JDBC 4.3.16.RELEASE
MySQL 5.6.36/5.7.19

**Comment by artembilan** [comment]
No objections to have such a fix.
Any chances that you can [Contribute](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc)?

Thanks

**Comment by brempusz** [comment]
Sure. Some questions first:
1) Do I have to create issue in JIRA (I don't have an account yet) or just continue with this GH issue?
2) Do I have to create PR for master and 4.3.x branch or just for one branch?

**Comment by garyrussell** [comment]
Thanks; you don't need a JIRA; generally, just a PR against master is all that is needed and we will cherry-pick. If the cherry-pick is not trivial, we may ask for a separate PR at that time, but that is rare.

**Comment by brempusz** [comment]
This can't be cherry-picked directly:  There is only one `catch(Ex1 | Ex2 | Ex3 e)` in master but 4.3.x source is 1.6 with multiple `catch()` clauses. Just let me know and I will create PR to 4.3.x.
