### ISSUE TITLE
Reconnection / retry error with Paho MQTT 1.2 leads to ever increasing thread usage

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-integration#2471]
As a follow up to my <a href="https://twitter.com/rotnroll666/status/1003935166484635649">tweet</a>.

Find attached a simple Spring Integration MQTT application ([mqtt-paho-client-threading-bug.zip](https://github.com/spring-projects/spring-integration/files/2075768/mqtt-paho-client-threading-bug.zip)). It's a Spring Boot app, just run

```
./mvnw clean spring-boot:run
```

You'll find the app trying to reach a MQTT broker on `tcp://localhost:45678` (I chose this port to make sure there is no broker answering).

The app will fail, print the MQTT Paho exception and continue.

I'll added a scheduled task that prints the number of live threads. As you see they'll increse by 2 threads after each failed connection retry.

This happens during startup as well as during runtime, for example if the broker goes away in between.

A downgrade to Paho 1.1.1 as suggested in https://github.com/eclipse/paho.mqtt.java/issues/402 respectivly https://github.com/SebaDro/SOS/commit/8b9f09eacdc842655274a9c94a64486067db3f5b helps, for example like this:

```
    <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-mqtt</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.paho</groupId>
                    <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
```

With Paho 1.1.1 the number of threads stays constant.

**Comment by hbergmey** [comment]
Unfortunately I cannot go back to 1.1.1 as then my client connections become unstable. As a matter of fact, I do not receive any further messages after the initial topic report. Paho 1.2.0 fixed this strange behavior.

Somehow we need to fix the thread shutdown issue.

**Comment by garyrussell** [comment]
They really need to fix the client; we can look at closing/creating a new client each time, but that just seems wrong.

**Comment by hbergmey** [comment]
Looking into the Paho Code, I see that the MqttAsyncClient can be setup to use an explicitly given ThreadPool like so:

`new MqttAsyncClient(url, clientId, persistence, new TimerPingSender(), Executors.newScheduledThreadPool(10))`

Do you see a chance to explicitly kill this threadpool on app/container shutdown?

**Comment by garyrussell** [comment]
My mistake; it's our bug; we do create a new client on each attempt; we just don't clean up the old one.

**Comment by hbergmey** [comment]
I join the "mea culpa" chant: My mistake was the @PreDestroy annotation at the wrong class. Obviously it only works in a Spring service.

I am now calling:
```
				IMqttToken disconnectToken = mqttClient.disconnect();
				disconnectToken.waitForCompletion(10000);
				mqttClient.close(true);
   			        mqttClient = null;
```

**Comment by garyrussell** [comment]
I tested your app against the snapshot locally and there is no more leak.

Releases that will include this fix are scheduled for next Wednesday.

**Comment by michael-simons** [comment]
Wow, awesome reaction. Thanks a lot!

**Comment by garyrussell** [comment]
Need similar logic in the outbound adapter.

**Comment by jmax01** [comment]
> 
> 
> Need similar logic in the outbound adapter.

Thanks!
