### ISSUE TITLE
File Handle Leak in RecursiveDirectoryScanner

### ISSUE THREAD

**Issue by Koizumi85** [spring-projects/spring-integration#2478]
Hi everyone,

I think there is a file handle leak in the `RecursiveDirectoryScanner` class in the current version (5.0.5.RELEASE).
I experienced Exceptions with "too many open files" in the `RecursiveDirectoryScanner` and followed it down to the following code in the `listFiles(File)` method:

```
try {
			Stream<File> fileStream = Files.walk(directory.toPath(), this.maxDepth, this.fileVisitOptions)
					.skip(1)
					.map(Path::toFile)
					.filter(file -> !supportAcceptFilter
							|| ((AbstractFileListFilter<File>) filter).accept(file));

	if (supportAcceptFilter) {
		return fileStream.collect(Collectors.toList());
	}
	else {
		return filter.filterFiles(fileStream.toArray(File[]::new));
	}
} catch (IOException e) {
	throw new IllegalArgumentException(e);
}
```

According to this Stackoverflow thread and my own experiences you have to close the `Stream` returned by `Files.walk`.

So the code should be changed to something like this in my opinion:

```
try (Stream<File> fileStream = Files.walk(directory.toPath(), this.maxDepth, this.fileVisitOptions).skip(1)
				.map(Path::toFile)
				.filter(file -> !supportAcceptFilter || ((AbstractFileListFilter<File>) filter).accept(file));) {

	if (supportAcceptFilter) {
		return fileStream.collect(Collectors.toList());
	}
	return filter.filterFiles(fileStream.toArray(File[]::new));
} catch (IOException e) {
	throw new IllegalArgumentException(e);
}
```

I created my own `RecursiveDirectoryScanner` with this fix and unless now I couldn't reproduce the Exceptions again.

**Comment by artembilan** [comment]
I would suggest you to provide a [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc), but having a dead line to release `5.0.6` today I'm going to PR it myself. Anyway thank you for the good report an solution!

Looking forward for more feedback from you!

**Comment by Koizumi85** [comment]
@artembilan 
I was thinking about making the PR, but we are in the release phase of our current project, so there is absolutely no time for it. Thank you for the feedback and the work on the PR :)
