### ISSUE TITLE
Extending RemoteFileTemplate to also support InputStream from streaming operations

### ISSUE THREAD

**Issue by silkentrance** [spring-projects/spring-integration#2491]
## Enhancement

Currently, the RemoteFileTemplate only supports either File, String or byte[] as the Message source type.

For streaming purposes, though, it would be nice to have it also support message sources of type InputStream.

Rationale behind this that we build our data in-memory and then render it as an input stream or get the resource from an internal service via a REST API, and we do not want to again store the information on the local storage as the overall volume would exceed the size of the local storage.

**Comment by silkentrance** [comment]
I can provide you with a PR for this if you like.

**Comment by artembilan** [comment]
Sorry, what operation do you mean?
There is the code like this for `send()`:
```
private StreamHolder payloadToInputStream(Message<?> message) throws MessageDeliveryException {
		try {
			Object payload = message.getPayload();
			InputStream dataInputStream = null;
			String name = null;
			if (payload instanceof InputStream) {
				dataInputStream = (InputStream) payload;
			}
			else if (payload instanceof File) {
				File inputFile = (File) payload;
				if (inputFile.exists()) {
					dataInputStream = new BufferedInputStream(new FileInputStream(inputFile));
					name = inputFile.getAbsolutePath();
				}
			}
			else if (payload instanceof byte[] || payload instanceof String) {
				byte[] bytes = null;
				if (payload instanceof String) {
					bytes = ((String) payload).getBytes(this.charset);
					name = "String payload";
				}
				else {
					bytes = (byte[]) payload;
					name = "byte[] payload";
				}
				dataInputStream = new ByteArrayInputStream(bytes);
			}
			else {
				throw new IllegalArgumentException("Unsupported payload type. The only supported payloads are " +
						"java.io.File, java.lang.String, byte[] and InputStream");
			}
			if (dataInputStream == null) {
				return null;
			}
			else {
				return new StreamHolder(dataInputStream, name);
			}
		}
		catch (Exception e) {
			throw new MessageDeliveryException(message, "Failed to create sendable file.", e);
		}
	}
```

So, the `if (payload instanceof InputStream) {` is indeed supported there.

We are fully open for contribution though. 
Maybe with your PR it becomes much cleaner what is the problem you try to point out.

Thank you!

**Comment by artembilan** [comment]
BTW we had this in the past: https://jira.spring.io/browse/INT-3746.

So, maybe your problem that you are in the version where `InputStream` is not supported yet ?..

**Comment by silkentrance** [comment]
Oh yes, you are correct in that I forgot to mention that this is not available in spring 4.

**Comment by silkentrance** [comment]
Is it possible to port back this behaviour as we are currently stuck with spring 4 due to spring-boot 1.5.x.

**Comment by artembilan** [comment]
Wait! But Spring Boot 2.0 is there for a while already: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes

And what is the fact that even Spring Cloud 2.0 is here as well: https://spring.io/blog/2018/06/19/spring-cloud-finchley-release-is-available

So, any chances to upgrade?
The issue is that even if we back-port this, there is no guarantee how quickly we will release the version for `4.3.x` branch: https://github.com/spring-projects/spring-integration/commits/4.3.x

**Comment by garyrussell** [comment]
It shouldn't be too hard to backport, but, as a work around, you can use

```java
template.execute(s -> {
	s.write(myInputStream, "foobar.txt");
	return true;
});
```

**Comment by silkentrance** [comment]
@artembilan I know, and, frankly speaking, I do not see any reason why we should not migrate. But since this is a rather big project with many stakeholders, the current version of spring boot it set to 1.5.x.

And many thanks for your advice, very appreciated, I will see what I can do about that!

**Comment by silkentrance** [comment]
@garyrussell  Thanks for your advice, very appreciated, I will look into that.

**Comment by silkentrance** [comment]
Please look into backporting this. In the mean time I will close this.

**Comment by silkentrance** [comment]
@garyrussell execute will close the session on finally, we will see how this works out with >2mil documents per year...

**Comment by silkentrance** [comment]
@garyrussell I have settled on extending the existing FileTransferringMessageHandler since the instance of the RemoteFileTemplate is declared as protected, along with your advice of calling execute directly on that instance. Thanks again.

**Comment by silkentrance** [comment]
@garyrussell I have removed the dependency towards FileTransferringMessageHandler and will now just use the RemoteFileTemplate.
