### ISSUE TITLE
Inconsistency with Spring Framework Release Versions

### ISSUE THREAD

**Issue by florianschmitt** [spring-projects/spring-integration#2507]
Hi, 

we just noticed, that in spring-integration Release 4.3.16.RELEASE, there is a dependency to spring-core Release 4.3.**17**.RELEASE [see here](https://github.com/spring-projects/spring-integration/blob/v4.3.16.RELEASE/build.gradle#L139).
Similary, spring-integration Release 4.3.17.RELEASE depends on spring-core Release 4.3.**18**.RELEASE [see here](https://github.com/spring-projects/spring-integration/blob/v4.3.17.RELEASE/build.gradle#L139).

Are these versions supposed to diverge, or is this a mistake? Which of these releases fit together?
Thanks, BR Florian

**Comment by garyrussell** [comment]
They are separate projects on separate release cycles; they just happen to be "close" at this time.

It's generally best to only declare the highest dependency (spring-integration in this case) and let it pull in its dependencies transitively.

The best place to look for curated spring dependencies is in the [spring boot dependency pom](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml) (Boot 2.0) and [here for the 4.3.x versions](https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-dependencies/pom.xml).

**Comment by florianschmitt** [comment]
Alright, thanks for the clarification.
