### ISSUE TITLE
HttpMessageHandlerSpec should not assert true on isClientSet in errorHandler method

### ISSUE THREAD

**Issue by imitbn** [spring-projects/spring-integration#2510]
Using spring-integration-http-5.0.6.RELEASE

If you try to add errorHandler to http outbound gateway, it will couse IllegalArgumentException.

```
@Bean
public IntegrationFlow outbound() {
    return IntegrationFlows.from("httpOutRequest")
        .handle(Http.outboundGateway("http://localhost:8080/foo")
            .httpMethod(HttpMethod.POST)
            .expectedResponseType(String.class)
            .errorHandler(new ResponseErrorHandler() {
                @Override
                public boolean hasError(ClientHttpResponse response) throws IOException {
                    return false;
                }
                @Override
                public void handleError(ClientHttpResponse response) throws IOException {
                }}))
        .get();
}
```

**Comment by artembilan** [comment]
Closed in favor of https://jira.spring.io/browse/INT-4503.

Please, consider do not duplicate the same ticket in JIRA and here on GitHub: they are equal from the back tracking perspective.

The only problem that we don't handle questions in back tracking systems.

(I guess we need to update that Contribution Guidelines doc 😉)

**Comment by artembilan** [comment]
The PullRequest for the reference: https://github.com/spring-projects/spring-integration/pull/2512
