### ISSUE TITLE
Silent error when message endpoint bean is depending on unfinished bean

### ISSUE THREAD

**Issue by fred84** [spring-projects/spring-integration#2565]
## Preconditions

- Spring Boot 2.0.5
- Spring Integration Starter
- Spring Webflux starter 
- Annotation style for message endpoints

## Current behaviour

When message endpoint is depending on unfinished bean
- it will not be registered
- application will start without errors

## Expected behaviour

Application will not start. Error will be written to logs

## Reproduction

https://github.com/fred84/spring-integration-di

**Comment by artembilan** [comment]
It turned out that issue is really on the Spring Boot side.
So, closing this in favor of https://github.com/spring-projects/spring-boot/issues/14666
