### ISSUE TITLE
Assert incorrectly triggered in FileReadingMessageSource

### ISSUE THREAD

**Issue by Stexxen** [spring-projects/spring-integration#2568]
## Bug report

An Assert is triggered incorrectly in FileReadingMessageSource

    FileReadingMessageSource source = new FileReadingMessageSource();
    source.setScanner(new RecursiveDirectoryScanner());
    source.setLocker(new NioFileLocker());
    source.setDirectory(new File(INBOUND_PATH));
    source.setFilter(new IgnoreHiddenFileListFilter());

    source.afterPropertiesSet();

Generates the following Exception

    java.lang.IllegalStateException: The 'filter' and 'locker' options must be present on the provided external 'scanner': org.springframework.integration.file.RecursiveDirectoryScanner@2a7f1f10
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.integration.file.FileReadingMessageSource.onInit(FileReadingMessageSource.java:340)
	at org.springframework.integration.context.IntegrationObjectSupport.afterPropertiesSet(IntegrationObjectSupport.java:176)

This is in 5.0.8.RELEASE.

It is triggered from the following code
https://github.com/spring-projects/spring-integration/blob/master/spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java#L337-L339

    Assert.state(!(this.scannerExplicitlySet && (this.filter != null || this.locker != null)),
				"The 'filter' and 'locker' options must be present on the provided external 'scanner': "
						+ this.scanner);

I can see what it is trying to do, but I think it should be written as follows

    Assert.state(!(this.scannerExplicitlySet && (this.filter **==** null || this.locker **==** null)),
				"The 'filter' and 'locker' options must be present on the provided external 'scanner': "
						+ this.scanner);

Also the error message is kinda wrong, as it's not testing the filter and locker options on the provided scanner, it's actually testing them on the FileReadingMessageSource object and then passing them to the provided scanner in the lines that follow.

If it would expedite things, I can provide a PR?

**Comment by artembilan** [comment]
No sure what makes you think this way, but the logic is like this:

If you provide an external `DirectoryScanner`, that's your responsibility to set `filter` and `locker` there.
In the `FileReadingMessageSource` we can't mutate external object. This is not how dependency injection works.
If you don't provide an external `DirectoryScanner`, you are free to configure `filter` and `locker` on the `FileReadingMessageSource`. In this case we mutate an internal  `DirectoryScanner` instance.
We can't assume what is the configuration of the provided `DirectoryScanner` because this is already not a `FileReadingMessageSource` responsibility.

Does it make sense to you?

Thanks

**Comment by Stexxen** [comment]
ahhhh I see. Thank you for the explanation.

I think the error message would probably be better if it stated something like
_The 'filter' and 'locker' options **should instead** be present on the provided external 'scanner_

As saying '_The 'filter' and 'locker' options must be present on the provided external 'scanner'_ suggests that the code is testing the external scanner, which it is not doing.

Cheers,
S.

**Comment by artembilan** [comment]
That sounds fine with me.
Feel free to open Pull Request on the matter!

Thanks
