### ISSUE TITLE
connectionOptions ServerURIs ignored

### ISSUE THREAD

**Issue by gregdymek** [spring-projects/spring-integration#2577]
```
Assert.state(this.getUrl() != null || connectionOptions.getServerURIs() != null,
 "If no 'url' provided, connectionOptions.getServerURIs() must not be null");
IMqttAsyncClient client = this.clientFactory.getAsyncClientInstance(this.getUrl(), this.getClientId());
```
it looks like server uris are ignored, when creating mqtt client

**Comment by artembilan** [comment]
The `connectionOptions` is used a bit late:
```
this.client.connect(connectionOptions);
```

And if we take a look into the `MqttAsyncClient`, we will see the logic like this:
```
String[] serverURIs = options.getServerURIs();
		String[] array = null;
		if (serverURIs == null) {
			array = new String[] { address };
		} else if (serverURIs.length == 0) {
			array = new String[] { address };
		} else {
			array = serverURIs;
		}
```

Does it make sense to you?

What issue do you have with that?

**Comment by gregdymek** [comment]
I was getting NO_URL_PROVIDED in server url when I provided serverUris in MqttConnectOptions as it's described here https://docs.spring.io/spring-integration/reference/html/mqtt.html so I had to use MqttPahoMessageHandler constructor with url, so these serverUris were not used, I'm serious :)

**Comment by artembilan** [comment]
Closed as *Invalid* because of lack of feedback from the reporter and no way to reproduce and understand a behavior.
