### ISSUE TITLE
MockIntegrationContext substituteMessageHandlerFor not working for ReactiveStreamsConsumer

### ISSUE THREAD

**Issue by dschulten** [spring-projects/spring-integration#2582]
Replacing a message handler in unit tests does not work for ReactiveStreamsConsumer:

https://github.com/spring-projects/spring-integration/blob/262e624ef47b6ac2709ed480c6e9614ebc96736f/spring-integration-test/src/main/java/org/springframework/integration/test/context/MockIntegrationContext.java#L139

assumes that the handler is a field named `handler`. However, ReactiveStreamsConsumer has a field named `messageHandler`:

https://github.com/spring-projects/spring-integration/blob/262e624ef47b6ac2709ed480c6e9614ebc96736f/spring-integration-core/src/main/java/org/springframework/integration/endpoint/ReactiveStreamsConsumer.java#L52

**Comment by dschulten** [comment]
Closed in favor of https://jira.spring.io/browse/INT-4537

**Comment by artembilan** [comment]
Please, don't duplicate the same issue in several places.
This is fully fine to have just JIRA or this GH issue. 
We manage them all as equal entities.

Thank you for the report BTW! Will fix soon.
