### ISSUE TITLE
Question: Potential bug with sftp session reuse?

### ISSUE THREAD

**Issue by davidgoate** [spring-projects/spring-integration#2605]
Is there something we are supposed to do to close SFTP sessions? If we leave a service running for ore than a couple of days (anecdotal I know), this is the error we see:

>Caused by: java.io.IOException: inputstream is closed
com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2911) ~[jsch-0.1.54.jar!/:na]
com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935) ~[jsch-0.1.54.jar!/:na]
com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:583) ~[jsch-0.1.54.jar!/:na]

>org.springframework.integration.sftp.session.SftpSession.write(SftpSession.java:155) ~[spring-integration-sftp-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]

If we restart the service, it'll immediately start "working" again.

My guess as perhaps some sort of connection pool is remaining open, or maybe there is some setting I am omitting to ensure the connections/sessions are handled properly.

# Code:

```java
@Configuration
@RequiredArgsConstructor
@EnableConfigurationProperties(SftpProperties.class)
@IntegrationComponentScan
@EnableIntegration
public class SftpConfiguration {
    private final SftpProperties properties;

    @Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return new CachingSessionFactory<>(sessionFactory);
    }

    @Bean
    @ServiceActivator(inputChannel = "test")
    public MessageHandler handler(@Autowired final SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory) {
        final SftpMessageHandler handler = new SftpMessageHandler(sftpSessionFactory);
        handler.setRemoteDirectoryExpression(new LiteralExpression(properties.getDirectory()));
        handler.setFileNameGenerator(message -> namingService.getName());
        handler.setUseTemporaryFileName(false);
        handler.setCharset(UTF_8.name());
        return handler;
    }
}
```

Could this be down to the use of a `CachingSessionFactory`? If this is the case, is there some process (like with JDBC connection pools) that would be used to keep connections alive or evict "dead" ones periodically?

**Comment by artembilan** [comment]
What you say really has to be done with the `CachingSessionFactory`: https://docs.spring.io/spring-integration/reference/html/sftp.html#sftp-session-caching

Actually the `@ServiceActivator` is a passive component and it obtains a session from even the `DefaultSftpSessionFactory` on demand. Therefore the next call should bring a new session anyway, since you don't use a `isSharedSession` flag.

You also can consider to use a `RequestHandlerRetryAdvice` for that `@ServiceActivator` to retry a write for the current request message in case of errors: https://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#retry-advice

Let us know how it works for you!

I don't see any problems from the Framework perspective.

**Comment by davidgoate** [comment]
@artembilan thanks for the feedback. I understand from what you're saying here that one way to improve stability would be to implement a retry on failure strategy, this sounds good for achieving my end goal of having the file successfully sent. What's less ideal though from my perspective,  is understanding what might have caused the issue in the first place - I see this routinely (not just a one off here or there) and the pattern it appears to follow is that after the app has been running for more than a couple of days these errors become more frequent and with (so far) 100% reliability simply restarting the app fixes the issue.

Could this actually just be that I have defined the session factory as a bean? Give this would (AKAIK) become a singleton in the context even is the service activator itself is called each time passively wouldn't it be provided with the session factory instance from the context which is a long lived singleton (and perhaps the caching comes into play)?

**Comment by artembilan** [comment]
No, that's not. The `DefaultSftpSessionFactory` is just stateless factory. It doens't hold sessions created on demand. And the `SftpMessageHandler` uses a `RemoteFileTemplate.execute(SessionCallback<F, T> callback)` which does this in the end:
```
finally {
			if (!invokeScope) {
				try {
					session.close();
				}
				catch (Exception ignored) {
					if (this.logger.isDebugEnabled()) {
						this.logger.debug("failed to close Session", ignored);
					}
				}
			}
		}
```
So, `session` is closed after each usage.

This is not a  `DefaultSftpSessionFactory` responsibility to retry in this case. That's definitely a target service matter.

There might be some policy on the SSH server though which is out of our control from the application perspective.

Not sure what you would like to see improved from our side...

**Comment by davidgoate** [comment]
@artembilan  thanks for the clarification. It wasn't anything in particular I was looking to improve. I was just hoping I'd missing something obvious with configuration or caching as an explanation for why I see these stream closed exceptions. If it's nothing to do with the session factory or the message handler then, as you say, perhaps there is nothing that can be done. It could be a problem with the target SFTP server closing connections perhaps, it just feels odd to me that I can reliably recreate this by running the app for a few days or more and then I can reliably fix the issue with a simple service restart. It felt a lot like "connection pools" or "reused sessions" which is what brought my attention to something with the name `CachingSessionFactory`. So it's right so say then based on your comments above that as far as spring integration is concerned these two are totally equivalent:


```java
@Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return new CachingSessionFactory<>(sessionFactory);
    }
```

and

```java
@Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return sessionFactory;
    }
```

In both cases the session factory will create a brand new connection (not reuse an old one) and this new connection is what is used to connect to the SFTP server.

**Comment by artembilan** [comment]
Oh! Sorry. I see what you mean.
I have missed this line ` return new CachingSessionFactory<>(sessionFactory);`.
Well, try to make a separate bean:
```
    @Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return sessionFactory;
    }

@Bean
public SessionFactory<ChannelSftp.LsEntry> cachingSftpSessionFactory( SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory) {
        return new CachingSessionFactory<>(sessionFactory);
    }
```

The `DefaultSftpSessionFactory` has to be managed by the application context as well.

**Comment by davidgoate** [comment]
@artembilan  ok thanks, will give this a go.

**Comment by garyrussell** [comment]
When we get a cached session for the pool, we check it's open state...

```java
			@Override
			public boolean isStale(Session<F> session) {
				return !session.isOpen();
			}
```

For SFTP, this maps to...

```java
	@Override
	public boolean isOpen() {
		return !this.closed && this.jschSession.isConnected();
	}
```

So, perhaps JSch is not correctly reporting a closed session.

I suppose we could consider enhancing the `isStale()` method to perform some simple operation instead.

**Comment by garyrussell** [comment]
BTW, one possibility is some network device (switch, router etc) might silently drop an idle connection (and neither the client nor server are informed).

However, I just tested it by shutting down the sshd server and JSch still reports that the session is connected.

**Comment by garyrussell** [comment]
My mistake; I killed the main daemon but the sshd instance I was connected too was still running.

**Comment by artembilan** [comment]
Ha, that's true!
`com.jcraft.jsch.Session`
```
 public boolean isConnected(){ return isConnected; }
```

So,  it does nothing, but simple `boolean` flat check.

Maybe use for that purpose a `sendIgnore()` or `sendKeepAliveMsg()`?

**Comment by davidgoate** [comment]
@garyrussell thanks for commenting on this. My "workaround" at this time is to change my code from:


```java
@Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return new CachingSessionFactory<>(sessionFactory);
    }
```

to

```java
@Bean
    @ConditionalOnMissingBean(name = "sftpSessionFactory")
    public SessionFactory<ChannelSftp.LsEntry> sftpSessionFactory() {
        final DefaultSftpSessionFactory sessionFactory = new DefaultSftpSessionFactory();
        sessionFactory.setHost(properties.getHost());
        sessionFactory.setPort(properties.getPort());
        sessionFactory.setUser(properties.getUser());
        sessionFactory.setPassword(properties.getPassword());
        sessionFactory.setAllowUnknownKeys(true);
        return  sessionFactory;
    }
```

I assume that's sufficient to avoid the possibility of caching behaviour from the `CachingSessionFactory`, but I think it'd be useful if the pooling behaviour did take care of this. In my case I'm actually running a batch job once a day, so the need for a session cache is probably overkill - but I'm sure such an issue could catch someone else out who has more of a need for this! Thanks for taking a look into this.

**Comment by Poorva17** [comment]
Hey team, I am using `spring-integration-sftp` version `5.5.12`.

I am using following code to create session factory.

```java
    DefaultSftpSessionFactory factory = new DefaultSftpSessionFactory(true);
    factory.setHost(myConfig.getHost());
    factory.setPort(myConfig.getPort());
    factory.setUser(myConfig.getUser());
    if (myConfig.getPrivateKey() != null) {
      factory.setPrivateKey(myConfig.getPrivateKey());
      factory.setPrivateKeyPassphrase(myConfig.getPrivateKeyPassphrase());
    } else {
      factory.setPassword(myConfig.getPassword());
    }
    factory.setAllowUnknownKeys(true);
    factory.setSessionConfig(buildSessionProperties(myConfig));
    factory.setTimeout(5000);
    factory.setChannelConnectTimeout(Duration.ofSeconds(5));
```


I am getting error: `failed to create SFTP connection. IllegalStateException`.
Reason for Illegal state exception is different like input stream closed, read timeout etc.

**Questions**
1. Is it something to do with connection timeout or using shared state flag being true while creating SFTP connection?
2. Will updating sprin-integration-sftp version to 6.x.x where JSch is replaced by APACHE MINA help in this case?

**Comment by artembilan** [comment]
@Poorva17 ,

This is very old issue and it has been closed for a while.
Please, consider to raise question on StackOverflow with much more info, like stack traces and so on.
It is very hard to connect your minimal story with whatever context is resolved in this issue.

**Comment by Poorva17** [comment]
hey @artembilan sure. I will raise slack overflow question.
