### ISSUE TITLE
JdbcChannelMessageStore: poor performance for large buffers (Oracle+?)

### ISSUE THREAD

**Issue by abrensch** [spring-projects/spring-integration#2628]
## Bug report

Hi,

having a performance-issue with JdbcChannelMessageStore.pollMessageFromGroup (spring integration 4.3.17, Oracle 12c ):

the processing time of the polling query (OracleChannelMessageStoreQueryProvider.getPollFromGroupQuery) scales linear with the number of messages for that group, adding about 1 microsecond per message to the query-time, so starting from 50k buffered messages it gets nasty.

Looking at Oracle's execution plan it has to scan and sort the table on every poll. Oracle CAN create execution plans that take the sort-order from an index, but that's very touchy and everything in the query that does not look like just following the index will cause it to fallback to the default scan+sort plan.

I did not check for Postgres and MySQL, so maybe it's just an Oracle issue?

The indexing from the schema-oracle.sql script looks quite sophisticated, so it seems it was engeneered at some point in time for high performance but degraded with later extensions?

thanx for checking,

regards, Arndt

**Comment by garyrussell** [comment]
Hmmm, the query is

```java
	@Override
	public String getPollFromGroupQuery() {
		return "SELECT %PREFIX%CHANNEL_MESSAGE.MESSAGE_ID, %PREFIX%CHANNEL_MESSAGE.MESSAGE_BYTES from %PREFIX%CHANNEL_MESSAGE " +
				"where %PREFIX%CHANNEL_MESSAGE.GROUP_KEY = :group_key and %PREFIX%CHANNEL_MESSAGE.REGION = :region " +
				"order by CREATED_DATE, MESSAGE_SEQUENCE FOR UPDATE SKIP LOCKED";
	}
```

And the iindex:

    CREATE INDEX INT_CHANNEL_MSG_DATE_IDX ON INT_CHANNEL_MESSAGE (CREATED_DATE, MESSAGE_SEQUENCE);

Looks to me like the index should be groupkey, region, createdDate, sequence.

Also, unlike MySQL (for example) `LIMIT 1`, I don't see a [row limiting clause](https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#BABBADDD).

cc/ @artembilan

**Comment by artembilan** [comment]
Gary, looks like you don't need me 😄 You are fully on board with the subject!

We need to dig for indexes though: I thought they are applied just for the `order by`, not the `where`...

And yes: I agreed that we need to limit the number of rows returned. That's definitely a cause of slowness when we have more and more records in the table.

I guess we have never tested it against Oracle.
I'm even not sure how it works at all since we have there this logic:
```
	Assert.state(messages.size() < 2,
				() -> "The query must return zero or 1 row; got " + messages.size() + " rows");
```

**Comment by artembilan** [comment]
Yeah... Looks like I'm wrong about indexes: https://docs.oracle.com/cd/E11882_01/server.112/e40540/indexiot.htm#CNCPT1895

> Composite indexes can speed retrieval of data for SELECT statements in which the WHERE clause references all or the leading portion of the columns in the composite index. Therefore, the order of the columns used in the definition is important. In general, the most commonly accessed columns go first.

So, the index must be on the `GROUP_KEY, REGION`  as well: https://use-the-index-luke.com/sql/sorting-grouping/indexed-order-by

And looks like we don't need to do an explicit `order by` after that at all.

@abrensch , you can implement your own `OracleChannelMessageStoreQueryProvider` and modify DB schema according your concerns.

Please, come back then to us with some feedback.

**Comment by garyrussell** [comment]
I have an old 10g XE installed on a VM; I just tested with 

    CREATE INDEX INT_CHANNEL_MSG_DATE_IDX ON INT_CHANNEL_MESSAGE (GROUP_KEY, REGION, CREATED_DATE, MESSAGE_SEQUENCE);

But it made no difference - 51+ seconds to retrieve 5k messages.

10g doesn't support the row limiting clause, but we don't really need it because we set the `JdbcTemplate` fetch size and max rows to 1.

**Comment by artembilan** [comment]
I think our index should start from the `REGION`, as well as queries - from bigger span to smaller.
But I still believe that won't make difference as you said...
Maybe that `setFetchSize(1)` and `setMaxRows(1)` don't have effect on Oracle and just drop extra records on the driver level, but not in the DB directly?..

**Comment by garyrussell** [comment]
It looks like they honor the fetch size (according to [their docs](https://docs.oracle.com/cd/A97335_02/apps.102/a83724/resltse5.htm)).

**Comment by artembilan** [comment]
Good. So, what does your "51+ seconds to retrieve 5k messages." mean then? How fast queue channel is polled or is this really a result of that our query execution directly in Oracle?

**Comment by garyrussell** [comment]
I am not sure; the explain plan certainly looks better.

Old

<img width="1393" alt="screen shot 2018-11-13 at 4 00 36 pm" src="https://user-images.githubusercontent.com/483832/48442871-6a86e400-e75d-11e8-92b8-ba5f039d6279.png">

New

<img width="1646" alt="screen shot 2018-11-13 at 3 55 52 pm" src="https://user-images.githubusercontent.com/483832/48442883-75417900-e75d-11e8-9930-afd869ac56db.png">

This is my test code; no delays there...

```java
	@Bean
	public ApplicationRunner runner(QueueChannel channel) {
		return args -> {
			for (int i = 0; i < 5_000; i++) {
				channel.send(new GenericMessage<>("foo"));
			}
			Message<?> received;
			logger.info("Starting");
			StopWatch watch = new StopWatch();
			watch.start();
			do {
				received = channel.receive(10_000);
			} while (received != null);
			watch.stop();
			logger.info(watch.prettyPrint());
		};
	}
```

**Comment by artembilan** [comment]
Do you use connection poll in your application?
Although that still might not help. It's just a cost of this message store. Might even be the fact that we spend a lot of time on the deserialization...

**Comment by artembilan** [comment]
Gary, pay attention, please, to the #2629.
When we call `channel.receive(10_000)`. we also include a `COUNT` query into the business which looks pretty bad for Postgre. so might be the same issue with Oracle as well.

Have just tested your scenario against in memory H2. There is no too much difference between old index and new one (just a couple milliseconds):
```
StopWatch '': running time (millis) = 10005
...
StopWatch '': running time (millis) = 10001
```
And, please, exclude 10 seconds for the last iteration since we are blocked for this time waiting for the message to appear in the store.

I think we still need to fix index anyway and really introduce that `isEmpty()` implementation.

**Comment by garyrussell** [comment]
The plot thickens - in my environment, the new index is slower and gets worse, and the old index shows consistent performance...

![oracle](https://user-images.githubusercontent.com/483832/48493106-3a8d1e80-e7f9-11e8-8182-94b538625eae.png)

The Y axis is the average time to retrieve 1 message when the initial count is on the X axis.

**Comment by garyrussell** [comment]
Doh - reworking without that 10 seconds...

**Comment by garyrussell** [comment]
Doh - reworked without that 10 seconds.

**Comment by garyrussell** [comment]
Updated to use a 0 consumer (receive) timeout - to avoid the `select count(message_id)` call.

Improved, but still the same trends...

![oracle](https://user-images.githubusercontent.com/483832/48497946-20583e00-e803-11e8-9820-bd8db25b7da9.png)

**Comment by artembilan** [comment]
So, do you want to say that even query plan is better that doesn't mean that the whole performance is improved?

**Comment by garyrussell** [comment]
I don't know - it just seems odd to me that an index specifically tailored to the query is not faster.

**Comment by artembilan** [comment]
It takes 20 seconds on MySQL to poll those 5000 messages. This is with the `size()`.

Without `size()` we have just 13 seconds.

With new index and without size we got only one second improvement.

**Comment by artembilan** [comment]
JIRA on the matter: https://jira.spring.io/browse/INT-4553

**Comment by garyrussell** [comment]
@abrensch After testing, this is what we are proposing:

```sql
CREATE TABLE INT_CHANNEL_MESSAGE (
	MESSAGE_ID CHAR(36) NOT NULL,
	GROUP_KEY CHAR(36) NOT NULL,
	CREATED_DATE NUMBER(19,0) NOT NULL,
	MESSAGE_PRIORITY NUMBER(19,0),
	MESSAGE_SEQUENCE NUMBER(19,0) NOT NULL ,
	MESSAGE_BYTES BLOB,
	REGION VARCHAR2(100) NOT NULL,
	constraint INT_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX INT_CHANNEL_MSG_DELETE_IDX ON INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);
-- Only needed if the message store has priorityEnabled set to true
-- CREATE UNIQUE INDEX INT_CHANNEL_MSG_PRIORITY_IDX ON INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_PRIORITY DESC, CREATED_DATE, MESSAGE_SEQUENCE);
```

And, if using a `PriorityChannel`:

```java
class MyOQP extends OracleChannelMessageStoreQueryProvider {

	@Override
	public String getPriorityPollFromGroupQuery() {
		return "SELECT /*+ INDEX(INT_CHANNEL_MESSAGE INT_CHANNEL_MSG_PRIORITY_IDX) */ " +
				"%PREFIX%CHANNEL_MESSAGE.MESSAGE_ID, %PREFIX%CHANNEL_MESSAGE.MESSAGE_BYTES from %PREFIX%CHANNEL_MESSAGE " +
				"where %PREFIX%CHANNEL_MESSAGE.GROUP_KEY = :group_key and %PREFIX%CHANNEL_MESSAGE.REGION = :region " +
				"FOR UPDATE SKIP LOCKED";
	}

}
```
- add index hint and remove order by clause.

Can you verify that it solves your problem?

Thanks

**Comment by abrensch** [comment]
Hi Gary,

thanx for your effort.

Yes that solves the linear scaling problem for the polling query. Making the "size" query dominant at higer level of throughput, just as reported in the sister-issue.

The size query I saw before, but it wasn't dominant, so I did not mention. There's not really any need for a size query - if the poll query has no hit then size = 0 ?

However, the priority-poll query looks like a hack, because it's missing the sort expression, just relying on the index hint to provide the expected sorting. Even if I would be sure that the sort order is the same (I'm not because of the "nulls last" logic in the committed version) - a hint is a hint and must not replace functional logic. 

There's also a swap in uniqueness, and you shouldn't have different logical models (where uniquness is pa part of) for different databse flavors.

but I think I can go with just the index change,

regards, Arndt

**Comment by garyrussell** [comment]
Good point about the sort - however, when I left the `order by`, the explain plan still showed a sort of the whole group.

I think we need the row-limit clause to prevent that  but my 10g XE doesn't support that and I am having trouble installing 18c on Ubuntu.

**Comment by garyrussell** [comment]
You can avoid the `size()` call if you set the poller's `receiveTimeout` to 0.

**Comment by garyrussell** [comment]
Hmmm - just tried this on 12c

```sql
SQL> SELECT /*+ INDEX(INT_CHANNEL_MESSAGE INT_CHANNEL_MSG_PRIORITY_IDX) */ INT_CHANNEL_MESSAGE.MESSAGE_ID from INT_CHANNEL_MESSAGE where 
INT_CHANNEL_MESSAGE.GROUP_KEY = 'foo' and INT_CHANNEL_MESSAGE.REGION = 'DEFAULT' order by MESSAGE_PRIORITY DESC NULLS LAST, CREATED_DATE, 
MESSAGE_SEQUENCE fetch first row only for update skip locked;
SELECT /*+ INDEX(INT_CHANNEL_MESSAGE INT_CHANNEL_MSG_PRIORITY_IDX) */ INT_CHANNEL_MESSAGE.MESSAGE_ID from INT_CHANNEL_MESSAGE where 
INT_CHANNEL_MESSAGE.GROUP_KEY = 'foo' and INT_CHANNEL_MESSAGE.REGION = 'DEFAULT' order by MESSAGE_PRIORITY DESC NULLS LAST, CREATED_DATE, 'MESSAGE_SEQUENCE fetch first row only for update skip locked
*
ERROR at line 1:
ORA-02014: cannot select FOR UPDATE from view with DISTINCT, GROUP BY, etc.
```

So it looks like the sort can't be avoided. At least with the hint, the sort won't actually do anything.

I guess the moral is don't use a priority queue with large groups.
