### ISSUE TITLE
How to handle the XXE attack in spring integration XML 

### ISSUE THREAD

**Issue by nvijaykarthik** [spring-projects/spring-integration#2650]
## Question
We are using Spring Integration XML to Process/Transform XML messages. 
Is there any way to stop the XXE attack. 
If it is a direct java code we can set the values as per the owasp settings
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#SAXTransformerFactory

Is there any thing exposed from spring to leverage that?

**Comment by garyrussell** [comment]
Which components are you using; some components, e.g. `StringSourceFactory` allow the application to pass in a TF rather than just creating a new instance.

But some components, e.g. `ResultToStringTransformer` do not; at a minimum we should allow the user to provide the TF in all cases.

**Comment by artembilan** [comment]
I think we need go ahead and configure all our default XML components usage to be protected from that XXE attack.

At the same time we definitely should expose their properties for possible external custom configuration.

**Comment by nvijaykarthik** [comment]
The sample application is in the following link "https://github.com/nvijaykarthik/spring-integration-xml-jms-sample"
We are trying to introduce the XXE prevention. 

Do i have to override the spring library to add the settings given in OWASP? or does spring provide any config or settings to enable this XXE prevention ?

I am trying to test with the sample xml in the code "https://github.com/nvijaykarthik/spring-integration-xml-jms-sample/blob/master/order.xml"

**Comment by garyrussell** [comment]
We need to make some changes to the framework to support this; we will do this ASAP.

**Comment by garyrussell** [comment]
Please report this to security@pivotal.io
