### ISSUE TITLE
Question on Micrometer Metrics Integration

### ISSUE THREAD

**Issue by chihaiaalex** [spring-projects/spring-integration#2663]
We have an application which was written using the Spring Integration Java DSL. 
When I use the metrics provided by the integration with Micrometer (see: https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/metrics.adoc), 
it would be nice to be able to customize the tags, names and other properties of each component that is registered in a flow. 

For example I have this simple flow:

```
@Bean
public IntegrationFlow processMessage() {
	return IntegrationFlows
			.from("messageProcessingChannel")
			.transform(this::extractFilePath)
			.split()
			.<String, File>transform(File::new)
			.transform(Files.toByteArrayTransformer())
			.channel("fileWriterChannel")
			.get();
}
```

And this is how a metric entry looks like:

spring_integration_send_seconds_count{exception="none",name="processMessage.org.springframework.integration.config.ConsumerEndpointFactoryBean#3",result="success",type="handler",} 1.0
spring_integration_send_seconds_sum{exception="none",name="processMessage.org.springframework.integration.config.ConsumerEndpointFactoryBean#3",result="success",type="handler",} 0.511265659

This looks very non intuitive to me. By looking at it I cannot say which of the transformation or message handling is represented by this component name.

Is this customization possible? Can I rename or apply custom tags to these components?

Thanks!

**Comment by artembilan** [comment]
The `name="processMessage.org.springframework.integration.config.ConsumerEndpointFactoryBean#3"` is a generated bean name for dome of your endpoint in the flow.
To make it more explicit consider to add `id` for them, e.g.:
```
.transform(this::extractFilePath, e -> e.id("extractFilePathTransformer"))
```

Let us know how it works for you!

**Comment by artembilan** [comment]
Closed as answered with comment above.
