### ISSUE TITLE
Question on reactive programming and Spring Integration

### ISSUE THREAD

**Issue by dinizssa** [spring-projects/spring-integration#2680]
I see lots of things going on with reactive programming and Spring 5 and I'm wondering what is the impact on Spring Integration framework itself regarding new features. I already found a few implementations available like Stream, WebFlux, etc. Are there plans for R2DBC and other adapters? Please share if any roadmap available. Thank you!

**Comment by garyrussell** [comment]
We use JIRA to track such issues; e.g. https://jira.spring.io/browse/INT-4566 and https://jira.spring.io/browse/INT-4568

If there is something else you are looking for, open issues there.

**Comment by artembilan** [comment]
There is also `FluxMessageChannel`, `ReactiveStreamsConsumer` and reactive polling mode for the `SourcePollingChannelAdapter`, when an output channel is a `FluxMessageChannel`.

I find this question as answered so closing.
Any other feature requests should go to the mentioned JIRA bug tracker.

Thanks for understanding.
