### ISSUE TITLE
Custom dirty Session using RemoteFileTemplate?

### ISSUE THREAD

**Issue by alturkovic** [spring-projects/spring-integration#2687]
I needed to implement a `CachingSessionFactory` but using a different kind of `Pool`. Currently, `CachingSessionFactory` uses `SimplePool` in the constructor.  I needed a pool which does some checks and synchronization over Redis. More specifically, I need to make sure I do not open more than X sessions toward one FTP server at any time. Since I am using this in a distributed environment, `SimplePool` does not meet my needs.

I've created a new Factory, but now I cannot mark my Session dirty because of the instance check in [RemoteFileTemplate.execute(SessionCallback)](https://docs.spring.io/spring-integration/api/org/springframework/integration/file/remote/RemoteFileTemplate.html#execute-org.springframework.integration.file.remote.SessionCallback-). Would it be possible to change this instance check from `CachingSessionFactory<?>.CachedSession` to a new interface like `DirtySession` so we can have custom `Session` implementations which can be marked dirty on exception?

**Comment by garyrussell** [comment]
@alturkovic  Yes; we should do something like that; now that we are on Java 8; we can add a `default` `dirty()` method to `Session` and always call it.

We have a bunch of releases going out today; we may not be able to get this in, though; feel free to issue a PR and we will try.
