### ISSUE TITLE
Can configure @EnablePublisher(proxyTargetClass=true)

### ISSUE THREAD

**Issue by italktothewind** [spring-projects/spring-integration#2695]
## Enhancement

Problem: As discussed in https://stackoverflow.com/questions/54150939/spring-cloud-stream-and-publisher-annotation-compatiblity/54151130, services using `@Publisher` annotation can't be injected using `@Autowire`

Possible solution: using an annotation like `@EnablePublisher(proxyTargetClass=true)`. Other proxy implementations of Spring like `@Cacheable` or `@Async` use this flag.

**Comment by artembilan** [comment]
Please, make yourself familiar with GitHub comments formatting, especially about code snippets: https://help.github.com/articles/basic-writing-and-formatting-syntax/

You are welcome to come back to us with Contribution: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by garyrussell** [comment]
Until the annotation is fixed, I added a work around [here](https://stackoverflow.com/questions/54119209/spring-cloud-stream-sendto-annotation-not-working/54119620#54119620).

**Comment by artembilan** [comment]
Another issue is like this: https://stackoverflow.com/questions/54207305/spring-cloud-stream-streamlistener-processing-messages-twice. 

To reconsider the `PublisherAnnotationBeanPostProcessor` bean as really a singleton and don't depend on particular name.
However at the same time end-user may declare several of them, so maybe it is better consider do not apply the `PublisherAnnotationAdvisor` to the same bean more than once.
