### ISSUE TITLE
Refactor PollSkipAdvice into an AbstractMessageSourceAdvice

### ISSUE THREAD

**Issue by cdombroski** [spring-projects/spring-integration#2717]
As the point of PollSkipAdvice is to skip fetching messages from the source based on some condition, it can be refactored into a AbstractMessageSourceAdvice instead of the MethodInterceptor it implements now.

**Comment by cdombroski** [comment]
I should be able to submit a PR for this today.

**Comment by garyrussell** [comment]
Thanks!

**Comment by garyrussell** [comment]
Actually, @artembilan just pointed out that the `PollSkipAdvice` can be used on a `PollingConsumer` as well, not just a polled message source.

So we can't refactor it; we could still provide a canned advice for this as well, but it would have to be a new class (and would perhaps be redundant).

**Comment by cdombroski** [comment]
Hmm... I can write it as a new class (thinking MessageSourceSkipAdvice), but without further work it would depend on a 'PollSkipStrategy' which in my mind doesn't quite match the idea conveyed by the new class name.

**Comment by cdombroski** [comment]
That commit is just a thought of what we could do. I can make a PR if it's good or make improvements if you have suggestions.

**Comment by artembilan** [comment]
@cdombroski ,

As @garyrussell , pointed out that `PollSkipAdvice` covers already such a `MessageSource`. So, we can simply use it over there as well. 
And your code confirms that we don't need extra class on the matter.

So, closing as "Won't Fix" with a "Works as Designed" argument 😄
