### ISSUE TITLE
Add an ability to log SQL queries executing in JdbcTemplate class provided by JdbcPollingChannelAdapter class when debug is enabled.

### ISSUE THREAD

**Issue by morozovivan95** [spring-projects/spring-integration#2727]
**Affects Version(s):** 5.1.2.RELEASE

There is a log message written in `JdbcTemplate` starting with "Executing prepared SQL statement", but it remains not continued with actual SQL query being executed due to the fact that JdbcPollingChannelAdapter does not implement `SqlProvider` interface. 

Are there any significant reasons not to provide this functionality which leads to absence of such an important debug information?

---

**Comment by artembilan** [comment]
Thank you for the report, @morozovivan95 !

I found similar problem in the `JdbcMessageHandler`.
Wasted time to figure out how to simplify our code over there, but looks like there is just on way with the current `JdbcTemplate` API...
