### ISSUE TITLE
File descriptor leak in DefaultSftpSessionFactory

### ISSUE THREAD

**Issue by jgoelen** [spring-projects/spring-integration#2739]
**Affects Version(s):** 5.x

Hi,

We discovered a file descriptor leak in the DefaultSftpSessionFactory. Whenever a new session gets created it reads the private key file without closing the stream ...

```
		// private key
		if (this.privateKey != null) {
			byte[] keyByteArray = StreamUtils.copyToByteArray(this.privateKey.getInputStream());
			// the code does not close the inputstream!!!
			String passphrase = this.userInfoWrapper.getPassphrase();
			...
```
This leak can be problematic when a remote SFTP server is down and the application tries to reconnect every x seconds.

I will create a PR to fix the issue.

**Comment by garyrussell** [comment]
This has already been fixed. See https://jira.spring.io/browse/INT-4498 and https://github.com/spring-projects/spring-integration/pull/2498

We changed it from `StreamUtils` to `FileCopyUtils` for exactly this reason.
