### ISSUE TITLE
Retire ChannelInterceptorAware in favor of org.springframework.messaging.support.InterceptableChannel

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#2749]
Consider to deprecate now with an extension of the `InterceptableChannel` and remove in the next version.

**Comment by artembilan** [comment]
The idea is to deprecate in the current `5.1.x` and remove altogether in the `5.2`.
But I agree that next `5.1.4` may really happen before `5.2 M1` 😄

**Comment by garyrussell** [comment]
We may have to defer the deprecation to 5.2 and remove in 5.3.

**Comment by artembilan** [comment]
Yeah... But that breaking change for protected method name is still going to be there anyway...

**Comment by garyrussell** [comment]
As I said; let's discuss when we have more time.
