### ISSUE TITLE
Consider using assertThatExceptionOfType rather than assertThatThrownBy

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-integration#2760]
Recently Spring Integration [migrated to AssertJ](https://github.com/spring-projects/spring-integration/commit/622d42c71a34df64c7b455e2b56b5a0985417f8b) and started using `assertThatThrownBy()` instead of an `ExpectedException` `@Rule`.

Spring Boot also made the same migration but we opted to use `assertThatExceptionOfType` rather than `assertThatThrownBy` because we felt it was a little easier to use and because it has [specialized versions for `IllegalArguementException`](https://github.com/spring-projects/spring-boot/blob/064f6478df06e23544cd9896600cc6096cd59c20/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/endpoint/EndpointIdTests.java#L50-L53), `IOException` and `IllegalStateException`.

For example, the following:

```java
assertThatThrownBy(() -> listener.onMessage(mock(Message.class)))
				.isInstanceOf(MessageConversionException.class)
				.hasCauseInstanceOf(IllegalStateException.class);
```

would be:

```
assertThatExceptionOfType(MessageConversionException.class).isThrownBy(()->
				listener.onMessage(mock(Message.class)))
				.withCauseInstanceOf(IllegalStateException.class);
```

We also have a [checkstyle rule](https://github.com/spring-projects/spring-boot/blob/7b0004d6c31b945024a5b0f7bea55b4984af0853/src/checkstyle/checkstyle.xml#L20-L28) to enforce the use of `assertThatIllegalArgumentExceptionIsThrownBy()` etc.

I thought it was worth raising an issue in case you also wanted to consider it.

**Comment by artembilan** [comment]
Nice! Thank you @philwebb !

Will consider to do that soon. 😄
