### ISSUE TITLE
Add discard channel support for splitters

### ISSUE THREAD

**Issue by alturkovic** [spring-projects/spring-integration#2765]
When encountering empty collections, splitter should be able to send the result to a discard channel. Currently, when encountering an empty collection, the splitter ends the flow. Some use-cases may rely on a custom split function which may returns empty collections. These use-cases should be able to define a discard channel so they can proceed with a possible compensation flow.

**Comment by artembilan** [comment]
Only correction that we should discard a *request message*, not a result of split function. Something similar what we have with a `filter` or an `aggregator`.
