### ISSUE TITLE
Consider Adding a DynamicSessionFactory

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#2771]
Questions about dynamic (S)FTP destinations come up a lot (example: https://stackoverflow.com/questions/54925614/setting-sftp-configuration-property-value-by-using-respective-message-header-key).

The [dynamic-ftp](https://github.com/spring-projects/spring-integration-samples/tree/master/advanced/dynamic-ftp) sample app is a reasonable solution, but we could consider adding a `DynamicSessionFactory` interface and implementations that can handle the situation with less complexity for the user.

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/INT-3205 for more info.
