### ISSUE TITLE
MessagePublishingErrorHandler Log does not handle logback-spring configuration

### ISSUE THREAD

**Issue by MiticoPalla** [spring-projects/spring-integration#2775]
**Affects Version(s):** \5.1.3.RELEASE

---
## Bug report
Hello,
i am trying to managethe logs for the class MessagePublishingErrorHandler but it seems that this particular class is not picking up the configuration from the logback-spring.xml configuration file.

For example, two things happens: A log of level WARN is written into the log even thought the root logger is set to have a INFO level (and no other category intercept this log) and a custom regex-replace I implementend is not taken into account (while it is working on classes like LoggingHandler)

Could you please give a look at that? 

Thanks

**Comment by artembilan** [comment]
Not sure what is your concern. If you don't have any specific logger configuration, the ROOT is going to be applied and `INFO` is lower than `WARN`, therefore it is showed in logs.
I'm sure If you configure the ROOT to the `ERROR`, such a `WARN` from the `MessagePublishingErrorHandler` is going to disappear from your logs.

Otherwise, please, share some minimal project to play with. And also some instruction how to reproduce.

Thanks for understanding.

**Comment by MiticoPalla** [comment]
Oh right, sorry for that, I overlooked the logger level. :-(

BTW my main concern is about the regex replace expression not working correctly. 
Actually i am using this as a pattern for my logback configuration: 

[%d{yyyy-MM-dd HH:mm:ss.SSS}] - ${PID:-????} %5p [%t] --- %c{1}: %replace(%msg){'Bearer\s[0-9a-zA-Z_\.\n\r-]{798}','***'}%n

So i can mask the autentication token when it gets logged. 

This replacement works for LoggingHandler class logs (i have logging-channel-adapter wire-tapping on the channel) but not for MessagePublishingErrorHandler direct logs that are written when for example a message is not delivered.

example : "Error message was not delivered.
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.errorChannel'... "

**Comment by artembilan** [comment]
I think such a question should go to the Logback project already.
My only guess that your `replace()` works for regular log messages, but doesn't for exceptions included to the logging, like we do in the `MessagePublishingErrorHandler`:
```
this.logger.warn("Error message was not delivered.", errorDeliveryError);
```

**Comment by MiticoPalla** [comment]
I have opened a bug for logback team to look on. Thanks for the feedback.

**Comment by garyrussell** [comment]
Thanks. Please add a link here so we can follow along.

**Comment by MiticoPalla** [comment]
yeah, of course https://jira.qos.ch/browse/LOGBACK-1459

**Comment by artembilan** [comment]
So, doesn't look like there is something we can do from Spring Integration project perspective.

Closing as *Invalid*
