### ISSUE TITLE
Publisher confirms timeout

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-integration#2797]
Related to: [this](https://stackoverflow.com/questions/54713121/spring-integration-publisher-confirms-with-timeout)

Problem I encountered is that at least once a week I get message that is not being confirmed from broker using Publisher Confirms as received. In this situation, my code is waiting for this signal from broker indefinitely (until process is restarted).

Is it possible to introduce publisherConfirmsTimeout that can be set, and if timeout is exceeded, we should treat message as not delivered (and probably send again).

**Comment by garyrussell** [comment]
Moved this to Spring Integration - it turns out we don't need changes in Spring AMQP; we already have a method on `RabbitTemplate` `getUnconfirmed(long age)`.

So, the channel adapter can have a scheduled task to call that method and emit any results on the nack channel.
