### ISSUE TITLE
Deprecate MetricsFactory and friends

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#2803]

**Comment by artembilan** [comment]
@garyrussell ,

Does it mean not only to deprecate `MetricsFactory` and everything around, but also remove their usage from our components?
For example in this code from the `AbstractMessageChannel`:
```
if (countsAreEnabled) {
				metricsContext = metrics.beforeSend();
				if (this.metricsCaptor != null) {
					sample = this.metricsCaptor.start();
				}
				sent = doSend(message, timeout);
				if (sample != null) {
					sample.stop(sendTimer(sent));
				}
				metrics.afterSend(metricsContext, sent);
				metricsProcessed = true;
}
```
only `metricsCaptor` should be left?

Thanks

**Comment by garyrussell** [comment]
I meant deprecate the user APIs (ChannelMetrics etc) but still retain the stats; then pull everything out in a later release.

**Comment by artembilan** [comment]
Yeah... I still have no idea how to proceed. 😢 

Let's circulate in on Monday!
