### ISSUE TITLE
Spring Integration 4.3 Reference Docs Not Rendered Properly on spring.io

### ISSUE THREAD

**Issue by mhgerov** [spring-projects/spring-integration#2825]
https://docs.spring.io/spring-integration/docs/4.3.19.RELEASE/reference/htmlsingle/#gw-completable-future

Right below at ===== Reactor Promise is when the headers fail to parse for Asciidoctor. Now the Table of contents only go up to that point. The error appears the same for html, htmlsingle, and pdf.

**Comment by garyrussell** [comment]
Thanks for reporting; fixed for the 4.3.x branch; I also fixed the 4.3.19 manual but it might take some time for the cache to clear.

Thanks again.
