### ISSUE TITLE
RedisUtils.isUnlinkAvailable bug

### ISSUE THREAD

**Issue by sojw** [spring-projects/spring-integration#2868]
**Affects Version(s):** \5.1.3

---

hi. there

we are upgrading to springboot 2.1.3.

since then, NE have occurred in the redis lock part of spring-integration.
we looked for the cause.

- https://github.com/spring-projects/spring-integration/blob/d21e8f03499c93939b0a618ce96a026eef940ca2/spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisUtils.java#L64

we have modified version of our redis server info and returned it.
ex) "111.111.111.111:7000.redis_version" -> "4.0.9"

If we handle this redis_version in the isUnlinkAvailable function, an NE occurs.
I think we need to fix this part.
If it does not fit in the pattern, try to return it as the default value by try / catch.

currently, we have downgraded to 5.1.2 and are running normally.

**Comment by lonnyDong** [comment]
“111.111.111.111:7000.redis_version" -> "4.0.9 , the point is  info.getProperty(VERSION_PROPERTY) can not get redis_version properly，cause the  key has changed. info.getProperty(VERSION_PROPERTY)  returns NULL
