### ISSUE TITLE
Cache in RedisUtils is not thread safe

### ISSUE THREAD

**Issue by pete-woods** [spring-projects/spring-integration#2884]
**Affects Version(s):** master

---

The `LinkedHashMap` in https://github.com/spring-projects/spring-integration/blob/master/spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisUtils.java is accessed from multiple threads when using `RedisLockRegistry`, resulting in concurrency exceptions. I worked around the problem in my app by overriding the implementation there with one using Guava's cache. Spring integration doesn't have a dependency on Caffeine or Guava, or I'd have submitted a simple patch.

**Comment by garyrussell** [comment]
Why do we call this on every remove call anyway? We should just cache the result in the store and registry during intiialization since the `RedisTemplate` is final in both cases.

**Comment by pete-woods** [comment]
Thanks for the quick fix!
