### ISSUE TITLE
Explain the need for an initial bridge in a subflow starting with a channel

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#2890]
See https://stackoverflow.com/questions/55591704/whats-the-purpose-of-automatically-added-bridge-component-after-router

**Comment by artembilan** [comment]
See my comments in that SO question. 
Maximum I would consider this as a documentation improvement for better end-user experience.

**Comment by garyrussell** [comment]
I am ok with closing this as "Working as Designed".

These bridges are very lightweight. Perhaps another option would be to add an option `suppressSyntheticBridges` on the `IntegrationGraphServer` (if the bridge input channel has a name with the  the form `.*\.#0`.

**Comment by garyrussell** [comment]
Converted to "documentation"
