### ISSUE TITLE
redisTemplate, how to determine the key doesn't exist or the value is empty by access redis once?

### ISSUE THREAD

**Issue by Farwell-Liu** [spring-projects/spring-integration#2945]
I am using spring redisTemplate to access redis server. When get a value from redis by a key, the key does not exits probably, or it existed but the value is empty. But the redisTemplate always return null. So I cannot distinguish them.

```
//it always returns null when key doesn't exist or value is empty
var v = redisTemplate.opsForValue().get("name");
```
I can use this code to determine if the key exists firstly:
```
if(redisTemplate.hasKey("name"))
```
And then I need to access the redis server again to get the value 
```
var v = redisTemplate.opsForValue().get("name");
```
And in step 2 I still don't know whether the key existed or not. Because the key may be deleted by others between step 1 and step 2. My business logic depend on whether the key exists or not, Or the value is empty.   

Actually I need step 1 and step 2 is atomic to solve some consistency problem. And another reason that I think it has better performance.

So is there a some method that return null(value is empty) or return redis nil(key doesn't exist)? Or will redisTemplate provides this method in future?

Thank you!

**Comment by artembilan** [comment]
We don’t handle questions on GitHub, more over it doesn’t look like your one is related to Spring Integration at all: https://spring.io/projects/spring-integration. Please, consider to raise it in some community forum like StackOverflow. 

If there is no way on the `RedisTemplate` you can consider such a functionality with low level client. Seems for me template gives us some access to it through an `execute()`. You also can perform a script there as well with your complicated logic.

Anyway this is invalid for this project therefore closing.
