### ISSUE TITLE
Need getMetricCaptor protected method in AbstractMessageHandler

### ISSUE THREAD

**Issue by amitsadafule** [spring-projects/spring-integration#2956]
## Enhancement

Hi,

I am trying to add a new metric in my handler class. I referred to AbstractMessageChannel and its subclass AbstractPollableChannel. Here AbstractMessageChannel class has a method called getMetricsCaptor(). 

In my case, I want to create a new metric in handler class, hence I tried to create a subclass of AbstractMessageHandler but there is no getMetricsCaptor() method.

It will be helpful, if you can provide the same. I can raise a MR if needed.

**Comment by garyrussell** [comment]
Yes, we can add that. Feel free to contribute.

**Comment by amitsadafule** [comment]
Created a pull request https://github.com/spring-projects/spring-integration/pull/2960
