### ISSUE TITLE
ScatterGatherHandler getting stuck after first message

### ISSUE THREAD

**Issue by alokpaul** [spring-projects/spring-integration#2967]
The `ScatterGatherHandler.handleRequestMessage()` is getting stuck at `gatherResultChannel.receive()` call as its not receiving any reply. 

The issue seems to be at 
```
....addInterceptor(0,
new ChannelInterceptor() {
	@Override
	public Message<?> preSend(Message<?> message, MessageChannel channel) {
		return enhanceScatterReplyMessage(message, gatherResultChannel, requestMessage);
	}
});
```
Its adding a new interceptor for each message processing.
But also only the `gatherResultChannel` from the first method call instance is being replied to, so the subsequent `gatherChannel` instance is not receiving the message and waiting.

**Comment by artembilan** [comment]
Confirmed.

We have a problem adding a new interceptor to the same channel object on every request message.

I hoped to have some optimization to avoid intermediate channels, but looks like I forgot that we have a request message context.
Will fix soon!

Note: we have just missed to have a test-case with several request messages... 😢

**Comment by artembilan** [comment]
Hm. I know why we placed that interceptor into the channel. When `gatherChannel` is an external bean, we don't have a knowledge that you are going to use it explicitly or not.

Please, consider do not use an external `gatherChannel` for your configuration. An internal one is going to be created and everything in downstream logic will rely on the `replyChannel` header.

I agree that logic with an interceptor is wrong, but that is a story to fix with this issue.

Stay tuned!
