### ISSUE TITLE
Enhancement: Convenience class for JmsMessageDrivenChannelAdapterListenerContainerSpec<JmsDefaultListenerContainerSpec, DefaultMessageListenerContainer>

### ISSUE THREAD

**Issue by agebhar1** [spring-projects/spring-integration#2970]
## Enhancement

Create class for concrete implementation of `JmsMessageDrivenChannelAdapterListenerContainerSpec<JmsDefaultListenerContainerSpec, DefaultMessageListenerContainer>` to avoid usage of `JmsMessageDrivenChannelAdapterListenerContainerSpec#configureListenerContainer(...)` and expose all methods of `JmsDefaultListenerContainerSpec` for convenience.

**Comment by agebhar1** [comment]
WIP #2969

**Comment by artembilan** [comment]
Closed in favor of PR #2969 .

If we have a Pull Request there is no reason in the separate issue. They are just the same matter on GitHub.
Let's have a discussion in that PR!

Thank you for understanding!

**Comment by agebhar1** [comment]
That's fine
