### ISSUE TITLE
NioFileLocker.unlock

### ISSUE THREAD

**Issue by matiastito** [spring-projects/spring-integration#2980]
Hi all, It appears to me that there is a bug in NioFileLocker.unlock() method (spring integration v5.1.4.RELEASE). 
Method clears up classloader level cache by calling FileChannelCache.closeChannelFor(fileToUnlock);, but it never tries to clean up its local lockCache.

**Comment by artembilan** [comment]
Good catch!

Feel free to contribute a fix!

Thanks
