### ISSUE TITLE
ImapMailReceiver bean is not initialized

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#2995]
See https://stackoverflow.com/questions/57126841/how-to-enable-imapfolder-read-write-mode-in-spring-mail-integration/57146996#57146996

```java
		return IntegrationFlows
				.from(Mail.imapInboundAdapter("imaps://usr:pwd@imap.host.com/INBOX")
						.searchTermStrategy(searchTermStrategy).shouldMarkMessagesAsRead(true).get(),
						e -> e.poller(Pollers.fixedRate(5000).maxMessagesPerPoll(1)))
				.log()
				.get();
```

No call to `afterPropertiesSet()` is made.

**Comment by artembilan** [comment]
You should not call `.get()` on the `IntegrationComponentSpec` when you use it this way via DSL.
After that `get()` we don't have any clues in the Framework how you declared that component. There we don't have any permissions to call `afterPropertiesSet()` for you.
When it is left without `get()` a Framework takes care about proper bean initialization.

Not sure if we have such a note in docs, but I treat this as end-user error and close as *Works as Designed*.

**Comment by garyrussell** [comment]
Doh; sorry; missed that.
