### ISSUE TITLE
Can sftp support Resource when upload

### ISSUE THREAD

**Issue by peacetrue** [spring-projects/spring-integration#2996]
**Affects Version(s):** \<Spring Integration version>
4.3.20.RELEASE
---

## Enhancement

I can't upload a remote file via sftp, It only supports byte[] and File. Can it support Resource?

`RemoteFileTemplate`

```
private StreamHolder payloadToInputStream(Message<?> message) throws MessageDeliveryException {
		try {
			Object payload = message.getPayload();
			InputStream dataInputStream = null;
			String name = null;
			if (payload instanceof File) {
				File inputFile = (File) payload;
				if (inputFile.exists()) {
					dataInputStream = new BufferedInputStream(new FileInputStream(inputFile));
					name = inputFile.getAbsolutePath();
				}
			}
			else if (payload instanceof byte[] || payload instanceof String) {
				byte[] bytes = null;
				if (payload instanceof String) {
					bytes = ((String) payload).getBytes(this.charset);
					name = "String payload";
				}
				else {
					bytes = (byte[]) payload;
					name = "byte[] payload";
				}
				dataInputStream = new ByteArrayInputStream(bytes);
			}
                        //add the follow code
			else if(payload instanceof Resource){
				dataInputStream = ((Resource)payload).getInputStream();
				name =((Resource)payload).getFilename();
			}
			else {
				throw new IllegalArgumentException("Unsupported payload type. The only supported payloads are " +
							"java.io.File, java.lang.String, and byte[]");
			}
			if (dataInputStream == null) {
				return null;
			}
			else {
				return new StreamHolder(dataInputStream, name);
			}
		}
		catch (Exception e) {
			throw new MessageDeliveryException(message, "Failed to create sendable file.", e);
		}
	}
```

**Comment by artembilan** [comment]
`dataInputStream = ((Resource)payload).getInputStream();`

It is very easy to have such a code in some `transformer` before calling remote file transfer. 
Since there is so simple workaround we are not going to backport it to previous versions.

**Comment by peacetrue** [comment]
@artembilan I want to upload a remote file directly instead of downloading the file locally and converting it to byte[] before uploading. `UrlResource` is the best choice.

**Comment by garyrussell** [comment]
You are using an old version; the current code has this...

```java
			if (payload instanceof InputStream) {
				dataInputStream = (InputStream) payload;
			}
			else if (payload instanceof File) {
				File inputFile = (File) payload;
...
```

This was added in 5.0 [INT-3746](https://jira.spring.io/browse/INT-3746).

So, an upstream transformer can simply transform the resource to an `InputStream`.

**Comment by garyrussell** [comment]
I think we can backport the support for `InputStream`, if you can't upgrade to a more recent version for some reason.

Let us know.

**Comment by peacetrue** [comment]
@garyrussell ``InputStream`` is ok, upgrade is a huge feature, no plan in a short time.

**Comment by garyrussell** [comment]
Backported [here](https://github.com/spring-projects/spring-integration/commit/4258da8deaef6d55576a424ddfaf8d7aed7957a3).

4.3.21 is currently planned for release on August 1.

**Comment by artembilan** [comment]
Reopen since the request was to have a convenience to send a `Resource` directly, without any transformation upstream.
