### ISSUE TITLE
Enhancement: Add flink like window aggregator.

### ISSUE THREAD

**Issue by zheh12** [spring-projects/spring-integration#3000]
**Affects Version(s):** 5.2.0

---

## Enhancement

I now use spring integration some data from web socket, and I want aggregating the data by time. I notice there is a message routing class `AggregatingMessageHandler` can process the normal aggregate.

But I think this aggregate is lack some time window based aggregate ability such as [flink](https://ci.apache.org/projects/flink/flink-docs-release-1.8/dev/stream/operators/windows.html).

So I suggest add the time window based aggregate to spring integration. I think this will also add more ability to spring cloud data flow which compares stream process with flink.

If this idea sounds good, please give me some suggestion, I will add code to make this implementation.

**Comment by artembilan** [comment]
There is a `groupTimeout` feature on the aggregator component, which really reflects such a *window* requirements: https://docs.spring.io/spring-integration/docs/current/reference/html/#agg-and-group-to.

On the other hand we have just introduced in the version `5.2` a `FluxAggregatorMessageHandler`, which does more in terms of *window* or *buffer* via Project Reactor: https://docs.spring.io/spring-integration/docs/5.2.0.M3/reference/html/whats-new.html#x5.2-flux-aggregator

So, I think we are covered with what you would like to add.
Let us know and we close the issue respective as `Fixed via...`

Thanks for understanding.

**Comment by garyrussell** [comment]
There is also the `TimeoutCountSequenceSizeReleaseStrategy` which can be used along with the group timeout in the standard aggregator.

**Comment by zheh12** [comment]
I know the groupTimeout, and I look at FluxAggregatorMessageHandler and TimeoutCountSequenceSizeReleaseStrategy. But I think they are not enough.

First of all, the most important, there is no different event time with processing time for all the solution. for example, `TimeoutCountSequenceSizeReleaseStrategy` uses processing time. For flink there is event time and processing time. And when use event time, it even can process out of order event time window. So there is a concept watermarkers.

For Spring and flux now api, there is no way to process event time out of order or with big latency.

Second, for Flink, there are four different windows for different purpose.

1. Tumbling Windows: A tumbling windows assigner assigns each element to a window of a specified window size. Tumbling windows have a fixed size and do not overlap.
2. Sliding Windows: The sliding windows assigner assigns elements to windows of fixed length. Hence, sliding windows can be overlapping if the slide is smaller than the window size. In this case elements are assigned to multiple windows.
3. Session Windows: The session windows assigner groups elements by sessions of activity. Session windows do not overlap and do not have a fixed start and end time, in contrast to tumbling windows and sliding windows.
4. Global Windows: A global windows assigner assigns all elements with the same key to the same single global window. This windowing scheme is only useful if you also specify a custom trigger. Otherwise, no computation will be performed, as the global window does not have a natural end at which we could process the aggregated elements.

I think for spring group-timeout, it is a session window. For `TimeoutCountSequenceSizeReleaseStrategy` window it is a tumbling window. For flux window api, it looks can get all the window, but it's api is very complex compare to flink api.I even don't know how to construct the semantics as flink semantics. I think flink for my application is too heavy. But I don't find any api as simple as flink for the real time window processing using spring data flow.

**Comment by garyrussell** [comment]
I believe you can achieve all of the above with custom `CorrelationStrategy` and `ReleaseStrategy` implementations.

The correlation strategy determines which group to add a message to; the release strategy decides whether it's time to release a group.

We'd be happy if you decide to contribute the implementations back to the framework.

**Comment by zheh12** [comment]
I'm working on a new handler `WindowMessageHandler` extend `AbstractMessageProducingHandler`. I am happy to send a pull request when i am done first version.
