### ISSUE TITLE
Add cancelIdleInterval to IMAP mail adapter XSD and parsers

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3017]
See https://stackoverflow.com/questions/57364689/how-to-set-cancel-idle-interval-attribute-of-imap-mail-receiver-channel-using-xm/57365795#57365795

**Comment by artembilan** [comment]
Also looks like the `ImapMailInboundChannelAdapterSpec` has obtained a `cancelIdleInterval()` option by mistake.

**Comment by garyrussell** [comment]
Right; I noticed that; not clear why it's a property on the `IMAPMailReceiver`.

**Comment by artembilan** [comment]
Ha! Good point! So, maybe this is a bug and not so *ideal-for-user-contribution*. We need to think more and refactor respectively.
