### ISSUE TITLE
Improve AbstractRemoteFileOutboundGateway

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3038]
@Bean
	public IntegrationFlow flow() {
		return IntegrationFlows.from(UploadGateway.class)
				.handle(Sftp.outboundGateway(template(), "put", "headers['file_name']"))
				.get();
	}

	@Bean
	public SftpRemoteFileTemplate template() {
		SftpRemoteFileTemplate template = new SftpRemoteFileTemplate(sessionFactory());
		template.setRemoteDirectoryExpression(new LiteralExpression("foo/test"));
		return template;
	}

Works fine.

But there is no way to configure the `remoteDirectoryExpression` if you use this CTOR

    .handle(Sftp.outboundGateway(sessionFactory(), "put", "headers['file_name']"))

>Caused by: java.lang.IllegalArgumentException: 'remoteDirectoryExpression' is required

We should either deprecate those CTORs or add support to the ARFOG/DSL to set the RDE.

Also, we should add `...ExpressionString()` variants for the `RemoteFIleTemplate` properties.

**Comment by artembilan** [comment]
Although I'm against a mutation of the externally provided object, but looks like the `FileTransferringMessageHandler` does exactly what you requested. And its DSL also provides those options.
This is definitely going to be easier fix, than considering some syntax sugar for DSL.
On the other hand we may have a smart internal logic like we do in the `FileReadingMessageSource` and its `DirectoryScanner`:
```
// Check that the filter and locker options are _NOT_ set if an external scanner has been set.
// The external scanner is responsible for the filter and locker options in that case.
Assert.state(!(this.scannerExplicitlySet && (this.filter != null || this.locker != null)),
	() -> "When using an external scanner the 'filter' and 'locker' options should not be used. " +
	"Instead, set these options on the external DirectoryScanner: " + this.scanner);
```

But I don't think that removing factory-based ctors is the right choice: there are some remote commands which don't require a `remoteDirectory`. Isn't it?

**Comment by garyrussell** [comment]
Agreed.

**Comment by garyrussell** [comment]
I think we should add an error log to the FTMH "Mutating an externally provided remote file template is discouraged and will be removed in a future release; you should mutate the template before providing it:".

**Comment by artembilan** [comment]
OK. We can do that, too. Then any remote template consumers are going to be free from those errors and it is going to be clearly an end-user configuration error to miss required properties.
