### ISSUE TITLE
Method singleUseConnections and closeStreamAfterSend not found

### ISSUE THREAD

**Issue by newtondev** [spring-projects/spring-integration#3048]
Version: 5.1.7.RELEASE

https://github.com/spring-projects/spring-integration/blob/5b43b6c7dd6069e68ce03de72770667bac4c7448/spring-integration-ip/src/test/java/org/springframework/integration/ip/dsl/IpIntegrationTests.java#L200

**Comment by artembilan** [comment]
See `AbstractConnectionFactorySpec`:

```
	/**
	 * This connection factory uses a new connection for each operation.
	 * @param single true for a new connection for each operation.
	 * @return the spec.
	 * @since 5.2
	 */
	public S singleUseConnections(boolean single) {
		this.target.setSingleUse(single);
		return _this();
	}
```
And `TcpOutboundGatewaySpec`:
```

	/**
	 * Set to true to close the connection ouput stream after sending without
	 * closing the connection. Use to signal EOF to the server, such as when using
	 * a {@link org.springframework.integration.ip.tcp.serializer.ByteArrayRawSerializer}.
	 * Requires a single-use connection factory.
	 * @param closeStreamAfterSend true to close.
	 * @return the spec.
	 * @since 5.2
	 */
	public TcpOutboundGatewaySpec closeStreamAfterSend(boolean closeStreamAfterSend) {
		this.target.setCloseStreamAfterSend(closeStreamAfterSend);
		return _this();
	}
```

So, everything is there, only the problem that yo need to use Spring Integration of version `5.2`, currently in the Milestone 4: https://github.com/spring-projects/spring-integration/releases/tag/v5.2.0.M4.
We are going to release `RC1` next week: https://github.com/spring-projects/spring-integration/milestone/15. 

So, closing as *Works as Designed*.
Thanks

**Comment by newtondev** [comment]
Thanks @artembilan, found it in the latest source code, but cannot use it in the current maven release version.

**Comment by artembilan** [comment]
The `singleUseConnections` is a part of the `AbstractConnectionFactory` as a `setSingleUse`. You can just configure the connection factory for your components not via DSL.
The `setCloseStreamAfterSend()` is a new API anyway: you are not able to use this feature until you upgrade to Spring Integration 5.2.
Just ignore it for now!
