### ISSUE TITLE
Revise new NullChannel() usage in favor of `nullChannel` bean

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3067]
The problem with a `new NullChannel()` that we won't get a consistent metrics on the `nullChannel` bean.

Also consider to change `successTimer` in the `NullChannel` into the `sendCounter` since we don't care about timing on the `nullChannel`, but rather how many messages have been discarded.

**Comment by garyrussell** [comment]
We can't change the meter type without adding special code to the graph server.

**Comment by artembilan** [comment]
OK. I think we can live with `0`-timer then. I hope it shows some throughput statistics anyway...

**Comment by garyrussell** [comment]
I only see these...
```
$ find . -name "*.java" | grep -v 'src/test' | xargs grep 'new NullChannel'
./spring-integration-file/src/main/java/org/springframework/integration/file/dsl/TailAdapterSpec.java:			this.factoryBean.setOutputChannel(new NullChannel());
./spring-integration-core/src/main/java/org/springframework/integration/transaction/ExpressionEvaluatingTransactionSynchronizationProcessor.java:	private volatile MessageChannel beforeCommitChannel = new NullChannel();
./spring-integration-core/src/main/java/org/springframework/integration/transaction/ExpressionEvaluatingTransactionSynchronizationProcessor.java:	private volatile MessageChannel afterCommitChannel = new NullChannel();
./spring-integration-core/src/main/java/org/springframework/integration/transaction/ExpressionEvaluatingTransactionSynchronizationProcessor.java:	private volatile MessageChannel afterRollbackChannel = new NullChannel();
./spring-integration-core/src/main/java/org/springframework/integration/aggregator/AbstractCorrelatingMessageHandler.java:	this.discardChannel = new NullChannel();
```

I guess we can't change the spec.

I suppose it was the aggregator where you saw problems?

**Comment by artembilan** [comment]
We can fix a `Spec`: the `MessageProducerSupport` has `setOutputChannelName()`. Of course, we would need to fix a `FileTailInboundChannelAdapterFactoryBean` as well, but it is not clear to me why would `TailAdapterSpec` worry about that `NullChannel` at all...

Yes, an `AbstractCorrelatingMessageHandler` is an origin of this issue, but I don't think we should leave all others as is.
Although I would say `ExpressionEvaluatingTransactionSynchronizationProcessor` should just deal with `null` value for those channels instead of polluting a `NullChannel`...
