### ISSUE TITLE
Missing documentation about how to correctly handle messages from SftpStreamingMessageSource (and other streaming message sources)

### ISSUE THREAD

**Issue by mschiavon-ewtsrl** [spring-projects/spring-integration#3071]
The documentation is missing indications about how to correctly cleanup resources after transforming messages coming from streaming message sources.

Looking at this source code:
https://github.com/spring-projects/spring-integration/blob/37cc201aeeaeab7c9a35d36dbb6c278719895569/spring-integration-core/src/main/java/org/springframework/integration/transformer/StreamTransformer.java#L66

it is *necessary* to cleanup the underlying session (it is not clear what to do if shared sessions are used in the session factory). Not cleaning up results in a memory leak (and keeps the corresponding ssh session opened on the remote server)

**Comment by garyrussell** [comment]
Please explain what more we should say [here](https://docs.spring.io/spring-integration/docs/5.2.0.BUILD-SNAPSHOT/reference/html/sftp.html#sftp-streaming).

>Version 4.3 introduced the streaming inbound channel adapter. This adapter produces message with payloads of type InputStream, letting you fetch files without writing to the local file system. Since the session remains open, the consuming application is responsible for closing the session when the file has been consumed. The session is provided in the closeableResource header (IntegrationMessageHeaderAccessor.CLOSEABLE_RESOURCE). ...

**Comment by mschiavon-ewtsrl** [comment]
Sorry, my bad, I didn't read that paragraph

**Comment by artembilan** [comment]
Closed as *Works as Designed*
