### ISSUE TITLE
GH-3026 -FTP Outbound Adapter

### ISSUE THREAD

**Issue by joaquinjsb** [spring-projects/spring-integration#3078]
**Affects Version(s):** 5.2.0.RELEASE

Hi,
I couldn't test the ftp outbound adapter in time, there's a problem that should be fixed regarding the issue https://github.com/spring-projects/spring-integration/issues/3026.

I couldn't test in time before the release:

on the FtpMessageHandlerSpec, the target is still a **FileTransferringMessageHandler**, you have to use the children class you created **FtpMessageHandler** so that it can see the override, on my end it isn't working because isChmodCapable still returns **false**.

![image](https://user-images.githubusercontent.com/2885322/66838927-df622f80-ef65-11e9-8a10-99295d4af8ec.png)

![image](https://user-images.githubusercontent.com/2885322/66838961-ee48e200-ef65-11e9-9d58-4c4596ed4faf.png)

**Comment by artembilan** [comment]
This is indeed a bug and we don’t have a test coverage. Please, go ahead and issue a Pull Request on the matter. If you wish, of course!

**Comment by joaquinjsb** [comment]
> This is indeed a bug and we don’t have a test coverage. Please, go ahead and issue a Pull Request on the matter. If you wish, of course!

let's give a try!

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-integration/commit/7aea76c6c45261cfa5fb62b4ec521769341e6912 and back-ported to `5.1.x` as https://github.com/spring-projects/spring-integration/commit/35b964cc79ead8c11ed2f062a3a40a94ad391933
