### ISSUE TITLE
Subflow with defaultOutputToParentFlow can trigger unwanted payload serialization when @EnableBinding is used

### ISSUE THREAD

**Issue by fwiersENO** [spring-projects/spring-integration#3081]
We are currently facing an odd issue (bug?) when using a subflow in an integration flow that uses the "defaultOutputToParentFlow" and "resolutionRequired(false)". This issue is triggered by using the "@EnableBindings" annotation (org.springframework.cloud.stream.annotation.EnableBinding).

A test that shows the issue is in code at: https://github.com/fwiersENO/spring-subflow-serialization

We use large payloads in the mesage between (direct) channels in integration flows that should not be serialized. Introducing a subflow unexpectedly triggered a serialization of the payload (at least, it looks like serialization is triggered). While trying to pinpoint the issue, one cause was found in the use of "defaultOutputToParentFlow". Further investigation showed that the serialization-issue only showed in combination with using the "@EnableBindings" annotation.

It is possible to make subflows without the use of "defaultOutputToParentFlow", but we prefer to use it and not have to worry about what "@EnableBindings" is doing to the integration flows.

Tested with spring-boot 2.1.9 / spring integration 5.1.8 / spring cloud stream 2.1.4.

**Comment by artembilan** [comment]
Can we have some stack trace on the matter?
Can you make your project based on Java 8?
Can that sample be as simple as possible?
It is not clear why do we need that custom `RabbitBindings`.

What I see in your code for *good*:
```
 .<InputPayload, Boolean>route(p -> p.subflow,
                m -> m.subFlowMapping(false, f -> f.transform(p -> false))
                    .subFlowMapping(true, f -> f.transform(p -> 1)))
            .handle(logBitPayload())
```

So, the one or another result of that `transform` is going to be returned to the main flow for that next `handle()`.

In the other case:
```
  .<InputPayload, Boolean>route(p -> p.subflow,
                m -> m.subFlowMapping(false, f -> f.transform(p -> false))
                    .resolutionRequired(false)
                    .defaultOutputToParentFlow())
            .handle(logBitPayload())
```
That `ParseMime.handle()` result is sent to the `logBitPayload()`.

Not clear yet what is the problem though...

Thanks for understanding.

**Comment by fwiersENO** [comment]
I updated the code to use Java 8 and removed code that was not required for the test (inlcuding `RabbitBindings`, I thought I needed it to use `@EnableBinding` but that was not the case) . I have seen 3 different stacktraces so far (which is a bit nasty in itself), one is shown below and two of them are shown here: https://github.com/fwiersENO/spring-subflow-serialization/blob/master/stacktrace-with-enablebindings.txt

To make the problem clear, some observations:

- Integration flow `goodFlow` is functionally the same as `faultyFlow`
- `testAppFlowGood`, which uses `goodFlow`, always succeeds, with or without the use if `@EnableBinding`.
- `testAppFlowBad`, which uses `faultyFlow`, always fails when `@EnableBinding` is used. When `@EnableBinding` is removed (line 24 in App.java), `testAppFlowBad` always succeeds.

What these tests show is that an integration flow can break by one of the side-effects of the `@EnableBinding` annotation. In this test `@EnableBinding` is completely non-functional, in actual applications this would be fully functional and the same side-effects of the `@EnableBinding` annotation will break certain integration flows that use a subflow that in turn uses `resolutionRequired(false)` and `defaultOutputToParentFlow`.

So now the question is: what side-effect of the `@EnableBinding` annotation is the cause of errors in `testAppFlowBad` ?

For reference, one of the stack-traces shown when using `mvn test`:
```
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'true'; nested exception is org.springframework.messaging.converter.MessageConversionException: Could not write JSON: No serializer found for class javax.mail.internet.InternetHeaders$MatchStringEnum and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: springdefflow.App$InputPayload["mimeMessage"]->javax.mail.internet.MimeMessage["allHeaderLines"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class javax.mail.internet.InternetHeaders$MatchStringEnum and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: springdefflow.App$InputPayload["mimeMessage"]->javax.mail.internet.MimeMessage["allHeaderLines"])
        at springdefflow.AppTest.testAppFlowBad(AppTest.java:80)
Caused by: org.springframework.messaging.converter.MessageConversionException: Could not write JSON: No serializer found for class javax.mail.internet.InternetHeaders$MatchStringEnum and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: springdefflow.App$InputPayload["mimeMessage"]->javax.mail.internet.MimeMessage["allHeaderLines"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class javax.mail.internet.InternetHeaders$MatchStringEnum and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: springdefflow.App$InputPayload["mimeMessage"]->javax.mail.internet.MimeMessage["allHeaderLines"])
        at springdefflow.AppTest.testAppFlowBad(AppTest.java:80)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class javax.mail.internet.InternetHeaders$MatchStringEnum and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: springdefflow.App$InputPayload["mimeMessage"]->javax.mail.internet.MimeMessage["allHeaderLines"])
        at springdefflow.AppTest.testAppFlowBad(AppTest.java:80)
```

**Comment by artembilan** [comment]
@fwiersENO ,

Thank you very much for making such a workable sample.

I have reproduced an issue.
I see what is going on.

When we turn on Spring Cloud Stream in our application (see `@EnableBinding`), a `BinderAwareChannelResolver` is appear in the application context and it is applied for all the routers defined in our application context:
```
@Deprecated
public class BinderAwareRouterBeanPostProcessor {

	public BinderAwareRouterBeanPostProcessor(AbstractMappingMessageRouter[] routers,
			DestinationResolver<MessageChannel> channelResolver) {
		if (routers != null) {
			for (AbstractMappingMessageRouter router : routers) {
				router.setChannelResolver(channelResolver);
			}
		}
	}

}
```

In this case when we fail with mapping (`true` key is missed), we convert this `boolean true` into `String "true"` and try to resolve such a channel from that `BinderAwareChannelResolver`.
This one is able to create a new channel and its `output` binding on the fly. After that we send a message to this channel which would like to have our payload to be serialized into a JSON - just because we are going to send a message to the binding destination already.

I'm not sure what to do with this, but feels like we can't apply a `BinderAwareChannelResolver` for all the routers unconditionally.

Perhaps some configuration property for router bean names or bean name patterns?

Anyway doesn't look like Spring Integration problem. 
Need to be moved back to Spring Cloud Stream.

/CC @olegz

**Comment by fwiersENO** [comment]
Thank you for the analyses of the cause of the issue @artembilan 
I do not know what the proper way is to resolve the issue either, but at least there is a simple workaround in this case: for any option where nothing needs to happen, add the option with a bridge like `.subFlowMapping(true, f -> f.bridge())`. 
Could you make an issue for Spring Cloud Stream? I am afraid I might get the details wrong when creating an issue for Spring Cloud Stream. Once that issue exists, this one can be closed.

**Comment by artembilan** [comment]
There is nothing to be afraid, @fwiersENO .

Just go ahead and create an issue over there with a link to this one.
It is really much better to have an issue as community-driven: we will have more eyes to track.

I'm fully open to continue discussion in that project, but as we agreed with you, there is nothing Spring Integration may fix for.

**Comment by fwiersENO** [comment]
OK done: https://github.com/spring-cloud/spring-cloud-stream/issues/1822
