### ISSUE TITLE
json__TypeId__ stripped from message when sending via JMS

### ISSUE THREAD

**Issue by khetho** [spring-projects/spring-integration#3086]
**Affects Version(s):** 5.1.5.RELEASE

---

In an integration flow Transformers.toJson() can be used to convert a payload into a Json structure. This function also adds a 'json__TypeId__' header that contains the class type of the object that was transformed into a Json string. Consider the following integration flow snippet where f is the integration flow

```java
 f.transform(Transformers.toJson())
 .log()
 .handle( Jms.outboundAdapter(connectionFactory)
                      .headerMapper(new DefaultJmsHeaderMapper())
                      .destination("my_queue")))
```
The logging line outputs as follows

`GenericMessage [payload={"id":null,"value":1}, headers={reference=12345, json__TypeId__=class za.co.hailer.dto.user.ContactDto}]
`
The message is then correctly placed on my_queue using JMS. On a consumer that is reading from my queue I have the following snippet of code

```java
f.log()
 .transform(Transformers.fromJson())
```
The output of the log line is

`GenericMessage [payload={"id":null,"value":1}, headers={reference=12345}]
`
The json__TypeId__ header value has been stripped off resulting in the following exception being thrown when Transformers.fromJson() is called

`Could not resolve 'json__TypeId__' in 'javaTypes'`

The issue is the [DefaultJmsHeaderMapper.java](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-jms/src/main/java/org/springframework/integration/jms/DefaultJmsHeaderMapper.java) does not support mapping headers with values that are class objects as the case is for 'json__TypeId__' header that Transformers.fromJson() adds to the message. 
This can be seen in the following section at the top of the DefaultJmsHeaderMapper.java file

```java
private static final List<Class<?>> SUPPORTED_PROPERTY_TYPES = Arrays.asList(new Class<?>[] {
			Boolean.class, Byte.class, Double.class, Float.class, Integer.class, Long.class, Short.class, String.class });
```
then in the fromHeaders method on line 169 unsupported types are filtered out from being mapped by the below

```java
if (SUPPORTED_PROPERTY_TYPES.contains(value.getClass())) {
```
Too keep my code generic I would have preferred not to provide the class in the Transformers.fromJson() call. As a work around I have implemented the following on the producer side  for now which ensures the header gets passed as I overwrite the class header with a string header based on the classes fully qualified name

```java
 f.transform(Transformers.toJson())
.enrichHeaders(h -> h.headerExpression("json__TypeId__", "headers['json__TypeId__'].getName()", true))
 .log()
 .handle( Jms.outboundAdapter(connectionFactory)
                      .headerMapper(new DefaultJmsHeaderMapper())
                      .destination("my_queue")));
```
with the log  on the producer side now showing the conversion

`
GenericMessage [payload={"id":null,"value":1}, headers={reference=12345, json__TypeId__=za.co.hailer.dto.user.ContactDto}]
`
which is also now coming through on the consumer side log
`GenericMessage [payload={"id":null,"value":1}, headers={reference=12345, json__TypeId__=za.co.hailer.dto.user.ContactDto}]
`
and the exception is gone.

The issue I would like to raise is a request to update DefaultJmsHeaderMapper to support class types.

**Comment by artembilan** [comment]
Active MQ has the code like this:
```
 protected void checkValidObject(Object value) throws MessageFormatException {

        boolean valid = value instanceof Boolean || value instanceof Byte || value instanceof Short || value instanceof Integer || value instanceof Long;
        valid = valid || value instanceof Float || value instanceof Double || value instanceof Character || value instanceof String || value == null;
```

so, we can't support `Class<?>` type in the `DefaultJmsHeaderMapper` unconditionally.
More over I think this is really not safe to do that unconditionally in any place at all.

The `Class<?>` transferred over the network really has be trusted first of all.
And in my feeling this kind of operation to covert a `Class` into `String` has to be as a part of application logic.

So, what you have done with the `enrichHeaders()` is right solution and sounds like the one which should be reflected in Docs at most.

Does it make sense to you?

Thanks

P.S. To make your `enrichHeaders()` smooth you can rely on the `JsonHeaders.TYPE_ID` constant and use a `headerFunction()` to get access to that header via constant as well.

**Comment by khetho** [comment]
I agree with you @artembilan from a security point of view. From a least privilege point of view the knowledge of  the class would be known by the sender and consumer and so can be specified explicitly when marshaling and marshaling in the application logic. In the case similar to the one I have where I am trying to make things generic I can then explicitly one can then enrich the headers accordingly. Indeed if one wanted they could extend DefaultJmsHeaderMapper  or implement their own JmsHeader.
