### ISSUE TITLE
Spring integration stream SFTP: pattern filter not working

### ISSUE THREAD

**Issue by lukasGemela** [spring-projects/spring-integration#3105]
Hi guys, 

as follow up on this issue

https://stackoverflow.com/questions/58752135/spring-integration-stream-sftp-pattern-filter-not-working/58753207#58753207

 I'm raising this ticket.
I have used Spring integration 5.2.0

**Comment by artembilan** [comment]
@lukasGemela ,

thank you for checking that functionality and sorry that we brought to you some pain with those unexpected files 😄 

I think as a workaround you can inject your own:
```
private CompositeFileListFilter<LsEntry> composeFilters(FileListFilter<LsEntry> fileListFilter) {
		CompositeFileListFilter<LsEntry> compositeFileListFilter = new CompositeFileListFilter<>();
		compositeFileListFilter.addFilters(fileListFilter,
				new SftpPersistentAcceptOnceFileListFilter(new SimpleMetadataStore(), "sftpStreamingMessageSource"));
		return compositeFileListFilter;
	}
```
with overridden `supportsSingleFileFiltering()` to return always `false`, so all those files are going to be filtered just after a fetch, not during processing each of them.

On the other hand let us know if you are OK with contribution: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

I guess what we need is a `continue;` in the block:
```
if (this.toBeReceived.size() > 0) { // don't re-fetch already filtered files
	file = poll();
}
```

Thank you again!

**Comment by lukasGemela** [comment]
@artembilan Hi, thank you for a workaround!

`continue;` in that block makes sense I think, maybe also break in 

```
else {
     file = null;
}
```

instead of assignment

**Comment by artembilan** [comment]
Yes, that makes sense too.

So, would you mind to raise a PR and we will continue discussion in the code already?

**Comment by lukasGemela** [comment]
@artembilan sure PR on the way
