### ISSUE TITLE
Add a reply timeout hook to TCP inbound gateway

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3107]
Allow the user to determine the action after a reply times out.

https://stackoverflow.com/questions/58796500/tcpinboundgateway-server-configuration-on-timeout-a-custom-message-to-be-sent

**Comment by artembilan** [comment]
I wonder if this feature could help us here:

```
/**
 * If errorOnTimeout is true, construct an instance that will send an
 * {@link ErrorMessage} with a {@link MessageTimeoutException} payload to the error
 * channel if a reply is expected but none is received. If no error channel is
 * configured, the {@link MessageTimeoutException} will be thrown.
 * @param errorOnTimeout true to create the error message.
 * @since 4.2
 */
public MessagingGatewaySupport(boolean errorOnTimeout) {
```

Looks like only HTTP one implement this logic when it is in a `gateway` mode:
```
public BaseHttpInboundEndpoint(boolean expectReply) {
	super(expectReply);
	this.expectReply = expectReply;
}
```

So, it looks like with that `MessageTimeoutException` and an `errorChannel` we have a hook to handle missed replies during timeouts.

**Comment by garyrussell** [comment]
Yes, it looks like that would work - the "hook" to return some other response can be done on the error flow.
