### ISSUE TITLE
NULL HttpEntity in headerFunction in HTTP inbound gateway

### ISSUE THREAD

**Issue by andreiamariei** [spring-projects/spring-integration#3114]
When trying to upgrade from version 5.1.8 to 5.2.1, our HTTP inbound gateway started throwing NPEs when evaluating header functions. Our code is quite basic:
```
IntegrationFlows.from(
                        inboundGateway( gatewayPath )
                                .headerFunction(SOME_HEADER, ent -> getSomeHeaderValue(ent ) )  // ent is null
```

Seems to be related to the call `FunctionExpression.getValue(...)` which ignores `EvaluationContext.getRootObject()`

Do you need more info on this?

**Comment by artembilan** [comment]
Confirmed.
Looks like `FunctionExpression` has to be fixed:
```
	public Object getValue(EvaluationContext context, Object rootObject) throws EvaluationException {
		return getValue(rootObject);
	}
```
The `rootObject` might be `null`, so we need to consult with the `context` for that one instead.

Would you mind to provide a fix?

Thanks

**Comment by artembilan** [comment]
The regression has been done here: https://github.com/spring-projects/spring-integration/commit/8f86ef918c0887db8800fd521d07ea44e6240bf2#diff-9f816d4b97a4332fc0368b15f4fdbc8aR277.

Where it calls an `Expression.getValue(EvaluationContext context, Object rootObject, @Nullable Class<T> desiredResultType)` with `null` for `rootObject`.
This is not what we should call according SpEL contract. So, the fix must be done in the `ExpressionEvalMap`. 

Although `FunctionExpression` may be effected with some refactoring as well.

Looks like a bit involved - will fix soon...
