### ISSUE TITLE
DefaultLockRepository fails to acquire lock on Oracle.

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-integration#3129]
The acquire method in the DefaultLockRepository fails to acquire the lock after the initial insert of the entry in the `%s_LOCK` table.   
https://github.com/spring-projects/spring-integration/blob/master/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java#L159-L166

i.e. the template update returns `0` for the row count updated even though there is an entry in the database.  And thus the insert is called a second time which throws a `DuplicateKeyException`

This behavior only shows up in Oracle.  I've tested on H2, MySql and Postgresql.

* We have wrapped the code in a TransactionTemplate on the Spring Cloud Task side and the same result occurred.
* Also tried to use the OracleXADataSource and this also did not work.   

Here is a sample application that replicates the behavior:  https://github.com/cppwfs/acquirelockfailtest
And it was tested using oracle/database:12.2.0.1-se2

A little more info can be found here: https://github.com/spring-cloud/spring-cloud-task/issues/640

**Comment by cppwfs** [comment]
Let's chat when you get a chance.

**Comment by artembilan** [comment]
See the workaround for current applications: https://github.com/spring-cloud/spring-cloud-task/issues/640#issuecomment-567708545

The fix for this issue will contain a changed schema for all the table in Oracle scripts.
