### ISSUE TITLE
Remove calls to no-arg superclass constructor

### ISSUE THREAD

**Issue by strkkk** [spring-projects/spring-integration#3132]
Hi,

In checkstyle project we adding a new check to detect calls to no-arg superclass constructor `super();`
https://github.com/checkstyle/checkstyle/pull/7387
Our analysis shows that there are many violations of this check in your source code.
Analysis report:
https://strkkk.github.io/checkstyle/7363_3/spring-integration/index.html#A1

Can you please share your thoughts - it this calls should be removed or they can be kept for some reason?

Any feedback are appreciated.

**Comment by garyrussell** [comment]
There are other "rules" about empty blocks; our Sonar ruleset barks about them so an empty constructor is a violation of that rule.

 we use `super()` when we need a no-arg ctor is needed without extra code.

The rule you cite seems bogus to me - if you look at the byte code generated, the compiler adds the same `super()` implicitly.

**Comment by garyrussell** [comment]
If you can make the rule only trigger if there is extra code in the constructor, it might then be useful.

**Comment by strkkk** [comment]
Thank you for reply.
> The rule you cite seems bogus to me - if you look at the byte code generated, the compiler adds the same `super()` implicitly.

Yeah, this is the reason why explicit call is redundant and goal of the check is to detect it.

**Comment by artembilan** [comment]
Well, I think we can change that `super()` call into a comment to satisfy all the rules around.
Also I think no one of them are aware about `private` empty ctors.

**Comment by garyrussell** [comment]
More discussion [here](https://github.com/checkstyle/checkstyle/pull/7387) about possibly changing EmptyBlock to allow empty no-arg CTORs.

**Comment by artembilan** [comment]
OK. So, placing "on-hold" until a resolution for linked issue in Checkstyle.

**Comment by strkkk** [comment]
@garyrussell 
> There is also the [EmptyBlock](https://checkstyle.sourceforge.io/config_blocks.html#EmptyBlock) checkstyle rule.

I checked this checkstyle rule and there is nothing about checking ctors. Can you please share checkstyle config that reports violation on empty ctor?

**Comment by garyrussell** [comment]
Interesting - I see checkstyle doesn't complain about empty CTORs and I just ran a test with our current Sonar rules and that passed too

https://sonar.spring.io/code?id=org.springframework.kafka%3Aspring-kafka-dist%3Asonar&selected=org.springframework.kafka%3Aspring-kafka-dist%3Asonar%3Aspring-kafka%2Fsrc%2Fmain%2Fjava%2Forg%2Fspringframework%2Fkafka%2Flistener%2FFoo.java

So this must have been some old rule on an older Sonar installation that is no longer triggered.

I therefore withdraw my objection.

**Comment by artembilan** [comment]
So, do we remove `super();` from our classes to satisfy requirements here?

**Comment by garyrussell** [comment]
I would say so, yes (over time).
