### ISSUE TITLE
SimplePool setPoolSize incorrectly updates internal fields

### ISSUE THREAD

**Issue by sergebg** [spring-projects/spring-integration#3143]
##  Bug report

When new pool size is less then existing, setPoolSize() method breaks consistency.
This happens when CachingSessionFactory is constructed using the most "convenient" constructor `CachingSessionFactory(SessionFactory<F> sessionFactory)`. In this case initial poolSize=Integer.MAX_VALUE. And so when later we are trying to setup some other value, the pool object becomes broken.

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-integration/commit/dba307adf62e703b8f5df9bc23330eb99ecf1a01
