### ISSUE TITLE
Issue with AbstractCorrelatingMessageHandler in handling sequences if used in nested ScatterGather sequence

### ISSUE THREAD

**Issue by sirimamilla** [spring-projects/spring-integration#3157]
**Affects Version(s):** 5.2.x, 5.1.x
---
If the output processor in ScatterGather returns a message, Scatter Gather is hanging indefinitely. 
This issue is present with all versions of Spring Integration.

This can be tested with SI version 5.1.3

Please find the test case here in the example git project.
https://github.com/sirimamilla/ScatterGatherTest

**Comment by sirimamilla** [comment]
I have the fix for the issue, once the issue is accepted, I will open pull request for the same. Currently I am not able to raise the pull request as it is dependent of fix for https://github.com/spring-projects/spring-integration/issues/3152

This fix needs to be done along with or after Pull Request https://github.com/spring-projects/spring-integration/pull/3153. To test the fix, issue 3152 needs to be resolved.

**Comment by artembilan** [comment]
@sirimamilla ,

tell me, please, how this issue is different from that one you are mentioning in the opened PR.

Thanks

**Comment by sirimamilla** [comment]
Hi @artembilan,

The issue mentioned in PR is a new bug that is introduced in 5.1.7 and above and is related to Original_ Header handling.

This issue is related to Sequence Handling that has one unhandled scenario. If we agree that this fix can be merged along with PR #3153. I will push this fix to PR #3153

**Comment by artembilan** [comment]
No, let's hold of from complicating that PR.
I'm about for final review and merging that one.

We can come back to this afterwards.

So, stay tuned!

**Comment by sirimamilla** [comment]
I have not pushed the changes to Test application, so you were not able to see the difference. you can review test application now.
