### ISSUE TITLE
Can't find method in handler

### ISSUE THREAD

**Issue by alextrs** [spring-projects/spring-integration#3161]
**Affects Version(s):** Spring-Boot 2.2.3 with spring-integration-kafka 3.2.0.RELEASE
**Java Version:** AdoptOpenJDK 11.0.4

Have simple flow:
```
return IntegrationFlows
   .from(Kafka.messageDrivenChannelAdapter(container))
   .transform(record -> SpecificData.get().deepCopy(Member.SCHEMA$, record))
   .channel("in.event")
   .get();
```

And handler:
```
@Component
public class MyListener {
  @ServiceActivator(inputChannel = "in.event")
  public void handleRuleChangeEvent(@Header(KafkaHeaders.RECEIVED_MESSAGE_KEY) String key, @Payload Member member) {
        System.out.println(key);
  ...
```

Member is in the same package:
```
@org.apache.avro.specific.AvroGenerated
public class Member extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
...
```
At run-time get and error:
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method handleRuleChangeEvent(java.lang.String,com.home.kfk.mykafka.Member) cannot be found on type com.home.kfk.mykafka.MyListener
```

**Comment by artembilan** [comment]
Any chances to have a simple project to reproduce?

Any chances to try with the latest Spring Integration `5.2.3.RELEASE`?
You can just simply override Spring Integration version in your Spring Boot project:
```
<properties>
    <spring-integration.version>5.2.3.RELEASE</spring-integration.version>
</properties>
```

Or just upgrade your Spring Boot to version `2.2.4.RELEASE`! That one brings exactly the mentioned Spring Integration version.

**Comment by alextrs** [comment]
Tried with ***2.2.4*** the same

Interesting that if I add "-Dspring.devtools.restart.enabled=false" it start working

Will create simple project

**Comment by artembilan** [comment]
So, ClassLoader issue. We might load that method call via SpEL in wrong one.
Would be great to see a very simple project to play with.

I even think Kafka and Avro are not related.

Thanks

**Comment by alextrs** [comment]
Here you go https://github.com/alextrs/kafka-cl-sample

**Comment by artembilan** [comment]
Thank you!

But it we reproduce an issue without Kafka and Avro?
I just don't have them locally. 😢

**Comment by alextrs** [comment]
Didn't try, but there is docker-compose.yaml to get you working Kafka environment with schema registry (if you have docker), just kick:
```
docker-compose up
```

**Comment by artembilan** [comment]
No, I can't do that. I don't have access to the `io.confluent:kafka-avro-serializer` somehow.
My Maven doesn't download it from anywhere.

**Comment by alextrs** [comment]
I removed Kafka and confluent serializer, please, pull again

**Comment by artembilan** [comment]
Great! Thank you!

No it's working an I really ca reproduce, but when I comment out ` .transform(record -> SpecificData.get().deepCopy(User.SCHEMA$, record))` it works back.
So, looks like that `deepCopy()` does something wrong with ClassLoader. Not a Spring Integration (or Spring Boot, Framework etc.) problem.

We need to figure out how to propagate a `ClassLoader` from `BeanFactory` into Avro, but it doesn't sound like this project responsibility already or even the whole Spring Boot...

**Comment by alextrs** [comment]
SpecificData constructor accepts ClassLoader as parameter how can I get the correct one to pass?

**Comment by alextrs** [comment]
Got it working using 
```new SpecificData(beanFactory.getBean(MyListener.class).getClass().getClassLoader())```
Thank you

**Comment by artembilan** [comment]
```
public class SpringConfig implements BeanClassLoaderAware {

    private ClassLoader classLoader;

   @Override
    public void setBeanClassLoader(ClassLoader classLoader) {
        this.classLoader = classLoader;
    }

   ...
     .transform(record -> new SpecificData(this.classLoader).deepCopy(User.SCHEMA$, record))

   ...
}

So, the problem with right way to propagate a bean `ClassLoader` into an Avro.
