### ISSUE TITLE
String key should be Object, cause removeSessionFactory and getSessionFactory works with Object

### ISSUE THREAD

**Issue by kezhevatov** [spring-projects/spring-integration#3169]
https://github.com/spring-projects/spring-integration/blob/509e8237e8aa374990f07d288da083eb2229bdf5/spring-integration-file/src/main/java/org/springframework/integration/file/remote/session/DefaultSessionFactoryLocator.java#L57

**Comment by artembilan** [comment]
Wow! That's good catch!

Indeed this is a bug: all other `DefaultSessionFactoryLocator` contracts are based on the `Object`, so this `addSessionFactory` has to be on `Object` as well.

As a workaround you can fully rely on the `DefaultSessionFactoryLocator(Map<Object, SessionFactory<F>> factories)` constructor.

Feel free to provide a contribution: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc 

Thanks!

**Comment by artembilan** [comment]
I think for binary backward compatibility we need to deprecate an existing method and introduce a new one.
The old one will be removed in the next version.
