### ISSUE TITLE
Priority header not mapped to JMS Message

### ISSUE THREAD

**Issue by micheljung** [spring-projects/spring-integration#3179]
**Affects Version(s):** 5.2.3.RELEASE
---

The [DefaultJmsHeaderMapper](https://docs.spring.io/spring-integration/api/org/springframework/integration/jms/DefaultJmsHeaderMapper.html) copies message headers from Spring Integration Messages to JMS Messages.

According to [Mapping Message Headers to and from JMS Message](https://docs.spring.io/spring-integration/reference/html/jms.html#jms-header-mapping), the `priority` header should be mapped, too:

> previously, the priority header was only used for outbound messages

However, this is not tested by [DefaultJmsHeaderMapperTests](https://github.com/spring-projects/spring-integration/blob/v5.2.3.RELEASE/spring-integration-jms/src/test/java/org/springframework/integration/jms/DefaultJmsHeaderMapperTests.java) and [has been broken 5 years ago](https://github.com/spring-projects/spring-integration/commit/c7286cc9911c2bc99d148b8a6b0cf60f61633174#diff-289792238953e560f221e09fd65041faR145).
by this statement:

https://github.com/spring-projects/spring-integration/blob/e9cfb0289ad0c19093c6c1e7efdb552b3aff8c79/spring-integration-jms/src/main/java/org/springframework/integration/jms/DefaultJmsHeaderMapper.java#L165-L166

Since `priority` is often a primitive (in my case, [`org.apache.activemq.command.Message#priority`](https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/command/Message.java#L74) is a `byte` but [`org.springframework.integration.jms.StubTextMessage#priority`](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-jms/src/test/java/org/springframework/integration/jms/StubTextMessage.java#L52) also uses `int`), checking it for `null` doesn't do the trick.

Interestingly, there's also `spring-jms`'s [SimpleJmsHeaderMapper](https://github.com/spring-projects/spring-framework/blob/master/spring-jms/src/main/java/org/springframework/jms/support/SimpleJmsHeaderMapper.java#L99) which looks almost identical but behaves correctly (in this case):

https://github.com/spring-projects/spring-framework/blob/a4179b479599c62a89b5e67dbfa0d28ad61c638b/spring-jms/src/main/java/org/springframework/jms/support/SimpleJmsHeaderMapper.java#L99

**Comment by micheljung** [comment]
My workaround:

```java
...
Jms.outboundAdapter(connectionFactory)
        .configureJmsTemplate(spec -> spec.jmsMessageConverter(outboundMessageConverter()))
...

  // TODO remove once https://github.com/spring-projects/spring-integration/issues/3179 is fixed
  private static MessageConverter outboundMessageConverter() {
    return new SimpleMessageConverter() {

      @Override
      @SuppressWarnings({"NullableProblems", "ConstantConditions"})
      protected ObjectMessage createMessageForSerializable(Serializable object, Session session) throws JMSException {
        if (!(object instanceof Message)) {
          throw new IllegalStateException("Unexpected type: " + object.getClass());
        }
        ObjectMessage message = super.createMessageForSerializable(object, session);
        message.setJMSPriority(((Message<?>) object).getHeaders().get(MessageHeaders.PRIORITY, Integer.class));
        return message;
      }
    };
  }
```

**Comment by artembilan** [comment]
We do map `priority` in Spring Integration with slightly different approach:
```
if (this.jmsTemplate instanceof DynamicJmsTemplate && this.jmsTemplate.isExplicitQosEnabled()) {
			Integer priority = StaticMessageHeaderAccessor.getPriority(message);
			if (priority != null) {
				DynamicJmsTemplateProperties.setPriority(priority);
			}
```

See `JmsSendingMessageHandler`. It is supplied with the `DynamicJmsTemplate` which has this code:
```
	public int getPriority() {
		Integer priority = DynamicJmsTemplateProperties.getPriority();
		if (priority == null) {
			return super.getPriority();
		}
		Assert.isTrue(priority >= 0 && priority <= 9, "JMS priority must be in the range of 0-9");
		return priority;
	}
```


So, consider to enable `explicitQosEnabled(true)` in that `configureJmsTemplate()`.

**Comment by artembilan** [comment]
Now I recall the reason: not all JMS providers allow to modify properties like `JMSPriority` in messages before sending on the client.
That might work with ActiveMQ, but definitely might not work with others.

Also pay attention that you have been misled: the `MessageHeaders.PRIORITY` is not mapped into a `setJMSPriority()` in that `SimpleJmsHeaderMapper` because it is not a `JMSPriority`. 
See the mentioned logic:
```
	if (StringUtils.hasText(headerName) && !headerName.startsWith(JmsHeaders.PREFIX)
						&& jmsMessage.getObjectProperty(headerName) == null) {
```
So, we try to check here a `priority` property. Meanwhile the real `setJMSPriority()` is mapped into a `JMSPriority`. See `org.apache.activemq.filter.PropertyExpression` for example.

Therefore a summary: or stay with your custom `MessageConverter`  if your JMS provider allows to modify a message, or follow a solution we suggest out-of-the-box: the `explicitQosEnabled(true)` and respective `MessageHeaders.PRIORITY` header in the `Message<?>` you send to this `Jms.outboundAdapter()`.

Does it make sense?

**Comment by micheljung** [comment]
> Does it make sense?

Let's say I understood enough of it :-) `explicitQosEnabled(true)` did the trick! Do you think this should be documented more clearly in [the JMS documentation](https://docs.spring.io/spring-integration/reference/html/jms.html)? I saw it's documented for `outbound-gatway`:

> The default priority of request messages. Overridden by the message priority header, if present. Its range is 0 to 9. This setting takes effect only if explicit-qos-enabled is true.

Not however in [Outbound Channel Adapter](https://docs.spring.io/spring-integration/reference/html/jms.html#jms-outbound-channel-adapter) or [Mapping Message Headers to and from JMS Message](https://docs.spring.io/spring-integration/reference/html/jms.html#jms-header-mapping)

Thank you for your help!

**Comment by artembilan** [comment]
Yep! Indeed it has to be documented. And I definitely think that "Mapping headers" section is the right way to go.

Thanks for the pointer!
