### ISSUE TITLE
MQTT should support `setManualAcks`

### ISSUE THREAD

**Issue by YiuTerran** [spring-projects/spring-integration#3181]
**Affects Version(s):** all

## Enhancement

MQTT is designed to provide reliable commuication. When broker send message using QoS>0, the client should do something before sending ack to ensure the message is really processed. 

For example, i created a thread pool to process message in parallel.

```java
    @Bean
    public ThreadPoolTaskExecutor mqttMessageExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(2);
        executor.setMaxPoolSize(10);
        executor.setQueueCapacity(100);
        executor.setThreadNamePrefix("mqtt_");
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.setWaitForTasksToCompleteOnShutdown(true);
        return executor;
    }
    @Bean
    public MessageChannel mqttInboundChannel(ThreadPoolTaskExecutor mqttMessageExecutor) {
        return new ExecutorChannel(mqttMessageExecutor);
    }
```

If the service shutdown abnormally when processing message, all message in queue will be lost. So, ack should be sent after `MessageHandler` handle the message. Or, using original `setManualAcks`, client can send ack manually.

**Comment by artembilan** [comment]
I guess you talk about this API in the `IMqttClient`:
```
	/**
	 * If manualAcks is set to true, then on completion of the messageArrived callback
	 * the MQTT acknowledgements are not sent.  You must call messageArrivedComplete
	 * to send those acknowledgements.  This allows finer control over when the acks are
	 * sent.  The default behaviour, when manualAcks is false, is to send the MQTT
	 * acknowledgements automatically at the successful completion of the messageArrived
	 * callback method.
	 * @param manualAcks if set to true, MQTT acknowledgements are not sent.
	 */
	public void setManualAcks(boolean manualAcks);
	
	/**
	 * Indicate that the application has completed processing the message with id messageId.
	 * This will cause the MQTT acknowledgement to be sent to the server.
	 * @param messageId the MQTT message id to be acknowledged
	 * @param qos the MQTT QoS of the message to be acknowledged
	 * @throws MqttException if there was a problem sending the acknowledgement
	 */
	public void messageArrivedComplete(int messageId, int qos) throws MqttException;
```

So, we need to consider an `AcknowledgmentCallback` implementation (together with the `AcknowledgmentCallbackFactory`) for MQTT.
See its implementation for AMQP in the `AmqpMessageSource`.

Something similar we have in the Spring Integration for Apache Kafka: https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java#L678

We have to populate an `IntegrationMessageHeaderAccessor.ACKNOWLEDGMENT_CALLBACK` to let the target app to ack processed messages manually.

@garyrussell , WDYT?

**Comment by garyrussell** [comment]
Yes; agreed.

**Comment by shanemwalker** [comment]
Hi there,

I have recently been using the manualAck feature within an MQTT integration flow. I have read through the documentation and have reviewed the Spring integration examples and I haven not been able to find the answer to the below question...

What is the best practice when using manualAck if a processing failure occurs and I don't want to Ack yet (to guarantee processing in a flow completes e.g. persist to a DB)? Not Ack'ing manually at all during an integration flow causes the adapter to stall until an entire spring boot restart (no more processing of any messages on the topic). 

How can I get the adapter to retry again without a restart? Is there any sort of timeout configurable within the adapter or is there a spring integration flow timeout I am missing (not specific to MQTT)?

Thank you in advance for any pointers here.

**Comment by artembilan** [comment]
@shanemwalker ,

your question is really specific to MQTT protocol by itself. Spring Integration is just a delegate and wrapper around Paho MQTT client.
You need to redirect your question to the MQTT community to determine the proper control flow for your use-case.
Then you can come back to us with feedback if anything is needed to be adjusted in Spring Integration.

For now it is fully wrong to ask questions on old closed GH issue or PRs.
More over it is not OK to ask question in GH issues or PRs.
There are `Discussions` tab for the purpose or, as I prefer, better to always ask questions on StackOverflow: someone else from community can help you - no need to wait for project team members to wake up.
Plus, as I said before: the question is not always related to this project.

**Comment by shanemwalker** [comment]
> @shanemwalker ,
> 
> your question is really specific to MQTT protocol by itself. Spring Integration is just a delegate and wrapper around Paho MQTT client. You need to redirect your question to the MQTT community to determine the proper control flow for your use-case. Then you can come back to us with feedback if anything is needed to be adjusted in Spring Integration.
> 
> For now it is fully wrong to ask questions on old closed GH issue or PRs. More over it is not OK to ask question in GH issues or PRs. There are `Discussions` tab for the purpose or, as I prefer, better to always ask questions on StackOverflow: someone else from community can help you - no need to wait for project team members to wake up. Plus, as I said before: the question is not always related to this project.

Hey Artem,

Apologies for raising this here. Thank you for your feedback.

Regards,

Shane
