### ISSUE TITLE
Tcp ClientModeConnectionManager logs Stacktrace

### ISSUE THREAD

**Issue by dwirtz** [spring-projects/spring-integration#3184]
**Affects Version(s):** \<5.2.3.RELEASE>
**Modul:**\<spring-integration-ip>

## Question

I am using the spring-integration-ip module for creating a TCP client to establish a connection to a certain TCP server. If this server is not available for any reason - so the connection cannot be established - the underlying **ClientConnectionFactory** throws an **Exception**. This exception is catched by the **ClientModeConnectionManager** and here I see a problem. 

The **ClientModeConnectionManager** does not even catch the exception but logs the stacktrace which I tried to prevent. Furthermore I want that exception to be delegated to an errorchannel which is not possible because the **ClientModeConnectionManager** does not rethrow the exception at all so the **DelegatingErrorHandlingRunnable** (which calls the manager) is not able to delegate the exception to an errorhandler. 

```
try {
   TcpConnection connection = this.clientConnectionFactory.getConnection();
   if (connection != this.lastConnection) {
      if (this.logger.isDebugEnabled()) {
          this.logger.debug("Connection " + connection.getConnectionId() + " established");
      }
   this.lastConnection = connection;
   }
  else {
     if (this.logger.isTraceEnabled()) {
          this.logger.trace("Connection " + connection.getConnectionId() + " still OK");
     }
  }
} catch (Exception e) {
   this.logger.error("Could not establish connection using " + this.clientConnectionFactory, e);
}
```
___

```
try {
   this.delegate.run();
} catch (UndeclaredThrowableException var2) {
   this.errorHandler.handleError(var2.getUndeclaredThrowable());
} catch (Throwable var3) {
   this.errorHandler.handleError(var3);
}
```

When we look at the TCP ConnectionFactories for being a TCP server all thrown exceptions seem to be wrapped into a kind of Spring Messaging Exception (what should usually happen in Spring integraton, shouldn't it?). 

So I asked myself if there is any chance to delegate the exception (in case a TCP client is not able to establish a connection) to an errorchannel or to prevent logging the stacktrace?

___

Example TCP Client creation:

```
final TcpClientConnectionFactorySpec client = 
    Tcp.netClient(host, port) // automatically provides a connection factory
         .deserializer(TcpCodecs.singleTerminator((byte) 0x00, 1000));

final TcpInboundChannelAdapterSpec inbound = 
    Tcp.inboundAdapter(client) // we can use an own connectionfactory here to suppress the exception, but this is rather a workaround
         .clientMode(true)
         .retryInterval(5000)
         .errorChannel("myErrorChannel"); // assume this channel is provided as a bean
```

**Comment by garyrussell** [comment]
It's not clear what you are asking.

Client mode is a bit weird - it's a server for incoming requests where the server initiates the connection.

By necessity, the connection is established asynchronously.

You can suppress the log by configuring your logging subsystem to not log at ERROR level from that class.

The error channel is meant for sending an error message when an incoming message fails to be processed correctly; not for exceptions like this.

We should, however, publish a `TcpConnectionExceptionEvent` for these exceptions so the application can get notifications.

	@EventListener
	public void listen(TcpConnectionEvent event) {
		...
	}

**Comment by garyrussell** [comment]
Correction:

We already do publish an event for this use case:

```
	@EventListener
	public void listen(TcpConnectionFailedEvent event) {
		System.out.println(event);
	}
```

>TcpConnectionFailedEvent [source=bean 'flow.null#0'; defined in: 'com.example.demo.Sigh3184Application'; from source: 'bean method flow', host=localhost, port=1234, cause=java.io.UncheckedIOException: java.net.ConnectException: Connection refused (Connection refused)]

**Comment by dwirtz** [comment]
Ok that explanation is really helpful for me. I think I was just a little bit confused but it makes sense to me that an error channel is used for errors related to a message.

Thank you 👍
