### ISSUE TITLE
DefaultSftpSessionFactory file resolving inconsistency

### ISSUE THREAD

**Issue by andybaer** [spring-projects/spring-integration#3211]
Using Spring Boot 2.2.4 with Spring Integration SFTP 5.2.3

`org.springframework.integration.sftp.session.DefaultSftpSessionFactory`

Actual Behavior:
Property `privateKey` expects the prefix `file:` since it is resolved by Spring.
Property `knownHosts` does not work with `file:` prefix since it is passed directly to JCraft.

Expected Behavior:
Both properties `privateKey` and `knownHosts` work with `file:` prefix.

**Comment by artembilan** [comment]
There is  an API like this:

```
 /**
   * Sets the instance of <code>KnownHosts</code> generated with
   * <code>stream</code>.
   *
   * @param stream the instance of InputStream from known_hosts file.
   *
   * @throws JSchException
   *         if an I/O error occurs.
   *
   * @see com.jcraft.jsch.KnownHosts
   */
  public void setKnownHosts(InputStream stream) throws JSchException{ 
```

So, we indeed can have that `knownHosts` as a `Resource` as well and propagate its `InputStream` into `JSch` properly.

Feel free to contribute the fix, @andybaer !

Thanks for pointing this out!

**Comment by artembilan** [comment]
@andybaer ,

Since you have not answered yet, but we are going to release tomorrow, I take an issue and will provide a Pull Request shortly.

**Comment by andybaer** [comment]
@artembilan 

Sorry for the late answer. I tried to get the build working behind the corporate proxy but failed to do so.

Thank you very much
