### ISSUE TITLE
spring-integration-zookeeper: Provide a mechanism to customize the Candidate Id

### ISSUE THREAD

**Issue by berngp** [spring-projects/spring-integration#3213]
As a Developer it would be useful to have the ability to customize the _Candidate Identifier_ used by the `LeaderInitiatorFactoryBean`.  Currently this _candidate identifier_ is always set to a random UUID.

In Exhibitor UI this is represented as the **Data as String** field. 
![image](https://user-images.githubusercontent.com/134985/76357359-cb341b80-62d4-11ea-803c-238b39157fc7.png)

**Comment by artembilan** [comment]
@berngp ,

See the fix for this issue: https://github.com/spring-projects/spring-integration/commit/46cf5db78a42c73c8574a9ef05143f5b6116231b.

Thank for your effort anyway!

**Comment by berngp** [comment]
Thanks @artembilan, looks great!
