### ISSUE TITLE
ServiceActivator methods not discovered if named "start", "stop" or "isRunning"

### ISSUE THREAD

**Issue by grubeninspekteur** [spring-projects/spring-integration#3230]
**Affects Version(s):** 5.1.0

## Bug report
If a service activator has methods named "start", "stop" or "isRunning", these cannot be automatically discovered by SI. The activating method must be specified explicitly.

`Target object of type [...] has no eligible methods for handling Messages.`

This happens due to these methods being filtered in [MessagingMethodInvokerHelper.java#L827](https://github.com/spring-projects/spring-integration/blob/a6fb891a817dacc1af9fa238fa0797623ea65416/spring-integration-core/src/main/java/org/springframework/integration/handler/support/MessagingMethodInvokerHelper.java#L827)

**Comment by garyrussell** [comment]
That is by design.

Can you explain your use case?

If you are trying to control the lifecycle of endpoints, the proper way to do that is via the [Control Bus](https://docs.spring.io/spring-integration/docs/5.2.5.RELEASE/reference/html/system-management.html#control-bus).

Send a message to the control bus with `someEndpoint.stop()`, etc.

**Comment by grubeninspekteur** [comment]
We just happened to name a method of an endpoint POJO "start". The error message was not helpful in finding the cause; If these method names are not allowed, maybe we should document it in [Service Activator](https://docs.spring.io/spring-integration/reference/html/service-activator.html)?

**Comment by garyrussell** [comment]
Maybe we should tighten up the filter to also check that there are no parameters on those methods (or `stop(Runnable)`).

@artembilan WDYT?

**Comment by artembilan** [comment]
Good catch! And I guess we just don't have any documentation on the matter.
I think we can just apply a `ControlBusMethodFilter` for discovered methods to check their legitimacy.
If method fail, we definitely should say something in the error about Control Bus.
And of course in the end we have to document this limitation.

Does it sound OK?

**Comment by grubeninspekteur** [comment]
Sounds good!

**Comment by artembilan** [comment]
So, since we all are OK with proposal, I wonder, @grubeninspekteur , if you can come up with a contribution on the matter: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by garyrussell** [comment]
I'll take it since M4 is tomorrow.
