### ISSUE TITLE
IdempotentReceiverInterceptor Improvement

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3241]
Enhance the `MetadataStoreSelector` to provide an option to evaluate an expression against the current value (if present) instead of simply `putIfAbsent`.

Consider https://stackoverflow.com/questions/61040057/spring-integration-process-files-line-by-line-persisting-read-state/61046158#61046158

Such an enhancement would allow a single MetadataStore entry with the key being the file and the value being the line number. The new option could compare the stored value to to the current line number and skip the line if it has already been processed.

Currently, we'd need a key containing the file name and line number.

**Comment by artembilan** [comment]
Hm. Sounds more like a `BiPredicate<OLD, NEW>` to compare existing value and what we would like to store.
In the end we could use a `replace(String key, String oldValue, String newValue)` to be sure that we don't override an entry stored by some other process.

WDYT?

**Comment by garyrussell** [comment]
Right - will push a PR for review (no docs yet).
