### ISSUE TITLE
SftpSession.exists() does not throw exception

### ISSUE THREAD

**Issue by superm1a3** [spring-projects/spring-integration#3247]
`SftpSession.exists()` method catches `SftpException` but ignores it. Why not throw a `NestedIOException` like other methods do?

In my code I use `exists` to check whether the remote file exists or not before I call `remove` to delete the file. In case when the logic inside `exists` throws an `IOException` (Pipe closed), it returns `false`, indicating the remote file does not exists.

Thanks,
Gary

**Comment by artembilan** [comment]
We need to think why is that exception ignored so far because the session contract is:
```
	/**
	 * Check if the remote file or directory exists.
	 * @param path the remote path.
	 * @return {@code true} or {@code false} if remote path exists or not.
	 * @throws IOException an IO exception during remote interaction.
	 */
	boolean exists(String path) throws IOException;
```

Meanwhile you can consider a workaround for your use-case like:
```
SftpRemoteFileTemplate remoteFileTemplate = new SftpRemoteFileTemplate(sessionFactory());
remoteFileTemplate.<Boolean, ChannelSftp>executeWithClient(client -> {
				client.lstat(path);
				return true;
		});
```

So, if an exception is thrown from that `lstat()` call, it won't return `false` for you, but will be re-thrown to your code.

**Comment by artembilan** [comment]
I think our solution must be like this: https://stackoverflow.com/questions/13202789/how-to-check-directory-is-existed-before-creating-a-new-directory-in-jsch

Where a logical answer is present in the comment from Ton Bosma: 

> I think Exception is to eager, it can be more specific: 
   ```
   try{
         channel.stat(folderName); 
      } 
      catch (SftpException e ) { 
          if (e.id == ChannelSftp.SSH_FX_NO_SUCH_FILE ) {
                channel.mkdir(folderName);
          }
          else {
            throw e;
          } 
     }
```

Does it make sense?

WDYT, @garyrussell ?

Thanks

**Comment by artembilan** [comment]
Even if I treat this as a enhancement I think we need to back-port it to correct a behavior according contract expectations.

**Comment by garyrussell** [comment]
I assume you mean...

    if (e.id == ChannelSftp.SSH_FX_NO_SUCH_FILE ) {
        return false;
    }
    else {
        throw e;
    }

Yes, I agree it should be back-ported even though it's a behavior change.

**Comment by artembilan** [comment]
Yes, sorry, copy/paste artifact.

PR is on its way. Stay tuned...
