### ISSUE TITLE
Spring Integration Java DSL stops working when used in a Spring Batch modular configuration

### ISSUE THREAD

**Issue by garethpowell** [spring-projects/spring-integration#3253]
**Describe the bug**
Spring Integration using the DSL produces a `NoSuchBeanDefinitionException:` No bean named `'javaDslInChildContextFlow.channel#0' available`, when the flow is configured within a child `ApplicationContext` configured in a modular Spring Batch setup.

The problem appears between Spring Integration releases `5.1.1` and `5.1.2` and is still present in the latest release.

A secondary observation is that the child `ApplicationContext` requires `@EnableIntegration` on it's `@Configuration` class, whereas previously it would work when specified on just the `@SpringBootApplication` class.

**To Reproduce**
Add an `IntegrationFlow` with the Java DSL to a Spring Batch child `ApplicationContext` while using a version of Spring Integration `5.1.2` or greater.

**Expected behavior**
The Integration flow is created/instantiated correctly.

**Sample**

Here's a link to a [minimal, reproducible sample](https://github.com/garethpowell/spring-integration-batch-problem).

There's a branch calling `working-version` that shows the same code working with the Spring Integration version downgraded to `5.1.1`

**Comment by artembilan** [comment]
I wonder why do you think it is a Spring Integration problem, but not Spring Batch?
Can we reproduce an issue without Spring Batch?

It really doesn't sound for me a reasonable to have access into beans in the child context from the parent one.
Also it is really a child context responsibility to have its own environment even if it has an access to the parent one. Therefore it sounds logical to request an `@EnableIntegration` in the child application context.

I don't mind about the problem, just want to narrow a black box as much as possible to figure out what to fix.

Thanks

**Comment by artembilan** [comment]
The change was this: https://jira.spring.io/browse/INT-4569

And we fail now on the `BeanDefinition existingBeanDefinition = this.beanFactory.getBeanDefinition(beanName);`.
Not sure yet "why?".

investigating that `ApplicationContextFactory` feature from Spring Batch...

**Comment by artembilan** [comment]
I think the problem is here:
```
 * <p>If this factory is hierarchical, will ask any parent factory if the bean cannot
 * be found in this factory instance.
```
We should not use a `containsBean()` for the goal to check a `BeanDefinition`.

Will fix soon...

**Comment by garethpowell** [comment]
Hi Artem, Sorry for not getting back to you yesterday, but pleased to see you've located the source of the issue.

Best regards, Gareth
