### ISSUE TITLE
Unreleased cached sessions when receiving file fails

### ISSUE THREAD

**Issue by javierestevez** [spring-projects/spring-integration#3271]
**Affects 5.2.5.RELEASE**

I have an inbound flow that reads files from a SFTP server using a `CachingSessionFactory` with size 1. I had a very strange situation where files were removed from the SFTP server after the polling occurred but before the message was built in `AbstractRemoteFileStreamingMessageSource#doReceive`. The call to `session.readRaw(remotePath)` failed with a `SftpException: No such file or directory` from `jsch` wrapped in a NestedIOException by `SftpSession`, which was caught and rethrown.

As a result, the session that was acquired to read the payload was not released back to the pool, and further attempts to obtain a session from the pool failed with:
```
org.springframework.messaging.MessagingException: nested exception is org.springframework.integration.util.PoolItemNotAvailableException: Timed out while waiting to acquire a pool entry.
```

I believe this is a bug and the session should be returned back to the pool in case of failure.

**Comment by artembilan** [comment]
I think you are right:

The problem is here:
```
Session<?> session = this.remoteFileTemplate.getSession();
try {
	return getMessageBuilderFactory()
			.withPayload(session.readRaw(remotePath))
			.setHeader(IntegrationMessageHeaderAccessor.CLOSEABLE_RESOURCE, session)
			.setHeader(FileHeaders.REMOTE_DIRECTORY, file.getRemoteDirectory())
			.setHeader(FileHeaders.REMOTE_FILE, file.getFilename())
			.setHeader(FileHeaders.REMOTE_HOST_PORT, session.getHostPort())
			.setHeader(FileHeaders.REMOTE_FILE_INFO,
								this.fileInfoJson ? file.toJson() : file);
}
catch (IOException e) {
	throw new UncheckedIOException("IOException when retrieving " + remotePath, e);
}
```
we probably need really to close that session in that `catch` block.

Feel free in providing a fix: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc !
