### ISSUE TITLE
Possible Bug: payload router not choosing correct method from overloaded methods

### ISSUE THREAD

**Issue by markortiz905** [spring-projects/spring-integration#3273]
**Describe the bug**
I am trying to implement router for my 3 channels
- namely mapped to Integer, Long and String
- my input int(1 to 10) will mapped to Integer channel
- my input long(Long.MAX) will mapped to String????

**To Reproduce**
here is my integration context to reproduce - let me know if you need the git branch for the whole code
```
<int:gateway service-interface="com.example.demo.PrinterService" 
    default-request-channel="inputChannel" ></int:gateway>

<bean id="interceptor" class="com.example.demo.CustomChannelIntercepter" />
<int:channel id="inputChannel">
    <int:queue capacity="10"/>
    <int:interceptors>
        <ref bean="interceptor" />
    </int:interceptors>
</int:channel>

<int:payload-type-router input-channel="bridgeChannel">
    <int:mapping type="java.lang.Integer" channel="intChannel"/>
    <int:mapping type="java.lang.Long" channel="longChannel"/>
    <int:mapping type="java.lang.String" channel="stringChannel"/>
</int:payload-type-router>


<int:channel id="intChannel" />
<int:channel id="longChannel" />
<int:channel id="stringChannel" />
<int:channel id="outputChannel" />

<bean id="printer" class="com.example.demo.PollableService" />

<int:service-activator ref="printer" method="printInt"
    input-channel="intChannel" output-channel="outputChannel">
</int:service-activator>

<int:service-activator ref="printer" method="printString"
    input-channel="stringChannel" output-channel="outputChannel">
</int:service-activator>

<int:service-activator ref="printer" method="printLong"
    input-channel="longChannel" output-channel="outputChannel">
</int:service-activator>


<int:bridge input-channel="inputChannel" output-channel="bridgeChannel">
    <int:poller fixed-rate="1" time-unit="SECONDS" max-messages-per-poll="2"/>
</int:bridge>
<int:channel id="bridgeChannel"></int:channel>
```

**Expected behavior**
- my input int(1 to 10) will mapped to Integer channel and will execute overloaded method of int param
- my input long(Long.MAX) will mapped to LOng channel and will execute overloaded method of long param

**Sample**
you can picture it out.

**Comment by artembilan** [comment]
Closed in favor of: https://stackoverflow.com/questions/61696638/spring-integration-payload-router-not-choosing-correct-channel

Please, don't raise an issue over here until it is confirmed there on StackOverflow.

Please, please bear with us: it is weekend right now. We will come back to you tomorrow in the morning.

Thanks for understanding!

P.S. We always can reopen if necessary
