### ISSUE TITLE
Reactive channel adapter not using error channel

### ISSUE THREAD

**Issue by sharif-93** [spring-projects/spring-integration#3276]
**Description**
I was trying to use `WebFlux.inboundGateway()` and use a custom error channel with `.errorChannel(customErrorChannel())`. I need this to prepare custom error response. But could not make the error channel to work and was getting default framework response for errors.

**Code**
I tried like the following
```
@Bean
public IntegrationFlow mainFlow() {
    return IntegrationFlows.from(WebFlux.inboundGateway(path)
            .errorChannel(customErrorChannel())
        )
        .transform(p -> {
            if(<some validation fails>)
                throw new RuntimeException("Error!");
            return "Ok Response";
        })
        .get();
}

@Bean
public PublishSubscribeChannel customErrorChannel() {
    return MessageChannels.publishSubscribe().get();
}

@Bean
public IntegrationFlow errorFlow() {
    return IntegrationFlows.from("customErrorChannel")
        .transform(p -> {
            return "Error Response";
        })
        .get();
}
```

**Link**
SO thread: https://stackoverflow.com/questions/61718691/how-to-use-custom-error-channel-to-produce-custom-error-response

**Comment by artembilan** [comment]
Turns out as a workaround you can add `.channel(MessageChannels.flux())` before your `transform()` and the error should be process through your `errorChannel`.

**Comment by sharif-93** [comment]
Tried with `.channel(MessageChannels.flux())` and it worked. Thanks!
