### ISSUE TITLE
DeadlockLoserDataAccessException during JdbcLock.unlock

### ISSUE THREAD

**Issue by astrubel** [spring-projects/spring-integration#3294]
A DeadlockLoserDataAccessException occurs at org.springframework.integration.jdbc.lock.JdbcLockRegistry$JdbcLock.unlock(JdbcLockRegistry.java:236)

I'm using the 4.3.19 release but no unlock() retrying is present in newer releases.

Could it be possible to retry unlock() in case of TransientDataAccessException like lock()?

```
while (true) {
	try {
		while (!doLock()) {
			Thread.sleep(100); //NOSONAR
		}
		break;
	}
	catch (TransientDataAccessException e) {
		// try again
	}
	...
}
```

Thank you in advance!

**Comment by artembilan** [comment]
I think I agree with your suggestion: indeed we can retry such an operation until success with no exceptions.

Feel free to raise a Pull Request. Although keep in mind that we are going to release tomorrow, not `4.3.23`, but still the fix must be present in the planed versions.

**Comment by astrubel** [comment]
Hi @artembilan,
Thank you very much for the merge!
Have you planed a date for the `4.3.23` version ?
Best regards

**Comment by artembilan** [comment]
July 22: https://github.com/spring-projects/spring-integration/milestone/37

Just after Spring Framework `4.3.28`!
