### ISSUE TITLE
StandardIntegrationFlowContext.getRegistrationById issue after setting Id

### ISSUE THREAD

**Issue by beardy247** [spring-projects/spring-integration#3306]
I have an issue retrieving an IntegrationFlowRegistration. I'm setting a custom Id on the flow, however when I try to retrieve the registration my code fails due to a null return value from getRegistrationById.

To reproduce:

```
...
this.context.registration(flow).register().setId("myId");
var registration = this.context.getRegistrationById("myId");
```
Results in registration being null.

Looking at the code 
```
	@Override
	public IntegrationFlowRegistration getRegistrationById(String flowId) {
		return this.registry.get(flowId);
	}
```
Setting the id doesn't update the key in registry so the lookup fails

Version 5.3.0.RELEASE

**Comment by artembilan** [comment]
Your issue is here: `.register().setId("myId")`
You should do `.registration(flow).id("myId").register()` instead.

I think we need to lose those `IntegrationFlowRegistration` setters to avoid similar conflicts.

**Comment by beardy247** [comment]
Thanks Artem

**Comment by deepak5127** [comment]
Hi @artembilan , Shall i work on this issue ?

**Comment by artembilan** [comment]
Hi @deepak5127 ,

Yes, you are welcome to take an issue and provide some possible fix as a Pull Request: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

Thanks
