### ISSUE TITLE
TransactionTimedOutException during DefaultLockRepository.acquire()

### ISSUE THREAD

**Issue by astrubel** [spring-projects/spring-integration#3307]
Hi,
I'm facing to `TransactionTimedOutException` that occurs at `DefaultLockRepository.acquire()`. I think is the parameter `timeout = 1` on the `@Transactional` annotation on it.
Why the lock is not retried in this case ? It's a naive question, really.
Thank you in advance!

**Comment by artembilan** [comment]
I think you are right: we need to add a `TransactionTimedOutException` into this catch:
```
catch (TransientDataAccessException e) {
					// try again
}
```

**Comment by astrubel** [comment]
I will create a pull request for it.
Could you backport to 4.3.x too ?

**Comment by artembilan** [comment]
> Could you backport to 4.3.x too ?

Marked respectively.
Will backport after the Pull Request.

Thanks

**Comment by astrubel** [comment]
What does represent the parameter `timeout` on the `@Transaction` annotation? Is it contains the access time to the database or only the transaction opening and processing time?

**Comment by artembilan** [comment]
Not sure what is your concern on the matter, but see its JavaDocs:
```
/**
	 * The timeout for this transaction (in seconds).
	 * <p>Defaults to the default timeout of the underlying transaction system.
	 * <p>Exclusively designed for use with {@link Propagation#REQUIRED} or
	 * {@link Propagation#REQUIRES_NEW} since it only applies to newly started
	 * transactions.
	 * @return the timeout in seconds
	 * @see org.springframework.transaction.interceptor.TransactionAttribute#getTimeout()
	 */
	int timeout() default TransactionDefinition.TIMEOUT_DEFAULT;
```

So, therefore it a timeout for the whole call including Java and DB access.

**Comment by astrubel** [comment]
So I think that 1s is not enough for db access through particular networks.

How can we expose this parameter to setup into project side?

Is it possible to replace `@Transactional` annotation by `TransactionTemplate` into `DefaultLockRepository.acquire()` and setup `TransactionTemplate.timeout`?
```
@Override
public boolean acquire(String lock) {
   // save previous transactionTemplate values
   int prevIso = transactionTemplate.getIsolationLevel();
   int prevTimeout = transactionTemplate.getTimeout();

   // setup acquire transaction
   transactionTemplate.setIsolationLevel(Isolation.SERIALIZABLE);
   transactionTemplate.setTimeout(this.getTimeout());
   transactionTemplate.execute(st -> {
      deleteExpired(lock);
      if (this.template.update(this.updateQuery, new Date(), this.region, lock, this.id) > 0) {
         return true;
      }
      try {
         return this.template.update(this.insertQuery, this.region, lock, this.id, new Date()) > 0;
      }
      catch (DuplicateKeyException e) {
         return false;
      }
   });

   // restore previous transactionTemplate values
   transactionTemplate.setIsolationLevel(prevIso);
   transactionTemplate.setTimeout(prevTimeout);
}
```

**Comment by artembilan** [comment]
I think the best and simplest way is to extend a `DefaultLockRepository` and override its `acquire()` with your own `@Transactional`.
But I see your point and really tended to remove that `timeout` altogether. No need to be so restrictive. Let's just rely on the underlying transaction management as it is explained on that `timeout()` option! 

Feel free to do such a change in your current PR - and we'll review & merger it shortly.

Thanks

**Comment by astrubel** [comment]
The current PR concern the management of the timeout exception. So I don't need to modify this one. 

You are true, for a particular case the simplest way is to extend and override!

Thank you so much for this talk ;)

**Comment by artembilan** [comment]
Cherry-picked to `5.3.x` & `5.2.x`.
Back-port to `4.3.x` as https://github.com/spring-projects/spring-integration/commit/b4d9831d9522059f51d35811d1ec6c4932c5e767

@astrubel ,

Thank you for contribution; looking forward for more!

**Comment by astrubel** [comment]
@artembilan Thank you very much
