### ISSUE TITLE
bug_report.md Does not Request a Version

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3321]
User should be asked to supply the version (s)he is reporting the bug against.

**Comment by artembilan** [comment]
Not sure what you mean, but you if contribute the fix, I'll review it shortly.

Does look like other Spring projects provide such an option.
Seems for me I heard that it was one of the reason why community wanted to go away from JIRA: too many not end-user friendly requests from the interface.

Thanks

**Comment by garyrussell** [comment]
I just mean add

**In what version(s) of the framework are you seeing this issue?**
e.g. 5.3.2.RELEASE

Between 

**Describe the bug**

and
**To Reproduce**
