### ISSUE TITLE
INT_METADATA_STORE table + older MySQL = 'Index column size too large'

### ISSUE THREAD

**Issue by no-simpler** [spring-projects/spring-integration#3323]
**Expected Behavior**

Running `schema-mysql.sql` on MySQL 5.6 or earlier with default configuration creates all tables without problems.

**Current Behavior**

Running `schema-mysql.sql` on MySQL 5.6 or earlier with default configuration causes an error:

```
Index column size too large. The maximum column size is 767 bytes.
```

**Context**

The root of the problem is the `INT_METADATA_STORE` table:

```sql
CREATE TABLE INT_METADATA_STORE  (
	METADATA_KEY VARCHAR(255) NOT NULL,
	METADATA_VALUE VARCHAR(4000),
	REGION VARCHAR(100) NOT NULL,
	constraint INT_METADATA_STORE_PK primary key (METADATA_KEY, REGION)
) ENGINE=InnoDB;
```

The primary key consists of two columns: `VARCHAR(255)` and `VARCHAR(100)`. Together they have `355` characters, which yields at least `1065` bytes (at 3 bytes per character).

MySQL 5.6 and earlier have the following [restriction](https://dev.mysql.com/doc/refman/5.6/en/innodb-limits.html):

> By default, the index key prefix length limit is 767 bytes.

There are plenty of workarounds, of course:

- We could configure `innodb-large-prefix` in our MySQL. (Not possible for us, unfortunately; at least not promptly.)
- We could drop the table altogether and avoid using `MetadataStore`.

I was wondering, whether `VARCHAR(255)` on `METADATA_KEY` is required? Maybe it could be painlessly slashed down to `155`?

**Comment by artembilan** [comment]
See this section in the docs: https://docs.spring.io/spring-integration/docs/current/reference/html/jdbc.html#initializing-the-database

We don't claim that we support all the RDBmS with our out of the box scripts. It is easy to take them and modify according your DB vendor. This is a task for your DBA. The changes done into table creation scripts don't effect Java code unless you change column name which is not acceptable by the framework. The column types and sizes could be changes. Also additional indexes and triggers could be added to those tables.

Closing as `Works as Designed`.

Thanks for understanding.
