### ISSUE TITLE
Don't make RemoteFileUtils.makeDirectories syncronized

### ISSUE THREAD

**Issue by dongja3** [spring-projects/spring-integration#3370]
**In what version(s) of Spring Integration are you seeing this issue?**
5.3.1.RELEASE

**Describe the bug**
It caused by org.springframework.integration.file.remote.RemoteFileUtils#makeDirectories, which is synchronized static method, when there are lots of (S)ftp move operation concurrently and slow speed of network, all requests of AbstractRemoteFileOutboundGateway#mv are queued and observed as very slow speed.

https://stackoverflow.com/questions/62772002/outbound-gateway-executes-the-mv-command-very-slowly

**Expected behavior**
in api doc, RemoteFileUtils#makeDirectories is static not synchronized, 
https://docs.spring.io/spring-integration/docs/5.3.1.RELEASE/api/
However, in source code is static and syncronized.

**Comment by garyrussell** [comment]
It was synchronized to fix a race condition.

https://github.com/spring-projects/spring-integration/pull/2915

**Comment by artembilan** [comment]
I think the request is valid. Even with that `synchronized` we definitely still may fail with race condition when our application is in cluster, so different nodes may try to create the same dirs at the same moment.

It is better to rework this logic to really catch an exception from the `session.mkdir(path)` when it says that `Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist` (`A file cannot be created if it already exists`). Probably as a second `session.exists(path)` check in the `catch` block...

WDYT?

**Comment by garyrussell** [comment]
Agreed; yes.

**Comment by dongja3** [comment]
Hi, Aterm, Gary
thanks for your prompt feedback, and look forward to the new release.
