### ISSUE TITLE
Support setting the trafficClass on sockets for udp via DSL.

### ISSUE THREAD

**Issue by Gerard414** [spring-projects/spring-integration#3410]
Setting the trafficClass is now not supported via DSL on UDP sockets.

I like that it is possbile to set the TrafficClass (similar as setting the timeout)

For example: 
`Upd.outboundAdapter(host, port).soTrafficClass(0x10).`

Extra behavior to setting the trafficClass 

I have created a workaround to set the traffic class on a udp socket.
This is not a neat way and may break on future updates for spring integration.

I need it because in our local network this is used to give priority to some udp messages.

**Comment by garyrussell** [comment]
Contributions are welcome; if you can't get to it, I'll take care of it tomorrow.

**Comment by Gerard414** [comment]
Thank you @garyrussell and @artembilan.

I'am very glad that this requested functionality is already added. I didn't expect that it will be added so soon :). As soon as this release is available we will use it.
