### ISSUE TITLE
ifAbsent support with ZsetOperations

### ISSUE THREAD

**Issue by ksinghddn** [spring-projects/spring-integration#3411]
**Expected Behavior**
ZsetOperations Should support ifAbsent method
**Current Behavior**

ZsetOperations does not support ifAbsent method currently

**Context**

I am trying to use Redis SortedSets for a project where I Need to insert a set only if its already not present. But with current implementation of RedisTemplate I am unable to achieve that as ifAbsent is not supported for ZsetOperations yet

**Comment by artembilan** [comment]
You probably better to raise this issue in the Spring Data project bug tracker: https://jira.spring.io/projects/DATAREDIS.

This project is about Enterprise Integration Patterns and messaging, not general "integration" : https://spring.io/projects/spring-integration

Thanks for understanding!
