### ISSUE TITLE
More refactoring to use a LogAccessor from the IntegrationObjectSupport

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3424]
For example an `AbstractPollingEndpoint` and its code like this:
```
if (logger.isDebugEnabled()) {
	logger.debug("Poll interrupted - during stop()? : " + e.getMessage());
}
```

**Comment by trungPa** [comment]
Am I correct to assume that we need to remove the `LogAccessor.is***Enabled()`s and replace them with `LogAccessor.***(Supplier<? extends CharSequence> messageSupplier)`? For example in OperationInvokingMessageHandler.java:
```
if (logger.isWarnEnabled()) {
	logger.warn("This component doesn't expect a reply. " +
			"The MBean operation '" + operation + "' result '" + result +
			"' for '" + objectName + "' is ignored.");
}
```
to
```
logger.warn(() -> "This component doesn't expect a reply. " +
		"The MBean operation '" + operation + "' result '" + result +
		"' for '" + objectName + "' is ignored.");
```

**Comment by artembilan** [comment]
That’s correct, @trungPa . 
Looking forward for your contribution !
Thank you!

**Comment by trungPa** [comment]
@artembilan can you assign this issue and #3549 to me?

**Comment by artembilan** [comment]
Unfortunately that’s not how GitHub works: we can assign only someone who is a part of the team or belongs to specially created group with an appropriate permission. Since in the end with the final merged contribution it doesn’t matter we don’t use that special group and say something in the issue comment that you claim it should be enough for external contributors to determine that this one is in progress . On the other hand I can assign it to myself to avoid any possible confusions while you are working on it. 
does it make sense ?

**Comment by trungPa** [comment]
@artembilan it sounds good.
So I'm leaving a comment here to say that I've been working on this issue.
