### ISSUE TITLE
Leaked kotlin-stdlib dependency on compile classpath

### ISSUE THREAD

**Issue by shanman190** [spring-projects/spring-integration#3428]
**In what version(s) of Spring Integration are you seeing this issue?**

Begins in 5.3.0.RELEASE and becomes and issue with 5.4.0

**Describe the bug**

Working with @marcingrzejszczak in Spring Cloud Contract on fixing the Gradle Kotlin support, I found that with 5.4.0 it's depending on Kotlin 1.4.10 which is then leaking from optional to compile and being brought into the latest snapshots of SCC Verifier Gradle Plugin which then results in a conflict for Gradle users (Gradle as of 6.7 is using 1.3.72). This effective kills SCC in the context of a project with Kotlin code.

**To Reproduce**

https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/producer_kotlin

1) Run `./gradlew build publishToMavenLocal` for the `common` project at the root of samples.
2) Run `./gradlew build` for the `producer_kotlin` project.

You can further interrogate `./gradlew dependencies` or `./gradlew dependencyInsight` to see the `kotlin-stdlib:1.4.0` dependency showing up off of spring-integration-core.

**Expected behavior**

For a clean Gradle build to be possible?

**Comment by artembilan** [comment]
I think you are asking to make Kotlin dep as optional. Which we indeed can do. Although the question is why do you use in that project `1.3.72`? Your claim about Gradle is not clear: I only see an explicit version in your project which you really can change to the mentioned `1.4.10` to make your project compatible with Spring portfolio from that generation when we have started to use Kotlin `1.4`.

**Comment by shanman190** [comment]
Also completely understand that in SCC kotlin-stdlib could be excluded, but since spring-integration-core declares it to be optional that's why I opened this ticket.

**Comment by shanman190** [comment]
Ok, so I'll try to be a little more explicit about the situation. Gradle itself is presently packaging a 1.3.72 version, so when a Gradle plugin (or one of its transitive dependencies) is using other versions that becomes a bit painful. 

As with the case of Spring Integration, [here](https://github.com/spring-projects/spring-integration/blob/6565b7cc43b1eb909f24880fd702ca300c7cc2d8/build.gradle#L432) you all declare Kotlin to be an optional dependency. However when published it's actually leaking out as a compile dependency as you can see in the pom.xml [5.4.0](https://search.maven.org/artifact/org.springframework.integration/spring-integration-core/5.4.0/pom) and started at [5.3.0.RELEASE](https://search.maven.org/artifact/org.springframework.integration/spring-integration-core/5.3.0.RELEASE/pom).

So this is really reporting to you all that the optional dependency isn't actually staying optional.

**Comment by artembilan** [comment]
Thanks for sharing your experience!
I'll take a look how that `compileOnly` will help us.

At the same time I really don't see this problem with `5.3.x` branch. Even the link to that Maven repo shows it like this:
```
   <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.3.72</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
```
So, that's indeed some issue with Gradle: our branch `5.3.x` is based on Gradle `6.4` meanwhile the `master` (5.4.x) on `6.7` already.

I hope the workaround to exclude `kotlin-stdlib-jdk8` dep from `spring-integration-core` is enough for for time being.

**Comment by artembilan** [comment]
Well, with `compileOnly` the `kotlin-stdlib-jdk8` dependency fully disappears from the final pom.
Looking further...

**Comment by shanman190** [comment]
@artembilan, yeah sorry that was my bad. I wasn't paying close enough attention and missed the optional xml tag. I was instead looking at scope and the artifactId only. 

By bad! 😆

**Comment by artembilan** [comment]
No problem! 
It is really suspicious situation: when I change Kotlin version from `1.4.10` to `1.3.72` it is populated properly into POM with my `optionalApi` variant... 😢

**Comment by shanman190** [comment]
Oh man! That's gonna be fun to figure out why the version change alone breaks the feature compatibility.
