### ISSUE TITLE
Gateway with no parameters

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-integration#3431]
If I have a Gateway defined as;
```
@Component
@MessagingGateway(defaultRequestChannel = "in", defaultReplyChannel = "out")
public interface MyGateway {
        MyResult run();
}
```
and a DSL flow as;
```
@Bean
public IntegrationFlow reconciliationFlow() {
   return IntegrationFlows.from("in")
       // do something
       .channel("out")
       .get();
```
and call as;
```
@Autowired MyGateway myGateway
MyResult myResult = myGateway.run();
```
I get the following error;
```
java.lang.IllegalStateException: receive is not supported, because no pollable reply channel has been configured
at org.springframework.util.Assert.state(Assert.java:73)
at org.springframework.integration.gateway.MessagingGatewaySupport.assertPollableChannel(MessagingGatewaySupport.java:475)
at org.springframework.integration.gateway.MessagingGatewaySupport.receive(MessagingGatewaySupport.java:462)
at org.springframework.integration.gateway.GatewayProxyFactoryBean.receive(GatewayProxyFactoryBean.java:538)
```

The intention here is that the Gateway doesn't need parameters, but should return something. If I redefine the Gateway's method to take a `String` as a parameters and pass an empty `String` from the call to the Gateway, the DSL flow works.

Is there a way to call a Gateway without parameters or is this a bug?

**Comment by garyrussell** [comment]
Please ask questions on StackOverflow; GitHub issues are for reporting actual bugs or asking for new features.

See [Invoking No-Argument Methods](https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#gateway-calling-no-argument-methods).

>To achieve send-and-receive semantics, you must provide a payload. To generate a payload, method parameters on the interface are not necessary. You can either use the @ Payload annotation or the payload-expression attribute in XML on the method element. The following list includes a few examples of what the payloads could be:

>  - a literal string

> - #gatewayMethod.name

> - new java.util.Date()

> - @someBean.someMethod()'s return value

>The following example shows how to use the @ Payload annotation:

```java
public interface Cafe {

    @Payload("new java.util.Date()")
    List<Order> retrieveOpenOrders();

}
```

But it can be as simple as `@Payload("''")`.

**Comment by artembilan** [comment]
Closed according supported mechanism via `@Payload` explained in the docs. 
See comment above.

**Comment by lafual** [comment]
Thanks for responding. RTFM ;-) Sorry to have wasted your time
