### ISSUE TITLE
Create a 'Build from Source' section in the README.md documentation

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-integration#3438]
Hello Spring Integration Team:

**Expected Behavior**

When I arrive to the [spring-integration](https://github.com/spring-projects/spring-integration) project there is no information about what JDK version should be used to import the project in the IDE (Java 8, 11?). It of course according for a contributor perspective

For example the [spring-framework](https://github.com/spring-framework/spring-framework) project has in its readme file the `Build from Source` section and indicating: 

* See the [Build from Source](https://github.com/spring-projects/spring-framework/wiki/Build-from-Source) Wiki page and the [CONTRIBUTING.md](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md) file. 

Where in the first link has the respective indications

**Current Behavior**

The readme file does not have a reference about neither `Build from Source` nor `See the Build from Source Wiki page` contents (something similar).

Exists the following in [Wiki](https://github.com/spring-projects/spring-integration/wiki), where appears in the right the [Requirements](https://github.com/spring-projects/spring-integration/wiki/Requirements) link. But really out of date

**Context**

Is not clear with what JDK I should use my IDE to work around (to contribute) Spring Integration.

Thanks for your understanding

**Comment by artembilan** [comment]
Hi @manueljordan !

Welcome back and sorry to see you have a pure experience with our instructions.
Will take care of it ASAP. Probably it still could be done as a PR so you will be able to review it.

Stay tuned!

**Comment by manueljordan** [comment]
Hello @artembilan and @garyrussell 

Don't worry. I reported this situation thinking in the future for any possible contribution by my side (and by others of course) and because I have an issue with IntelliJ Idea, so I thought that perhaps there is an instruction that should be listed in the requested documentation and thus it resolves my situation. Really huge thanks for the quick fix/solution
