### ISSUE TITLE
JdbcLockRegistry throws IllegalMonitorStateException in case of TransientDataAccessException

### ISSUE THREAD

**Issue by ohubaut** [spring-projects/spring-integration#3445]
**In what version(s) of Spring Integration are you seeing this issue?**

Identified in 5.4.2, but  bug has been back ported in 4.3x, 5.1.x and 5.2x branches
This issue was introduced by GH-3294

**Describe the bug**

The JdbcLockRegistry improperly unlock the delegate (a ReentrantLock) in case a TransientDataAccessException or a TransactionTimedOutException is thrown.
As this occurs in a while loop, the next time the delegate is unlocked, it not longer as a owner thread and throws an IllegalMonitorStateException.

**To Reproduce**

1. Instantiate a JdbcLockRegistry with a mock of LockRegistry
2. Acquire a lock
3. Configure the mock to throw a TransientDataAccessException on LockRegistry#delete
4. IllegalMonitorStateException is thrown

**Expected behavior**

The exception should not be thrown. The delegate should only be unlocked _**after**_ the while loop has exited

**Sample**

No sample provided as the issue is trivial to identify by looking at the code of the faulty PR.

**Comment by artembilan** [comment]
Confirmed. It is indeed am omission during review.

I think your test scenario with the mock `LockRepository` really makes sense and would give us a coverage which we have missed from the original fix.

Note: versions `4.3.x` and `5.1.x` have reached their EoL. Therefore after fixing this is everybody is encouraged to upgrade to respective supported version.

@ohubaut ,

thank you for reporting this! It would be great if you can contribute the fix together with the test.

**Comment by ohubaut** [comment]
Hi,

Pull request is available. 
Unfortunately, a test in another module (ftp) fails, so it is marked as red, but I tested the jdbc module locally and all tests were passing.

**Comment by artembilan** [comment]
No worries. I've re-ran the CI build.
Anyway I know that you didn't touch other modules.
Will review and probably merge shortly.
Let's continue discussion on your PR from now on!
