### ISSUE TITLE
Paho loses connection if the message converter returns null

### ISSUE THREAD

**Issue by deen13** [spring-projects/spring-integration#3454]
**In what version(s) of Spring Integration are you seeing this issue?**

5.2.8.RELEASE

**Describe the bug**

The paho mqtt client loses the connection if a custom converter returns null. In my case the application pairs each incoming message with some mandatory information. If the information are absent for any reason we return null in order to stop the spi message delivery.

#### MqttPahoMessageDrivenChannelAdapter
```java
@Override
public void messageArrived(String topic, MqttMessage mqttMessage) {
	Message<?> message = this.getConverter().toMessage(topic, mqttMessage);
	try {
		sendMessage(message);
	}
	catch (RuntimeException e) {
		logger.error("Unhandled exception for " + message.toString(), e);
		throw e;
	}
}
```

#### MessageProducerSupport
```java
protected void sendMessage(Message<?> messageArg) {
		Message<?> message = messageArg;
		if (message == null) {
			throw new MessagingException("cannot send a null message");
		}
              
                ...
}
```

**To Reproduce**

1. Implement a PahoMessageConverter
2. Make the `toMessage` method return null
3. Send a message and observe the client getting disconnected

**Expected behavior**

The client should drop the message entirely if the converter returns null.

**Comment by garyrussell** [comment]
The contract for `converter.fromMessage()` is marked as `@Nullable` so this does seem a reasonable request.

**Comment by garyrussell** [comment]
```java
	/**
	 * Convert to a message builder.
	 * @param topic the topic.
	 * @param mqttMessage the MQTT message.
	 * @return the builder.
	 */
	AbstractIntegrationMessageBuilder<?> toMessageBuilder(String topic, MqttMessage mqttMessage);
```

It is not marked `@Nullable`, but it probably should be.

**Comment by artembilan** [comment]
It is probably not OK to lose the connection, but at the same time I don't think it is OK to drop messages off if some converter logic returns `null`. This is not what most users would expect. We probably just need to think about sending such a bad message to the `errorChannel` instead of dropping it silently.

The current `MqttMessageConverter` is not to let to return `null`.
Currently the `MqttPahoMessageDrivenChannelAdapter` uses this contract though:
```
AbstractIntegrationMessageBuilder<?> toMessageBuilder(String topic, MqttMessage mqttMessage);
```
where its default implementation is about mapping bytes from the MQTT message and populating some useful headers.
No `null` is expected over there.

Therefore my suggestion is to handle any error (or `null`) from the conversion as an `ErrorMessage` producing instead of silent dropping and let end-user to rely on `null` return from the custom conversion for filtering logic. It is just not this channel adapter responsibility to lose the data.

**Comment by garyrussell** [comment]
Agreed; I wasn't offering an opinion on what to do when the converter returns null, just that the API is inconsistent with the super interface, which does, indeed, specify `@Nullable` on its method returns.

**Comment by artembilan** [comment]
I think that really was our intention to not have it as a `@Nullable` with this `MqttMessageConverter` which is indeed natural for this type of annotations on methods: if you don't want it as nullable, you just don't specify it on your method contract. We still probably should check for `null` in the `MqttPahoMessageDrivenChannelAdapter` to avoid unexpected NPE throwing.

**Comment by garyrussell** [comment]
Same thing on the outbound adapter...

```java
	@Override
	protected void handleMessageInternal(Message<?> message) {
		Object mqttMessage = this.converter.fromMessage(message, Object.class);
		String topic = this.topicProcessor.processMessage(message);
		if (topic == null && this.defaultTopic == null) {
			throw new IllegalStateException(
					"No topic could be determined from the message and no default topic defined");
		}
		publish(topic == null ? this.defaultTopic : topic, mqttMessage, message);
	}
```

Maybe throw an exception there?

**Comment by artembilan** [comment]
Hm. Looks like we are covered against `null` in the `MqttPahoMessageHandler` impl:
```
protected void publish(String topic, Object mqttMessage, Message<?> message) {
		Assert.isInstanceOf(MqttMessage.class, mqttMessage, "The 'mqttMessage' must be an instance of 'MqttMessage'");
```

**Comment by garyrussell** [comment]
OK

**Comment by deen13** [comment]
Hey!

Thanks for fixing the issues that fast! I've seen that this is labelled as backport and available on the 5.4.x branch. Is there a way for me to get the commit before the 5.5 release?

**Comment by artembilan** [comment]
The version `5.4.3` with this fix is going to be released tomorrow:  https://calendar.spring.io/

**Comment by deen13** [comment]
Awesome! I didn't know about the calendar but comes in pretty handy. :)
