### ISSUE TITLE
Update commons-net from 3.7 to 3.7.2

### ISSUE THREAD

**Issue by MichaelF25** [spring-projects/spring-integration#3463]
We run into an issue after upgrading to Spring Boot 2.4.x which upgrades Spring Integration to 5.4.x and upgrades Apache Commons Net from 3.6 to 3.7.
Seems like there's a bug introduced in commons-net-3.7 which is resolved in commons-net-3.7.2 within the FTPS Client (we faced some SSL errors).
For now, we updated the dependency to commons-net manually to current version 3.7.2 which resolved the SSL errors.
Since commons-net-3.7.2 is a bugfix release, we didn't go into details what the causing issue was.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/d4a4e244608c54b3e91935a4d578b7ae0e0e7785.

Thanks for reporting!
