### ISSUE TITLE
Possible inconsistency of exception propagation depending on transformer code

### ISSUE THREAD

**Issue by GrafDiffusore** [spring-projects/spring-integration#3474]
**In what version(s) of Spring Integration are you seeing this issue?**

5.2.4.RELEASE

**Describe the bug**

My test for handling of exceptions thrown inside a flow fails when I'm using a lambda as an argument to `transform` and passes when I'm using a subclass of `AbstractPayloadTransformer`

**Expected behavior**

I was expecting no difference for tests.

**Sample**

In code below, uncomment lambda version and comment subclass version of transformer to fail the test. Not sure if it's real bug or lack of understanding on my side. Still, was expecting no difference in behavior.

```
@RunWith(SpringRunner.class)
public class ErrorHandlingTests {

    @Autowired
    BuggyService buggyService;

    interface BuggyService {
        @Nonnull
        String process(@Nonnull String input);
    }

    @EnableIntegration
    @Configuration
    static class Config {
        @Bean
        IntegrationFlow flowWithException() {
            return IntegrationFlows.from(BuggyService.class)
/*
                    .<String, String>transform(s -> {
                        if (s.contains("oops"))
                            throw new IllegalArgumentException("Bad value");
                        return s;
                    })
*/
                    .transform(new AbstractPayloadTransformer<String, String>() {
                        @Override
                        protected String transformPayload(String s) {
                            if (s.contains("oops"))
                                throw new IllegalArgumentException("Bad value");
                            return s;
                        }
                    })
                    .handle((p, h) -> "Received " + p)
                    .get();
        }
    }

    @Test
    public void testExceptionInFlow() {
        assertEquals("Received hehe", buggyService.process("hehe"));
        try {
            buggyService.process("he oops he");
            fail();
        } catch (IllegalArgumentException e) {
            assertEquals("Bad value", e.getMessage());
        }
    }

}
```

**Comment by artembilan** [comment]
I think you concern makes sense and it really should not matter what API you choose for transformer.

So, I guess we just should not wrap into an `IllegalStateException` if the exception is already `RuntimeException` in the `LambdaMessageProcessor`.

With that said we are not going to treat it as critical bug and won't back-port it since it might be a breaking change for some one.
So, the fix is only going to the current `5.5` version with an appropriate Migration Guide note.
