### ISSUE TITLE
Consider improving the content type handling in int-http:outbound-gateway

### ISSUE THREAD

**Issue by mauromol** [spring-projects/spring-integration#3483]
**Expected Behavior**

I place a Java bean on the message payload and invoke a remote service with `<int-http:outbound-gateway>`, leaving `extract-request-payload` to `true`. I know Spring Integration uses `RestTemplate` and I know I have Jackson on my classpath, so I expect it to use the Jackson message converter to convert my payload to a JSON request body, as a programmatic use of the `RestTemplate` would normally do.

**Current Behavior**

```
org.springframework.web.client.RestClientException: No HttpMessageConverter for my.java.Bean and content type "application/x-java-serialized-object"
```

**Context**

The problem lies in `org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.createHttpEntityFromPayload(Message<?>, HttpMethod)`, which does this:

- if the HTTP header `Content-Type` is set, it uses it
- otherwise tries to guess it by virtue of `org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.resolveContentType(Object)`, which, after testing for some relevant cases, falls back to setting `x-java-serialized-object` content type

This breaks the ability of `RestTemplate` to detect which converter to use more smartly, based on the class of the body: `org.springframework.http.converter.AbstractHttpMessageConverter.canWrite(MediaType)` by default returns `true` if the media type is `null` and `org.springframework.http.converter.AbstractHttpMessageConverter.canWrite(Class<?>, MediaType)` then returns `true` or `false` solely depending on the body class. Instead, with the content type set to `x-java-serialized-object`, `org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.canWrite(Class<?>, MediaType)` for instance will return `false` just because `x-java-serialized-object` is not among the list of supported content types.

The solution here is to add an upstream header enricher which sets the `Content-Type` header to `application/json`, but this is quite annoying and potentially verbose (since I have to add an endpoint and possibly an intermediate channel). If the above resolution of the content type (when unspecified) is indeed needed for some reason I am missing, an acceptable alternative could be to have a `contentType` attribute on the `<int-http:outbound-gateway>` tag, so that I can force the content type to use directly on the gateway, with no need for an extra endpoint.

**Comment by artembilan** [comment]
Thank you for reporting such a reasonable improvement, @mauromol !

See PR for the fix: https://github.com/spring-projects/spring-integration/pull/3485

**Comment by artembilan** [comment]
See also Migration Guide note: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-5.4-to-5.5-Migration-Guide#http-outbound-endpoint-and-content-type-header
