### ISSUE TITLE
Consider adding 'setSimpleContent' to 'ImapIdleChannelAdapterSpec'

### ISSUE THREAD

**Issue by imod** [spring-projects/spring-integration#3492]
**Expected Behavior**

I would like to have to possibility to set the flag for `simpleMessage` via spec adapter:

```
Mail.imapIdleAdapter(receiver)
	.autoStartup(true)
	.javaMailProperties(props)
	.shouldReconnectAutomatically(true)
	.simpleContent(true) <-- this is new
	...
```

**Current Behavior**

currently i have to create an external instance of the receiver and pass it to `Mail.imapIdleAdapter` ] 

```
ImapMailReceiver receiver = new ImapMailReceiver(recieverConfig.getUrl());
receiver.setJavaMailAuthenticator(new YootureGmailAuthenticator(recieverConfig.getUsername()));
receiver.setJavaMailProperties(mailProperties);
receiver.setSimpleContent(true); <-- this is the flag 
...

Mail.imapIdleAdapter(receiver)
			.autoStartup(true)
			.shouldReconnectAutomatically(true);
```

**Context**

adding the option to set `simpleContent` in the fluent spec builder, would simplify the code.

There is also a comment about this by @artembilan on https://jira.spring.io/browse/INT-4299?focusedCommentId=182887&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-182887

**Comment by imod** [comment]
@artembilan wow - 6 hours from request to implementation, thats awesome, many thanks!

**Comment by artembilan** [comment]
I could do that faster if I would wake earlier 😉 .

Plus I spend almost an hour reworking all the tests to JUnit 5.

Sorry, next time I will ask you to contribute the fix.
This one was my own fault to miss such an option to expose on the `ImapIdleChannelAdapterSpec` when we did that for the `MailInboundChannelAdapterSpec` during migration: https://jira.spring.io/browse/INT-4159.

Anyway, thank you for report! We still treat this as a contribution 😄
