### ISSUE TITLE
Make TcpConnectionInterceptorSupport.getConnectionId() final

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3520]
Overriding the connection id will cause routing problems because the connection id in inbound messages is from the core connection, not the interceptor.

**Comment by artembilan** [comment]
See comment on a proposed PR: https://github.com/spring-projects/spring-integration/pull/3536#issuecomment-814139629.

We definitely can not do any changes in the code to avoid the possible complexity, but probably we can mention something in the docs when deal with interceptors on the inbound side?..

**Comment by artembilan** [comment]
@garyrussell ,

Any further thoughts about this?
Do we close it as is? Fix right now in doc? Or move to GA milestone?

Thanks
