### ISSUE TITLE
MQTT v5

### ISSUE THREAD

**Issue by slavino** [spring-projects/spring-integration#3522]
https://github.com/spring-projects/spring-integration/blob/52511e4d84599a5b1a9a4710e585e4a6190d5171/build.gradle#L666

MQTTv5
Would it make sense either to have a choice of choosing proper package/artifact ?

```
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.mqttv5.client</artifactId>
            <version>1.2.5</version>
        </dependency>
```

**Comment by artembilan** [comment]
It's not just that simple change in the dep artifact name. There must be some implementation done.

This is a duplication of: https://github.com/spring-projects/spring-integration/issues/3432
