### ISSUE TITLE
TcpNetServerConnectionFactory race condition between open notification and reads

### ISSUE THREAD

**Issue by izushinskiy** [spring-projects/spring-integration#3523]
**In what version(s) of Spring Integration are you seeing this issue?**

This is present in `org.springframework.boot` `2.4.1` and `2.4.4` - which I think maps to  spring-integration `5.4.5`. 

**Describe the bug**

`TcpNetServerConnectionFactory` line number 185 to 187: A notification of a new connection is sent asynchronously to reads from the connection. This means that there are no guarantees that the user will be notified of the connection before receiving messages from the connection.

Specifically, this means that I can not create the necessary objects to handle connection reads before receiving reads from the connection. 

I don't know if the same is the case for close events (though this is not an issue for my application).

Interestingly, `TcpNioServerConnectionFactory` doesn't seem to have the same issue (though I haven't been able to follow its logic closely enough to be sure). 

**To Reproduce**

Write something like this:

```
connectionFactory = new TcpNetServerConnectionFactory(HARDCODED_TCP_PORT);

connectionFactory.registerListener((bar) -> System.out.println("READ"));
connectionFactory.setApplicationEventPublisher((foo) -> System.out.println(foo.getClass().getSimpleName()));
```

And then connect to the above server. Sometimes an open event will be printed first and sometimes "READ".

**Expected behavior**

I would expect the open event to be sent and handled first before any reads are done.

**Comment by garyrussell** [comment]
Interesting; the reason for this is the event is (currently) published on the server thread that is handling new connections.

The reason it's not a problem with NIO is because all NIO read events (selection keys) are processed (and dispatched to other threads) by the same thread that processes the accept, so it's impossible to process a readable selection key until after the open event has been published.
