### ISSUE TITLE
Fix minor SonarQube smells

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3549]
See Sonar report for the current `main`: https://sonar.spring.io/project/issues?id=org.springframework.integration%3Aspring-integration%3Amain&resolved=false&severities=MINOR&types=CODE_SMELL

Mostly those smells are about a `Magic Number` rule violation.

In some places we indeed need to extract a constant for such a default value, but in other places it really would be better just to place a `// NOSONAR` comment after the code line to ignore it from Sonar analysis.

**Comment by trungPa** [comment]
I'm going to make a pull request on this issue soon.

**Comment by trungPa** [comment]
although this is not really related to the issue at hand but doesn't TestingUtilities.waitStopListening() wait up for 20 seconds instead of 10 as stated in the docs?

**Comment by artembilan** [comment]
I think we just missed to look into those JavaDocs when we adjusted a default timeout.
Sometime with heavy loaded environment 10 seconds is not enough to verify.
So, if you fix that JavaDoc in your PR, it would be great.

Thank you for being so precise!

**Comment by trungPa** [comment]
Unfortunately I can't just fix the JavaDocs to state that it defaults to 20 seconds. The problem is that the method actually waits up to `delayArg * 2` milliseconds. To make it consistent with the other methods we have to revise several method calls so I think I will ignore this for now.

**Comment by artembilan** [comment]
> Unfortunately I can't just fix the JavaDocs to state that it defaults to 20 seconds. 

OK, @trungPa . Would you mind then to raise a separate special issue for this `TestingUtilities` inconsistency?
Thanks

**Comment by artembilan** [comment]
Nice job, @trungPa !

This is the current state of smells: https://sonar.spring.io/project/issues?id=org.springframework.integration%3Aspring-integration%3Amain&resolved=false&sinceLeakPeriod=false&types=CODE_SMELL.

I'm reopening this issue since we have got new smells as you see and looks like they became visible after fixing those.
So, this is a normal process, but let's aim to `0` issue on Sonar!

**Comment by trungPa** [comment]
@artembilan Since I've been working on this issue I think I will clean up the rest.
Can you give me some comments on the magic number smells? There are currently 6 of them that I'm wondering if we should use a constant variable or just add a `// NOSONAR`
As for the line count smell in `TestMailServer.doRun()` (L397), I see that the `// NOSONAR` was removed in 0dfbfa06. Was it a mistake or we are going to refactor `doRun()`?

**Comment by artembilan** [comment]
Sure! You can take any issue you want.

I find the `// NOSONAR` easier to do because it is hard find the name for every single magic number. And from math perspective it is really easier to read it inline, not as a constant.
Plus if that number does not make sense to expose as `public` one for external configuration, it really does not bring too much value to deal with constants.

Don't pay attention to `TestMailServer`. That one is fully deprecated in favor of Greenmail support and is going to be remove altogether in the next major version.
