### ISSUE TITLE
SftpInboundAdapter - RemoteDirectoryExpression is not evaluated on each poll

### ISSUE THREAD

**Issue by eazaretzky** [spring-projects/spring-integration#3554]
**In what version(s) of Spring Integration are you seeing this issue?**

5.3.2.RELEASE

**Describe the bug**

According to the documentation, it's possible to specify a `remote-directory-expression` to make the sftp inbound adapter dynamically poll from the result of the expression. 

> Starting with version 4.2, you can specify remote-directory-expression instead of remote-directory, letting you dynamically determine the directory on each poll — for example, remote-directory-expression="@myBean.determineRemoteDir()".

This is not working as discussed in this StackOverflow question: https://stackoverflow.com/questions/67218120/poll-different-remote-directories-using-sftpinboundadapter-and-remotedirectoryex

**To Reproduce**

Create an IntegrationFlow that uses a SftpInboundAdapter with a `remoteDirectoryExpression` like:

```
@Bean
public IntegrationFlow flow() {
    return IntegrationFlows.from(
            Sftp.inboundAdapter(sftpSessionFactory())
                    .preserveTimestamp(true)
                    .localDirectory(new File("sftp-inbound"))
                    .deleteRemoteFiles(true)
                    .autoCreateLocalDirectory(true)
                    .remoteDirectoryExpression(
                            EXPRESSION_PARSER.parseExpression("@directoryProvider.getDirectory()"))
                    .filter(getFilter())
            , e -> e.id("sftpInboundAdapter")
                    .autoStartup(true)
                    .poller(Pollers.fixedDelay(5, TimeUnit.SECONDS)))
            .log()
            .channel("processing")
            .get();
}
``` 

The bean `DirectoryProvider` returns a different folder (in round-robin) on each call

**Expected behavior**

On each poll, the remoteDirectoryExpression should be evaluated

**Comment by artembilan** [comment]
The regression happens after this fix: https://github.com/spring-projects/spring-integration/commit/26cfab579c7ad98e516e396a92a0e7d04a9f9110.

Will revise what we have so far and cover with the tests.

**Comment by garyrussell** [comment]
It was actually broken by this https://github.com/spring-projects/spring-integration/commit/2b0598291c382ea747bf44930fb0d74811ffde1a#diff-5cf48e4a44621b0db6054c8a9e16984162574bc33cff1ef69e5f968d143c2dc3 years earlier.

It's not clear why the expression evaluation was removed there.

**Comment by garyrussell** [comment]
Sorry; you were right; it was just moved there.
