### ISSUE TITLE
Minor refactoring to make TestingUtilities.waitStopListening() consistent with the JavaDocs

### ISSUE THREAD

**Issue by trungPa** [spring-projects/spring-integration#3598]
As mentioned in #3549, `TestingUtilities.waitStopListening(serverConnectionFactory, delayArg)` actually waits for `delayArg * 2` milliseconds which is inconsistent with the JavaDocs. I think we should revise this method and increase `delayArg` when calling it.
For instance `TestingUtilities.waitStopListening(server1, 10000L)` to `TestingUtilities.waitStopListening(server1, 20000L)`

**Comment by artembilan** [comment]
I think we need to change that `if (n++ > 200) {` to the `if (n++ > 100) {` as it was before.
We can change the consumer of this API as you suggest for 20 seconds eventually if we really face a timing problem.
This way we are going to be consistent with API and JavaDocs for them.
