### ISSUE TITLE
Kafka MessageHandler Does Not Synchronize with a non-Kafka TM for Producer-Only Transactions

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3600]
`TransactionSynchronizationManager.getResource()` returns `null` when there is an existing synchronizing transaction, so we run in a local transaction.

https://stackoverflow.com/questions/68460690/wrapping-streambridge-send-and-jpa-save-inside-a-transaction/68461298#68461298

**Comment by artembilan** [comment]
Looks like we just can call `this.kafkaTemplate.inTransaction()` instead of something local artificial...
