### ISSUE TITLE
AMQP Error: NoSuchMethodError thrown when used with SpringCloud Stream rabbit binder

### ISSUE THREAD

**Issue by gm2552** [spring-projects/spring-integration#3603]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.2 (as part of SpringBoot 2.5.3)

**A clear and concise description of what the bug is.**

When utilizing the rabbit MQ spring cloud streams binder in Spring Cloud 2020.0.3 along with Spring Integration 5.5.2 (as part of SpringBoot 2.5.3), a NoSuchMethodError is thrown at application startup.

**Steps to reproduce the behavior.**

The following GitHub project is a simple Spring Cloud Streams application that reproduced the problem.  Simply run the application in an IDE or use the maven spring boot plugin by running 'mvn spring-boot:run'.  This test application does not require a RabbitMq instance be present as the error is thrown before a connection is attempted.

This application has been tested on multiple machines each resulting in the error.

https://github.com/gm2552/streams-boot253-rabbit-test

**A clear and concise description of what you expected to happen.**

Expecting the application to successfully connect to a configured RabbitMQ instance (depending on configuration).  The sample application above runs successfully using SpringBoot 2.5.2 and the appropriate Spring Integration dependencies.

**Comment by artembilan** [comment]
Duplicates this one: https://github.com/spring-projects/spring-integration/issues/3601.

Sorry for inconvenience.

The Spring Cloud 2020.0.3 was not mean to be upgraded to Spring Boot 2.5.3. Not sure how that happened on your side, but better to stick with whatever Spring Cloud brings for you or downgrade just Spring Integration version as I suggest in the mentioned issue.

Thanks for understanding!
