### ISSUE TITLE
Mail Receiver fetch redundant Messages 

### ISSUE THREAD

**Issue by wangYX657211334** [spring-projects/spring-integration#3619]
**Version**
`org.springframework.integration:spring-integration-mail:5.5.3`

**Describe the bug**

example:
``` java
Pop3MailReceiver mailReceiver = ...;
mailReceiver.setMaxFetchSize(10);
Object[] messages = mailReceiver.receive();
```
The above code execute result `messages.length` is 10, it is right
but,  in the `org.springframework.integration.mail.AbstractMailReceiver.searchAndFilterMessages` method,  fetch all messages, Cause performance problems
`spring-integration-mail` source code:
``` java
private MimeMessage[] searchAndFilterMessages() throws MessagingException {
    this.logger.debug(() -> "attempting to receive mail from folder [" + this.folder.getFullName() + "]");
    Message[] messagesToProcess;
    Message[] messages = searchForNewMessages();
    if (this.maxFetchSize > 0 && messages.length > this.maxFetchSize) {
        Message[] reducedMessages = new Message[this.maxFetchSize];
        System.arraycopy(messages, 0, reducedMessages, 0, this.maxFetchSize);
        messagesToProcess = reducedMessages;
    }
    else {
        messagesToProcess = messages;
    }
    this.logger.debug(() -> "found " + messagesToProcess.length + " new messages");
    if (messagesToProcess.length > 0) {
        fetchMessages(messages);
    }

    this.logger.debug(() -> "Received " + messagesToProcess.length + " messages");

    MimeMessage[] filteredMessages = filterMessagesThruSelector(messagesToProcess);

    postProcessFilteredMessages(filteredMessages);
    return filteredMessages;
}
```
[commit link](https://github.com/spring-projects/spring-integration/commit/c7ff99a4e8232c34f84ebefd5845676ab3ef5324#diff-de4001fbf6502d7d9069aee66e68de592c340d1a7814f34260acb9c794b37538)
`fetchMessages(messages);` changed to `fetchMessages(messagesToProcess);` ?

**Comment by artembilan** [comment]
Yes, indeed simple copy/paste bug.

Any chances that you can fix via contribution: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc ?

**Comment by wangYX657211334** [comment]
great pleasure join contribution.
