### ISSUE TITLE
Move `IntegrationFlows` factory content into the `IntegrationFlow` interface with the same reason and deprecate it

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3623]
**Expected Behavior**

Since `IntegrationFlow` is an `interface` nothing stops us to have `static` methods in it.
The better end-user experience would be just to have imported an `IntegrationFlow` interface and go with fluent API from there an our `@Bean` definitions.

**Current Behavior**

We have to know about an `IntegrationFlows` factory and don't forget to import it into our code.

**Context**

It is a little burden do not forget to import an `IntegrationFlows` factory to get access to `from(...)` API.
Better to let to end-users to deal only with an `IntegrationFlow` interface as return type on a `@Bean` definition, as well as in the bean definition code.
Similar API exposure exits in the `WebClient` from WebFlux.

**Comment by oxcafedead** [comment]
Can't we just remove `IntegrationFlows` class if this is targeted for 6.0 - a major version which should allow a bit of breaking changes?

**Comment by artembilan** [comment]
Well, it would be less drastic for end-users to migrate their projects to a new API.
A deprecated class won't harm, but removal would be a bomb for all the projects which need to upgrade.
We can consider to remove it in the next `6.1` version.
