### ISSUE TITLE
TraceId spreading between containers thread pools

### ISSUE THREAD

**Issue by CyberpunkPerson** [spring-projects/spring-integration#3649]
Hi Spring Team!

I faced with an issue that during consuming of few messages in parallel with load by threads from different threadPools (carContainer-C-1 & aircraftContainer-C-1) thraceId could be the same. This problem is critical for tracking. 

I tried the following to fix it, but still have the issue:
 
1. Addition of interceptor with `MDC.clear()` at the end of the handle flow before outbound adapter.
2. Addition Task Decorator   
```
SimpleAsyncTaskExecutor executor = new SimpleAsyncTaskExecutor();
        executor.setThreadNamePrefix("aircraftContainer");
        executor.setTaskDecorator(runnable -> {
            return new Runnable() {
                @Override
                public void run() {
                    try {
                        runnable.run();
                    } finally {
                        MDC.clear();
                    }
                }
            };
        });

 ContainerProperties properties = new ContainerProperties("topic-name");
 properties.setConsumerTaskExecutor(executor);
```

Sleuth config:
```
  sleuth:
    trace-id128: true
    sampler:
      probability: 0.1
    messaging:
      kafka:
        enabled: true
    integration:
      enabled: true
    async:
      enabled: false
```
Kafka as message broker
Spring Integration 5.5.2

Perhaps I'm digging in a wrong way. Would be great to read your thoughts.
Thanks in advance.

Best regards,
Andrew

**Comment by CyberpunkPerson** [comment]
Hi Spring Team!
Here is a [Tracing](https://github.com/CyberpunkPerson/Tracing)  - sandbox project.

**Comment by artembilan** [comment]
Hi @CyberpunkPerson !

Thank you for the sample, but unfortunately it is very complicated and it is hard to digest it with all the complex business logic you have included.
I believe Lombok and Protobuf are really overkill over here.

I guess your main concern here that different threads for Kafka consumer produces the same `traceId`.
We over here, on Spring Integration side does not do any tracing instrumentation, therefore better to move the question to Spring Cloud Sleuth.
But I understand your prospective as well: it doesn't matter who from Spring team would help you to figure out what is going on and how to fix.
So, I'll chat to Spring Cloud Sleuth for some insights.

If you could confirm that very simple Spring Cloud application just with Spring Kafka and Spring Cloud Sleuth (no Lombok, no Protobuf, no Spring Integration, no Docker) leads to the same outcome, I'd be glad to carry on from there.

Thanks

**Comment by artembilan** [comment]
Please, enable `DEBUG` for the `org.springframework.cloud.sleuth` category and show us logs around those listener container consumptions.
We wonder if there is the `traceId` set before consumption or so.

Thanks

**Comment by CyberpunkPerson** [comment]
Hi, sorry for delay, have pretty intense right now. Log output file [here](https://github.com/CyberpunkPerson/Tracing/blob/develop/tracing-output.txt).

**Comment by CyberpunkPerson** [comment]
Simple Kafka consumer app on it's way.

**Comment by artembilan** [comment]
The log is too huge.
Would you mind to point us to the place where those Marvel and DC containers use the same trace?
So far I don't see a collision.

Thank you!

**Comment by CyberpunkPerson** [comment]
You can just make a search for traceId = `619222340a57214162f8ec5e63cedeeb`. It appears in dcContainer-C-1 and spreading on marvelContainer-C-1. At the middle of the log it would be the same for both till the end.

Thank you for your assist.

**Comment by artembilan** [comment]
I found this part of those logs:
```
2021-11-15 12:02:44.859 [marvelContainer-C-1] DEBUG [traceId=6192223410707a071f7ef6da551f3959, spanId=cd7b1baea2743cc6] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Received a message in pre-send GenericMessage [payload=id: "\355j}j\252\271L\211\230\362\314g\222\360P\352"
news {
  id: "\017\332Z$\335iN\230\267\034E\023\030\265\316\320"
  hero_id: "\350M\315tj\353I\232\245f\207\220U\350\323\261"
  hero_name: "Does not really matter"
  description: "Does not really matter either"
}
, headers={b3=[B@9dda4b9, kafka_offset=53577, kafka_consumer=brave.kafka.clients.TracingConsumer@3307cb18, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, kafka_receivedMessageKey=e84dcd74-6aeb-499a-a566-879055e8d3b1, sourceData=ConsumerRecord(topic = marvel-news, partition = 0, leaderEpoch = 0, offset = 53577, CreateTime = 1636966964725, serialized key size = 36, serialized value size = 111, headers = RecordHeaders(headers = [RecordHeader(key = b3, value = [54, 49, 57, 50, 50, 50, 51, 52, 48, 97, 53, 55, 50, 49, 52, 49, 54, 50, 102, 56, 101, 99, 53, 101, 54, 51, 99, 101, 100, 101, 101, 98, 45, 55, 49, 55, 48, 49, 50, 97, 54, 50, 56, 51, 53, 99, 50, 52, 102, 45, 48])], isReadOnly = false), key = e84dcd74-6aeb-499a-a566-879055e8d3b1, value = [B@a9ff21b), kafka_receivedTopic=marvel-news, kafka_receivedTimestamp=1636966964725, kafka_groupId=tracing.99758840-9990-4652-bc67-6e0c1f7f9e00}]
2021-11-15 12:02:44.859 [dcContainer-C-1] DEBUG [spanId=ab08e6f3caede51e, traceId=6192223410707a071f7ef6da551f3959] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Created a new span in pre send NoopSpan(6192223410707a071f7ef6da551f3959/ab08e6f3caede51e)
2021-11-15 12:02:44.859 [marvelContainer-C-1] DEBUG [traceId=6192223410707a071f7ef6da551f3959, spanId=cd7b1baea2743cc6] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Extracted result from headers NoopSpan(619222340a57214162f8ec5e63cedeeb/4a912231d5f21637)
2021-11-15 12:02:44.859 [marvelContainer-C-1] DEBUG [traceId=619222340a57214162f8ec5e63cedeeb, spanId=4a912231d5f21637] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Put span in scope NoopSpan(619222340a57214162f8ec5e63cedeeb/4a912231d5f21637)
2021-11-15 12:02:44.859 [marvelContainer-C-1] DEBUG [traceId=619222340a57214162f8ec5e63cedeeb, spanId=4a912231d5f21637] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Created a new span in pre send NoopSpan(619222340a57214162f8ec5e63cedeeb/4a912231d5f21637)
```
So, the `marvelContainer` had one trace `6192223410707a071f7ef6da551f3959` and that it switches to the `619222340a57214162f8ec5e63cedeeb` and store it into its `ThreadLocal` for subsequent calls.

Probably that `b3=[B@9dda4b9` Kafka header container such an info which is the same for records sent to both DC and Marvel topics...

**Comment by CyberpunkPerson** [comment]
Hi @artembilan 
I'm using this [Spammer](https://github.com/CyberpunkPerson/Tracing/tree/master/tracing-spammer) to send messages and there is no any header config (as you may see [here](https://github.com/CyberpunkPerson/Tracing/blob/master/tracing-spammer/src/main/java/com/github/cyberpunkperson/tracing/spammer/Spammer.java)).

Moreover I made simple kafka application [here](https://github.com/CyberpunkPerson/kafka-tracing) as you asked above and used the same [Spammer](https://github.com/CyberpunkPerson/Tracing/tree/master/tracing-spammer) and traceId has been unique. 

Perhaps it's simply wrong Spring Integration in my app, could you please have a look at [Kafka Config](https://github.com/CyberpunkPerson/Tracing/blob/master/tracing-handler/src/main/java/com/github/cyberpunkperson/tracing/handler/domain/source/dc/configuration/DcKafkaConfiguration.java) and [Flow Config](https://github.com/CyberpunkPerson/Tracing/blob/master/tracing-handler/src/main/java/com/github/cyberpunkperson/tracing/handler/domain/source/dc/configuration/DcConfiguration.java), just in case?

Thank you for your assist.

**Comment by artembilan** [comment]
I see only this as wrong point:
```
    ConsumerFactory<String, byte[]> marvelConsumerFactory() {
        KafkaProperties properties = dcKafkaProperties();
```
So, looks like you reuse the same DC properties to configure Marvel factory.

How that suppose to work at all?

**Comment by CyberpunkPerson** [comment]
In this particular case it's change nothing, because both of them lead only on kafka cluster url.

**Comment by artembilan** [comment]
Thank you for your patience!

I have reproduced an issue:
```
2021-11-23 14:03:37.142 [marvelContainer-0-C-1] DEBUG [spanId=9665c59f4e72ba3c] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Extracted result from headers NoopSpan(619d3aa0dd73150d92c373d8a2a08410/2e4739c394cb1e19)
2021-11-23 14:03:37.142 [dcContainer-0-C-1] DEBUG [spanId=4f3178c09175dcf9, traceId=619d3aa04cd202272b173c1eb36b1666] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Extracted result from headers NoopSpan(619d3aa0dd73150d92c373d8a2a08410/2a3106320808575b)
2021-11-23 14:03:37.142 [dcContainer-0-C-1] DEBUG [spanId=2a3106320808575b, traceId=619d3aa0dd73150d92c373d8a2a08410] org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor Put span in scope NoopSpan(619d3aa0dd73150d92c373d8a2a08410/2a3106320808575b)
```
So, at some point, under concurrency, the message from DC container is enhanced with the traceId header from a message from the Marvel container.

The `TracingChannelInterceptor` is a singleton for the whole application and it has that shared `ThreadLocalSpan`, which for me feels like have a flaw with its: `final LinkedBlockingDeque<SpanAndScope> spans = new LinkedBlockingDeque<>();` in the:
```
void remove() {
		this.threadLocalSpan.remove();
		if (this.spans.isEmpty()) {
			return;
		}
		try {
			SpanAndScope span = this.spans.removeFirst();
			if (log.isDebugEnabled()) {
				log.debug("Took span [" + span + "] from thread local");
			}
			this.threadLocalSpan.set(span);
		}
		catch (NoSuchElementException ex) {
			if (log.isTraceEnabled()) {
				log.trace("Failed to remove a span from the queue", ex);
			}
		}
	}
```
We remove the current thread local state, but at the same time we populate it with the value from that queue. And this one might exactly be not closed from the previous interaction with this channel interceptor in the other thread.

WDYT?

**Comment by artembilan** [comment]
This this discussion: https://github.com/spring-projects/spring-integration/discussions/3682. It raises similar problem, but with much simple sample.

**Comment by CyberpunkPerson** [comment]
At first not totally clear what is a purpose of the `final LinkedBlockingDeque<SpanAndScope> spans = new LinkedBlockingDeque<>()` - it seems to be a stack of  calls, if so why it's not in ThreadLocal?

Also we found similar approach in Zipkin [ThreadLocalSpan.getCurrentSpanInScopeStack()](https://github.com/openzipkin/brave/blob/5be287b91c3d18da9fc7a597d71b12b27be6043c/brave/src/main/java/brave/propagation/ThreadLocalSpan.java#L174). Not sure why it was done this way in `TracingChannelInterceptor ` , but looks like some sort of optimization and something went wrong.

**Comment by artembilan** [comment]
That's my thought, too. 
Let's move the issue to  https://github.com/spring-cloud/spring-cloud-sleuth/issues!
Does look like Spring Integration is involved somehow in the problem

**Comment by gigermocas** [comment]
Just an observation,

`TracingChannelInterceptor` extends `ExecutorChannelInterceptor`, and from its documentation:
`Supported on {@link org.springframework.messaging.MessageChannel} implementations that can be configured with an {@code Executor}.`

And we are seeing it intercepting `DirectMessage` message channels.

In my specific case, that was the workaround that I ended up implementing, but it's not a "fix" for all circumstances.

**Comment by artembilan** [comment]
See further in the hierarchy:
```
public interface ExecutorChannelInterceptor extends ChannelInterceptor {
```
So, an implementation of the `ExecutorChannelInterceptor` can really be used for those `DirectChannel`.

I think the problem is really with the proper concurrency handling around that shared `spans` queue.
It must be placed as a stack into a current `ThreadLocal`, nothing more.

**Comment by CyberpunkPerson** [comment]
Artem thanks for your help!
Move the issue [here](https://github.com/spring-cloud/spring-cloud-sleuth/issues/2064)

Best regards,
Andrew
