### ISSUE TITLE
Clean up RedisLockRegistry cache automatically 

### ISSUE THREAD

**Issue by Meteorkor** [spring-projects/spring-integration#3655]
**In what version(s) of Spring Integration are you seeing this issue?**
spring-integration-redis:5.3.3.RELEASE and more?

**Describe the bug**
I'm trying to use RedisLockRegistry as a Singleton.
```
val lock = redisLockRegistry.obtain("key");
try{
  if(lock.tryLock()){
      //business logic
  }
}finally{
  lock.unlock()
}

```
There seems to be a memoryLeak in the service, so I checked
`RedisLockRegistry.locks` was cumulatively occurring.

[obtain](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java#L156)
put into `RedisLockRegistry.locks`

when i check the code
I didn't see the part where 
[expireUnusedOlderThan()](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java#L163)
was called.

Do I have to call it manually?
but, expireUnusedOlderThan() will search the entire stored lock.
I thought there was a way to remove it from my LockRegistry in the lock.unlock() step, but I couldn't find it.

Or should I not use it by declaring it as a bean?(or use prototype?)

**To Reproduce**
Declare RedisLockRegistry as bean and call obtain().

**Expected behavior**
no memory leak
or
How to properly use RedisLockRegistry

**Comment by Meteorkor** [comment]
@artembilan 

I changed this,
Can I post it as a PR?

>I had a thought to do a change to the LinkedHashMap.removeEldestEntry(Map.Entry<K,V> eldest) implementation to remove entries automatically when cache overflow happens.

https://github.com/spring-projects/spring-integration/commit/ed7edd6cfb3971cee727fde7a5a65229c0f76f18

**Comment by artembilan** [comment]
Yes, you can open a PR: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc.

But why ` LinkedHashMap.removeEldestEntry()` doesn't work for us? What is the reason behind that complex logic with queue and lock?

Thanks

**Comment by Meteorkor** [comment]
>But why LinkedHashMap.removeEldestEntry() doesn't work for us?


If I use ` LinkedHashMap.removeEldestEntry() `, i think i will use `Collections.synchronizedMap()` together

If I use `Collections.synchronizedMap()`, it will operate as one lock for all accesses(cache get), so I maintain a `ConcurrentHashMap` to use a distributed lock and hold the entire lock only when necessary(write and remove).
