### ISSUE TITLE
Support Google Cloud Storage Based Distributed Lock

### ISSUE THREAD

**Issue by fireboy-will** [spring-projects/spring-integration#3668]
Google Cloud Storage (GCS) offers [strong consistency](https://cloud.google.com/storage/docs/consistency) for its operations, which could be used as the base for the atomic Compare And Set computation of a distributed lock.

One can only obtain the lock by successfully creating an object in a GCS bucket provided the object does not exist at the time of creation.  Therefore, when multiple processes try to obtain the lock, one and only one of them would succeed.

Once obtained, the owning process would proceed with its critical section that is meant to be executed once, and subsequently deletes the GCS object as the unlock operation once the critical section is completed.

To coordinate the competing claim on the lock, the owning process should renew the lifetime of the lock periodically to accommodate its potentially long critical section.  At the meantime, other competing processes would check if the lock has expired and delete the GCS object left by the owning process in case the owning process can't renew its own lock for any reason, such as loss of network connection, crash of its process, blocked computation, and etc.

Spring Integration currently offers several LockRegistry implementations.  Many of them are based on the availability of a separate non-trivial central system, such as relational DB (JdbcLockRegistry), Redis (RedisLockRegistry), and Zookeeper (ZookeeperLockRegistry).  GcsLockRegistry based on the afore-mentioned GcsLock would a complement, which requires only a simple, convenient, reliable, and readily available coordinating system.

**Comment by artembilan** [comment]
This is better to be implement in the [Spring Cloud GCP](https://github.com/GoogleCloudPlatform/spring-cloud-gcp) project which has respective dependency on Spring Integration, but not vise-versa.

Closing this one with the hope that you'll open respective issue over there.

Feel free to cross-link back to here.

Thank you!
