### ISSUE TITLE
native STOMP headers removed by WebSocketInboundChannelAdapter

### ISSUE THREAD

**Issue by freynder** [spring-projects/spring-integration#3675]
Hi,

I use the WebSocket Inbound Channel Adapter with the StompSubProtocolHandler for inbound STOMP over websocket. Our client application sets a few STOMP headers that we need to read in the backend. However, these headers are explicitely removed in WebSocketInboundChannelAdapter, please see below:
https://github.com/spring-projects/spring-integration/blob/f5f1c82082dadd4ca9408b3e29e195a83e784ccc/spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java#L359

Is there any reason to do so? When comparing to HTTP for example, those headers are mapped and still accessible in the resulting Message.

Thank you,

**Comment by artembilan** [comment]
I cannot recall at the moment why did we remove that header, but would you mind to share more context how those custom headers can appear in the `nativeHeaders` entry?
What do you send on the client side?
I see this in my tests:
```
headers = {MessageHeaderAccessor$MutableMessageHeaders@8484}  size = 9
 "simpMessageType" -> {SimpMessageType@8498} "MESSAGE"
 "stompCommand" -> {StompCommand@8500} "MESSAGE"
 "nativeHeaders" -> {LinkedMultiValueMap@8502}  size = 5
  key = "nativeHeaders"
  value = {LinkedMultiValueMap@8502}  size = 5
   "destination" -> {ArrayList@8525}  size = 1
   "content-type" -> {ArrayList@8527}  size = 1
   "subscription" -> {ArrayList@8529}  size = 1
   "message-id" -> {ArrayList@8531}  size = 1
   "content-length" -> {ArrayList@8533}  size = 1
 "simpSessionAttributes" -> {ConcurrentHashMap@8504}  size = 0
 "simpHeartbeat" -> {long[2]@8506} [0, 0]
 "simpSubscriptionId" -> "subs1"
 "contentType" -> {MimeType@8510} "application/json"
 "simpSessionId" -> "e2b9fd630bcd4a5cbad5d991ba46ac1d"
 "simpDestination" -> "/topic/foo"
```
So, most of those `nativeHeaders` are remapped to the top-level header entries with that `simp` prefix.

I probly won't mind to restore such a header, if you really confirm that plain `@MessageMapping` with regular Spring Websocket support gives you an access to this one.

Thank you!

**Comment by freynder** [comment]
Hi,

Thank you for the quick response. 

The STOMP header provided by the client is specific to the application.

I can confirm it can be retrieved through `@MessageMapping` as I'm migrating this code to spring integration. Extract:
```
    @MessageMapping("/inbound.send")
    public ServerMessage receive(@Payload ClientMessage message, Message<ClientMessage> m,
            SimpMessageHeaderAccessor headers) throws Exception {
        String sessionId = headers.getNativeHeader(APP_SPECIFIC_SESSION_ID).get(0);
```

Thank you

**Comment by artembilan** [comment]
OK. Got it. Restoring then `SimpMessageHeaderAccessor.NATIVE_HEADERS` header entry in the message the `WebSocketInboundChannelAdapter` is producing...

**Comment by freynder** [comment]
Really impressed with the quick resolution, thank you very much.
