### ISSUE TITLE
UrlConnection timeout required for FeedEntryMessageSource

### ISSUE THREAD

**Issue by pinkeshsagar-harptec** [spring-projects/spring-integration#3677]
**Expected Behavior**

FeedEntryMessageSource should timeout the connection when server is unresponsive for desired amount of time

**Current Behavior**

FeedEntryMessageSource holds the connection infinitely which is blocking other threads.

Here is stackoverflow url: https://stackoverflow.com/questions/69822045/threads-are-being-blocked-while-receiving-data-from-rss-feed-adapter?noredirect=1#comment123697506_69822045

**Comment by artembilan** [comment]
It looks like the best way is to expose an `UrlConnection` as a `FeedEntryMessageSource` configuration variant.

See the linked SO thread for a workaround.

Will fix this soon.

**Comment by garyrussell** [comment]
Actually, I don't think we can do that - the `UrlConnection` would be opened too soon.

Maybe a `Supplier<UrlConnection>` ?

**Comment by garyrussell** [comment]
Right; but the reader is created at runtime in `getFeed()` whenever the fetch list is empty - I don't think we can reuse the same connection each time.

**Comment by garyrussell** [comment]
That said, given that the `UrlResource` allows customization (as you described on GitHub), do we really need this change at all?

**Comment by pinkeshsagar-harptec** [comment]
So does this mean it will be a sequential execution for multiple threads accessing different urls?

**Comment by artembilan** [comment]
I’m not sure why make such an assumption, but it probably deserves its own SO thread with much more info
