### ISSUE TITLE
PublisherAnnotationBeanPostProcessor has dependency on itself, breaks when using Spring Boot

### ISSUE THREAD

**Issue by kewne** [spring-projects/spring-integration#3694]
If I declare the following configuration class in a Spring Boot application:
```java
@Configuration
@EnablePublisher
public class IntegrationConfiguration
```
the application fails to start because the instantiated `PublisherAnnotationBeanPostProcessor` [requests itself as a bean](https://github.com/spring-projects/spring-integration/blob/db14faddd1ce4d62657d262359d2483b2979eab1/spring-integration-core/src/main/java/org/springframework/integration/aop/PublisherAnnotationBeanPostProcessor.java#L79).

By default, Spring Boot disallows this unless you set `spring.main.allow-circular-references: true`, which IMO you shouldn't do without a good reason.

# Expected behavior

No circular dependency error should be raised.

`PublisherAnnotationBeanPostProcessor` could still check for a duplicate with an explicit bean request;
perhaps just checking whether a definition exists would be enough.

**Comment by artembilan** [comment]
Confirmed:

```
2021-12-14 10:18:17.182 ERROR 3896 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  org.springframework.integration.internalPublisherAnnotationBeanPostProcessor
└──<-──┘

```

**Comment by kewne** [comment]
Just wanted to leave a (late) note of appreciation for taking the time to fix this, thank you very much 🙇
