### ISSUE TITLE
Incomplete shutdown of Mqttv5PahoMessageDrivenChannelAdapter

### ISSUE THREAD

**Issue by mrpiggi** [spring-projects/spring-integration#3697]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.6

**Describe the bug**

Calling `Mqttv5PahoMessageDrivenChannelAdapter.doStop()` does not disconnect and close the underlying `IMqttAsyncClient`
https://github.com/spring-projects/spring-integration/blob/30bb8467b44e2445e6bcb0f3c1fc39afd5f4ed84/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/Mqttv5PahoMessageDrivenChannelAdapter.java#L187-L200

**Expected behavior**

I am not sure if the current behavior is intended or a bug. At least, calling `MqttPahoMessageDrivenChannelAdapter.doStop()` does exactly that
https://github.com/spring-projects/spring-integration/blob/30bb8467b44e2445e6bcb0f3c1fc39afd5f4ed84/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java#L202-L216

If the current behavior is as desired, what do I need to do to disconnect and close the underlying `IMqttAsyncClient`?

**Comment by artembilan** [comment]
I think we are missing `this.mqttClient.disconnect().waitForCompletion(getDisconnectCompletionTimeout());` alongside with that `unsubscribe()`.
The `client.close()` has to be done in the `destroy()` implementation, which we also are missing at the moment.

Thank you! Will fix shortly.
