### ISSUE TITLE
javadoc double dots

### ISSUE THREAD

**Issue by i7paradise** [spring-projects/spring-integration#3699]
https://github.com/spring-projects/spring-integration/blob/30622b285c5e83fc10f437f0680abfc0cdace45a/spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlow.java#L50

`MessageChannels..queue` -> `MessageChannels.queue`

**Comment by artembilan** [comment]
Fixed.
Thank you!
Looking forward for more feedback!
