### ISSUE TITLE
RedisLockRegistry unlock() is not releasing the Redis lock in High Available Cluster (multiple master-slave)

### ISSUE THREAD

**Issue by davinders88** [spring-projects/spring-integration#3727]
I am using SpringBoot **RedisLockRegistry** with following versions.
id 'org.springframework.boot' version '2.3.7.RELEASE'
implementation 'org.springframework.data:spring-data-redis:2.3.7.RELEASE'
implementation 'redis.clients:jedis:3.2.0'

**Description:**
I am using **RedisLockRegistry** to implement distributed locks. It was all working perfectly in one master Redis  cluster **but failed in multiple master-slave Redis cluster**. When I am calling the the lock.unlock() it's not giving any exception, I think it has released the JVM lock but not the Redis lock. As I have set the expiry 60 seconds, Subsequent RedisLockRegistry.obtain("lockkey"), made from another instance of application, does not work for 60 seconds (blocks for 60 seconds) as explained in code flow. 

As same code is working in lower environment (single master node) but not in production (multiple master-slave nodes cluster),  I am raising this issue. Please help.
One more difference between lower env. and prod is that, in prod, we have multiple instances of application. And this issue happens only if subsequent lock call is made from another instance of application.

**Code Flow:**
Service/Application **instance 1**:
RedisLockRegistry.obtain("devgosain1_test@gmail.com").lock();  //works
lock.unlock(); // No Exception, it should have unlocked JVM and REDIS lock, but as per my analysis it did not release the Redis lock.

Service/Application **instance 2**:
RedisLockRegistry.obtain("devgosain1_test@gmail.com").lock(); // Subsequent lock call, made from another instance 2, fails for 60 seconds.

Service/Application **instance 1**:
RedisLockRegistry.obtain("devgosain1_test@gmail.com").lock(); // Works, if subsequent lock call made from the same instance 1.

After 60 seconds: **instance 2**
RedisLockRegistry.obtain("devgosain1_test@gmail.com").lock(); // Gets the lock.

**Expected behavior:**  lock.unlock(); must release Redis lock form Redis cluster.

Could it be possible that lock gets removed from master but not from slaves? Not sure.
Seems like why subsequent lock call is working in same instance because lockClientId is same and its not trying to get the lock object again instead just setting the the expiry.

**RedisLockRegistry OBTAIN_LOCK_SCRIPT**
```
private static final String OBTAIN_LOCK_SCRIPT =
			"local lockClientId = redis.call('GET', KEYS[1])\n" +
					"if lockClientId == ARGV[1] then\n" +
					"  redis.call('PEXPIRE', KEYS[1], ARGV[2])\n" +
					"  return true\n" +
					"elseif not lockClientId then\n" +
					"  redis.call('SET', KEYS[1], ARGV[1], 'PX', ARGV[2])\n" +
					"  return true\n" +
					"end\n" +
					"return false";
```

**SpringBoot Redis Configurations**

```
@Bean
	public RedisConnectionFactory jedisConnectionFactory(JedisClientConfiguration jedisClientConfiguration) {
		RedisClusterConfiguration redisConfig = new RedisClusterConfiguration();
		List<RedisNode> nodes = new ArrayList<RedisNode>();
		RedisNode node = new RedisNode(redisHost, port);
		nodes.add(node);
		redisConfig.setClusterNodes(nodes);
		redisConfig.setPassword(password);
	    JedisConnectionFactory jedisConFactory = new JedisConnectionFactory(redisConfig, jedisClientConfiguration);
	    return jedisConFactory;
	}
	
	@Bean
    public RedisTemplate<String, String> redisTemplate(RedisConnectionFactory factory) {
        RedisTemplate<String, String> template = new RedisTemplate<>();
        template.setConnectionFactory(factory);
        template.setEnableTransactionSupport(true);
        template.afterPropertiesSet();
        return template;
    }
	
	@Bean 
	public JedisClientConfiguration getJedisClientConfiguration() { 
		JedisClientConfiguration.JedisClientConfigurationBuilder builder = (JedisClientConfiguration.JedisClientConfigurationBuilder) JedisClientConfiguration.builder(); 
		GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig(); 
		genericObjectPoolConfig.setMaxTotal(maxActive); 
		genericObjectPoolConfig.setMaxIdle(maxIdle);
		genericObjectPoolConfig.setMinIdle(minIdle); 
		genericObjectPoolConfig.setTestWhileIdle(true);
		
		Duration connectTimeoutDuration = Duration.ofMillis(connectTimeout);
		Duration readTimeDuration = Duration.ofMillis(readTimeout);
		return builder.connectTimeout(connectTimeoutDuration).readTimeout(readTimeDuration).usePooling().poolConfig(genericObjectPoolConfig).and().useSsl().build(); 
	} 
	
	@Bean
    public RedisLockRegistry redisLockRegistry(RedisConnectionFactory redisConnectionFactory) {
        return new RedisLockRegistry(redisConnectionFactory, registryKey, 60_000);
    }

```

**Comment by davinders88** [comment]
I have fixed the issue by updating the spring-integration-redis version to 5.5.8. But not exactly sure what was the issue in 5.3.4.RELEASE.
In new Jar, new command **PUBLISH** was called after **UNLINK** and **DEL** command in RedisLockRegistry class. Seems like to sync the unlock changes to whole Redis Cluster.
Is it the lock was not getting released from slave nodes.? Or getting removed from one salve but not from others.? Or the lock was not getting removed at all?

**Comment by artembilan** [comment]
OK. So, your problem was visible only when you use a cluster for Redis itself.
Apparently we just haven't tested this distributed lock implementation with Redis cluster.
So, if you say the solution works, then it is indeed recommended to use the latest Spring Integration which has the fix with the `PUBLISH` solution.
The fix has been provided for other reasons, but I'm glad that it makes sense for Redis cluster environment.

I'm not sure if we need to reopen an issue to investigate since we already have a version of the library which works for everyone.

FYI @Meteorkor .

Thanks

**Comment by artembilan** [comment]
Fixed with the commit:  https://github.com/spring-projects/spring-integration/commit/3c32daa25a7077f31049089cb56fd044807b1a68

**Comment by davinders88** [comment]
@artembilan , Thanks for the quick reply. I am glad that it's working with updated jar. It would be helpful if we can get explanation for the probable reason, why it was not working with old implementations.
