### ISSUE TITLE
Spring Integration File Polling custom processing order not working

### ISSUE THREAD

**Issue by connectkjain14** [spring-projects/spring-integration#3736]
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

Spring-Integration-File : 5.5.7

**Describe the bug**

I have configured spring integration to poll a directory. I have configured InBoundChannelAdaptor with poller configuration of

maxMessagesPerPoll = -1 trigger = PeriodicTrigger(1000)

Also I have provided custom comparator while creating the FileReadingMessageSource, to process the files based on modification datetime. My folder is having 2000 files, but files are not processing in the lastModified manner, means the oldest file should process first, but it is not happening.

**Expected behavior**

Files should get process in the custom ordering provided

**Sample**

https://stackoverflow.com/questions/70458037/spring-integration-custom-processing-order-not-working

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by artembilan** [comment]
I have answered to your SO question.
Let's continue discussion over there!
I don't see any issue on the Framework side yet.
