### ISSUE TITLE
Socket not closed when using UnicastSendingMessageHandler. Results in Too Many Open Files exception

### ISSUE THREAD

**Issue by fraggle222** [spring-projects/spring-integration#3739]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.9 Release (and many older releases)

**Describe the bug**

UnicastSendingMessageHandler is used to send UDP messages and implements a handleMessageInternal method which calls sendAndClose method which creates a new DatagramSocket (if needed) and then calls datagramSocket.send(packet);  It does not however close the socket after the send. If sending many udp packets in quick succession this will lead to an exception with "Too Many Open Files" as the message. There is some dependency on the ulimit settings for this on the underlying linux box.

Note: We have only looked at this when UnicastSendingMessageHandler.acknowledge flag is set to false, unclear if the socket close happens after acknowledgement if this flag is set to true. 

While there is a work around available, which is to subclass UnicastSendingMessageHandler and implement the doStop method and call the protected super.doStop(), this is not obvious and the UnicastSendingMessageHandler should either handle sockets properly or directly implement a public method that can be used to close the socket.

 
**To Reproduce**

On a Linux system like CentOS this can be reproduced as follows. Some adjustment of the number of messages to be sent may be needed depending on the settings on the Linux box (review ulimit settings for allowed open files).

for(int i=0;i<100000;i++) {
    UnicastSendingMessageHandler handler = new UnicastSendingMessageHandler(ipAddress, port);
    handler.handleMessage(MessageBuilder.withPayload("test").build());
}

(note you can also try to run this with multiple threads to have better concurrency which is more likely to trigger the issue, however we have reproduced with the code above as well).

**Expected behavior**

Socket should be closed after send or a public method should be exposed in the class that allows for closing of the socket. Previously in history there may have been a shutdown method that did this but it seems this was removed many years ago.

Edit: After some comments below I would revise expected behavior to say that the component should allow for the destination IP address and Port to be set in the message itself (or via other methods) and the underlying socket can be maintained while supporting the ability to send to many different Ip/ports with different messages. 

**Sample**

for(int i=0;i<100000;i++) {
    UnicastSendingMessageHandler handler = new UnicastSendingMessageHandler(ipAddress, port);
    handler.handleMessage(MessageBuilder.withPayload("test").build());
}

**Comment by artembilan** [comment]
This is not correct usage of the component:
```
for(int i=0;i<100000;i++) {
    UnicastSendingMessageHandler handler = new UnicastSendingMessageHandler(ipAddress, port);
```
The `UnicastSendingMessageHandler` must be declared as a singleton bean and then the socket, created internally only once, is closed properly when this component is stopped:
```
protected synchronized DatagramSocket getSocket() throws IOException {
		if (this.socket == null) {
			...
		}
		return this.socket;
	}

protected void doStop() {
		closeSocketIfNeeded();
                ...
	}
```

So, what you show us does not fit into a proper and reasonable usage of the component which can be managed only from Spring IoC container.
Well, you can do that manually (call `stop()`), but it is still wrong to create such a component on each iteration in your cycle.
Consider to have it as a `singleton`.

If you deal with many UDP addresses and really need to have the sender dynamically, then it is different story and we can  address it in the separate discussion, e.g. on StackOverflow.

But it is not a problem if the framework that you use its components outside of the framework.

Thanks for understanding.

**Comment by fraggle222** [comment]
Understood that using "new" with Spring components in this way is not really the supported design pattern ( not part of some bean, service creation, etc). 

> If you deal with many UDP addresses and really need to have the sender dynamically, then it is different story and we can address it in the separate discussion, e.g. on StackOverflow.

Yes a common pattern with UDP is to send messages to many clients. An example is in the IoT space where many thousands of IoT devices are sending UDP messages to a cloud server and the server sometimes sends responses or commands back to those devices.

For this use case are you suggesting that Sping Integration components not be used to send the outgoing message, and instead, just simply create a DatagramSocket and then call send() and close()? 

An alternate implementation of UnicastSendingMessageHandler (or perhaps a different class?) would allow with a singleton instance, for dynamic creation of a DatagramSocket and allow for sending and closing this. Perhaps this could be considered as an enhancement?

**Comment by artembilan** [comment]
See this one: https://docs.spring.io/spring-integration/docs/current/reference/html/ip.html#advanced-outbound-configuration.
So, it is still could be as a singleton bean and resolve host/port from the message you send.
Just look into that alternative ctor:
```
	/**
	 * Construct UnicastSendingMessageHandler based on the destination SpEL expression to
	 * determine the target destination at runtime against requestMessage.
	 * @param destinationExpression the SpEL expression to evaluate the target destination
	 * at runtime. Must evaluate to {@link String}, {@link URI} or {@link SocketAddress}.
	 * @since 4.3
	 */
	public UnicastSendingMessageHandler(String destinationExpression) {
```

**Comment by garyrussell** [comment]
Yes; you can still use just one socket to send to multiple destinations. Why would you want the overhead of creating a tearing down a new socket for each packet?

**Comment by fraggle222** [comment]
I don't want the overhead, of creating/destroying a socket, however, I don't see a clear way even using destinationExpression to avoid this using the UnicastSendingMessageHandler. Using plain DatagramSocket and DatagramPacket it would be straight forward. If example with UnicastSendingMessageHandler or other sping component is given then of course I will close this ticket.

**Comment by garyrussell** [comment]
Something like this:

```java
return new UnicastSendingMessageHandler(
		new FunctionExpression<Message<?>>(msg -> msg.getHeaders().get("url", String.class)));
```

Then `udpChannel.send(MessageBuilder.withPayload("test").setHeader("url", "udp://someHost:1234").build());`, where `udpChannel` is the handler's input channel.

The framework is designed to connect components with channels, rather than calling methods like `handleMessage()` directly.

**Comment by artembilan** [comment]
Closed with the requested sample.
