### ISSUE TITLE
Feature Request - Enable the ability to write custom stateful reactive code in the middle of the flow

### ISSUE THREAD

**Issue by jifeiiii** [spring-projects/spring-integration#3764]
**Expected Behavior**
I'd like there to be an option of writing reactive code in the middle of the flow. There's currently the `fluxTransform()` that enables the option of writing reactive code for transformations only. I'd really like there to be an option of writing custom reactive code for operations like `buffer()`, `bufferTimeout()`, `flatMap()` and more reactor specific functions.

**Current Behavior**
Possible only with `fluxTransform()` of with the unrecommended `bridge(e -> e.reactive())`.

**Context**
A [SO issue](https://stackoverflow.com/questions/71649191/reactive-spring-integration-access-flux-in-the-middle-of-an-integrationflow)

**Comment by artembilan** [comment]
You probably misunderstood the `fluxTransform()` a bit. 
This is exactly a Java DSL operator which does whatever you need with reactive streams in the middle of the flow: it does convert the flow into a `Flux` and apply any mentioned Reactor operator on top of it.
See it JavaDocs for more info:
```
	/**
	 * Populate a {@link FluxMessageChannel} to start a reactive processing for upstream data,
	 * wrap it to a {@link Flux}, apply provided {@link Function} via {@link Flux#transform(Function)}
	 * and emit the result to one more {@link FluxMessageChannel}, subscribed in the downstream flow.
	 * @param fluxFunction the {@link Function} to process data reactive manner.
	 * @param <I> the input payload type.
	 * @param <O> the output type.
	 * @return the current {@link BaseIntegrationFlowDefinition}.
	 */
	@SuppressWarnings(UNCHECKED)
	public <I, O> B fluxTransform(Function<? super Flux<Message<I>>, ? extends Publisher<O>> fluxFunction) {
```

See also that `Flux.transform(Function)` for more info:
```

	/**
	 * Transform this {@link Flux} in order to generate a target {@link Flux}. Unlike {@link #transformDeferred(Function)}, the
	 * provided function is executed as part of assembly.
	 * <blockquote><pre>
	 * Function<Flux, Flux> applySchedulers = flux -> flux.subscribeOn(Schedulers.boundedElastic())
	 *                                                    .publishOn(Schedulers.parallel());
	 * flux.transform(applySchedulers).map(v -> v * v).subscribe();
	 * </pre></blockquote>
	 * <p>
	 * <img class="marble" src="doc-files/marbles/transformForFlux.svg" alt="">
	 *
	 * @param transformer the {@link Function} to immediately map this {@link Flux} into a target {@link Flux}
	 * instance.
	 * @param <V> the item type in the returned {@link Flux}
	 *
	 * @return a new {@link Flux}
	 * @see #transformDeferred(Function) transformDeferred(Function) for deferred composition of Flux for each @link Subscriber
	 * @see #as(Function) as(Function) for a loose conversion to an arbitrary type
	 */
	@SuppressWarnings({"unchecked", "rawtypes"})
	public final <V> Flux<V> transform(Function<? super Flux<T>, ? extends Publisher<V>> transformer) {
```

That's exactly the place where you can apply your `buffer()`, `bufferTimeout()`, `flatMap()`.

I'm closing this as invalid since the feature is already present in the framework.

**Comment by jifeiiii** [comment]
That's awesome. Thanks!
