### ISSUE TITLE
5.5.10 unable to run on Java 8

### ISSUE THREAD

**Issue by thomasbigger584** [spring-projects/spring-integration#3767]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.10

**Describe the bug**

We upgraded a minor version from 5.5.9 to 5.5.10 and now getting an error running on Java 8 due to `List.of` in class `org.springframework.integration.support.json.JacksonJsonUtils` introduced in Java 9.  This should be at least a major upgrade as it affects those only able to run on Java 8.

```
IntegrationTest > testKafkaConsumer() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:658
            Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                Caused by: java.lang.NoSuchMethodError at JacksonJsonUtils.java:58
```

**To Reproduce**

Create an integration flow with kafka and run it with java 8.

**Expected behavior**

I expect this to run on Java 8.

**Comment by artembilan** [comment]
A duplication of https://github.com/spring-projects/spring-integration/issues/3761
