### ISSUE TITLE
Protobuf Support

### ISSUE THREAD

**Issue by devlap2** [spring-projects/spring-integration#3772]
**Expected Behavior**
I'd like there to be a `Transformer` of `ProtobufToObjectTransformer`. The `Transformers` class should include a `fromProto` function and a `toProto` function.

**Current Behavior**
There is no Protocol Buffers support in Spring Integration at all.

**Context**
Protocol Buffers are a popular and wide used mechanism for serializing structured data. This is a standard in the big data development and support to it will, later on, enable the development of grpc support.

**Comment by artembilan** [comment]
I suggest to align the impl with existing Avro transformers - `SimpleFromAvroTransformer` & `SimpleToAvroTransformer`: `FromProtobufTransformer` and `ToProtobufTransformer`.

We also might borrow some ideas from Spring Cloud Function to support gRPC channel adapters: https://spring.io/blog/2021/12/02/spring-cloud-function-3-2-is-out.

See also: https://github.com/spring-projects/spring-integration/issues/2626

and contribution is welcome: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc !

**Comment by ipanimnim** [comment]
Agree with @artembilan. This can be renamed to Protobuf & grpc support / we should add another grpc focused ticket. Grpc support is super important either.
