### ISSUE TITLE
Elasticsearch channel adapter & gateway addition

### ISSUE THREAD

**Issue by ipanimnim** [spring-projects/spring-integration#3774]
**Expected Behavior**
There's should be Elasticsearch support in Spring Integration. Reactive & non Reactive (by implementing reactively and using `.block()`). Spring Data Elasticsearch can help a lot.

**Current Behavior**
As @artembilan said: "Some Elasticsearch is implemented as of Spring Cloud Stream Sink application: https://github.com/spring-cloud/stream-applications/tree/main/applications/sink/elasticsearch-sink." 

**Context**
I'm adding issues to the most needed extensions that don't appear in the library today.

**Comment by ipanimnim** [comment]
It's also worth mentioning that ES mostly prefers bulk operations, therefore there should be native support for this.

**Comment by artembilan** [comment]
Duplicate of https://github.com/spring-projects/spring-integration/issues/3527
