### ISSUE TITLE
Debezium channel adapters & gateways support

### ISSUE THREAD

**Issue by markusherbert** [spring-projects/spring-integration#3779]
**Expected Behavior**
There should be support for Reactive and non Reactive code (with .block()).

**Current Behavior**
No native support

**Context**
This [implementation can give a good inspiration.](https://github.com/spring-cloud/stream-applications/tree/main/applications/source/cdc-debezium-source). The current implementation that exists to MongoDb's change stream can be quite similar.

**Comment by ppojejje** [comment]
Support

**Comment by artembilan** [comment]
I'm sorry, @ppojejje , it is not clear what is an intention of such a comment.

Should we treat it as a spam and report your user for abusing: https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam ?

**Comment by ppojejje** [comment]
@artembilan Sorry. Just meant to emphasize that I also see the need for debezium support.

**Comment by artembilan** [comment]
Right. Then it is better to be more specific and maybe share some thoughts how this could be implemented.

I'm not so good with Debezium to give you an immediate answer when and how this can be fixed, but we are really opened for contribution: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc
