### ISSUE TITLE
i wannt to encode uri in  WebSocketConnectionManager

### ISSUE THREAD

**Issue by TheheiWorld** [spring-projects/spring-integration#3813]
**Expected Behavior**

if uri is 'ws://localhost:5000/test?sgin=abc%2',   WebSocketConnectionManager encode uri %2 to %252 ,
but i need %S

**Current Behavior**

**Context**

**Comment by artembilan** [comment]
The logic there is like this:
```
	public ConnectionManagerSupport(String uriTemplate, Object... uriVariables) {
		this.uri = UriComponentsBuilder.fromUriString(uriTemplate).buildAndExpand(
				uriVariables).encode().toUri();
	}
```

So, uri is indeed encoded. Maybe you need to look into exactly opposite way: provide *not encoded* uri and then that ` WebSocketConnectionManager` will a proper encoding for you?

**Comment by artembilan** [comment]
The related Spring Framework issue has been fixed.
Feel free to contribute the fix for this one respectively.
