### ISSUE TITLE
v5.5.12 tag not in GitHub?

### ISSUE THREAD

**Issue by ae-govau** [spring-projects/spring-integration#3815]
https://github.com/spring-projects/spring-integration/tree/v5.5.12 shows warning:

`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

And I can't find it on the command line either...

```
$ git remote -v
origin	https://github.com/spring-projects/spring-integration (fetch)
origin	https://github.com/spring-projects/spring-integration (push)
$ git fetch origin
$ git checkout v5.5.11
HEAD is now at 837f8ff00f [artifactory-release] Release version 5.5.11
$ git checkout v5.5.12
error: pathspec 'v5.5.12' did not match any file(s) known to git
```

Trying the commit shown in GitHub also fails:

```
$ git checkout 7b450eba9b655bf65a82785f394e0ca37bfe6739
fatal: reference is not a tree: 7b450eba9b655bf65a82785f394e0ca37bfe6739
```

Something gone awry in the build/release process?

**Comment by artembilan** [comment]
Might be something off with GitHub.
The release is here: https://github.com/spring-projects/spring-integration/releases/tag/v5.5.12 and as you see it is really created from that tag showing us the warning.
It even shows correct commit history: https://github.com/spring-projects/spring-integration/commits/v5.5.12

Perhaps when I did a couple release retries because of flaky environment I forgot to uncheck `Release Branch` box.
Then I've gone later and removed that branch from here on GH.

The tag is there for me locally anyway:
```
git tag -l 'v5.5.*'

v5.5.0
v5.5.0-M1
v5.5.0-M2
v5.5.0-M3
v5.5.0-RC1
v5.5.1
v5.5.10
v5.5.11
v5.5.12
v5.5.2
v5.5.3
v5.5.4
v5.5.5
v5.5.6
v5.5.7
v5.5.8
v5.5.9
```

So, what do you treat as a bug and what would you suggest to fix?

And for cleaner context: what really drove you to look into this issue since what community needs so far are just releases in the Maven Central: https://search.maven.org/search?q=g:org.springframework.integration ?

**Comment by ae-govau** [comment]
@artembilan - thanks, there's definitely something weird with how that commit is stored in GitHub. Looks like the Grafana project had a similar issue: https://github.com/grafana/grafana/issues/45642 - and from that I ran `git fetch --tags` (rather than a normal `git fetch` and that has locally resolved it for me.

That said, that banner in GitHub is weird - feels like it's a rare(?) bug on their end?

On the why do I want to pull the source? 5.5.12 (or something else in Spring Boot 2.7.0) has broken something in our tests, and my experience with Spring is nothing beats pulling the source and running `git grep` / `git log -p -- xxx` until I can figure out what's changed. :)

Our failure message, not that I'm expecting help debugging it, it's just what brought me here:

```
org.springframework.messaging.MessageHandlingException: error occurred in message handler
    [bean 'xxxx' for component 'xxx.org.springframework.integration.config.ConsumerEndpointFactoryBean#xxx';
        defined in: 'xxxx'; from source: 'bean method xxxx']; nested exception is
            org.springframework.data.mapping.MappingException: No property message found on entity class org.springframework.integration.mongodb.store.MongoDbMessageStore$MessageWrapper to bind constructor parameter to!,
                failedMessage=GenericMessage [
                    payload=xxx(xxx=xxxx), contentType=application/octet-stream), headers={id=xxx, timestamp=xxxx}]
```

**Comment by ae-govau** [comment]
I think the underying issue causing me problems lies in Spring Data Commons 2.6.4 -> 2.7.0 bump https://github.com/spring-projects/spring-data-commons/commit/1e38b4c6babbd382a5999b944885fa2410d22a9f

**Comment by artembilan** [comment]
Well, if we are good with that commit, let’s consider to close this issue then! Perhaps `git fetch --tags` works here for you as well as it works for me.

regarding that error from MongoDB, I’d like to hear more: I kinda claim here that Spring Integration `5.5.x` generation is compatible with that Spring Boot `2.7.x`. So, something might need to be fixed on our side , even if it will go reflection way to support several Spring Data versions… But, please, a separate issue . No hijacking like I just did 😅

thanks

**Comment by ae-govau** [comment]
Re the Git issue - it's actually right - the tagged commit is not on the 5.5.x branch:
https://github.com/spring-projects/spring-integration/commits/5.5.x

**Comment by artembilan** [comment]
Good catch! So, I definitely had released this through release branch and then removed it from repo. Will cherry-pick that commit tomorrow . Perhaps with history re-write to preserve timeline…

**Comment by ae-govau** [comment]
Sounds like a good plan to me.

**Comment by ae-govau** [comment]
@artembilan - have opened #3816 for the actual issue - that took a crazy amount of time to narrow down.

**Comment by artembilan** [comment]
I have injected `Release version 5.5.12` commit into `5.5.x` branch, but doesn't look like that have fixed the warning on the tag: https://github.com/spring-projects/spring-integration/commits/5.5.x.

Anyway I consider this as fixed.

Will look into your other problem a bit later.

Thank you!
