### ISSUE TITLE
MessageGroup.getMessages().stream() broken(?) in 5.5.12 (or other Spring Boot 2.7.0 dependency bump)

### ISSUE THREAD

**Issue by ae-govau** [spring-projects/spring-integration#3816]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.12 (from Spring Boot 2.7.0)

Issue does not occur with 5.5.11 and Spring Boot 2.6.7.

**Describe the bug**

Attempting to get the payload while iterating over the result of `.getMessage().stream()` throws an exception. Doing the same without the `.stream()` works as expected.

```java
a.releaseStrategy(x -> {  
    x.getMessages().forEach(m -> System.err.println("This works: " + m.getPayload().toString()));
    x.getMessages().stream().forEach(m -> System.err.println("This blows up: " + m.getPayload().toString()));
    return true;
});
```

**To Reproduce**

When running with Spring Boot 2.7.0 (5.5.12 integration) we see this:

```
This works: Hi!
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.158 s <<< FAILURE! - in test.BugTest
[ERROR] testThing  Time elapsed: 0.643 s  <<< ERROR!
org.springframework.messaging.MessageHandlingException: error occurred in message handler [bean 'flow.aggregator#0' for component 'flow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0'; defined in: 'test.Thing'; from source: 'bean method flow']; nested exception is org.springframework.data.mapping.MappingException: No property message found on entity class org.springframework.integration.mongodb.store.MongoDbMessageStore$MessageWrapper to bind constructor parameter to!
        at test.BugTest.testThing(BugTest.java:35)
Caused by: org.springframework.data.mapping.MappingException: No property message found on entity class org.springframework.integration.mongodb.store.MongoDbMessageStore$MessageWrapper to bind constructor parameter to!
        at test.BugTest.testThing(BugTest.java:35)
```

**Expected behavior**

Running the same against Spring Boot 2.6.7 gives the expected result:

```
...
This works: Hi!
This blows up: Hi!
...
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Sample**

<https://github.com/ae-govau/message-group-issue>

**Comment by artembilan** [comment]
Thanks for the report, @ae-govau !

So, if I downgrade just Spring Data according to Spring Integration `5.5.x` dependencies:
```
    <properties>
        <spring-data-bom.version>2021.0.11</spring-data-bom.version>
    </properties>
```
It comes back to work. But is not robust and not what we would like to have to go ahead with target project.


Another solution is to use this message store instead:
```
    @Bean
    ConfigurableMongoDbMessageStore mongoMessageStore(MongoDatabaseFactory df) {
        return new ConfigurableMongoDbMessageStore(df, "foo");
    }
```

Which is the recommended way for a long time anyway: https://docs.spring.io/spring-integration/docs/current/reference/html/mongodb.html#mongodb-message-store.

There is the fix like this in the `main`: https://github.com/spring-projects/spring-integration/commit/860f9fea3f4e6fd6261fe13ca4610fb4eecdc88c which I'm going to try to back-port to `5.5.x`.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/469bd6ba044ffbea76a7dc359ce5d0b2d764bc3e.

So, or use `ConfigurableMongoDbMessageStore` or wait for the next `5.5.13` release 😄 

Thank you for this again!

**Comment by ae-govau** [comment]
Thanks @artembilan - really appreciate the quick turnaround and alternate suggestions. We'll give the `ConfigurableMongoDbMessageStore` a go - have managed to subsitute that, and with a few changes to accommodate our `MongoTemplate` (`ConfigurableMongoDbMessageStore` doesn't play nice if there are already MongoMappingConverters installed), all our tests are passing.
