### ISSUE TITLE
CachingSessionFactory slowness if setPoolSize is called without initializing initial sessionCacheSize

### ISSUE THREAD

**Issue by gauravbrills** [spring-projects/spring-integration#3826]
Version :
5.5.10

Migrating from 5.1.13 and 5.5.10

**Describe the bug**

We were doing a spring 2.6 migratoin and hence also upgrading spring integration version to 5.5.10 . Our existing code used to initialize CachingSessionFactory as below

```
      CachingSessionFactory<LsEntry> csf = new CachingSessionFactory<LsEntry>(sf ); 
       scsf.setPoolSize(connectionInfo.getPoolSize());
      // Refer https://github.com/spring-projects/spring-integration/pull/2606
      csf.setTestSession(true);
      csf.setSessionWaitTimeout(props.getSftp()
            .getSessionWaitTimeout());
```
Post migrating we observed that the `setPoolSize` method was degrading our performance and in itself taking aroudn 30 seconds . This is mainly due to the method calling `SimplePool.setPoolSize` which as the poolsize was not initialized keeps a default pool size as Integer.MAX_VALUE and hence when setPoolSize tries to reduce the pool size it goes into a long loop in order to clear it up . The same worked in the old version as the old code used to break in case there was nothing returned on poll . 

**Diff here** https://github.com/spring-projects/spring-integration/compare/v5.1.13.RELEASE...v5.5.10#diff-1da249bba02f27de259b1f47687338cb6204ca4754afd457ef82a1d17c912ca1 

**To Reproduce**

The below code 

```
      CachingSessionFactory<LsEntry> csf = new CachingSessionFactory<LsEntry>(sf ); 
       scsf.setPoolSize(connectionInfo.getPoolSize());
      // Refer https://github.com/spring-projects/spring-integration/pull/2606
      csf.setTestSession(true);
      csf.setSessionWaitTimeout(props.getSftp()
            .getSessionWaitTimeout());
```

**Expected behavior**
 
I think the design makes sense to clear the pool but it could lead to performance issues in case the poolsize is not initialized at the start like ` CachingSessionFactory<LsEntry> csf = new CachingSessionFactory<LsEntry>(sf, connectionInfo.getPoolSize()); ` . There could be a fix or this needs to be documented in code so people take care in case of upgrades.  

**Sample**

```
      CachingSessionFactory<LsEntry> csf = new CachingSessionFactory<LsEntry>(sf ); 
       scsf.setPoolSize(connectionInfo.getPoolSize());
      // Refer https://github.com/spring-projects/spring-integration/pull/2606
      csf.setTestSession(true);
      csf.setSessionWaitTimeout(props.getSftp()
            .getSessionWaitTimeout());
```

**Comment by artembilan** [comment]
I see your point, @gauravbrills .

If you have a possible fix in mind, feel free to contribute it or share over here.
I will think how that `while (delta < 0) {` algorithm could be changed...

**Comment by gauravbrills** [comment]
Sure we were working on patching our code but I will add PR once I get time next week
