### ISSUE TITLE
Method call: Method messageSender(java.lang.String) cannot be found

### ISSUE THREAD

**Issue by waytoharish** [spring-projects/spring-integration#3836]
Hi Team,
I am trying to use Spring integrated to Publish a message to GCP topic but i am getting below error
**Method call: Method messageSender(java.lang.String) cannot be found**

My Configuration Code is like-
1. Gateway
public interface PubsubOutboundGateway {
    void sendToPubsub(String text);

}

2. Service Activator
@Component
public class GspConfig {

   public MessageHandler messageSender(PubSubTemplate pubsubTemplate) {
        return new PubSubMessageHandler(pubsubTemplate, "myTopic");
    }
}

3. XML Config-
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:int="http://www.springframework.org/schema/integration"
       xmlns:int-http="http://www.springframework.org/schema/integration/http"
       xsi:schemaLocation="
    http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/integration
    http://www.springframework.org/schema/integration/spring-integration.xsd
    http://www.springframework.org/schema/integration/http
    http://www.springframework.org/schema/integration/http/spring-integration-http.xsd">
 <int:channel id="myInputChannel"></int:channel>

    <int:service-activator
            input-channel="myInputChannel"
            ref="gspConfig"/>

    <int:gateway
            service-interface="com.hksharma.config.PubsubOutboundGateway"
            default-request-channel="myInputChannel">
        <int:method name="sendToPubsub"/>
    </int:gateway>
</beans>

4. I am invoking the same in the Controller class like-
  @Autowired
    private PubsubOutboundGateway messagingGateway;

        messagingGateway.sendToPubsub("Test");

Please can you suggest me what wrong i am doing .

**Comment by artembilan** [comment]
The `PubSubMessageHandler` must be declared as a bean. Then this bean you can use in the `<int:service-activator ref="">`.
The current your approach is not correct: you point to the `GspConfig` and let the framework to decide which method to call.
In the end you really would like to have a `PubSubMessageHandler.handleMessage()` to be called.

Either way this is a StackOveflow candidate: nor a bug, neither a feature request.
Closing as `Invalid`
