### ISSUE TITLE
Migrate MongoDB tests to Testcontainers

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3839]
Currently our integration tests rely on the MongoDB server provided by the host of the test execution and use JUnit 4 rule for condition evaluation.
We cannot have externally configured MongoDB server on CI environment anymore, so SonarQube reports pure coverage, since most of MongoDB tests are ignored.

Switch integration tests for MongoDB to Testcontainers since Docker is available in most modern environments.
This way we also will be able to migrate all those tests to JUnit 5.

See `MosquittoContainerTest` for example.

**Comment by artembilan** [comment]
@oxcafedead,

I wonder if you can now look into this since you have a similar experience migration Redis tests.

Thank you!

**Comment by oxcafedead** [comment]
@artembilan,
Sure, I will take a look at this one.
