### ISSUE TITLE
MessageHistory does not copy the original message when handling an errormessage

### ISSUE THREAD

**Issue by emagiz** [spring-projects/spring-integration#3843]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.11

**Describe the bug**

MessageHistory does not copy the original message when handling an errormessage.
When we use messagehistory in an integration flow the original message in the errormessage is always null. When we do not use messagehistory the originalmessage in the errormessage is not null and corresponds to the originalmessage.

Code part here:
https://github.com/spring-projects/spring-integration/blob/ba8a26f616509849e7e0751d2f8df2e1af9ed46b/spring-integration-core/src/main/java/org/springframework/integration/history/MessageHistory.java#L113

**To Reproduce**

Add messagehistory to any flow producing an error.
Flow details:
<si:channel fixed-subscriber="false" id="tstrrr.rrrmssg.entry.channel.channel"/>
<si:inbound-channel-adapter channel="tstrrr.rrrmssg.entry.channel.channel" expression="'hallo'" id="tstrrr.rrrmssg.entry.receive.InboundError">
    <?emagiz mendix-association="E"?>
    <si:poller fixed-delay="5" time-unit="SECONDS"/>
</si:inbound-channel-adapter>
<si:service-activator input-channel="tstrrr.rrrmssg.entry.channel.channel" expression="payload[10]" id="tstrrr.rrrmssg.entry.activate.serviceActivator" requires-reply="false"/>

We are listening for errors and then checking by using this:
System.out.println("IS ORIGINAL MESSAGE NULL? :" + (message.getOriginalMessage() == null));

**Expected behavior**
The original message is copied along to the new message

**Sample**

				IntegrationMessageHeaderAccessor headerAccessor = new IntegrationMessageHeaderAccessor(message);
				headerAccessor.setHeader(HEADER_NAME, history);
				Throwable payload = ((ErrorMessage) message).getPayload();
				Message originalMessage = ((ErrorMessage) message).getOriginalMessage();
				ErrorMessage errorMessage = new ErrorMessage(payload, headerAccessor.toMessageHeaders(), originalMessage);
				message = (Message<T>) errorMessage;

**Comment by artembilan** [comment]
Confirmed.

Would you mind providing a contribution on the matter: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc ?

Thanks
