### ISSUE TITLE
[Feature Request] Apache Cassandra outbound channel adapter

### ISSUE THREAD

**Issue by rolkhas2** [spring-projects/spring-integration#3851]
**Expected Behavior**
As an Apache Cassandra user, I'd expect there to be Apache Cassandra channel adapters (preferable to Reactive ones). I've seen [requests for Apache HBase](https://github.com/spring-projects/spring-integration/issues/3777) (which I support since it'll be a great option), but I haven't seen any mentions of Cassandra support, even though that's a super popular database.

**Current Behavior**
There's no Apache Cassandra support for Spring Integration \ Reactive Spring Integration (no sync \ async channel adapter).

**Context**
I think that Spring Integration got a pretty great amount of channel adapters, but definitely not all of the ones that are needed. [Apache Cassandra isn't on the list](https://docs.spring.io/spring-integration/docs/current/reference/html/), even though it can help lots of users.

**Comment by artembilan** [comment]
That's not correct.
We have an extension project for exactly this one: https://github.com/spring-projects/spring-integration-extensions/tree/main/spring-integration-cassandra.
And it is indeed reactive one.
There is probably just need to move it to this project as a module and document properly: https://github.com/spring-projects/spring-integration-extensions/issues/254

It would be great to have some contribution on the matter: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

**Comment by rolkhas2** [comment]
@artembilan Sorry for the lack of knowledge (didn't know about this repo). Thanks for the quick response. I'll check on that later.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/a08713fe874131a41cb9191cd7c8d04ed0d03574
