### ISSUE TITLE
Log SFTP Transfer with SftpProgressMonitor

### ISSUE THREAD

**Issue by earocker** [spring-projects/spring-integration#3855]
It would be nice to be able to upload files to SFTP with a default or custom com.jcraft.jsch.SftpProgressMonitor

By implementing SftpProgressMonitor we'd be able to see actual transferring log

**Current Behavior**
There is no way to see file transfer progress

**Context**
I'd like to have in the logs proof that a file got fully and successfully transferred.

**Comment by artembilan** [comment]
There is the way. Something like this to be called from your service activator:
```
		template.executeWithClient((ClientCallbackWithoutResult<ChannelSftp>) client -> {
			try {
				client.put("data", "remoteFile", new SftpProgressMonitor() {

					@Override 
					public void init(int op, String src, String dest, long max) {
						
					}

					@Override 
					public boolean count(long count) {
						return false;
					}

					@Override 
					public void end() {

					}
					
				});
			}
			catch (SftpException e) {
				throw new RuntimeException(e);
			}
		});
```

I doubt at the moment that we are going to expose this as a first class citizen functionality on the `SftpMessageHandler` since it doesn't fit either way to other file stores protocols.

**Comment by earocker** [comment]
I see. that code is actually really helpful! and might suffice for my use case!!

thanks a lot
