### ISSUE TITLE
Message can be obtained when DefaultMailHeaderMapper is used

### ISSUE THREAD

**Issue by XhstormR** [spring-projects/spring-integration#3860]
**Expected Behavior**

Message can be obtained when DefaultMailHeaderMapper is used.

**Current Behavior**

I am using imapInboundAdapter to receive mail, and I want to manually set the received mail as read or unread, I use the 
 `setFlag(Flags.Flag.SEEN, true)` method of Message, but I found that after using DefaultMailHeaderMapper, AbstractMessageHandler handles The MimeMessage object becomes MimeMultipart, which means that there is no Message object to set the Flag.

**Context**

Here is the code I am using:

```kotlin
    @Bean
    fun integrationFlow() = IntegrationFlows.from(mailInboundChannelAdapterSpec()) {
        it.poller(Pollers.fixedDelay(Duration.ofSeconds(2)))
    }
        .channel(INPUT_CHANNEL)
        .handle(MailMessageHandler())
        .get()

    private fun mailInboundChannelAdapterSpec() =
        Mail.imapInboundAdapter("imaps://user:pass@imap.qq.com:993/INBOX")
            .simpleContent(false)
            .autoCloseFolder(false)
            .embeddedPartsAsBytes(false)
            .shouldDeleteMessages(false)
            .shouldMarkMessagesAsRead(false)
            .maxFetchSize(1)
            .headerMapper(DefaultMailHeaderMapper())
```

**Comment by artembilan** [comment]
See documentation: https://docs.spring.io/spring-integration/docs/current/reference/html/mail.html#mail-mapping. 
It clearly stay that when you use a `HeaderMapper`, the payload is not a `MimeMessage` any more. Also that option JavaDocs:
```
	/**
	 * Set the header mapper; if a header mapper is not provided, the message payload is
	 * a {@link MimeMessage}, when provided, the headers are mapped and the payload is
	 * the {@link MimeMessage} content.
	 * @param headerMapper the header mapper.
	 * @since 4.3
	 * @see #setEmbeddedPartsAsBytes(boolean)
	 */
	public void setHeaderMapper(HeaderMapper<MimeMessage> headerMapper) {
```

The logic is like this:
```
				if (this.headerMapper != null) {
					headers = this.headerMapper.toHeaders(message);
					payload = extractContent(message, headers);
				}
```

I'm not sure what drives you that it has to behave differently.

The point is: if you want the whole `MimeMessage` as a payload in downstream service, there is no reason to extract its headers since they are going to be available in that `MimeMessage` anyway. Kinda an overhead to extract headers if no content extraction.

The resolution for this issue is `Works as Designed`, but I'll leave it opened until your answer.

Thanks

**Comment by XhstormR** [comment]
Is there a way to set the flags parameter of the Message object while using the DefaultMailHeaderMapper, because I also want to get the metadata in the header like the mail subject、the received date and the from address.

**Comment by XhstormR** [comment]
Ok, I found out that we can directly use DefaultMailHeaderMapper to extract headers:
```
val headers = DefaultMailHeaderMapper().toHeaders(message.payload)
```

**Comment by artembilan** [comment]
That's the one way to go.
The other one could be with `MimeMessage` re-fetching via its `Message-ID` and folder API.
See some example in the docs when we discuss about transaction synchronizations: https://docs.spring.io/spring-integration/docs/current/reference/html/mail.html#mail-tx-sync

**Comment by XhstormR** [comment]
I tried it, but the object obtained is not MimeMessage type , but the processed message object.

This is the code:

```kotlin
@Bean
fun integrationFlow() = IntegrationFlows.from(mailInboundChannelAdapterSpec())
    .handle(MailMessageHandler())
    .get()

private fun mailInboundChannelAdapterSpec() =
    Mail.imapIdleAdapter("imaps://user:pass@outlook.office365.com:993/INBOX")
        .autoStartup(true)
        .shouldReconnectAutomatically(true)
        .simpleContent(false)
        .autoCloseFolder(false)
        .embeddedPartsAsBytes(false)
        .shouldDeleteMessages(false)
        .shouldMarkMessagesAsRead(false)
        .headerMapper(DefaultMailHeaderMapper())
        .transactional(PseudoTransactionManager())
        .transactionSynchronizationFactory(DefaultTransactionSynchronizationFactory(MailMessageProcessor()))
```

```kotlin
class MailMessageProcessor : TransactionSynchronizationProcessor {

    private companion object {
        val LOGGER = getLogger()
    }

    override fun processBeforeCommit(holder: IntegrationResourceHolder) {
        LOGGER.info("processBeforeCommit")
    }

    override fun processAfterCommit(holder: IntegrationResourceHolder) {
        LOGGER.info("processAfterCommit")

        //  Not always MimeMessage objects
        when (val payload = holder.message.payload) {
            is String -> order(payload)
            else -> return
        }
    }

    override fun processAfterRollback(holder: IntegrationResourceHolder) {
        LOGGER.info("processAfterRollback")
    }
}
```

**Comment by artembilan** [comment]
That's correct: the `payload` is exactly what we got after `MimeMessage` processing in the `MailReceiver`, but you have headers to deal with. See `MailHeaders.RAW_HEADERS` and its `MultiValueMap<String, String>` value. One of those is going to be the mentioned `Message-ID`.
Although you still need to create the `Folder` somehow, so probably the way you use `DefaultMailHeaderMapper` manually is much simpler...

**Comment by XhstormR** [comment]
i see，thanks for your answer, it is very helpful,
