### ISSUE TITLE
AOT support for MQTT + Eclipse Paho

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-integration#3900]
Hi, i love your MQTT support, but MQTT Paho doesn't work out-of-the-box in an AOT context. I crafted some hints that make my example work. Perhaps you would consider including them for others?

Here's the commit demonstrating the hints and a pretty [typical inbound/outbound example w/ Spring Integration MQTT ](https://github.com/spring-tips/spring-integration-mqtt-and-hivemq/blob/75d6dba5b08959fac8db4c93dd2fb55ed5cb867d/src/main/java/com/example/hivemq/HivemqApplication.java#L54
)

Here's the hints, if for whatever reason that github repo should be lost: 

```java

    static class MqttHints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {

            var classes = new Class<?>[]{
                    JSR47Logger.class,
                    LoggerFactory.class,
                    NetworkModuleFactory.class,
                    WebSocketNetworkModuleFactory.class,
                    WebSocketSecureNetworkModuleFactory.class,
                    SSLNetworkModuleFactory.class,
                    TCPNetworkModuleFactory.class,
                    Logger.class};

            var resources = Map.of(
                    "org/eclipse/paho/client/mqttv3/logging/JSR47Logger.class", false, //
                    "org/eclipse/paho/client/mqttv3/internal/nls/logcat.properties", false, //
                    "org/eclipse/paho/client/mqttv3/internal/nls/messages", true
            );

            for (var c : classes) {
                hints.reflection().registerType(c, MemberCategory.values());
            }

            for (var entry : resources.entrySet()) {
                var bundle = entry.getValue();
                var path = entry.getKey();
                if (bundle)
                    hints.resources().registerResourceBundle(path);
                else
                    hints.resources().registerPattern(path);

            }
        }
    }
```

**Comment by artembilan** [comment]
Hi @joshlong !

You know it is better to ask for this support directly in Eclipe Paho project: https://github.com/eclipse/paho.mqtt.java
As it is states by the GraalVM reachability metadata repo contribution: https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md.

Also I think some of your hints are redundant or erroneous.

1. The ServiceLoader is supported by GraalVM as out-of-the-box feature, so we don't need many of those classes to register manually for reflection: https://github.com/oracle/graal/issues/563#issuecomment-459121737.
We need to double check with modern GraalVM version to be sure in our (Eclipse Paho) extra hints.
2. I'm not sure why `org/eclipse/paho/client/mqttv3/logging/JSR47Logger.class` is marked as a resource in your case...

Out of scope: Spring Integration also supports MQTT V5 if that is useful for your sample though: https://docs.spring.io/spring-integration/docs/current/reference/html/mqtt.html#mqtt-v5

**Comment by joshlong** [comment]
Alright, I've raised an issue there. I hope they're able to do this before we go GA w spring boot. it would be amazing to have all the major modules working out of the box in spring integration when Boot goes GA. 

https://github.com/eclipse/paho.mqtt.java/issues/963

**Comment by artembilan** [comment]
This is working config for the current GraalVM and Spring AOT support:
```
	static class MqttHints implements RuntimeHintsRegistrar {

		@Override
		public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
			ReflectionHints reflectionHints = hints.reflection();
			Stream.of(
							"org.eclipse.paho.client.mqttv3.logging.JSR47Logger",
							"org.eclipse.paho.mqttv5.client.logging.JSR47Logger")
					.forEach(type -> reflectionHints.registerTypeIfPresent(classLoader, type,
							MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS));

			ResourceHints resources = hints.resources();
			Stream.of(
							"org/eclipse/paho/client/mqttv3/internal/nls/messages",
							"org/eclipse/paho/client/mqttv3/internal/nls/logcat",
							"org/eclipse/paho/mqttv5/common/nls/messages",
							"org/eclipse/paho/mqttv5/client/internal/nls/logcat")
					.forEach(resources::registerResourceBundle);
		}

	}
```

Closed in favor of linked Eclipse Paho issue.

**Comment by artembilan** [comment]
FYI the native image support has made it into Rome code base: https://github.com/rometools/rome/issues/599
