### ISSUE TITLE
Add Kotlin Coroutines Support

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3902]
### Discussed in https://github.com/spring-projects/spring-integration/discussions/3894

<div type='discussions-op-text'>

<sup>Originally posted by **tomvandenberge** September 25, 2022</sup>
Hi,
I'm using Spring Integration in various Kotlin (previously Java) projects. Some of these projects are using coroutines. So far, I haven't been able to find a way to use coroutines together with Spring Integration. I'd love to be able e.g. to have a suspending function as a service activator. Currently this is not possible.

I realise that this probably requires fundamental changes to Spring Integration, but I wanted to check with you if this is something that is already on your roadmap?

Thanks,
Tom</div>

**Comment by tomvandenberge** [comment]
Thanks for looking into this. I would say coroutines is a bit more than just another Reactive Streams library -- it's a feature that's built into the kotlin language itself. Other parts of the Spring framework already provide support for coroutines, e.g. WebFlux, which allows you to use suspending @Controller functions. In my view, Spring Integration could provide similar support, meaning that it's possible to use Spring Integration components using suspending functions. I don't see how you can do this very easily though; I think it means making all Spring Integration components work with suspending functions.

**Comment by artembilan** [comment]
Well, I look at that from the point of view of this Java framework. 
It is really out of my scope if that is high-level language feature or some extra library. For me me it is just a set of respective types I can deal with in the framework Java code.
And that's probably not a surprise why Spring Framework asks for the `kotlinx-coroutines-reactor` dependency...
But that's already this framework responsibility how to deal with those types.

From end-user perspective it indeed would look similar to that `@RequestMapping` for `suspend fun`:
```
    @ServiceActivator(inputChannel = "input")
    suspend fun render(payload: String): String {
```

The change (I believe) is going to happen only in one place - `MessagingMethodInvokerHelper`. So, all other messaging annotations would be able to be used with `suspend` functions as well.

Another part of the puzzle indeed going to be a `@MessagingGateway` for those `suspend` method definitions on the interface.

Since it is still a Reactive Streams library to make the whole integration flow fully suspendable we have to use a `FluxMessageChannel` in between endpoints as we recommend for `Flux` and `Mono`: https://docs.spring.io/spring-integration/docs/current/reference/html/reactive-streams.html#reactive-streams.

**Comment by artembilan** [comment]
@tomvandenberge ,

here you are PR: https://github.com/spring-projects/spring-integration/pull/3905 !
