### ISSUE TITLE
How to send kafka msg from presend method of ChannelInterceptor to one DLQ

### ISSUE THREAD

**Issue by DKumarKartik** [spring-projects/spring-integration#3918]
**Expected Behavior**

So when some exception happens in preSend method of ChannelInterceptor may be it should reach to any DLQ channel instead of given topic so that we can track that record.

**Current Behavior**

So when some exception happens in preSend method of ChannelInterceptor we lost that record.

**Context**

Currently we are doing some operation in presend method and if some exception occurs in that method it tends to loss of current record and it moves to next record.
So we are loosing that particular record.
If there is a mechanism to send those record to some DLQ it will be help full.

**Comment by artembilan** [comment]
This sounds more like a question with some design solution.
Please, raise your concern on StackOveflow with much more info, including some configuration to determine your logic.

There we will decide if this is something what has to be improved somehow on the framework side.

Closed as `Invalid`
