### ISSUE TITLE
Support `@Import`ing gateway interfaces

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-integration#3923]
**Expected Behavior**
```
@MessagingGateway
interface MyGateway {
  void enqueue(MyObject o)
}

@Configuration
@Import(MyGateway)
class IntegrationConfig {}
```

A gateway proxy for `MyGateway` is added to the context.

**Current Behavior**

Currently, this import produces `BeanInstantiationException: Specified class is an interface`.

**Context**
[We usually use `@Import` rather than `@ComponentScan`](https://stackoverflow.com/questions/74158211/is-there-a-directive-to-individually-import-a-spring-integration-gateway-in-java) for more fine-grained control (and slightly faster startup). I'd like to be able to `@Import` a gateway interface in the same way we do for service classes. I think this would be possible with a `BeanFactoryPostProcessor`.

**Comment by artembilan** [comment]
The `@Import` annotation is out of Spring Integration scope and its behavior cannot be controlled.

I don't know if Spring Data has something like manual Repository registration, but this `@MessagingGateway` has really been designed after Spring Data Repository interfaces scanning.

More over whatever you are asking is already available like this:
```
@Bean 
AnnotationGatewayProxyFactoryBean myGateway() {
    return new AnnotationGatewayProxyFactoryBean(MyGateway.class);
}
```

Can you tell us, please, what is wrong with this approach?

I gave you similar answer in your other issue: https://github.com/spring-projects/spring-integration/issues/3920.

Why did you ignore that and raised a new one, plus SO thread?

**Comment by chrylis** [comment]
I asked a question on SO primarily so that whatever the best answer is found will be visible to anyone else who is trying to write similar code. The feature request here is very much not ignoring #3920; I'm suggesting something new that I know isn't supported right now but that would be convenient to have.

Please note that your solution _does not_ provide what I'm asking for, because the `AnnotationGatewayProxyFactoryBean` will not match `@ConditionalOnBean(MyGateway)`.

**Comment by artembilan** [comment]
OK. So, you suggest then to have some thing like `@IntegrationImport` like a brother for existing `@IntegrationComponentScan`.
Kinda realign what we have so far with a `@ComponentScan` and its brother `@Import`.

I think what you are talking about with a conditional based on type can be fixed with a generic argument on the `AnnotationGatewayProxyFactoryBean`.
This is that kind of limitation Spring Framework has at the moment around target type guessing from the `FactoryBean`.
The `@IntegrationComponentScan` ends up with a `beanDefinition.setAttribute(FactoryBean.OBJECT_TYPE_ATTRIBUTE, serviceInterface);`.
Or... we may consider to implement `MergedBeanDefinitionPostProcessor` for scanning `AnnotationGatewayProxyFactoryBean` and setting the same `FactoryBean.OBJECT_TYPE_ATTRIBUTE` attribute after guessing it from that `AnnotationGatewayProxyFactoryBean`.

**Comment by chrylis** [comment]
I will do some experimentation this weekend, but I think it might be possible to handle this without having a specific `@IntegrationImport` through a `BeanFactoryPostProcessor`.

**Comment by chrylis** [comment]
I expect that I'm missing sanity checks for some corner cases, especially regarding when the `ConfigurableListableBeanFactory` is not the usual `DefaultLBF`. `ImportBeanDefinitionRegistrar` is guaranteed to be passed a `BeanDefinitionRegistry`, but `BeanFactoryPostProcessor` isn't. That said, this seems to be working for me!

The basic logic is to find bean definitions annotated with `@MessagingGateway` whose beanClass is an interface type, remove those, and replace them with definitions created by `MessagingGatewayRegistrar` (the same logic applied by `@IntegrationComponentScan`). Since that class doesn't provide a hook to set the wrapped bean definition, the information about the original interface bean is discarded.

```
public class MessagingGatewayBeanFactoryPostProcessor implements BeanFactoryPostProcessor {

    private final MessagingGatewayRegistrar registrar = new MessagingGatewayRegistrar();

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        var bdr = (BeanDefinitionRegistry) beanFactory;
        var interfaceBeans = findMessagingGatewayInterfaceBeans(beanFactory);
        interfaceBeans.forEach((name, metadata) -> {
            bdr.removeBeanDefinition(name);
            registrar.registerBeanDefinitions(metadata, bdr);
        });
    }

    static Map<String, AnnotationMetadata> findMessagingGatewayInterfaceBeans(ListableBeanFactory bf) {
        Map<String, AnnotationMetadata> interfaceBeans = new LinkedHashMap<>();

        for (String beanName : bf.getBeanNamesForAnnotation(MessagingGateway.class)) {
            var bd = bf.getBeanDefinition(beanName);
            if (!(bd instanceof AnnotatedBeanDefinition)) {
                continue;
            }

            var metadata = ((AnnotatedBeanDefinition) bd).getMetadata();
            interfaceBeans.put(beanName, metadata);
        }

        return interfaceBeans;
    }
}
```

**Comment by artembilan** [comment]
Hi @chrylis !

Thank you for sharing your experience, but tell me, please, what the problem you try to solve with this?
As long as you call that `bf.getBeanNamesForAnnotation(MessagingGateway.class))` it means that there are bean definitions with that `@MessagingGateway`.
And how do they appear in the application context?
What is an end-user configuration you try to hack against?

**Comment by chrylis** [comment]
This single modification addresses two challenges that my team is facing:

1. We mostly use `@Import` for constructing our configuration bean definitions (except when some complex configuration is required). Specifically exporting an `AnnotationGatewayProxyFactoryBean` from an `@Bean` method does cause the bean to be created, but it requires more boilerplate code than is necessary and is not as clear to read as `@Import(MyGateway.class)`.
2. More functionally, with this approach, the bean of type `MyGateway` is present in the context when Boot auto-configuration is applied, so client configuration that is `@ConditionalOnBean(MyGateway.class)` will match reliably.

**Comment by artembilan** [comment]
Sorry, you didn't answer my question.
What do we need this post-processing for?
The `@Import(MyGateway.class)`, but you still use that `bf.getBeanNamesForAnnotation(MessagingGateway.class))`, so there is already something in your configuration.
What is that `AnnotationGatewayProxyFactoryBean` exporting looks like?

Just show me that your configuration for what that `BeanFactoryPostProcessor` impl makes sense. 😄

**Comment by chrylis** [comment]
Does this answer it?

```
@Configuration
// no IntegrationComponentScan
@Import({
  MyGateway.class,
  // ^ Normally this Import would fail because MyGateway is an interface
  MyService.class,
})
class Config {}

@MessagingGateway(defaultRequestChannel = "foo")
interface MyGateway {
  void enqueue(String value)
}

class MyService {
  @Autowired
  MyGateway gateway
}
```

**Comment by chrylis** [comment]
(By the way, if this post-processor looks useful, I am happy to try to work up a PR for it. I might need direction on where the tests should go.)

**Comment by artembilan** [comment]
Yes, please, open PR.

I really didn't think about `BeanDefinition` registration for a plain `@Component` from the `@Import`.

The `GatewayInterfaceTests` should be a good candidate to play with.

Thank you!

**Comment by chrylis** [comment]
What's the baseline Java version for `main`? I tried to build with Java 11 and got an error on `spring-integration-test-support` that it wanted 17, which looks like the 6.0 baseline. (Should I contribute to another branch to try to get this retrofit into the 5.x series?)

**Comment by artembilan** [comment]
Right, the `main` (`6.0`) is Java 17.
Not sure that this will make it into `5.x` though.
There is just plain workaround to stay with an `@IntegrationComponentScan`.
Or manually register a `BeanFactoryPostProcessor` you propose.

The generic arg support, which has been just merged, won't be back-ported to `5.x` because that one is really a breaking change.
Therefore I doubt in this `@Import` feature to be back-ported as well...

**Comment by chrylis** [comment]
That's up to you, but I wrote it against 5.5.14, and I don't see a reason why the implementation shouldn't work as far back as 4.0 (it uses only core Spring Context features and the `MessagingGatewayRegistrar`).

**Comment by artembilan** [comment]
Sure!
Let see your PR against `5.5.x` then!
We simply can forward-port it to the `main`.
The `4.0.x` generation is long EoL already: https://spring.io/projects/spring-integration#support

**Comment by chrylis** [comment]
Oh, I know 4.x is dead... that was two startups ago!

**Comment by artembilan** [comment]
You know, I'm starting looking into this.
Thank you for all your feedback!

stay tuned about PR

**Comment by chrylis** [comment]
Thanks! I ran into a database meltdown on our application, so I've been distracted from the PR for a couple of days, but I'm happy to get back to it if practical. That said, I know you're trying to get 6.0 GA.
