### ISSUE TITLE
Change default MessagingGateway bean name in 6.0

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-integration#3926]
Currently, if `@MessagingGateway` is applied without a `name` parameter, Spring Integration applies the convention of camel-casing the interface's simple name. This convention is prone to collisions; for example, I have an interface `DeliverSink` that I've been retrofitting, and in the process I ended up trying to also name its channel `deliverSink` and the `@Bean IntegrationFlow deliverSink`, leading to the predictable failures.

Spring Boot moved to using the FQCN for `@ConfigurationProperties` and similar automatically-declared beans. As autowiring by type is now the usual style, I suggest changing the default name for declarative gateways to be the FQCN in Spring Integration 6.0. This would be a breaking change but adaptable for applications that need the old behavior by adding the `name` parameter.

**Comment by artembilan** [comment]
I don't think it is valid to compare a `@MessagingGateway` with a `@ConfigurationProperties`.
The `@Component` and its infrastructure is what we have to rely on.
See the javadocs for the `FullyQualifiedAnnotationBeanNameGenerator`:

```
 * An extension of {@code AnnotationBeanNameGenerator} that uses the fully qualified
 * class name as the default bean name if an explicit bean name is not supplied via
 * a supported type-level annotation such as {@code @Component} (see
 * {@link AnnotationBeanNameGenerator} for details on supported annotations).
 *
 * <p>Favor this bean naming strategy over {@code AnnotationBeanNameGenerator} if
 * you run into naming conflicts due to multiple autodetected components having the
 * same non-qualified class name (i.e., classes with identical names but residing in
 * different packages).
 *
 * <p>Note that an instance of this class is used by default for configuration-level
 * import purposes; whereas, the default for component scanning purposes is a plain
 * {@code AnnotationBeanNameGenerator}.
```

Therefore so far we are good for our result from the `@IntegrationComponentScan` and only will use another strategy when we already implement an `@Import` support for these interfaces.

It was like that from day first, so it even better to look at this opposite: if you have  conflict, use a `name` attribute.
What feels annoying for you, might not be what would be expected to be broken for others.

**Comment by chrylis** [comment]
I can see the reasoning for following the upstream's different naming strategies for component-scanned and `@Import`ed beans. At the moment, the registrar does not provide a mechanism to change naming strategy; it's hard-coded (because it's only applied to `@IntegrationComponentScan`). Should I investigate making this configurable? If so, would it be best to do it at the level of the registrar instance or by making a new method overload?

**Comment by artembilan** [comment]
The `ImportBeanDefinitionRegistrar` has another method:
```
	default void registerBeanDefinitions(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry,
			BeanNameGenerator importBeanNameGenerator) {
```
we can override in the `MessagingGatewayRegistrar`.
As well as propagate from the same method impl in the `IntegrationComponentScanRegistrar`.

And therefore in the end the `@IntegrationComponentScan` must expose a new attribute:
```
	Class<? extends BeanNameGenerator> nameGenerator() default BeanNameGenerator.class;
```
Exactly the same what we have so far in the `@ComponentScan`.

**Comment by artembilan** [comment]
If you are OK with my conclusion, I can start working on this.
And the feature about custom `BeanNameGenerator` may even make it into `5.5.x`.
I even see that we may not expose a `nameGenerator()` since the `AnnotationConfigApplicationContext` can be configured respectively:
```
	/**
	 * Provide a custom {@link BeanNameGenerator} for use with {@link AnnotatedBeanDefinitionReader}
	 * and/or {@link ClassPathBeanDefinitionScanner}, if any.
	 * <p>Default is {@link AnnotationBeanNameGenerator}.
	 * <p>Any call to this method must occur prior to calls to {@link #register(Class...)}
	 * and/or {@link #scan(String...)}.
	 * @see AnnotatedBeanDefinitionReader#setBeanNameGenerator
	 * @see ClassPathBeanDefinitionScanner#setBeanNameGenerator
	 * @see AnnotationBeanNameGenerator
	 * @see FullyQualifiedAnnotationBeanNameGenerator
	 */
	public void setBeanNameGenerator(BeanNameGenerator beanNameGenerator) {
```
