### ISSUE TITLE
Consider adding request attribute support for webclient in webflux integration

### ISSUE THREAD

**Issue by saxenaj** [spring-projects/spring-integration#3936]
**Expected Behavior**
It seems like webflux integration doesnt support for request attributes.

**Current Behavior**
Currently below code line up creating new DefaultRequestBodyUriSpec on every call
[WebFluxRequestExecutingMessageHandler](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-webflux/src/main/java/org/springframework/integration/webflux/outbound/WebFluxRequestExecutingMessageHandler.java#L223)

Even if i pass custom webclient which has all the attributes added, above implementation ignores existing attributes in webclient.

**Context**
I am passing request attributes which is getting used in exchangefilter to influence the flow. This request attribute is of type String as Key and Value as a user defined object. 

My expectation is to pass this information in request attributes so that it will eventually available in exchangefilter for further processing but i dont find a way to pass these request attribute in webflux integration.

There is a workaround to pass required information in headers but headers only support String key value pair. It become difficult to pass information in format of String as key and user defined object as value.

As a workaround,i end up creating my own requestexecutingmessagehandler by extending [WebFluxRequestExecutingMessageHandler](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-webflux/src/main/java/org/springframework/integration/webflux/outbound/WebFluxRequestExecutingMessageHandler.java#L223) and adding required attributes.

**Comment by artembilan** [comment]
For more context: https://stackoverflow.com/questions/74215136/how-to-add-request-attribute-through-spring-webflux-integration-for-outbound-gat.

@saxenaj ,

[the contribution is welcome](https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc)!

I didn't look in details what is to deal with request attributes, but probably they can be resolved by SpEL expression against request message, since it really sounds like request-specific feature.

Thank you!

**Comment by saxenaj** [comment]
Thanks @artembilan for prompt response. I will be happy to contribute.
I am planning to add a new attribute in webflux schema for outbound gateway which is similar to uri-variable-expression.  

Here user can pass a map which contain key-value pair which needs to be set in request attribute in the outbound configuration xml.

In [WebFluxRequestExecutingHandler](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-webflux/src/main/java/org/springframework/integration/webflux/outbound/WebFluxRequestExecutingMessageHandler.java#L17) , i will be evaluating using StandardEvaluationContext which is already present in application context and generates a map with key value pairs and eventually this map will be set as request attributes.
Let me know if it sounds reasonable.

**Comment by artembilan** [comment]
Yep! Sounds good. With only one remark that this must not be a map of expression, but more like a single expression which has to be evaluate into a `Map<String, Object>`.
I mean, please, don't follow the logic we have in the `AbstractHttpRequestExecutingMessageHandler` for `uriVariablesExpression`.
It is more like what we have now in the `GraphQlMessageHandler` for the `variablesExpression`.

**Comment by saxenaj** [comment]
Ok!! I believe this is what you are referring to with [VariablesExpression](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-graphql/src/main/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandler.java#L169). In this example,i see that [SupplierExpression ](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-graphql/src/main/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandler.java#L56) is provided with null. In webflux outbound scenario, are we expecting user to provide the supplierExpression. Also can you pls give me an example of single expression(probably with String Key and custom object as Value) which will evaluate to Map<String, Object> using SupplierExpression. I was trying to find in Spring integration code and didnt find any.

**Comment by artembilan** [comment]
No-no. don't jump too deep in details of that `GraphQlMessageHandler`: the `new SupplierExpression<>(() -> null)` is just a default "no value" expression.
Of course end-user is going to set anything else into the `setAttributesExpression(Expression attributesExpression)`.
Any `Expression` impl is valid. Mostly we really talk about a SpEL, which is going to be supplied from the mentioned XML config.
Here you can find docs about SpEL and its map support: https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#expressions-inline-maps.

**Comment by saxenaj** [comment]
Hi @artembilan - I have went through the contribution guide and created a PR for this issue https://github.com/spring-projects/spring-integration/pull/3950. 
Pls review it and let me know if there are any changes needed.
