### ISSUE TITLE
Transformer output-channel bean could not be found

### ISSUE THREAD

**Issue by tksarul** [spring-projects/spring-integration#3953]
Spring Boot `3.0.0`

```
@Gateway(requestChannel = "integration.student.gateway.channel" )
public String processStudent(Student student);

 @Bean
 @Transformer(inputChannel = "integration.student.gateway.channel", outputChannel = "integration.student.objectToJson.channel")
  public ObjectToJsonTransformer objectToJsonTransformer() {
      return new ObjectToJsonTransformer(new Jackson2JsonObjectMapper(new ObjectMapper()));
  }
```
Console error on server startup:
```
Description:
A component required a bean named 'integration.student.objectToJson.channel' that could not be found.
Action:
Consider defining a bean named 'integration.student.objectToJson.channel' in your configuration.
```

Same code works well at Spring Boot `2.7.6`

**Comment by artembilan** [comment]
Confirmed.
There is a new algorithm for messaging annotations on `@Bean` and looks like we have missed the fact to post-pone channel resolutions until after start of the application:
```
			new BeanDefinitionPropertiesMapper(handlerBeanDefinition, annotations)
							.setPropertyValue(SEND_TIMEOUT_ATTRIBUTE)
							.setPropertyReference("outputChannel")
							.setPropertyReference("defaultOutputChannel");
```
That `propertyReference("outputChannel")` will try to find a bean during injection and I guess you really don't have such a bean in your configuration and it is create later on via some `@ServiceActivator(inputChannel = "integration.student.objectToJson.channel")`.
Will fix it shortly.

Thank you for feedback!

(It is sad to see these kind of issue after GAs when we really are asking to try new version with our RCs: https://spring.io/blog/2022/10/25/spring-integration-6-0-0-rc1-available)
