### ISSUE TITLE
WebFluxOutboundChannelAdapterParser silently ignores encoding-mode attribute if web-client attribute is present

### ISSUE THREAD

**Issue by aljopainter** [spring-projects/spring-integration#3954]
**In what version(s) of Spring Integration are you seeing this issue?**

2.7.1 but I believe that 6.0.0 also has this problem

**Describe the bug**

When the ```web-client attribute``` is included in the declararation of a ```webflux:outbound-gateway``` using XML namespace support, the ```encoding-mode``` attribute will be ignored silently because the encoding mode from the ```UriBuilderFactory``` of the ```web-client``` will be used instead.

**To Reproduce**

Include an ```encoding-mode``` attribute and a ```web-client``` with a different ```encoding-mode``` within the ```UriBuilderFactory```.

**Expected behavior**

An error or warning to signal that ```encoding-mode``` is ignored.

**Sample**

Similar to https://github.com/spring-projects/spring-integration/pull/3939

**Comment by artembilan** [comment]
Thank you for reporting this, @aljopainter !

Feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc.

**Comment by aljopainter** [comment]
I'll give it a shot.

**Comment by artembilan** [comment]
@aljopainter ,

any progress on this?
Apparently we are going to release `5.5.16` next Tuesday.
Probably would be great to have this in.

Thank you!

**Comment by artembilan** [comment]
Taking this myself: not time to wait for external contribution.
