### ISSUE TITLE
FTPInboundChannelAdapter: Incorrect file modification time if FTP server time zone differs from local time zone

### ISSUE THREAD

**Issue by sebastianhaberey** [spring-projects/spring-integration#3965]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.15

**Describe the bug**

If the FTP server has a different time zone than the local system, the received file will have the date / time of the file on the server, and the time zone of the local system.

Example:

* FTP Server time zone: Australia/Brisbane 
* Local time zone: Europe/Berlin
* Creation time of file on server: `2022-12-10T00:32+01:00[Australia/Brisbane]`
* Creation time of file downloaded by FTPInboundChannelAdapter: `2022-12-10T00:32+01:00[Europe/Berlin]`

**To Reproduce**

I have attached a small sample project that starts an FTP server via Docker / Testcontainers, uploads a test file, then downloads the file.

**Expected behavior**

The received file should have the correct creation time.

**Sample**

[sample.zip](https://github.com/spring-projects/spring-integration/files/10195960/sample.zip)

**Comment by artembilan** [comment]
Our logic in the `FtpInboundFileSynchronizer` is like this:
```
	protected long getModified(FTPFile file) {
		return file.getTimestamp().getTimeInMillis();
	}
```

What is your idea how ti fix it?
I'm not good with time zones: what should we do to calculate it properly?

That `file.getTimestamp()` return a `Calendar` instance which has a property like `getTimeZone()`.
Not sure how, but this might help us.

Thank you and looking forward for your insight!

**Comment by sebastianhaberey** [comment]
I believe the `Calendar` instance in the FTPFile is already incorrect. So my guess is the issue happens earlier when the FTPFile is created from the raw information received from the FTP server.

Unfortunately I don't know much about the FTP protocol. If we get something like "2022-12-10T00:32:00" from the FTP server, we're out of luck since that means something different depending on the server's time zone.

If we get the creation time as a unix timestamp in milliseconds (long value), that would be good, because that's an absolute point in time and can be converted to local time easily.

**Comment by artembilan** [comment]
OK. I have no idea what you are looking for as a the fix on Spring Integration level then.

See if `FTPClientConfig` set into `DefaultFtpSessionFactory` where we produce an `FTPClient` helps you somehow to mitigate the mentioned discrepancy with time zones.
There is this property for our consideration then:
```
    /**
     * <p>
     * setter for the serverTimeZoneId property.  This property
     * allows a time zone to be specified corresponding to that known to be
     * used by an FTP server in file listings.  This might be particularly
     * useful to clients such as Ant that try to use these timestamps for
     * dependency checking.
     * </p><p>
     * This should be one of the identifiers used by
     * <code>java.util.TimeZone</code> to refer to time zones, for example,
     * <code>America/Chicago</code> or <code>Asia/Rangoon</code>.
     * </p>
     * @param serverTimeZoneId The serverTimeZoneId to set.
     */
    public void setServerTimeZoneId(final String serverTimeZoneId) {
```

**Comment by sebastianhaberey** [comment]
Yes, you are right. I debugged this deep into `org.apache.commons.net.ftp.parser.UnixFTPEntryParser#parseFTPEntry` and the information received from the FTP server looks like this:

`-rw-r--r--    1 1000       ftpgroup            0 Dec 10 01:46 foo.txt`

I see no way of getting an absolute timestamp from this. I think manually setting the `serverTimeZoneId` property is the way to go. Thank you for your input! I am closing this because it's not a Spring Integration issue.
