### ISSUE TITLE
RecordFilterStrategy with int-kafka:message-driven-channel-adapter

### ISSUE THREAD

**Issue by ViacheslavProshkin** [spring-projects/spring-integration#3966]
I found out that I can't use `RecordFilterStrategy` when I create `KafkaMessageDrivenChannelAdapter` through xml configuration, i.e. `<int-kafka:message-driven-channel-adapter> `. 
Still I can inject it via usual `<bean>`.

2.3.1.RELEASE

**Comment by artembilan** [comment]
Spring Integration Kafka extension project is out of support already for a while.
See its README and respective mentioning of migrating to Spring Integration module.
See our support policy: https://spring.io/projects/spring-integration#support.
Therefore we will do the fix, but only for the currently supported `6.0.x` and `5.5.x` versions.
