### ISSUE TITLE
IntegrationObjectSupport.conversionService property has flipped access modifiers

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-integration#3968]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.14

**Describe the bug**

In `IntegrationObjectSupport`, most of the properties have public setters (for external configuration) and protected getters. However, the `conversionService` property has this reversed: The setter is protected but the getter is public. I am wanting to externally set the `conversionService` on a channel adapter (specifically SNS, because I want to customize the JSON formatting but after the adapter has evaluated expressions against the payload POJO), but the property isn't visible unless I subclass it. Based on the other dependency properties, this appears to be a typo in the declarations.

**Comment by artembilan** [comment]
I don't think we need to worry about making getter as `protected`: having it as `public` does not hurt
But I definitely agree that setter has to become `public`.

Feel from to contribute the fix!

As a side effect: I'm not sure what you talk about JSON formatting and this `ConversionService` relationship.
Would you mind to share more info: I just don't understand how `ConversionService` helps in JSON formatting...
Thanks

**Comment by chrylis** [comment]
I wish to supply my own custom-configured Jackson converter for SNS operations. The only two ways I can see to do this are to provide a named bean and invoke it from the `bodyExpression` or to provide a `ConversionService` with a custom Jackson mapper.

**Comment by artembilan** [comment]
Hm. OK. You know it might be better to separate concerns and have a transformer upfront which would do that JSON serialization: https://docs.spring.io/spring-integration/docs/current/reference/html/message-transformation.html#json-transformers

**Comment by chrylis** [comment]
> Hm. OK. You know it might be better to separate concerns and have a transformer upfront which would do that JSON serialization: https://docs.spring.io/spring-integration/docs/current/reference/html/message-transformation.html#json-transformers

That was my first attempt, but doing that results in a payload type of `String` by the time the `SnsMessageHandler` sees the message, so the structured properties are not available for setting as message attributes or (now) group and deduplication IDs.

**Comment by artembilan** [comment]
I'm not sure why do you need to do that?
The logic there is like this:
```
			if (this.bodyExpression != null) {
				snsMessage = this.bodyExpression.getValue(getEvaluationContext(), message);
			}

			if (snsMessage instanceof SnsBodyBuilder) {
				publishRequest.withMessageStructure("json").setMessage(((SnsBodyBuilder) snsMessage).build());
			}
			else {
				publishRequest.setMessage(getConversionService().convert(snsMessage, String.class));
			}
```
So, if no `bodyExpression`, and `payload` is not an `SnsBodyBuilder`, we set the provided payload after converting to `String`, where string to string is indeed string.
What do I miss?

**Comment by chrylis** [comment]
I want to pass a payload of type `BusinessObject` to the handler so that I can use its properties in `topicArnExpression`, `messageGroupIdExpression`, and `messageDeduplicationIdExpression`, but then I want to customize the JSON serialization. I suppose that what I really want is the ability to provide a `Function<BusinessObject, String> bodyFormatter`, but the code path for converting `BusinessObject` into `String` uses either a SpEL expression with a context that I can't modify or a `ConversionService` call.

**Comment by artembilan** [comment]
Right, I see: first get access to all the attributes from the `BusinessObject` then transform to some JSON for body.
So, IO believe that is what a `this.bodyExpression` is for: you declare an `ObjectMapper` bean anyway or take it from Spring Boot auto-configuration.
And then in that `bodyExpression` you do a simple call: `@objectMapper.writeValueAsString(payload)`:
```
	/**
	 * The {@link Expression} to produce the SNS notification message. If it evaluates to
	 * the {@link SnsBodyBuilder} the {@code messageStructure} of the
	 * {@link PublishRequest} is set to {@code json}. Otherwise, the
	 * {@link #getConversionService()} is used to convert the evaluation result to the
	 * {@link String} without setting the {@code messageStructure}.
	 * @param bodyExpression the {@link Expression} to produce the SNS notification
	 * message.
	 */
	public void setBodyExpression(Expression bodyExpression) {
```

**Comment by chrylis** [comment]
That's just what I was meaning: It requires a "global variable". I'm trying to build microservices client libraries that encapsulate predefined `IntegrationFlow` endings for specific message-driven applications, and I don't want to pollute the Spring context or risk bean collisions. The `Transformers.toJson(mapper)` flow step is useful and configurable, but it prevents the `SnsMessageHandler` from being able to use business properties, and it also makes auto-configuration of mappings much more difficult.

**Comment by artembilan** [comment]
There is a `org.springframework.integration.expression.FunctionExpression` for your consideration.
So, that `bodyExpression` could be configured as `setBodyExpression(new FunctionExpression<Message<?>>(m -> ...))`.

**Comment by chrylis** [comment]
I had not seen that adapter before, and I think it is exactly what I'm looking for. It might be worth looking at inverting the interfaces over the life of Spring Integration 6 to eventually have `ExpressionEvaluation implements Function`.

**Comment by garyrussell** [comment]
>It might be worth looking at inverting the interfaces...

That would be a huge undertaking (for little benefit IMHO); there are hundreds of such expressions used in the framework.

Furthermore, there are many expressions where `#variable`s are available (in addition the the `Message<?>` as the root expression evaluation object. Those use cases would require significant rework to convert them to functions.
