### ISSUE TITLE
Sftp Session cannot open directory from the absolute path

### ISSUE THREAD

**Issue by jonchngau** [spring-projects/spring-integration#3974]
**In what version(s) of Spring Integration are you seeing this issue?** 6.0.0

**Describe the bug**
After upgrading to 6.0.0,
When using spring integration with sftp inbound, there is exception of SSH_FX_NO_SUCH_FILE thrown when doing file synchronization from remote to local.
After troubleshooting, it is related to SftpSession.doList()
it is now removing all leading and trailing slash.
So, if I used /a/b/c as remote directory in the synchronization.
remotePath = a/b/c
remoteDir = a/b
remoteFile = c

and it will cause the above error, because it regards remoteDir as relative path.
E.g. if home directory is "/home/user", then it will locate /home/user/a/b instead of /a/b

I have tried to extends the DefaultSftpSessionFactory and SftpSession,
it works normally after i change the following code

`String remotePath = StringUtils.trimTrailingCharacter(StringUtils.trimLeadingCharacter(path, '/'), '/');`

to

`String remotePath = StringUtils.trimTrailingCharacter(path, '/');`

Please advice the purpose of trim leading slash.

**To Reproduce**

login to sftp server with remote directory not under home directory

**Expected behavior**

sftp inbound or outbound to directory outside home directory should be supported.

**Comment by artembilan** [comment]
> login to sftp server with remote directory not under home directory

How to do that please?
How user can navigate into remote dir not under his/her `home`?
Any code to let us to reproduce?

Thanks

**Comment by artembilan** [comment]
OK. I think I see what you mean.
The `ChannelSftp` has the logic like this:
```
  private String remoteAbsolutePath(String path) throws SftpException{
    if(path.charAt(0)=='/') return path;
    String cwd=getCwd();
//    if(cwd.equals(getHome())) return path;
    if(cwd.endsWith("/")) return cwd+path;
    return cwd+"/"+path;
  }
```
So, if we have a leading `/`, it was treated as an absolute path.
Otherwise we navigates it into a user home as relative one.

Need to revise what we have so far with this new `SftpClient`...

**Comment by artembilan** [comment]
Proposal: https://github.com/spring-projects/spring-integration/pull/3976.

This report is another sample to question a report why do we release milestones and release candidates before going GA?
What does stop some of you to follow our requests and test your solution on early stages: https://spring.io/blog/2022/10/25/spring-integration-6-0-0-rc1-available ?
