### ISSUE TITLE
MessagingGatewaySupport.handleSendAndReceiveError() loses (i.e. "throws away") current header information

### ISSUE THREAD

**Issue by altruie** [spring-projects/spring-integration#3997]
**In what version(s) of Spring Integration are you seeing this issue?**

6.0.2

**Describe the bug**

A _subflow_ has returned a `MessagingException` which contains a message with headers that correspond to the state at the time of the creation of the exception, including the `history` header that gives the history up to that point in the flow.  The method `MessagingGatewaySupport.handleSendAndReceiveError()` "_throws away_" this information in favour of the `headers` in the `requestMessage` at the time of the call to the gateway, apparently because the `replyChannel` and/or `errorChannel` in the subflow `error` will not be current.

		else {
			Throwable errorToReThrow = error;
			if (error instanceof MessagingException &&
					requestMessage != null && requestMessage.getHeaders().getErrorChannel() != null) {
				// We are in nested flow where upstream expects errors in its own errorChannel header.
				errorToReThrow = new MessageHandlingException(requestMessage, error);
			}
			rethrow(errorToReThrow, "gateway received checked Exception");
			return null; // unreachable
		}
	}

**To Reproduce**

1. Enable `message history`
2. Configure a flow **A** that makes a gateway call to another flow **B**, setting the `error-channel` on **A** to a channel `myErrorChannel`
3. Configure the flow **B** to call a transformer
4. The message that arrives at the transformer will have the `history` header containing the `transformer` as last item
5. The transformer throws an exception
6. The message that arrives at `myErrorChannel` will not have the `transformer` item in the items in the`history` header

**Expected behavior**

Rather than "_throw away_" all of the subflow headers in `errors`, can set `errorChannel` and `replyChannel` headers to be current but retain the other headers from the `error` exception.

**Sample**

**Comment by artembilan** [comment]
I'd be glad to see some simple project to reproduce an issue, but it feel like a duplication of https://github.com/spring-projects/spring-integration/issues/3984.

The `DefaultErrorMessageStrategy` does not copy headers from a failed message.
I think if you look into a `MessagingException` payload of that `ErrorMessage` in your `myErrorChannel`, you'll see a `failedMessage` property which would have an expected history.

While it may be treated as a bug, it behaves like this for years.
Therefore I look into this as an improvement in next version with possible breaking change to deal with in the end.

Let us know your thoughts and we will close this one respectively!

**Comment by altruie** [comment]
I agree that they are similar but perhaps intervening in different circumstances.

The part of `MessagingGatewaySupport.handleSendAndReceiveError()` that I extracted in the original post executed in a case where the `DefaultErrorMessageStrategy` is not invoked -- when the gateway has an `errorChannel` defined, if I understand correctly.  So perhaps the "enhancement" (as opposed to "bug") would need to applied in both cases .. in the `DefaultErrorMessageStrategy` #3984 and in #3997 the `handleSendAndReceiveError()` for the areas that do not use the `ErrorMessageStrategy`.  

I'm looking at making a simple example project to demonstrate.

**Comment by artembilan** [comment]
The part you show has nothing to do with `errorChannel`. It really is executed when no `errorChannel` configured and that `MessageHandlingException` is thrown up. 
So, then your concern is not clear: how message history can be preserved if we don't send any messages but rather throw an exception?
And well: all the requested info is really there in that `MessageHandlingException.failedMessage`.
So, what do I miss from the code you are pointing to?

**Comment by altruie** [comment]
Apologies, I mistakenly wrote ***when that gateway has an errorChannel defined*** when effectively, as you mention, this is when no `errorChannel` is configured. 

The method `handleSendAndReceiveError()` receives for the `error` argument a `MessageTransformationException` which contains a `failedMessage` with the `headers` at the time of the exception.  The following code encapsulates the `MessageTransformationException` within a `MessageHandlingException`:

		Throwable errorToReThrow = error;
		if (error instanceof MessagingException &&
				requestMessage != null && requestMessage.getHeaders().getErrorChannel() != null) {
			// We are in nested flow where upstream expects errors in its own errorChannel header.
			errorToReThrow = new MessageHandlingException(requestMessage, error);
		}
		rethrow(errorToReThrow, "gateway received checked Exception");

I'm just realizing (having checked in debugging) that I have the original `MessageTransformationException` available in the `cause` of the `MessageHandlingException`, so I can pull it out of the `cause` chain.  

Thanks very much, this has cleared things up for me.  I'm happy to close out the faux-bug.

**Comment by artembilan** [comment]
Yes. I see what you mean, but for preserving context of the error we cannot just re-throw your `MessageTransformationException` at that point as is.
We are in context of the `requestMessage` and error we got here is really related to it.
Therefore for a proper stack trace we raise a `new MessageHandlingException(requestMessage, error)`.
You still got your info, though, down the stack trace, in the `cause`.
