### ISSUE TITLE
Reusing of MQTT connection (clientId) results in error log "... Never happens."

### ISSUE THREAD

**Issue by aretap** [spring-projects/spring-integration#4014]
This issue is slightly realated to GH-3685 (https://github.com/spring-projects/spring-integration/issues/3685).

I am trying to use one MQTT connection with a single clientId for subscriber as well as publisher channels.

Problem is that in <tt>MqttConnectOptions</tt> is the timeout specified in *seconds* while in <tt>org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(long)</tt> is expected in *milliseconds*.

<pre>
MqttConnectOptions.setConnectionTimeout(int seconds)
client.connect(this.connectionOptions).waitForCompletion(long milliseconds)
</pre>

So calling:

<pre>
Mqttv3ClientManager.start() {
  ...
  client.connect(this.connectionOptions).waitForCompletion(this.connectionOptions.getConnectionTimeout());
  ...
}
</pre>

times out very quickly (default seems to be 30 seconds but they actually time out in 30 milliseconds) and an attempt to call the <tt>reconnect()</tt> method is made even though the connection is still becoming connected. That results in:

<pre>
17:17:04,334 ERROR [main] o.s.i.m.c.Mqttv3ClientManager:110 MQTT client failed to connect. Never happens.
Connect already in progress (32110)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1399)
        at org.springframework.integration.mqtt.core.Mqttv3ClientManager.start(Mqttv3ClientManager.java:107)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
</pre>

This just prints the error message in log, but the connection seems to be established without further problems and the application works.

**Comment by artembilan** [comment]
Yeah... That's a bug: we must not use `getConnectionTimeout()` for `waitForCompletion()`.

Possible better to introduce `completionTimeout` to the `ClientManager` API like we have in channel adapters.

Feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc !

**Comment by aretap** [comment]
I was thinking about just simply converting the <tt>getConnectionTimeout()</tt> from *seconds* to *milliseconds* before passing it to the <tt>waitForCompletion(long millis)</tt> method which, actually, waits for the connection to become estabilished to the server as specified in the <tt>MqttConnectOptions.setConnectionTimeout(int)</tt> method contract (JavaDoc) *"... time interval the client will wait for the network connection to  the MQTT server to be established"*. So it seems to me okay to use that timeout value in the <tt>waitForCompletion(long millis)</tt> method when connecting to the MQTT Broker server during the application startup.

<pre>
	/**
	 * Sets the connection timeout value. This value, measured in seconds, defines
	 * the maximum time interval the client will wait for the network connection to
	 * the MQTT server to be established. The default timeout is 30 seconds. A value
	 * of 0 disables timeout processing meaning the client will wait until the
	 * network connection is made successfully or fails.
	 * 
	 * @param connectionTimeout
	 *            the timeout value, measured in seconds. It must be &gt;0;
	 */
	public void setConnectionTimeout(int connectionTimeout) {
        ...
	}
</pre>

Are you sure that introducing a new <tt>completionTimeout</tt> constant in the <tt>ClientManager</tt> API is the way to go?

**Comment by aretap** [comment]
You are right that the <tt>diconnectForcibly(long)</tt> method is exactly the same use-case of the error. You are also right that the same use-case is in the <tt>Mqttv5ClientManager</tt> class. That makes it four problematic places now.

If I look at the <tt>MqttPahoMessageDrivenChannelAdapter</tt> class and how the <tt>getCompletionTimeout()</tt> method is used there for connecting/disconnecting and subscribing/unsubscribing, it seems to me legitimate to re-use the <tt>getConncetionTimeout()</tt> method for both, connecting and diconnecting to the MQTT server *after the values are correctly converted to the target method time units.*

**Comment by artembilan** [comment]
So, to make ourselves on the same page: do you suggest to fix both `ClientManager` impls to use that `getConncetionTimeout()` for all the use-case and with a proper converting to milliseconds?
On the other hand it sounds like you suggest to deprecate `getCompletionTimeout()` (and therefore `disconnectCompletionTimeout` as well) in favor of just  `getConncetionTimeout()`  in the `AbstractMqttMessageDrivenChannelAdapter` and in the and in the `AbstractMqttMessageHandler`?

Looks like in the `Mqttv5PahoMessageDrivenChannelAdapter` we do use a `getCompletionTimeout()` for disconnect as well though...
Therefore there was really a reason in those extra properties since in the end they don't rely on a `conncetionTimeout` in the Paho client.
So, don't we need instead just introduce a `completionTimeout` into a `ClientManager` API for safety and consistency with the Paho client?
I might agree about deprecating a `disconnectCompletionTimeout` since in the end that has to just a `completionTimeout` either way.
But about reusing `conncetionTimeout` for everything I'm in doubt yet...

**Comment by aretap** [comment]
I hear you when you look at it from the higher perspective than me in the beginning. Now it sounds reasonable to me to introduce a <tt>completionTimeout</tt> property to the <tt>ClientManager</tt>.

About deprecating the <tt>disconnectCompletionTimeout</tt>... I don't mind either way. The focus here should be on keeping the consistency.

**Comment by artembilan** [comment]
Sure! So, we go this route then:

1. Introduce `completionTimeout` into a `ClientManager` abstraction and fix inappropriate usages of the `conncetionTimeout` over there.
2. Deprecate a `disconnectCompletionTimeout` in favor of `completionTimeout` for consistency with other similar places.

Contribution is welcome!

**Comment by aretap** [comment]
Ah, sorry guys, for coming too late with solving this issue...
