### ISSUE TITLE
Document the various time-out attributes and how they apply inside/outside of chains [INT-2217]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#6199]
**[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert)** opened **[INT-2217](https://jira.spring.io/browse/INT-2217?redirect=false)** and commented

Components can have various attributes defined in the XML schema regarding "time-outs" e.g.:

-send-timeout
-receive-timeout
-timeout
-request-timeout
-reply-timeout
-default-request-timeout
-default-reply-timeout

How should they to be used? Which are available inside and outside of chains?

e.g. special case Routers:

'router is different I guess since it must be the last component in the chain - and the channels it sends to would be outside of the chain itself'

Create a dedicated chapter in the reference manual to provide a common overview regarding timeouts in SI.

---

**Affects:** 2.1 M3

**Issue Links:**
- #6198 For Enrichers that define 'request-' and 'reply-channel' attributes - add: 'request-timeout' and 'reply-timeout' attributes

**Comment by artembilan** [comment]
I think we can treat this as fixed even if we don't have a dedicated chapter for timeouts.

Here is the router doc: https://docs.spring.io/spring-integration/docs/current/reference/html/message-routing.html#router-common-parameters
Here is a `@MessagingGateway`: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#gateway-timeouts
The `receiveTimeout` explanation: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#endpoint-pollingconsumer
Also see, for example: https://docs.spring.io/spring-integration/docs/current/reference/html/amqp.html#amqp-inbound-channel-adapter and similar channel adapters chapters with their own explanation for timeouts.
