### ISSUE TITLE
Add support to <object-to-map-transformer> for reference of 'object-mapper' [INT-2341]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#6321]
**[Artem Bilan](https://jira.spring.io/secure/ViewProfile.jspa?name=abilan)** opened **[INT-2341](https://jira.spring.io/browse/INT-2341?redirect=false)** and commented

Now **ObjectToMapTransformer** uses **Jackson ObjectMapper** for transformation 'payload' to String and the same - to the Map.
It should support injection of an ObjectMapper as well as \<object-to-json-transformer>.

---

**Affects:** 2.1 RC2

**Comment by artembilan** [comment]
Duplicate of https://github.com/spring-projects/spring-integration/issues/8257
