### ISSUE TITLE
Doc: For Gateways improve documentation of the various timeout settings [INT-2849]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#6822]
**[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert)** opened **[INT-2849](https://jira.spring.io/browse/INT-2849?redirect=false)** and commented

* Provide various Use-Case Samples: How do request- and reply-timeouts apply when using Direct vs QueueChannels
* Add a note that users should not set the reply-timeout attribute when using a DirectChannel-based reply channel
* Consider creating a Jira for logging a warning if users configure a gateway with a reply-timeout attribute when using a DirectChannel-based reply channel

---

**Affects:** 2.2. GA

**Reference URL:** http://forum.springsource.org/showthread.php?133010-Behaviour-of-the-default-reply-timeout-of-the-int-gateway

**Comment by artembilan** [comment]
I find this as fixed in the: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#gateway-timeouts
