### ISSUE TITLE
Create a RemoteFileSplitter [INT-3222]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#7197]
**[Gary Russell](https://jira.spring.io/secure/ViewProfile.jspa?name=grussell)** opened **[INT-3222](https://jira.spring.io/browse/INT-3222?redirect=false)** and commented

Use the `RemoteFileOperations.get()` to get a remote (S)FTP file as a Stream and use a pluggable strategy for breaking the stream into chunks (e.g. LF, fixed buffer size).

Include the ability to preProcess the stream (e.g. GUnzip).

---

**Issue Links:**
- #7178 Chunking (S)FTP Reading Endpoint
  (_**"supersedes"**_)

**Comment by artembilan** [comment]
The combination of Streaming Inbound Channel Adapter (see https://docs.spring.io/spring-integration/reference/sftp/streaming.html) and [`FileSplitter`](https://docs.spring.io/spring-integration/reference/file/splitter.html) should do the trick.
A `GUnzip` feature can be achieved with an [`UnZipTransformer`](https://docs.spring.io/spring-integration/reference/zip.html#zip-transformer) in between.

It is better to not combine responsibilities in a single component.
