### ISSUE TITLE
Spring integration service-interface gateway bridge should only forward message initiated by the gateway [INT-3660]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#7619]
**[Aodhagán Collins](https://jira.spring.io/secure/ViewProfile.jspa?name=aigeec)** opened **[INT-3660](https://jira.spring.io/browse/INT-3660?redirect=false)** and commented

I am using Spring integration to launch Spring batch jobs. I have a number of input routes e.g. file polling and http requests. These all route to a batch-int Job Launching Gateway. The referenced Job Launcher has a task executor so job launches are asynchronous. This gateway replies on a specified channel.

This specified channel 'jobLaunchReplyChannel' is pub/sub and has a logger listening to it. This channel is also used as the reply channel for a service-interface gateway.

The issue I am having is that when jobs are requested via sources that are not the gateway (e.g. the poller) the Bridge that is added by gateway throws an exception because no reply channel is set on replies.

---

**Affects:** 3.0.4

**Reference URL:** http://stackoverflow.com/questions/28743577/spring-integration-service-interface-gateway-reply-channel-as-shared-pub-sub

**Comment by artembilan** [comment]
I find this as a duplication of https://github.com/spring-projects/spring-integration/issues/3985.
Same problem - different report.
