### ISSUE TITLE
MQTT is not re-subscribing after reconnect

### ISSUE THREAD

**Issue by iamceph** [spring-projects/spring-integration#8550]
**In what version(s) of Spring Integration are you seeing this issue?**

**6.0.2 with Spring Boot 3.0.2**

**Describe the bug**

When the client loses connection (and auto-reconnect is on) and then reconnects, existing subscriptions are not re-subscribbed. Application restart is needed to re-subscribe.

**To Reproduce**

- Start the sample application
- Connect to the MQTT broker
- Send message
- Stop the MQTT broker
- Start the MQTT broker
- Send message

After the reconnection, no message will appear in the sample application.

**Expected behavior**

I expect to re-subscribe to the topic and receive messages

**Sample**

The sample includes MQTT broker in the `infra` folder.

[Sample Here](https://github.com/iamceph/spring-integration-mqtt-bug).

[Original thread on StackOverflow](https://stackoverflow.com/questions/75404056/spring-integration-mqtt-not-re-subscribing-after-reconnect)

**Comment by artembilan** [comment]
So, the idea is to ignore a `reconnect` param of the `connectComplete()` and always re-subscribe.
