### ISSUE TITLE
Decouple `BeanDefinitionRegistryPostProcessor` implementations

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-integration#8611]
While reviewing [an issue in Spring Framework](https://github.com/spring-projects/spring-framework/issues/30411#issuecomment-1532798212), I've noticed that Spring Integration has BeanDefinitionRegistryPostProcessor implementations that are also doing something else. 

We're considering reviewing this contract so that such post-processors are automatically excluded from AOT processing (as they operation on the bean factory that's pre-processed by it). Can you please review `DefaultConfiguringBeanFactoryPostProcessor` and `MessagingAnnotationPostProcessor` so that they only perform bean definition registry post-processing and nothing else?

**Comment by artembilan** [comment]
Sure! What deadline should we aim this for, please?

**Comment by snicoll** [comment]
If we change something, it will be in Spring Framework 6.1 at the earliest. Thanks!

**Comment by artembilan** [comment]
Reopen for `MessagingAnnotationPostProcessor` part.
