### ISSUE TITLE
Spring integration micrometer make beans their tracing configurable by body/headers

### ISSUE THREAD

**Issue by brianmarting** [spring-projects/spring-integration#8634]
In my application with spring integration with micrometer I have the following flows (the letters are beans): 

- A -> B -> Z
- X -> Y -> Z

For the first flow I want to enable the tracing and observability, but I want no monitoring and tracing for the second flow. This means that bean Z should be enabled for tracing on flow 1 but not on flow 2. When I disable X and Y on my end, I do not see them being traced anymore, but i still see the Z eventually which does not add any value. I also cannot exclude Z since it does add a lot of value in the flow of A and B.
My question now is, could we make this more configurable when looking at the following (just a suggestion):

In spring-integration-core, we have the class `AbstractMessageHandler` with the method `handleMessage` that has the following code:
```java
		if (isObserved()) {
			handleWithObservation(message, getObservationRegistry());
		}
```
where the `isObserved` checks 
```java
	@Override
	public boolean isObserved() {
		return !ObservationRegistry.NOOP.equals(this.observationRegistry);
	}
```

Could we add another or more checks here to enable it depending on e.g. message body/headers?

**Comment by artembilan** [comment]
After some discussion with the team we decided to follow your request and introduce something like `Predicate<Message<?>> observePredicate` option for Spring Integration components.
Exactly those which override that `isObserved()`:
```
AbstractMessageChannel
MessageHandlerSupport
MessageProducerSupport
MessagingGatewaySupport
```

So, in the end you will be able to inject whatever predication is OK for your logic against message that component is handling.
That is going to be to something similar we have so far with a `setObservationConvention()` API so far.

**Comment by brianmarting** [comment]
Seems like I overlooked that, thanks for the help, I'll check it tomorrow 😄

**Comment by brianmarting** [comment]
For future readers, it indeed works as described above, code: 

        observationRegistry.observationConfig()
                .observationPredicate((name, context) -> {
                    if (context instanceof MessageSenderContext messageSenderContext) {
                        return Optional.ofNullable(messageSenderContext.getCarrier())
                                .map(MutableMessage::getHeaders)
                                .map(headers -> !headers.containsKey("SOME HEADER"))
                                .orElse(true);
                    }

                    if (context instanceof MessageReceiverContext messageReceiverContext) {
                        return Optional.ofNullable(messageReceiverContext.getCarrier())
                                .map(Message::getHeaders)
                                .map(headers -> !headers.containsKey("SOME HEADER"))
                                .orElse(true);
                    }

                    return true;
                });
