### ISSUE TITLE
Revise an ExecutorService injections in favor of injected TaskExecutor

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#8642]
Samples are `PostgresChannelMessageTableSubscriber`, `org.springframework.integration.hazelcast.leader.LeaderInitiator`.
These threads potentially can be created as virtual threads with Java 21.

**Comment by artembilan** [comment]
What I don't like with a single managed `TaskExecutor` that threads in different components are going to have same prefix in their names.
It is a bit inconvenient when you trace the logic in the logs.
With the name of a thread dedicated to the specific component it is very clear what is going on.

Probably the whole paradigm of managed executor doesn't bring any value when we switch to virtual threads.
It might really be convenient from microservice perspective when Spring Boot gives us this or that `TaskExecutor` automatically, but for more complex and asynchronous applications like with Spring Integration, it is really misleading to use same prefix name for all virtual threads.

We can continue discussion though since I don't claim to be expert in this area: just sharing my pain over years with single managed executor.

Out of context, but still might be an argument for `TaskExecutor` injection in some places, @tzolov . See, there is an `org.springframework.core.task.support.ExecutorServiceAdapter` for our convenience when we would like to deal with `Future<?> submit()`.

**Comment by garyrussell** [comment]
I didn't mean a single shared TE, each component can get its own.

In any case, as I've said before, unless something has changed, VTs don't get a `name` for logging purposes; I added this property to the listener container:

https://github.com/spring-projects/spring-kafka/issues/2501

**Comment by artembilan** [comment]
Yeah...
The point is that we talk about those components which uses only a single thread, like `LockRegistryLeaderInitiator`.
But yeah, for consistency, a single-threaded `TE` could be used as well.
