### ISSUE TITLE
Fix dependency registration for Messaging annotation parsers

### ISSUE THREAD

**Issue by benmaes** [spring-projects/spring-integration#8654]
**Expected Behavior**

I'm building an application which transfers/transforms messages between TCP and MQTT.
I would like to monitor the connections, to be able to configure some alerts when connections stay down for a certain amount of time/consecutive negative checks.

**Current Behavior**

I implemented multiple @Scheduled methods with a fixed delay of x seconds to check both the status of Tcp and Mqtt connections. For Tcp I'm checking if there are open connections by calling `getOpenConnectionIds()` on either `AbstractClientConnectionFactory` or `AbstractServerConnectionFactory` which works fine and does the job.

I'm trying to do something similar for checking the connection (NOT subscription) with the Mqtt-broker but without success. The most obvious way would be to call the `isConnected()` method on `IMqttAsyncClient` in either `Mqttv5PahoMessageDrivenChannelAdapter` or `Mqttv5PahoMessageHandler`, but since this client has private access, I'm not able to check the connection.

**Context**

Is there any way of achieving this with the existing codebase? If not, would it be possible to:

- provide a getter which returns if the client is connected in both `Mqttv5PahoMessageDrivenChannelAdapter` and `Mqttv5PahoMessageHandler`
```
	public boolean isConnected() {
		return mqttClient.isConnected();
	}

```
- publish internal application events similar to the `TcpConnectionOpenEvent` once the Mqtt client is connected successfully to the broker?

**Comment by artembilan** [comment]
Starting with version `6.0` we have a `ClientManager` abstraction which provides a `getClient()`.
And that one can be used for requested `isConnected()` check.
We also have a bunch of `MqttIntegrationEvent` implementations for your consideration: 
https://docs.spring.io/spring-integration/docs/current/reference/html/mqtt.html#mqtt-events
https://docs.spring.io/spring-integration/docs/current/reference/html/mqtt.html#mqtt-shared-client

Let us know if that works for you!

**Comment by benmaes** [comment]
I'm able to check the connection using the ClientManager, but I see a strange side-effect when publishing to Mqtt. 
On application startup, the `doStart` methods are called in this order `Mqttv5PahoMessageHandler` -> `Mqttv5ClientManager` -> `Mqttv5PahoMessageDrivenChannelAdapter`. 
This means only the adapters are fully functional, but for the handlers, the client that is set in the mqttClient property is null, since the doStart method of the clientmanager was not executed yet and so no client was created.
This causes a nullpointer when trying to publish a method (Mqttv5PahoMessageHandler line 265 -> mqttClient.isConnected() check).

Is there a way to manage the order in which the doStart methods are triggered? That way I can make sure the ClientManagers are started first. Or am I doing something wrong here?

**Comment by benmaes** [comment]
Thanks for the answer. The workaround (putting phase of ClientManager to Integer.MIN_VALUE) works, now the ClientManagers are started first, before the MessageHandlers.

These are the logs WITHOUT the workaround:


```

2023-06-26 09:23:39,808 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor , - Starting beans in phase -2147483648 
2023-06-26 09:23:39,808 [main] TRACE o.s.c.s.DefaultLifecycleProcessor , - Starting bean 'myMqttv5PahoMessageHandler.serviceActivator' of type [org.springframework.integration.config.ConsumerEndpointFactoryBean] 
2023-06-26 09:23:39,808 [main] INFO  o.s.i.endpoint.EventDrivenConsumer , - Adding {message-handler:myMqttv5PahoMessageHandler.serviceActivator} as a subscriber to the 'myMqttOutboundChannel' channel 
2023-06-26 09:23:39,808 [main] INFO  o.s.i.channel.DirectChannel , - Channel 'application.myMqttOutboundChannel' has 1 subscriber(s). 
...
2023-06-26 09:23:39,815 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor , - Starting beans in phase 0 
2023-06-26 09:23:39,816 [main] TRACE o.s.c.s.DefaultLifecycleProcessor , - Starting bean 'myClientManager' of type [org.springframework.integration.mqtt.core.Mqttv5ClientManager] 
2023-06-26 09:23:40,415 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor , - Successfully started bean 'myClientManager' 
```
And here is the config:

```

    @Bean
    public ClientManager<IMqttAsyncClient, MqttConnectionOptions> myClientManager() {
        return new Mqttv5ClientManager(mqttConnectionOptions, "myClientId");
    }

    @Bean
    @ServiceActivator(inputChannel = "myMqttOutboundChannel")
    public Mqttv5PahoMessageHandler myMqttv5PahoMessageHandler(ClientManager<IMqttAsyncClient, MqttConnectionOptions> myClientManager) {
        Mqttv5PahoMessageHandler messageHandler = new Mqttv5PahoMessageHandler(myClientManager);

        messageHandler.setConverter(new StringMessageConverter());
        messageHandler.setDefaultQos(mqttProducerProperties.getQos());

        return messageHandler;
    }

    @Bean
    public MessageChannel myMqttOutboundChannel() {
        return new DirectChannel();
    }

    @Bean
    public TcpInboundGatewaySpec tcpInboundFlow(OnRouteFlowProperties onRouteFlowProperties) {
        return getTcpInboundGatewaySpec(onRouteFlowProperties.getTcpConsumer().getPort());
    }

    private TcpInboundGatewaySpec getTcpInboundGatewaySpec(Integer port) {
        return Tcp.inboundGateway(Tcp.nioServer(port)
                        .id("nioServerId")
                        .deserializer(TcpCodecs.stxetx())
                        .serializer(TcpCodecs.stxetx())
                        .mapper(tcpMessageMapper)
                        .backlog(30))
                .errorChannel("errorChannel")
                .id("tcpInboundGatewayId");
    }


    @Bean
    public IntegrationFlow myFlow(TcpInboundGatewaySpec tcpInboundFlow) {
        return IntegrationFlow.from(tcpInboundFlow)
                .handle(Message.class, (message, headers) -> {
                    String input = new String((byte[]) message.getPayload(), StandardCharsets.UTF_8);

                    log.info(
                            "Incoming message from TCP",
                            StructuredArgumentsUtil.tcpMessageReceived()
                    );

                    myMqttOutboundChannel().send(MessageBuilder
                            .withPayload(getParsedBody(input))
                            .setHeader(MqttHeaders.TOPIC, topic)
                            .setHeader(MqttHeaders.MESSAGE_EXPIRY_INTERVAL, mqttBrokerProperties.getPublishMessageExpiration())
                            .setHeader(Headers.CONTENT_TYPE, Headers.CONTENT_TYPE_JSON)
                            .build());

                    log.info(
                            "Sent message to MQTT",
                            StructuredArgumentsUtil.mqttMessagePublished()
                    );

                    return Tcp.ACK;
                })
                .get();
    }
```

**Comment by artembilan** [comment]
OK. I see. So, the `@ServiceActivator` mechanism doesn't register a dependency between a `ConsumerEndpointFactoryBean` created on the fly with that `@Bean` for `Mqttv5PahoMessageHandler`.
And therefore a dependent `ClientManager` is not started together with that consumer endpoint.

So, I'm treating this as a bug and will fix it soon.

I'll repurpose your issue to respective bug since, essentially, your one has been just a question which we don't handle in issues.
