### ISSUE TITLE
Inconsistent behaviour of FileReadingMessageSource related to the AcceptOnceFileListFilter

### ISSUE THREAD

**Issue by pziobron** [spring-projects/spring-integration#8683]
**In what version(s) of Spring Integration are you seeing this issue?**
 
For example:
 
6.1.2.RELEASE
 
**Describe the bug**
The behaviour of the _FileReadingMessageSource_ is inconsistent when using _AcceptOnceFileListFilter_ and watch service.
More specifically when watch service in the _FileReadingMessageSource_ :
- is set to **false**, the remove method of the _AcceptOnceFileListFilter_ **is not called**
- is set to **true**, the remove method of the _AcceptOnceFileListFilter_ **is called** on DELETE event (in the _WatchServiceDirectoryScanner_: https://github.com/spring-projects/spring-integration/blob/4e464e9ce5129c9098163857ebd62060e8b57e6a/spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java#L543)
 
This is problematic as I would expect the _AcceptOnceFileListFilter_ is controlled by the developer (not by Spring Integration framework).
For example consider the following scenario:
 
1. _FileReadingMessageSource_  is polled with fixed delay of **1ms** (ExecutorChannel is used to process input messages in threads)
2. Watch service is enabled (WatchEvents(CREATE, MODIFY, DELETE)) [DELETE is required here to monitor the directory renaming]
3. _AcceptOnceFileListFilter_ is used in the _ChainFileListFilter_
4. In the end of processing the input file is removed from the disk and the file is removed from the _AcceptOnceFileListFilter_ after that (however there is nothing to remove as the file has been already removed by the code in the _WatchServiceDirectoryScanner_ class)
 
This could cause _the java.io.FileNotFoundException_ when reading that input file, example logs:
`[1] 2023-07-19 15:26:49.175 [pool-2-thread-2] INFO  o.s.i.handler.LoggingHandler - GenericMessage [payload=D:/test/test121.eml, headers={..., timestamp=1689776809154}]`
`....`
`[2] 2023-07-19 15:26:51.358 [scheduling-1] INFO  c.h.m.s.c.g.g.helper.FlowHelper - File [D:/test/test121.eml] has been removed successfully !`
`[3] 2023-07-19 15:26:51.360 [pool-2-thread-3] INFO  o.s.i.handler.LoggingHandler - GenericMessage [payload=D:/test/test121.eml, headers={..., timestamp=1689776811359}]`
`[4] 2023-07-19 15:26:51.367 [pool-2-thread-3] WARN  c.h.m.s.c.g.g.l.LogRetryListener - Error occurred for feed: [reuters], file: [D:/test/test121.eml]! Retry attempt:[1], Error details: [java.io.FileNotFoundException: D:/test/test121.eml (The system cannot find the file specified)]`
 
The problem is that the _WatchServiceDirectoryScanner_ removes the file from the _AcceptOnceFileListFilter_ right after the file is physically removed from the disk. That causes a new message is generated (in the line [3]) which I would like to prevent by using _AcceptOnceFileListFilter_ .
The example code which is handling the file removal (and _AcceptOnceFileListFilter_ filter) after processing:
```java
public IntegrationFlow uncompressFlow(UncompressHandler uncompressHandler) {
        return from(Channels.UNCOMPRESS_CHANNEL)
                .log(m -> format("Uncompressing the file: [%s]", m.getHeaders().get(FileHeaders.FILENAME)))
                .handle(uncompressHandler, e -> e.advice(
                        flowHelper.createRetryAdvice(config.getGlobal().getUncompressRetryConfig())))
                .publishSubscribeChannel(f -> f.subscribe(flowDef -> removeOriginalFileAfterFlow(flowDef, flow -> flow
                        .log(m -> format("The file: [%s] has been uncompressed ! Removing it from the folder: [%s]",
                                m.getHeaders().get(FileHeaders.FILENAME),
                                flowHelper.getSourceFileFrom(m.getHeaders()).getParent()))
                        .nullChannel())))
                .nullChannel();
    }
 
private void removeOriginalFileAfterFlow(IntegrationFlowDefinition<?> flowDef, IntegrationFlow flow) {
    flowDef.publishSubscribeChannel(s -> s
        .subscribe(flow)
        .subscribe(subFlow -> subFlow.delay(DELAY_BEFORE_FILE_DELETION_GROUP_ID, d -> d
                        //To avoid the error: cannot access the file because it is being used by another process
                        .defaultDelay(config.getGlobal().getRemoveOriginalFileDelay()))
                .handle((payload, headers) -> {
                    flowHelper.deleteOriginalFile(headers);
                    return payload;
                }).nullChannel())
        .subscribe(subFlow -> subFlow.delay(DELAY_ACCEPT_ONCE_GROUP_ID, d -> d
                        //To avoid duplicate message to be generated by other thread !
                        .defaultDelay(config.getGlobal().getAcceptOnceRemoveItemDelay()))
                .handle((payload, headers) -> {
                    acceptOnceFileListFilter.remove(headers.get(FileHeaders.ORIGINAL_FILE, File.class));
                    return payload;
                })
                .log(INFO, m -> format("Removed file %s from acceptOnce filter !",
                        m.getHeaders().get(FileHeaders.FILENAME))).nullChannel()));
}
```

 
**To Reproduce**
It is hard to reproduce the issue as it is related to the multithreading processing but it could be done by using the snippets of the code above...
 
**Expected behavior**
 
There are 3 solutions that come to my mind:
 

1. remove the code from the _WatchServiceDirectoryScanner_ which is responsible for removing the file from the _AcceptOnceFileListFilter_: https://github.com/spring-projects/spring-integration/blob/4e464e9ce5129c9098163857ebd62060e8b57e6a/spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java#L5432
2. make it configurable in FileReadingMessageSource (introduce the flag which can be used to prevent removing a file from the _AcceptOnceFileListFilter_)
3. Pass information about the file event type somewhere in the headers so that the message could be dropped in case of DELETE event

Maybe there is another solution to that problem but only these 3 come to my mind for the moment.
Besides, this could be misleading that _AcceptOnceFileListFilter_ is affected in a different way depending on the watch service flag of the _FileReadingMessageSource_. What is Your opinion on that ?

**Comment by artembilan** [comment]
And why just don't remove that:
```
                .handle((payload, headers) -> {
                    acceptOnceFileListFilter.remove(headers.get(FileHeaders.ORIGINAL_FILE, File.class));
                    return payload;
                })
```
logic from your code?

There is no way to react for a DEL event without watch service, therefore your clean up logic would make sense in that case.
Looks like with watch service it is handled by the `FileReadingMessageSource` and we don't need to interact with `AcceptOnceFileListFilter` manually.

We cannot make it conditional in the `FileReadingMessageSource` since you said it yourself: renaming feature works really that way - delete then create.


I'm not sure about your:

> That causes a new message is generated (in the line [3]) which I would like to prevent by using `AcceptOnceFileListFilter`.

Since we just don't emit a message for removed file:
```
			if (StandardWatchEventKinds.ENTRY_DELETE.equals(event.kind())) {
				Path filePath = file.toPath();
				if (this.pathKeys.containsKey(filePath)) {
					WatchKey watchKey = this.pathKeys.remove(filePath);
					watchKey.cancel();
				}
				if (getFilter() instanceof ResettableFileListFilter<File> resettableFileListFilter) {
					resettableFileListFilter.remove(file);
				}
				boolean fileRemoved = files.remove(file);
				if (fileRemoved) {
					logger.debug(() -> "The file [" + file +
							"] has been removed from the queue because of DELETE event.");
				}
			}
```
Pay attention to that `files.remove(file)` which drops just removed file from a collection to produce.

Maybe you are thinking that the file in a renamed directory is the same, but it is not the case for any operation system where the file is identified by its absolute path.
You may consider some custom filter for your chain to identify a file by its content processed.
This way you may skip it even after dir renaming.

Please, confirm also that you really use the mentioned `6.1.2` version.

**Comment by artembilan** [comment]
Yes, please, try with the latest `6.1.2`. We have there a fix like this: https://github.com/spring-projects/spring-integration/commit/208d7bc09a195fcd9af4c261f7ca336cb1a97aca.
Not sure, though, how is that related to your problem.

It would be great to have some simple sample to reproduce how a message is emitted when DELETE event happens.

Maybe that is a side-effect of an `OVERFLOW` event since you say that problem appears only with  thousands of files.

Perhaps our:
```
								if (!StandardWatchEventKinds.ENTRY_MODIFY.equals(kind)) {
									walkedFiles.add(file.toFile());
								}
```
logic in the `walkDirectory()` should skip `ENTRY_DELETE` kind as well?..

**Comment by artembilan** [comment]
Correction. We call that `walkDirectory()` exactly with a `StandardWatchEventKinds.OVERFLOW`, so there cannot be `DELETE` in case of:
```
else if (StandardWatchEventKinds.OVERFLOW.equals(event.kind())) {
	processFilesFromOverflowEvent(files, event);
}
```

Therefore I'd like to hear more from you to determine how is that possible that mesage is emitted for `DELETE` event.

**Comment by pziobron** [comment]
I am going to investigate this in debug mode. However, I am bit busy at the moment as I am releasing the current solution on production - the performance tests were successful. I cannot take a risk and go live with the latest spring integration version untouched (the errors appear from time to time). I am using a slightly modified version of the FileReadingMessageSource class (I've removed the lines responsible for deleting file from the AcceptOnce filter). In the first phase we are going to process only about 60000 files per day but the final goal is to process (detect) about 8 millions of files per day. Obviously, this is temporary workaround (due to the release deadline) and I am determined to solve the problem in the clear and elegant way. I will provide more information about this issue here as soon as it will be possible.

**Comment by pziobron** [comment]
Hello,
I've tried to reproduce the issue related to the extra notification about new file emitted right after file removal. However, I haven't observed this behaviour any more.
I think You can close this issue for now.
