### ISSUE TITLE
Support age (s/ftp) and size over time filters (both file and s/ftp)

### ISSUE THREAD

**Issue by gdupontf** [spring-projects/spring-integration#8691]
**Expected Behavior**

Enhance available file filtering strategies out-of-the-box.

**Current Behavior**

Filtering files based on a last-modified strategy isn't currently possible out-of-the-box.
There are publically-available [possible implementations](https://stackoverflow.com/questions/64628653/lastmodifiedfilelistfilter-for-sftp-inbound-adapter) to consider.
Same deal with watching file size over time.  

**Context**

Such functionality is desirable especially for the numerous cases where one doesn't control the producer side and thus can't use a marker file.
The size-based strategy is, as always, a guard against slow producers and, in the case of SFTP, extreme edge case network slowdowns.
I would expect the size-based strategy to make use of a metadata store, probably.

**Comment by artembilan** [comment]
We don't this as priority, so feel free to contribute.
I don't think this kind of `timestamp` and/or `size` comparison should go to the metadata store.
See our `LastModifiedFileListFilter`, for example.

**Comment by gdupontf** [comment]
I can try to dabble in it when I get the chance.

And look into refactor guidelines to share some logic with the existing filter.

**Comment by artembilan** [comment]
@AdamaSorho ,

this one also should be as straightforward modeling after `LastModifiedFileListFilter` example for (S)FTP and SMB modules.
