### ISSUE TITLE
MongoDbChannelMessageStore ignores Auto Index Creation property

### ISSUE THREAD

**Issue by sdobberstein** [spring-projects/spring-integration#8692]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.1

**Describe the bug**

When starting up the Application the MongoDbChannelMessageStore ignores the `spring.data.mongodb.auto-index-creation` property and goes ahead and automatically creates the indexes.   Looking at the code for `MongoDbChannelMessageStore` and `AbstractConfigurableMongoDbMessageStore` it looks like they both create the indexes in the `afterPropertiesSet()` method without any regard to that property.

The reason it is an issue for us is that we are trying to use it with AWS DocumentDB.   In that case the auto-generated name for some of the indexes ends up being too long resulting in the following error:
```
{
    "ok": 0,
    "code": 67,
    "errmsg": "namespace name generated from index name is too long",
    "operationTime": {
        "$timestamp": {
            "t": 1690812708,
            "i": 1
        }
    }
}
```

**To Reproduce**

1.  When setting up your Spring Integration configuration, create a channel that is backed by a MongoDbChannelMessageStore.
```
@Bean
public MongoDbChannelMessageStore mongoDbChannelMessageStore(MongoDatabaseFactory databaseFactory)
{
	return new MongoDbChannelMessageStore(databaseFactory);
}

@Bean
public MessageChannel myExampleChannel(MongoDbChannelMessageStore mongoDbChannelMessageStore)
{
	MessageGroupQueue messageGroupQueue = new MessageGroupQueue(mongoDbChannelMessageStore, "myExample");
	return new QueueChannel(messageGroupQueue);
}
```
2.  Turn off auto-index creation.
```
spring.data.mongodb.auto-index-creation=false
```
3.  Start up your Application, then check the indexes on the collection.
```
db.channelMessages.getIndexes();
```
4.  You will see that the indexes have been created.

**Expected behavior**

If we turn off the `spring.data.mongodb.auto-index-creation` property, it should be applied consistently across the project.

**Sample**

Example repository:
https://github.com/sdobberstein/spring-integration-mongodb-issue

**Comment by artembilan** [comment]
Spring integration cannot use those Spring Boot properties, but we really can expose a `createIndex(boolean)` option on those components, which, in the end, can be customized after Spring Boot.

Feel free to contribute such a simple solution: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc !

**Comment by AdamaSorho** [comment]
@artembilan I would like to work on this. I am a first time contributor.

**Comment by artembilan** [comment]
@AdamaSorho ,

Good. Let's start from here, if you can pull the project locally and create a branch for this feature to fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

**Comment by AdamaSorho** [comment]
Hi @artembilan,

I have read, forked the project, and created a local branch for this feature.  
What I understood is we need to expose a `createIndex(boolean)` option which will be used to create the index or not in after `afterPropertiesSet` method.   
  
Since it is my first contribution, I am wondering what the best way to do that is. Could you help me to get started? 

Thank you

**Comment by AdamaSorho** [comment]
Ok thank you!

I have implemented that. Adding a `createIndex` property with `false` value to the `messageStore` bean seems to have no effect to the field `createIndex` in `MongoDbChannelMessageStore`. However, when I add a `createIndex` property with `false` value to the `abstractMessageStore` in `ConfigurableMongoDbMessageStore-CustomConverter.xml` changes the `createIndex` to `false` effectively. Am i missing something?

Is it okay for the `AbstractConfigurableMongoDbMessageStore` to create indexes even the `createIndex` is false? Because, in the actual implementation, it will.

**Comment by artembilan** [comment]
Well, this one has to work:
```
	<beans:bean id="messageStore" parent="abstractMessageStore">
		<beans:constructor-arg name="mappingMongoConverter" ref="customConverter"/>
		<beans:property name="createIndex" value="false"/>
	</beans:bean>
```
if you have a `setCreateIndex(boolean)` on a `MongoDbChannelMessageStore` class.

In that config there is similar to this for priority:
```
	<beans:bean id="priorityMessageStore" parent="abstractMessageStore">
		<beans:property name="priorityEnabled" value="true"/>
	</beans:bean>
```

If course we need to check for that property to be set to `true` (default) before attempting index creation.

Well, I probably can see what is going on. The mentioned `priorityMessageStore` uses same MongDB and same collection. So, indexes might be created by this one, so we probably need to `dropAllIndexes()` before creating an application context in that `testWithCustomConverter()`.

You know, if you have something in hands, feel free to open pull request and we will continue our discussion over there already on code lines.

**Comment by AdamaSorho** [comment]
I created a pull request #8716
