### ISSUE TITLE
Not possible to add handlers for channels requests to DefaultSftpSessionFactory

### ISSUE THREAD

**Issue by allbiin** [spring-projects/spring-integration#8713]
**Expected Behavior**
It should be possible to add handlers for channel requests to DefaultSftpSessionFactory.

**Current Behavior**
It is not possible to add handlers for channels requests to DefaultSftpSessionFactory.

**Context**
See https://stackoverflow.com/questions/76906857/migration-to-spring-boot-3-how-can-i-handle-keepaliveopenssh-com-requests-f

**Comment by artembilan** [comment]
@AdamaSorho ,

you may take a look here, please.

Something like `protected createSftpClient(ClientSession clientSession, SftpVersionSelector initialVersionSelector, SftpErrorDataHandler errorDataHandler)` to let end-user to override.

Thanks
