### ISSUE TITLE
Improve performance of "obtainLock" blocking during "expireUnusedOlderThan" runtime of "RedisLockRegistry"

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-projects/spring-integration#8730]
**In what version(s) of Spring Integration are you seeing this issue?**

6.0.7.RELEASE

**Describe the bug**

When running "expireUnusedOlderThan" on "RedisLockRegistry", too many target lock objects are holding locks for too long.
The "obtain" operation on another thread will have a longer blocking time.

The Redis call is made at "lock.isAcquiredInThisProcess" in the link below, so if RedisLockRegistry has a lot of lock objects, this can take a long time.

https://github.com/spring-projects/spring-integration/blob/863c525790444204f34ec7846002a5512c036d66/spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java#L252

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

To avoid holding a lock for too long, the scopes that hold the lock should be broken up into individual objects.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/50c53e08aacc84f64e9d6266d331e9bc1fa32891
