### ISSUE TITLE
Syntax error in MQTT Java DSL example.

### ISSUE THREAD

**Issue by mikoto2000** [spring-projects/spring-integration#8738]
**In what version(s) of Spring Integration are you seeing this issue?**

commit: 50bf00e6a16d4cdf43ac661cb525050d5531c2be (MQTT document)

**Describe the bug**

MQTT Java DSL example code has syntax error.

Need to remove the semicolon.

https://github.com/spring-projects/spring-integration/blob/50bf00e6a16d4cdf43ac661cb525050d5531c2be/src/reference/antora/modules/ROOT/pages/mqtt.adoc?plain=1#L238-L240

**To Reproduce**

N/A

**Expected behavior**

Build success only copy and paste.

**Sample**

N/A

**Comment by artembilan** [comment]
Confirmed.
Feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc.

We are going to release next Milestone tomorrow, though.

CC: @AdamaSorho 

Thanks
