### ISSUE TITLE
mqtt connection lost and could not reconnect when network is unstable

### ISSUE THREAD

**Issue by timbotetsu** [spring-projects/spring-integration#8739]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.2

**Describe the bug**

mqtt connection lost and could not reconnect when network is unstable and _MqttConnectOptions.setAutomaticReconnect(true)._ continue throwing ```Lost connection; will attempt reconnect on next request``` for two or more connections use same client id that mqtt broker keep kicking out when mqtt broker only accept same client id using **one** connection.

**To Reproduce**

set two breakpoints at [MqttPahoMessageHandler.java#L196](https://github.com/spring-projects/spring-integration/blob/df67c59f8e171fe30135e6057ecbfa8f5b4d9785/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/outbound/MqttPahoMessageHandler.java#L196) and [MqttAsyncClient.java#L1467](https://github.com/eclipse/paho.mqtt.java/blob/f4e0db802a4433645ef011e711646a09ec9fae89/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L1464)

keep application publishing and receiving messages constantly.

kill or kick out mqtt connection for publishing,  MqttAsyncClient will try to reconnect, MqttPahoMessageHandler will try to publish.

MqttPahoMessageHandler will checkConnection before publish message, sometimes [this.client != null && !this.client.isConnected()](https://github.com/spring-projects/spring-integration/blob/df67c59f8e171fe30135e6057ecbfa8f5b4d9785/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/outbound/MqttPahoMessageHandler.java#L196) could be true if MqttAsyncClient is going to **connect** or **connecting**, new connection will be created.

two or more connections use same client id will be kicked randomly for mqtt broker accepts only one incoming connection with one client id, make application in race condition.

**Expected behavior**

new mqtt connection use new client id, or keep only one connection with a different client id for publishing by default?

**Workaround**

we found receiving is stable though setAutomaticReconnect is true or false. so we create a **noReconnect** client factory only for publishing and **it just works**.

```java
@Bean
@Primary
public MqttPahoClientFactory mqttPahoClientFactory() {
    DefaultMqttPahoClientFactory factory = new DefaultMqttPahoClientFactory();

    MqttConnectOptions options = new MqttConnectOptions();
    options.setAutomaticReconnect(true);
    options.setServerURIs(mqttProperties.getServerUrl().split(","));
    options.setUserName(mqttProperties.getUsername());
    options.setPassword(mqttProperties.getPassword().toCharArray());
    factory.setConnectionOptions(options);

    return factory;
}

@Bean
@Qualifier("noReconnectMqttPahoClientFactory")
public MqttPahoClientFactory noReconnectMqttPahoClientFactory() {
    DefaultMqttPahoClientFactory factory = new DefaultMqttPahoClientFactory();

    MqttConnectOptions options = new MqttConnectOptions();
    options.setAutomaticReconnect(false);
    options.setServerURIs(mqttProperties.getServerUrl().split(","));
    options.setUserName(mqttProperties.getUsername());
    options.setPassword(mqttProperties.getPassword().toCharArray());
    factory.setConnectionOptions(options);

    return factory;
}
```

**Comment by artembilan** [comment]
Is there a chance that you can try your solution with a shared client: https://docs.spring.io/spring-integration/reference/mqtt.html#mqtt-shared-client ?

**Comment by timbotetsu** [comment]
ok, I will make an attempt. Please wait for my reply :)

**Comment by timbotetsu** [comment]
> Is there a chance that you can try your solution with a shared client: https://docs.spring.io/spring-integration/reference/mqtt.html#mqtt-shared-client ?

tried, but not work.

It still has a chance to create two connections with same client id. only one client id is different from others allowed.

**Comment by artembilan** [comment]
Ok. Any chances to know how to configure Mosquito broker to accept only one client? So, I will be able to reproduce it in our tests.
Thanks

**Comment by timbotetsu** [comment]
[the mqtt spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028) says a client id have to be unique and the correct behaviour is to kick the oldest one off and replace it with the new one. So I think Mosquitto only accepts same client id with one client by default.

**Comment by artembilan** [comment]
I’m not sure then how that doesn’t work with shared client manager for what we have a plenty of tests.

**Comment by timbotetsu** [comment]
We also curious about why codes do not work in our unstable-network production environment.

After trying lots of methods to reproduce this problem, by holding reconnecting connection, we only can reproduce in dev environment, and find a workaround to solve our problem.

This problem occurs after we upgrade from spring boot 2.7.X and spring integration 5.X.

**Comment by artembilan** [comment]
So, the recommendation is not to use same client id for different connections.
Or you must use different ids for your channel adapters and try to rely on a shared one via `ClientManager`.

I'm not sure what you looking for as a fix on the framework side.
Thanks

**Comment by timbotetsu** [comment]
sorry for our mistake, we found that this is not an issue of spring integration mqtt

we send a packet exceed the size limit of broker, then the broker disconnect the application's connection :(
