### ISSUE TITLE
RemoteFileTemplate needlessly marks session dirty in case of no such file error

### ISSUE THREAD

**Issue by kdebski85** [spring-projects/spring-integration#8745]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.3

**Describe the bug**

The issue applies to all classes which extend `org.springframework.integration.file.remote.RemoteFileTemplate`.  The description below uses `SftpRemoteFileTemplate` from `spring-integration-sftp` as an example.

`RemoteFileTemplate::execute` method marks session dirty in case of any exception.
It prevents session to be reused and makes `CachingSessionFactory` inefficient.
As a result, too many sessions are created and SFTP server may reject new connections.
Certain exceptions, like `SftpConstants.SSH_FX_NO_SUCH_FILE `, should not cause session to be marked dirty.

**To Reproduce**

1. Configure `DefaultSftpSessionFactory` to point to some valid SFTP
2. Wrap the factory with `CachingSessionFactory`
3. Configure `SftpRemoteFileTemplate` to use created `CachingSessionFactory`
4. Use `SftpRemoteFileTemplate::list` method with some path that does not exist on the server

**Expected behavior**

1. SftpRemoteFileTemplate::list throws exception (the current behaviour)
2. Session is not marked dirty and can be reused by further calls (currently it is marked dirty and cannot be reused)

Probably each class that extends `RemoteFileTemplate` should be able to define strategy for differentiating if an exception should mark session dirty.

**Workaround**
Use `SftpRemoteFileTemplate::exists` before each `SftpRemoteFileTemplate::list` (call `list` only when `exists` returns `true`)

**Comment by artembilan** [comment]
I think we can come up with something like `protected boolean shouldMarkSessionAsDirty(Exception ex)` with some default implementations for those `RemoteFileTemplate` extensions (default one should just return `true`).
If there is some peculiar situation where for some exception you must not mark it as dirty, then you will be able to extend `SftpRemoteFileTemplate` and override this method.

Let us know if you are will to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

Thank you!

**Comment by kdebski85** [comment]
@pakorcz thank you for finding the source of the issue!
@artembilan thank you for fixing the issue!
