### ISSUE TITLE
Using Postgres as ChannelMessageStore: use `DELETE ... RETURNING` to make polling a single operation

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-integration#8760]
Performance using Postrges was greatly improved with the fix from #8711.

But looking at our database performance view I think there is still room to improve.
We could use the `DELETE ... RETURNING` clause to make this a single statement operation.
The select and delete statements are still the biggest contributors to wait time for polling.

I'd be happy to contribute a PR for this, but first like to discuss wether you'd accept it.

**Comment by artembilan** [comment]
Sure!
Let's see what we can do with this feature!

I guess we may introduce a new `class PostgresChannelMessageStore extends JdbcChannelMessageStore` and override respective methods.

Here is our contribution guidelines: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc
