### ISSUE TITLE
Documentation suggests that SNAPSHOT is the stable version

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-integration#8774]
When visiting https://docs.spring.io/spring-integration/reference/6.2/index.html, i'm greeted by this banner:

![image](https://github.com/spring-projects/spring-integration/assets/98899556/80124410-d3b0-4eba-a179-5ca2b87b6caf)

While it's true that the RC is not stable yet, it should link to the last stable version, not to the snapshot.

**Comment by garyrussell** [comment]
@mhalbritter I pinged you on Slack - this is a current limitation of the new Antora docs generation.

**Comment by artembilan** [comment]
This is going to be fixed automatically on Antora when we GA in November.
Other new projects on our Antora aggregator are suffering same problem: 
https://docs.spring.io/spring-shell/reference/3.2/index.html
https://docs.spring.io/spring-kafka/reference/3.1/index.html
