### ISSUE TITLE
Error: Problem occurred while synchronizing to local directory

### ISSUE THREAD

**Issue by abufaarooq** [spring-projects/spring-integration#8784]
I've been running into this issue for a while now and need assistance solving it. This error randomly presented itself:

org.springframework.messaging.MessagingException: Problem occurred while synchronizing 'example/of/directory' to local directory; nested exception is org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is org.springframework.integration.util.PoolItemNotAvailableException: Failed to obtain pooled item

**Comment by artembilan** [comment]
This sounds more like a StackOverflow question with much more info.
Also, consider to update to the latest Spring Integration version: https://spring.io/projects/spring-integration#learn

**Comment by artembilan** [comment]
Closed as `Invalid` if favor of respective SO question: https://stackoverflow.com/questions/77397765/spring-integration-sftp
