### ISSUE TITLE
Redis lock is hardly ever unlocked 

### ISSUE THREAD

**Issue by egor-ponomarev** [spring-projects/spring-integration#8795]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.4

**Describe the bug**

We got a regression after updating spring-integration-redis 6.1.2 to 6.1.4, looks like this [change](https://github.com/spring-projects/spring-integration/issues/8730) was the root cause.

We have several instances of a service, each instance has several threads and we have a periodic task, which is launched each X seconds and should be run only in one thread at time (only one thread from all threads provided by all instances, no parallel runs), no matter which one. In other words, we use spring integration redis lock as a distributed lock. 

**To Reproduce**

Simplifying, we have something like this:

```
private ExpirableLockRegistry lockRegistry;

@Scheduled(fixedDelayString = 10 seconds)
public void run() {
lockRegistry.expireUnusedOlderThan(10 seconds);
	var lock = lockRegistry.obtain();
	boolean success = lock.tryLock();
        if (success) {
 		 // do some job
        }
        return;
}
```
As you can see we don't release the lock, and we do it on purpose we don't want the job would be run less frequently than once per 10 seconds

**Expected behavior**

This job should be run each 10 seconds 

**Actual behavior**
The job is run hardly ever (it can be several minutes instead of 10 second)

Because a thread can't release the local lock, localLock#isLocked is always true, as result expireUnusedOlderThan doesn't clean expired locks

**Comment by artembilan** [comment]
See Javadocs:
```

	/**
	 * Remove locks last acquired more than 'age' ago that are not currently locked.
	 * @param age the time since the lock was last obtained.
	 * @throws IllegalStateException if the registry configuration does not support this feature.
	 */
	void expireUnusedOlderThan(long age);
```

your expectations is wrong.
This contract does not unlock locks: it just removes them from a local cache.
Even if it is a distributed lock, it is still guarded by the local `ReentrantLock`. And this one cannot be unlocked by some other thread.

I'm not sure in your business logic, but you need to re-think some other way when you follow a standard `ReentrantLock` contract.

**Comment by egor-ponomarev** [comment]
@artembilan thank you for your feedback! 
But is it wrong to consider a lock expired when it is removed from redis (expired by ttl)?

**Comment by artembilan** [comment]
We don't have a knowledge about that event in a local service.
It is standard approach for distributed locks to start treating lock as broker and assume that other service can obtain it from the store.
The local lock held longer than TTL is treated a broken.
Again: the `expireUnusedOlderThan()` is only for local cache to free some memory, but it is done only against those local locks which are not locked at the moment.
According to the `ReentrantLock` contract the lock cannot be unlocked in the other thread. Therefore the fix you are pointing to.
Even if we would have some contract to check if lock entry is expired in the store, we still would not be able to unlock local `ReentrantLock` in the other thread.

**Comment by egor-ponomarev** [comment]
Thank you for explanation, then I will close this issue
