### ISSUE TITLE
404 when accessing Spring Integration docs

### ISSUE THREAD

**Issue by herder** [spring-projects/spring-integration#8796]
Sorry, I'm not sure that this is the correct place to post an issue, but I couldn't find a better place for it:

One of the top links that comes up in Google when searching for "spring integration" is https://docs.spring.io/spring-integration/docs/current/reference/html/index-single.html , but that link gives a 404.

It seems that the docs have been moved for Spring projects, but I'm wondering if it would be possible to add a redirect to the new place? (https://docs.spring.io/spring-integration/reference/index.html)

**Comment by artembilan** [comment]
This has been fixed now.
