### ISSUE TITLE
`RedisLockRegistry` missing crucial logging messages

### ISSUE THREAD

**Issue by Haarolean** [spring-projects/spring-integration#8803]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.1

**Describe the bug**

Currently, `RedisLockRegistry` logs the moment a lock is release:
```java
if (LOGGER.isDebugEnabled()) {
    LOGGER.debug("Released lock; " + this);
}
```

But there's no such a thing logged for the event of acquiring such a lock. The only way around this would be probably enabling redis queries logging which is not ideal.
I believe understanding _both_ the moments a lock is acquired and release is important for debugging problems, but spring integration doesn't provide such a possibility.
I'd be happy to raise a PR if we find this useful.

**Expected behavior**

Logging the event of acquiring a lock.

**Comment by artembilan** [comment]
Sure thing! Feel free to open pull request and we’ll look next week.
Thank you!

**Comment by artembilan** [comment]
I have scheduled this for the next `6.2.1` and I don't treat this as a bug.
If you issue the PR, then we can consider to back-port it.

Thanks
