### ISSUE TITLE
ERROR: StackOverflow

### ISSUE THREAD

**Issue by LGAKing** [spring-projects/spring-integration#8807]
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

spring-integration-core: 6.0.2

**Describe the bug**

When my flow exceeds 1000 blocks, integration generates an error: stackoverflow. While the issue can be temporarily addressed by configuring -Xss, it is not sustainable to keep increasing -Xss as the number of blocks continues to grow. The computer configuration is as follows:

MacOS:  Ventura 13.1 (22C65)
CPU: Apple M1 Pro
Mem: 32 GB

**Comment by artembilan** [comment]
Why did you close the issue?
Is there anything wrong you have found and fixed on your side?
Any chance to understand how to reproduce it otherwise?
If you even reopen the issue whatsoever...
