### ISSUE TITLE
Problem with `SKIP LOCKED` on MySQL in Spring Integration 6.2.0

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-integration#8818]
**In what version(s) of Spring Integration are you seeing this issue?**

6.2.0

**Describe the bug**

In a fairly simple setup using `MySqlChannelMessageStoreQueryProvider`, I get a locking error from the MySQL 8 database:

```
rg.springframework.dao.CannotAcquireLockException: PreparedStatementCallback; SQL [INSERT into _spring_integration_CHANNEL_MESSAGE(
    MESSAGE_ID,
    GROUP_KEY,
    REGION,
    CREATED_DATE,
    MESSAGE_PRIORITY,
    MESSAGE_BYTES)
values (?, ?, ?, ?, ?, ?)
]; Lock wait timeout exceeded; try restarting transaction
```

**To Reproduce**

1) Start the `docker-compose.yaml` in the root of the linked GitHub repository to start MySQL
2) Run the Spring Boot application.

**Expected behavior**

There should be no lock wait timeout exceeded exception.

**Sample**

See https://github.com/wimdeblauwe/spring-integration-test/tree/main

I also created this SO question: https://stackoverflow.com/questions/77679425/lock-wait-timeout-exceeded-when-trying-to-implement-outbox-pattern-with-spring

The problem seems to be related to the fix done in https://github.com/spring-projects/spring-integration/issues/8711. When reverting back to Spring Boot 3.1.6, the problem goes away. Or removing the `SKIP LOCKED` from the `MySqlChannelMessageStoreQueryProvider` also fixes the problem on Spring Boot 3.2.0. Alternatively, PostgreSQL works fine with the `SKIP LOCKED`.

**Comment by artembilan** [comment]
This is not the problem of Spring Integration, but rather a default `isolation level` on MySQL: https://stackoverflow.com/questions/5836623/getting-lock-wait-timeout-exceeded-try-restarting-transaction-even-though-im.

You may consider to configure your DB for `transaction-isolation = READ-COMMITTED` or do this fix in your code:
```
									.handle(sendEmailMessageHandler, e ->
											e.poller(poller ->
													poller.fixedDelay(1000)
															.transactional(
																	new TransactionInterceptorBuilder()
																			.isolation(Isolation.READ_COMMITTED)
																			.build())))
```

Closing as `Works as Designed`

**Comment by wimdeblauwe** [comment]
Thanks for the info! Should this not be added to the release notes to avoid people upgrading running into this?

**Comment by artembilan** [comment]
Thanks for the pointer!
Added a note into Migration Guide: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-6.1-to-6.2-Migration-Guide#skip-locked-and-mysql

**Comment by wimdeblauwe** [comment]
For anybody else that has this issue: Using the `TransactionInterceptorBuilder` inline like in the given proposal changes the retry behaviour compared to how it worked before. You need to turn it into a `@Bean` to have the same behaviour as with Spring Integration 6.1. Not sure if this is a bug or not, but my test that tested if retries happen correctly started failing when I did this (using Spring Integration 6.2.0):

```
.handle(sendEmailMessageHandler, e ->
  e.poller(poller ->
    poller.fixedDelay(1000)
      .transactional(
	new TransactionInterceptorBuilder()
		.isolation(Isolation.READ_COMMITTED)
	.build())))
```

If I did this, my test was ok again:

```
  ...
  .handle(sendEmailMessageHandler, e ->
  e.poller(poller ->
    poller.fixedDelay(1000)
      .transactional(transactionInterceptor)))
  }

  @Bean
  public TransactionInterceptor transactionInterceptor() {
    return new TransactionInterceptorBuilder()
        .isolation(Isolation.READ_COMMITTED)
        .build();
  }
```

**Comment by artembilan** [comment]
Correct, the logic there is like this:
```
	public PollerSpec transactional() {
		TransactionInterceptor transactionInterceptor = new TransactionInterceptorBuilder().build();
		this.componentsToRegister.put(transactionInterceptor, null);
		return transactional(transactionInterceptor);
	}
```
So, we create an internal instance and schedule it to be registered as a bean.
That is really what required.
When you call:
```
	public PollerSpec transactional(TransactionInterceptor transactionInterceptor) {
		return advice(transactionInterceptor);
	}
```
There is no way to know if this provided instance is a bean or not. Therefore if you don't provide a `TransactionManager`, that interceptor has to be registered as a bean manually to be able to determine `TransactionManager` from the application context.

**Comment by wimdeblauwe** [comment]
ok, thanks for confirming. Don't know if this should be added to the note in the migration guide? Because somebody just copy/pasting the code from there will not have a properly working system.

**Comment by artembilan** [comment]
Edited my example adding `.transactionManager(transactionManager)` to the `TransactionInterceptorBuilder` definition.
I don't believe it even worked before. Might be just a side-effect that there was no `SKIP LOCKED` in version `6.1.x`...
