### ISSUE TITLE
ClientWebSocketContainer prevents application context from start, when websocket connection is not yet available

### ISSUE THREAD

**Issue by dwirtz** [spring-projects/spring-integration#8835]
**In what version(s) of Spring Integration are you seeing this issue?**

* Spring Boot Version: 3.1.6
* Spring Integration Websocket Version: 6.1.5

**Describe the bug**

I am using a spring integration flow to connect an application via a websocket to another one (called **websocket server**, for simplicity). Usually the **websocket server** must not be available when the application starts its flow. 

- Due to a change within the spring-integration-websocket library from version **6.1.4** to **6.1.5** (see [Error handling in WebSocketInboundChannelAdapter start() method](https://github.com/spring-projects/spring-integration/issues/8785) ) the above requirement is not fulfilled anymore. This is because the *ClientWebSocketContainer* throws an exception on start which makes the application startup fail ( [see DefaultLifecycleProcessor](https://github.com/spring-projects/spring-framework/blob/232225b2aab29910f62d7d6a441cdb0af4269177/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java#L284) ). 

Honestly, I am not sure whether this is a bug because the fix within Issue 8785 at least makes sense to me. Nevertheless how should that actually work? How can I use that library to connect to a **websocket server** application which might not be available at the time my application starts? Of course, I could delegate the connection handling into my application, but this is not what I am expecting from a library. Connection handling done by other spring-integration libraries like **spring-integration-amqp** seem to handle this differently.

**To Reproduce**

. Provide a `ClientWebSocketContainer` as a bean on startup
.. use `autoStartup=true` (which is the default)
. Provide a `WebSocketInboundChannelAdapter` as a bean on startup by using ClientWebSocketContainer
. Define an integrationflow using the `WebSocketInboundChannelAdapter`
. Start the application

**Expected behavior**

When I start the application I want the application to startup successfully even if the **websocket server** is not yet available. This seems not be possible or not well supported by the library. 

**Sample**

[Reproducible Sample](https://github.com/dwirtz/spring-integration-websocket-startup-example)

**Comment by artembilan** [comment]
I think there is nothing we can do since we don't control in the library when that connection from the server is available.
Therefore you might need to think about doing `autoStartup=false` and then use a Control Bus to start it manually when you are sure that connection is there.
Or... You can wrap `adapter.start()` into a retry pattern to handle such a connection error.

I'm not sure what you mean about AMQP because the logic there in the `SimpleMessageListenerContainer` is similar to what we have here for WebSockets:
```
	private void waitForConsumersToStart(Set<AsyncMessageProcessingConsumer> processors) {
		for (AsyncMessageProcessingConsumer processor : processors) {
			FatalListenerStartupException startupException = null;
			try {
				startupException = processor.getStartupException();
			}
			catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				throw RabbitExceptionTranslator.convertRabbitAccessException(e);
			}
			if (startupException != null) {
				throw new AmqpIllegalStateException("Fatal exception on listener startup", startupException);
			}
		}
	}
```

What is your idea how Spring Integration would handle this situation for you?

**Comment by dwirtz** [comment]
Thank you for you're answer. 

I was just wondering why the spring-integration-amqp behaves differently at runtime. Analysing the startup routine from that library gave me the following information:

- the startupException is not even set, when the autostart triggers
- the startup routine (AsyncMessageProcessingConsumer.run()) is scheduled via [taskexecutor ](https://github.com/spring-projects/spring-amqp/blob/main/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java#L560) and is rerun by the library itself (at least as long as the startup fails)
- I am experiencing an `AmqpIOException` which **does not** set the startupException. Those the spring-integration-amqp library does handle connection problems differently in the way, that
  - it repeats the starting routine
  - it **does not** interpret a connection error as a startup failure
  - it does **only** interpret startup failures as fatal errors (and connection problems do not belong to that kind of errors)

see [Connection Problems Handling at startup](https://github.com/spring-projects/spring-amqp/blob/main/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java#L1332)

```
catch (AmqpIOException e) {
  if (e.getCause() instanceof IOException && e.getCause().getCause() instanceof ShutdownSignalException
						&& e.getCause().getCause().getMessage().contains("in exclusive use")) {
    getExclusiveConsumerExceptionLogger().log(logger, "Exclusive consumer failure", e.getCause().getCause());
    publishConsumerFailedEvent("Consumer raised exception, attempting restart", false, e);
}
else {
    logConsumerException(e);
}
}
```

Regarding my expectations:
- I would expect that if a system/communication endpoint is not yet available on startup that the library handles the reconnection mechanism for me, so I i do not have to apply boilerplate code by myself
- Maybe the point is: problems are differentiated and handled differently. connection problems as describes above leads to a reconnecting routine which is done by the library itself. The latter one is what I expect for this library too. Any chance for that?

**Comment by artembilan** [comment]
OK. I see what you mean about Spring AMQP. When we catch an exception after `mainLoop();` and it is not fatal we go to:
```
killOrRestart(aborted);
```
where that `aborted` is `false`.
There is not such a logic in the `WebSocketClient` which is used from the `ClientWebSocketContainer` in Spring Integration.

To be consistent and realign logic with client libraries I would suggest you to transfer this issue into Spring Framework where that `WebSocketClient` is implemented.
It is really not Spring Integration AMQP module logic to restart consumer for possible connection failure.
Therefore it feels logical to do a reconnect in the `WebSocketClient` implementation instead of this `ClientWebSocketContainer` in Spring Integration.

Does that make sense?

**Comment by dwirtz** [comment]
Actually yes, now it makes sense to me. I didn't see that the `SimpleMessageListenerContainer` is part of the _spring-rabbit_ library of the springframework. I implicitly thought that it belongs to the `spring-integration-websocket` library (because of the naming _container_ ). My fault.
So I further read the `spring-websocket` code to be able to follow you're idea. As far as I can see there is the [ConnectionManagerSupport](https://github.com/spring-projects/spring-framework/blob/main/spring-websocket/src/main/java/org/springframework/web/socket/client/ConnectionManagerSupport.java) which declars the connection handling for websocket connections but does not tell anything about errorhandling. There are several implementations at least one within the `spring-integration-websocket` library. Nevertheless the intention where the error handling must be done is not documented by the `spring-websocket` developers. 

Regarding consistency of connection handling i fully agree with you that this should be done by spring framework. Thank you for the discussion. I am going to close that issue and will transfer the topic to `spring-websocket`.
