### ISSUE TITLE
"Dispatcher has no subscribers for channel "controlBusChannel""

### ISSUE THREAD

**Issue by cwichlei** [spring-projects/spring-integration#8970]
**In what version(s) of Spring Integration are you seeing this issue?**
6.2.1

**Describe the bug**
Integrationtesting a control bus configuration produces the error "Dispatcher has no subscribers for channel "controlBusChannel"" when using @ContextConfiguration(classes = ControlBusConfiguration.class)
When @ContextConfiguration is removed, the UnicastingDispatcher and ServiceActivator are linked correctly.

**To Reproduce**

1. Create class ControlBusConfiguration

```java
@Configuration
public class ControlBusConfiguration {

    @Bean
    public IntegrationFlow controlBusFlow() {
        return IntegrationFlow.from(controlBusChannel())
            .controlBus()
            .get();
    }

    @Bean(name = "controlBusChannel")
    public MessageChannel controlBusChannel(){
        return new DirectChannel();
    }
}
``` 

2. Create test class ControlBusConfigurationIT
```java
@SpringBootTest
@ContextConfiguration(classes = ControlBusConfiguration.class)
public class ControlBusConfigurationIT {

    @Autowired
    public MessageChannel controlBusChannel;

    @Autowired
    public ConfigurableApplicationContext applicationContext;

    @Test
    public void test() {
        controlBusChannel.send(MessageBuilder.withPayload("startup()").build());
    }
}
``` 

**Expected behavior**
UnicastingDispatcher and ServiceActivator are linked although @ContextConfiguration is used.

**Sample**
https://github.com/cwichlei/control-bus-test

**Comment by artembilan** [comment]
When you do `@ContextConfiguration(classes = ControlBusConfiguration.class)`, you are limited the scope for the Spring Boot.
The Spring Boot comes with many auto-configurations including `IntegrationAutoConfiguration` which brings us the `@EnableIntegration`.
The last one provides an infrastructure to parse those `IntegrationFlow` definitions and wire everything together.

So, you need to determine for yourself: you want to have normal full infrastructure, or just test your `ControlBusConfiguration`?
Either way, according to your code, the `@EnableIntegration` has to be there this or other way.

Closed as `Works as Designed`.
