### ISSUE TITLE
Search feature in Spring Integration docs not working

### ISSUE THREAD

**Issue by erwinetchart** [spring-projects/spring-integration#8985]
Hi all, 

Well, not really much to describe here, i found that the search in spring integration documentation doesn't work, at least for some days (3 or more).

![image](https://github.com/spring-projects/spring-integration/assets/8241652/d01827ed-672a-4f7c-9592-e8d77622d1a1)

Tested in Firefox and Chrome in linux versions.

Regards.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/1d906b86df842824d5a8159294efc128c4da78a8
