### ISSUE TITLE
Consider renaming (or rewriting) `KotlinSplitterSpec.function` to make the project compilable with Kotlin K2

### ISSUE THREAD

**Issue by KvanTTT** [spring-projects/spring-integration#9028]
https://github.com/spring-projects/spring-integration/blob/34f901f7dba3b8fd5bd9e0d9379f3e23db06be33/spring-integration-core/src/main/kotlin/org/springframework/integration/dsl/KotlinSplitterSpec.kt#L36

**Expected Behavior**

The project is compiled succesfully if switch Kotlin to some new K2 version (for instance, `2.0.0-Beta4`).

**Current Behavior**

Compilation fails with the following error:

```
spring-integration/spring-integration-core/src/main/kotlin/org/springframework/integration/dsl/KotlinSplitterSpec.kt:36:3 : Inline function 'fun <reified P> function(crossinline function:
 (P) -> Any): Unit' cannot be recursive
```

**Context**

It looks like the function callee resolving is incorrect in case of using inheritance, Java, type parameters and SAM. See https://youtrack.jetbrains.com/issue/KT-66663 for detail.

**Comment by artembilan** [comment]
Was fixed via: https://github.com/spring-projects/spring-integration/commit/3849d6adde634972c56322387441a969f3c47fba
