### ISSUE TITLE
.m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: 已断开连接

### ISSUE THREAD

**Issue by Marblog** [spring-projects/spring-integration#9029]
**In what version(s) of Spring Integration are you seeing this issue?**

6.0.2

**Describe the bug**
When I use this method
 **mqttOutboundChannel.send(message);**

The consle '2024-03-18T17:33:19.822+08:00 ERROR 23144 --- [Rec: testClient] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: 已断开连接'
and also did not catch any exceptions

**Comment by Marblog** [comment]
Thank you for your reply，My expected functionality is that I receive a message from my subscriber，I parse the topic，Then the server is given a topic reply by default, with unlimited content, proving that I have received the message.So how do I send a message on a topic?Thank you very much！

Here is my configuration code

`@Configuration
public class MqttIntegrationConfig {
    @Bean
    public MqttPahoMessageDrivenChannelAdapter inbound() {
        MqttPahoMessageDrivenChannelAdapter adapter =
                new MqttPahoMessageDrivenChannelAdapter("tcp://127.0.0.1:1883", "testClient", "wdzn/#");
        adapter.setCompletionTimeout(5000);
        adapter.setConverter(new DefaultPahoMessageConverter());
        adapter.setQos(1);
        adapter.setOutputChannel(mqttInputChannel());
        return adapter;
    }

    @Bean
    public MessageChannel mqttInputChannel() {
        return new DirectChannel();
    }

    @Bean
    public MessageChannel mqttOutputChannel() {
        return new DirectChannel();
    }

    @Bean
    public MqttPahoClientFactory mqttClientFactory() {
        DefaultMqttPahoClientFactory factory = new DefaultMqttPahoClientFactory();
        MqttConnectOptions options = new MqttConnectOptions();
        options.setServerURIs(new String[]{"tcp://127.0.0.1:1883"});
        factory.setConnectionOptions(options);
        return factory;
    }

    @Bean
    @ServiceActivator(inputChannel = "mqttOutputChannel")
    public MessageHandler mqttOutbound() {
        MqttPahoMessageHandler messageHandler =
                new MqttPahoMessageHandler("testClient", mqttClientFactory());
        messageHandler.setAsync(true);
        messageHandler.setDefaultTopic("wdzn/#");
        return messageHandler;
    }
    @Bean
    @ServiceActivator(inputChannel = "mqttInputChannel")
    public MessageHandler handler() {
        return message -> {
            String payload = message.getPayload().toString();
            //Parse and send messages
        };
    }
}`

**Comment by artembilan** [comment]
What you are taking about is a request-reply pattern which is not implemented in Spring Integration MQTT module yet. More over it won’t be for MQTT v3 at all. You can try a combination of channel adapter pairs on request or and responder sides: https://www.emqx.com/en/blog/mqtt5-request-response

**Comment by Marblog** [comment]
> What you are taking about is a request-reply pattern which is not implemented in Spring Integration MQTT module yet. More over it won’t be for MQTT v3 at all. You can try a combination of channel adapter pairs on request or and responder sides: https://www.emqx.com/en/blog/mqtt5-request-response

Thank you for your guidance
