### ISSUE TITLE
spring integration lock is not working after upgrading to 6.2.x from 5.5.x

### ISSUE THREAD

**Issue by YiyiSmile** [spring-projects/spring-integration#9050]
**In what version(s) of Spring Integration are you seeing this issue?**

6.2.3

**Describe the bug**

We use the spring integration distribution lock feature on our DB2 database. The lock table is created on DB2. Previously it was working well with spring boot 2.7.x and spring integration 5.5.x. But lately we upgrade springboot from 2.7.x to 3.x, the spring integration also got upgraded to 6.2.x, then when we run our application, we notice this issue - the update to the lock table is failed with 'bad SQL GRAMMER' error. Dig further,w e can see the log shows 'Invalida data conversion: Parameter instance instance 2024-03-25T07:43:xxxx is invalid for the requested conversion. ERRORCODE = -4461, SQLSTATE = 42851.

We digged the issue a bit, and found that the issue has nothing to do with spring-integration-core, but caused by spring-integration-jdbc. Because when we change our pom file, keep spring-integration-core at version 6.2.x, only downgrade spring-integration-jdbc to previous 5.5.x version, the issue was gone.

**To Reproduce**

The reproduce step is quite straightforward, prepare the DB2 environment, create the lock table, then write a springboot application with version 3.x to call the lock-obtaining method, then the issue will occur.

**Expected behavior**

Obtain the lock successfully.

**Sample**

**Comment by artembilan** [comment]
Can we see the whole stack trace for the error?
It feels like DB2 driver does not support conversion from the `LocalDateTime` into `TIMESTAMP`: https://stackoverflow.com/questions/60467668/persist-a-localdatetime-into-a-db2-timestamp-column.

Apparently we need to convert it back to the `java.sql.Timestamp`.

Will be fixed shortly...

**Comment by artembilan** [comment]
Have just pushed the fix.
Any chances that you can test it against `6.2.4-SNAPSHOT`?
Thanks
