### ISSUE TITLE
PostgresChannelMessageTableSubscriber not properly handling Database Failover

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-integration#9061]
**In what version(s) of Spring Integration are you seeing this issue?**

6.x

**Describe the bug**

When the database is doing a failover the `PostgresChannelMessageTableSubscriber` doesn't notice and will never receive new notifications.
For example on AWS RDS instance with multi-AZ standby, when performing a failover the IP address for the DNS does change. But `PostgresChannelMessageTableSubscriber` never re-establishes a connection, nor has some other measurement in place to validate that the connection is still valid.

**To Reproduce**

Perform a DB failover. After this no more messages will be processed.

**Expected behavior**

Eventually the `PostgresChannelMessageTableSubscriber` obtains a new connection after failover, and message processing will work again.

**Sample**

Sorry, not being able to provide a complete sample, as this involves infrastructure 🤷‍♂️

**Comment by joshiste** [comment]
I'd also be happy to contribute a PR for this. 

I would propose to use a [configurable timeout for retrieving PGNotifications instead of waiting forever](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java#L196) and when the received list is empty to re-new the connection

**Comment by joshiste** [comment]
P.S. I also think it's a pity that the `PostgresChannelMessageTableSubscriber` is a final class. If it either would be an interface or non-final, It would be a lot easier for users to get rid of the faulty behavior...

**Comment by artembilan** [comment]
Thank you for looking into this!
I'm not sure how would an interface for the `PostgresChannelMessageTableSubscriber` help since this class has a lot of specific logic.

Will look into your PR shortly.
