### ISSUE TITLE
PostgresSubscribableChannel notifyUpdate() handles all messages in a single executor's thread

### ISSUE THREAD

**Issue by pchurzin** [spring-projects/spring-integration#9102]
**Expected Behavior**

PostgresSubscribableChannel::notifyUpdate should submit a task for every message instead of single task for all messages.

**Current Behavior**
spring-integration-jdbc:6.2.0

At the moment [PostgresSubscribableChannel::notifyUpdate](https://github.com/spring-projects/spring-integration/blob/aa6de8248c501134544874dce3a85b933d05c24d/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresSubscribableChannel.java#L179) submit a task which polls for all messages.

**Context**

Consider a running application. Every message sent to the channel produce a notification which in turn results notifyUpdate to submit a task. 
But after the application restart, if there are messages in the channel backed by PostgresSubsribableChannel, notifyUpdate called only once since there are no new notifications and all the messages are processed by a single thread in the provided executor.
Such a behaviour results in a slow message handling.

Maybe I don't understand why it was implemented like this? Thanks in advance.

**Comment by artembilan** [comment]
That deliberately was done for a single thread handling for simplicity and to preserve an order messages are put into DB.
The "slow message handling" is out of this channel implementation scope. That sounds more like a logic of your application.
If an order is not important for you you can opt out to use a `bridge` and subsequent `ExecutorChannel` where you will be able to control how process those messages in parallel.

**Comment by pchurzin** [comment]
Ok, I see. Thank you!
