### ISSUE TITLE
Unexpected warn logs when using spring-integration in combination with webmvc

### ISSUE THREAD

**Issue by epantke** [spring-projects/spring-integration#9103]
**In what version(s) of Spring Integration are you seeing this issue?**
6.2.4

**Describe the bug**

When using spring-integration in combination with the xml elements from the webmvc xml namespace `mvc:resources` or `mvc:annotation-driven` the following warnings are shown: 
```
26-Apr-2024 14:24:48.960 WARNING [RMI TCP Connection(2)-127.0.0.1] org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization Bean '(inner bean)#597faa00' of type [org.springframework.web.servlet.resource.ResourceUrlProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [integrationRequestMappingHandlerMapping]? Check the corresponding BeanPostProcessor declaration and its dependencies.
26-Apr-2024 14:24:48.965 WARNING [RMI TCP Connection(2)-127.0.0.1] org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization Bean '(inner bean)#218f313c' of type [org.springframework.web.servlet.resource.ResourceUrlProviderExposingInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [integrationRequestMappingHandlerMapping]? Check the corresponding BeanPostProcessor declaration and its dependencies.
26-Apr-2024 14:24:49.086 WARNING [RMI TCP Connection(2)-127.0.0.1] org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization Bean '(inner bean)#1ef73af4' of type [org.springframework.web.servlet.handler.ConversionServiceExposingInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [integrationRequestMappingHandlerMapping]? Check the corresponding BeanPostProcessor declaration and its dependencies.
```

When using only one of the elements only a subset of these warning appear. With `mvc:resources` the warning for the `ResourceUrlProvider` and `ResourceUrlProviderExposingInterceptor` are logged. With `mvc:annotation-driven` the warning for the `ConversionServiceExposingInterceptor` is shown.

The spring framework (6.1.6) documentation states that having dependencies in BPPs is not recommended and might cause issues.
> If you have beans wired into your BeanPostProcessor by using autowiring or @Resource (which may
> fall back to autowiring), Spring might access unexpected beans when searching for type-matching
> dependency candidates and, therefore, make them ineligible for auto-proxying or other kinds of
> bean post-processing
> [Spring Framework Docs](https://docs.spring.io/spring-framework/reference/core/beans/factory-extension.html#beans-factory-extension-bpp)

These log messages pollute the logs in any application using spring-integration this way; making it harder to identify the warnings that concern the application code and the beans defined within.

**To Reproduce**

* Build the sample project in the attached zip.
* Deploy the war in a matching web server (we used Tomcat 10.1.20)
* Observe the warnings in the logs.
[warn-minimal-example.zip](https://github.com/spring-projects/spring-integration/files/15130855/warn-minimal-example.zip)

**Expected behavior**

When using spring-integration in combination with spring-webmvc, no warnings are produced by the dependencies included.

**Sample**

[warn-minimal-example.zip](https://github.com/spring-projects/spring-integration/files/15130855/warn-minimal-example.zip)

**Comment by artembilan** [comment]
Thank you for the report.
I simply was able to reproduce it with our `IntegrationGraphControllerTests`.
It emits warning similar to yours:
```
2024-04-26 12:11:07,434 WARN [main] [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean '(inner bean)#39f5b723' of type [org.springframework.web.servlet.handler.ConversionServiceExposingInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [integrationRequestMappingHandlerMapping]? Check the corresponding BeanPostProcessor declaration and its dependencies.
```
Because I indeed have there the mentioned `<mvc:annotation-driven />`.

Will investigate the reason and come up with the fix.

**Comment by artembilan** [comment]
The problem happens in the `IntegrationRequestMappingHandlerMapping.setApplicationContext()`.
It uses its `initApplicationContext(context);` which does:
```
	protected void detectMappedInterceptors(List<HandlerInterceptor> mappedInterceptors) {
		mappedInterceptors.addAll(BeanFactoryUtils.beansOfTypeIncludingAncestors(
				obtainApplicationContext(), MappedInterceptor.class, true, false).values());
	}
```

And since this `IntegrationRequestMappingHandlerMapping` is a `DestructionAwareBeanPostProcessor`, it is created and initialized earlier for bean post-processing phase.
That one pulls those `MappedInterceptor` populated by the MVC XML configuration.
And that's exactly where it is not OK, because those beans are populated into an application context too early.

I think as a fix I'll extract that `DestructionAwareBeanPostProcessor` logic into separate component, so it won't affect the `HandlerMapping` initialization logic.
