### ISSUE TITLE
Inconsistent behaviour between listing and downloading the files.

### ISSUE THREAD

**Issue by SimoneGiusso** [spring-projects/spring-integration#9123]
**In what version(s) of Spring Integration are you seeing this issue?**

6.2.4

**Describe the bug**

`/` at the beginning of the remote dir path is not necessary when listing files although it is necessary to download them

**To Reproduce**

```kotlin
    @Test
    fun testFileDownload() {
        sftpTemplate.list("remote-dir").forEach { // All the files under remote-dir are listed
            log.info { it.filename }
        }

        log.info { "---- FINISHED TO LIST DIRECTORIES -----\n\n\n\n" }

        sftpTemplate.get("/remote-dir/MyFile.csv") { // remote-dir/MyFile.csv won't work
            inputStream -> inputStream.use {
                localDir.mkdir()
                FileUtils.copyInputStreamToFile(inputStream, File(localDir.absolutePath + "test.csv"))
        }}
    }
```

**Expected behavior**

`sftpTemplate.get` should work also with `"remote-dir/MyFile.csv"` as input.

See also [stackOverflow question](https://stackoverflow.com/questions/78437303/error-while-downloading-with-sftpinboundfilesynchronizingmessagesource-spring-co/78437695#78437695).

**Comment by artembilan** [comment]
For `LIST` command we do this:
```
		remoteDir =
				!remoteDir.isEmpty() && remoteDir.charAt(0) == '/'
						? remoteDir
						: this.sftpClient.canonicalPath(remoteDir);
```
For `GET` - do not:
```
	public InputStream readRaw(String source) throws IOException {
		return this.sftpClient.read(source);
	}
```

So, maybe this is a problem and we can try to normalize path if it does not start with `/`?

**Comment by SimoneGiusso** [comment]
Yes, both commands should threat the dirPath in the same way.

Here probably the GET should normalize the path as the LIST command does.

I found unexpected the fact that one command without "/" does not work while it works for the other.

**Comment by SimoneGiusso** [comment]
Additionally, in the message's header `file_remoteDirectory`, two `'/'` are present before the remote repository name

**Comment by artembilan** [comment]
@SimoneGiusso , do you mean for the `SftpOutboundGateway` with a `Command.GET` ?
Or what part of the flow you are talking about which produces the `Message` for you?

**Comment by artembilan** [comment]
The canonical path has been fixed.
I need more info about:

> two `/` are present before the remote repository name

Thanks

**Comment by SimoneGiusso** [comment]
> The canonical path has been fixed. I need more info about:
> 
> > two `/` are present before the remote repository name
> 
> Thanks

If you enable the logging level to debug, you should see that `file_remoteDirectory` header for the message emitted contains the remote_repository path and two `/`.

Example: 

`//my_remote_repository` instead of just `/my_remote_repository`

**Comment by SimoneGiusso** [comment]
> > The canonical path has been fixed. I need more info about:
> > > two `/` are present before the remote repository name
> > 
> > 
> > Thanks
> 
> If you enable the logging level to debug, you should see that `file_remoteDirectory` header for the message emitted contains the remote_repository path and two `/`.
> 
> Example:
> 
> `//my_remote_repository` instead of just `/my_remote_repository`

But's this is a minor problem.

**Comment by artembilan** [comment]
Sure! But what I have to run to follow such a debug procedure ?

**Comment by SimoneGiusso** [comment]
> Sure! But what I have to run to follow such a debug procedure ?

If you run my demo in the other opened issue with this config in the `application-test.yaml` file:

```yaml
logging:
  level:
    org.springframework.integration.*: debug
```

You should see logged something similar to

`2024-05-08T13:33:19.407+02:00 DEBUG 35630 --- [   scheduling-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'bean 'sftpChannel'', message: GenericMessage [payload=/tmp/extractions/MyFile1_data.csv, headers={file_remoteHostPort=localhost:2222, file_name=85819-VALUATIONPRICE_Equities-ValuationPrice_20240507T050000+0200_data.csv, file_remoteDirectory=//deliveries, file_originalFile=/tmp/extractions/MyFile1_data.csv, id=7d1b4bd1-9452-c652-403d-6c607498e5c6, file_relativePath=MyFile1_data.csv, file_remoteFile=MyFile1_data.csv, timestamp=1715167999402}] `

As you'll `file_remoteDirectory` value has two '`/`'

**Comment by artembilan** [comment]
Thanks, @SimoneGiusso .
Unfortunately, from GitHub it is not obvious that we may talk about the same sample.
So, would be great to point there properly.
Here it is anyway: https://github.com/spring-projects/spring-integration/issues/9124#issuecomment-2099292877

**Comment by SimoneGiusso** [comment]
> Thanks, @SimoneGiusso .
> 
> Unfortunately, from GitHub it is not obvious that we may talk about the same sample.
> 
> So, would be great to point there properly.
> 
> Here it is anyway: https://github.com/spring-projects/spring-integration/issues/9124#issuecomment-2099292877

Yes it is this one. Thanks

**Comment by artembilan** [comment]
Right. When I change my test for this `.remoteDirectory("/sftpSource")`, I indeed se double `/` in the `file_remoteDirectory` header.
Will fix shortly: https://github.com/spring-projects/spring-integration/issues/9129
