### ISSUE TITLE
ErrorMessages are mangled by observed message channels

### ISSUE THREAD

**Issue by SkylerArnold-Corista** [spring-projects/spring-integration#9198]
**In what version(s) of Spring Integration are you seeing this issue?**

6.3.0

**Describe the bug**

When [micrometer observation](https://docs.spring.io/spring-integration/reference/metrics.html#micrometer-observation) is enabled for a MessageChannel that's being used for error handling, the `ErrorMessage`s that are sent through the channel are silently converted into `MutableMessage`s, and the `originalMessage` is lost.

From [the example repo](https://github.com/SkylerArnold-Corista/observation-clobbers-error-message) linked below:
```java
    @Bean
    public IntegrationFlow integrationFlow() {
        return IntegrationFlow.fromSupplier(() -> new GenericMessage<>(UUID.randomUUID().toString()), c -> c.poller(p -> p
                        .fixedDelay(3000)
                        .errorChannel("errorChannel")  // THE PROBLEMATIC BIT
                        .taskExecutor(exampleTaskExecutor())
                ))
                .handle(m -> {
                    throw new RuntimeException();
                })
                .get();
    }
```
If I set up a service activator to handle the `ErrorMessage`s published to `errorChannel`, it can't actually receive ErrorMessages and instead it only gets `MutableMessage<Throwable>`s.

This is an issue in my real project because my error handling logic needs access to the original message (from `ErrorMessage::getOriginalMessage`), which isn't possible if the message gets converted into a MutableMessage.

I've done a bit of digging and it seems this is happening in [AbstractMessageChannel::sendWithObservation](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-core/src/main/java/org/springframework/integration/channel/AbstractMessageChannel.java#L337) and [MutableMessage::of](https://github.com/spring-projects/spring-integration/blob/main/spring-integration-core/src/main/java/org/springframework/integration/support/MutableMessage.java#L132). I assume this is an issue any time you send a non-mutable message type through an observed channel & expect it to come out the other side as the same type, not just for my usecase.

**Workaround**

This is similar to [this issue](https://github.com/spring-cloud/spring-cloud-sleuth/issues/761) that was raised in the Sleuth project a while ago. Unfortunately, [the recommended workaround](https://stackoverflow.com/a/46979119) for that situation doesn't work here, because the interceptors are applied to the message after it's already been converted to a `MutableMessage`. I also tried to use a custom `ErrorMessageStrategy` to wrap the `ErrorMessage` in a `MutableMessage` before it gets sent from the `MessagePublishingErrorHandler`, but sadly the `ErrorMessageStrategy` can only return `ErrorMessage` types, so that didn't work. 

Instead, I'm currently just disabling observation for my error handling channel all together, which has the unfortunate effect of causing the traceId of the logs for the error handling code not to line up with the traceId of the rest of the IntegrationFlow.

**Sample**

[Here's a small example](https://github.com/SkylerArnold-Corista/observation-clobbers-error-message) that reproduces the problem. If you run the project you'll see a lot of ugly stack traces, instead of the expected `Error from [...]` logs that should be happening. If you uncomment the [!errorChannel](https://github.com/SkylerArnold-Corista/observation-clobbers-error-message) observation pattern, the problem goes away.

**Comment by artembilan** [comment]
Yeah... I see the problem: didn't think about tracing on error channels.
Will fix it shortly.
As a workaround I can suggest only an extension of the `ErrorMessage` where you would put `originalMessage` into headers.
This way, even if it is swwapped to the `MutableMessage` in the tracing channel, that info is still going to be available in the respective custom header.
