### ISSUE TITLE
SMB outbound gateway doesn't seem to support the GET command

### ISSUE THREAD

**Issue by smitsjelle** [spring-projects/spring-integration#9211]
Spring integration version used: 6.2.1 (also tested on 6.2.5)

When configuring a SMB outbound gateway through XML configuration with a 'get' command, and point the 'expression' field to the name of the file I with to retrieve, I receive an IOException: `[path] is not a directory. Cannot list resources`

Upon some further investigation, it appears that [AbstractRemoteFileOutboundGateway#get](https://github.com/spring-projects/spring-integration/blob/27b194f537261ddf7e2cf2f90ebf26b274cc0f2b/spring-integration-file/src/main/java/org/springframework/integration/file/remote/gateway/AbstractRemoteFileOutboundGateway.java#L1101), that is invoked for get commands will execute a list action against the (Smb)Session. The list action is supposed to return a single file. If so, it is copied to the local directory, otherwise an error is thrown. In contrast with the [SftpSession#list](https://github.com/spring-projects/spring-integration/blob/27b194f537261ddf7e2cf2f90ebf26b274cc0f2b/spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/SftpSession.java#L104), the [SmbSession#list](https://github.com/spring-projects/spring-integration/blob/27b194f537261ddf7e2cf2f90ebf26b274cc0f2b/spring-integration-smb/src/main/java/org/springframework/integration/smb/session/SmbSession.java#L135) will always throw an example if a list is attempted on a non-directory SMB file. 

It seems that the SmbSession should also have logic in place that will list the directory instead, and filter files based on the path provided, just like the SftpSession has? When using SFTP instead of SMB, a similar setup as presented below works.

**To Reproduce**
Configure a SMB share that hosts a simple 'smbtest.txt' file in the 'test' folder.

Run the XML below (with the proper directory) and see that.

```
<int:inbound-channel-adapter channel="trigger" expression="'trigger'">
	<int:poller fixed-delay="10" time-unit="SECONDS"/>
</int:inbound-channel-adapter>

<int:channel id="trigger"/>

<smb:outbound-gateway session-factory="smbSessionFactory" 
	request-channel="trigger" 
	reply-channel="nullChannel"
	remote-directory="/" 
	auto-create-directory="true"
	command="get" 
	expression="'smbtest.txt'"
	local-directory="tmp/" 
	auto-create-local-directory="true"/>
	
<bean id="smbSessionFactory" class="org.springframework.integration.smb.session.SmbSessionFactory">
	<property name="host" value="localhost"/>
	<property name="domain" value=""/>
	<property name="username" value="username"/>
	<property name="password" value="password"/>
	<property name="shareAndDir" value="test"/>
</bean>
```

**Expected behavior**
The file is created in the auto-created 'tmp' local directory.

**Comment by artembilan** [comment]
We just didn't have a respective test for plain `GET`. The one with `.options(AbstractRemoteFileOutboundGateway.Option.STREAM)` goes different path.
Fixed and will be released June 18.

Thank you for the report!

**Comment by smitsjelle** [comment]
Hi, thank you for the quick reply and fix. 

I have applied the fix and the problem using the SMB outbound gateway has indeed been resolved, but I now run into the issue that the behavior of the inbound channel adapter is also changed. 

Previously, the setup described in the sample config below worked perfectly, giving me the files in my `somedir/anotherdir` directory. With the applied changes this 'list' operation is considered to be a get single file operation, and will fail with `IOException: [somedir/anotherdir] is not a file`. As a workaround, it seems that it is possible to provide 'remote-directory' as `somedir\anotherdir`, as that bypasses line 137 that checks for the occurence of the `/`, and the SMB calls seem to become normalized (as I am now effectively calling the path `(...)/test/somedir\anotherdir/`).

Is this intended behavior, where the remote directory may not contain multiple directories, and 'share and dir' of the SessionFactory **must** point to the parent of the desired directory? That seems to be in contrast with e.g. SFTP or file inbound gateways, where the 'remote directory' field can contain multiple directories. 

Sample config:
```
<smb:inbound-channel-adapter 
    session-factory="smbSessionFactory" 
    local-directory="/tmp/smb"
    auto-create-local-directory="true"
    channel="smbInbound" 
    remote-directory="somedir/anotherdir"> <!-- Used to work pre-6.2.6, now needs to be 'somedir\anotherdir' to achieve the same -->
        <si:poller fixed-rate="10" time-unit="SECONDS"/>
</smb:inbound-channel-adapter>

<si:channel id="smbInbound"/>
(...)
<bean id="smbSessionFactory" class="org.springframework.integration.smb.session.SmbSessionFactory">
	<property name="host" value="localhost"/>
	<property name="domain" value=""/>
	<property name="username" value="username"/>
	<property name="password" value="password"/>
	<property name="shareAndDir" value="test"/>
</bean>
```

**Comment by artembilan** [comment]
@smitsjelle ,

Thank you for feedback.
Please, raise a new issue.
Apparently this might even not work for SFTP as well.
Looks like an algorithm for `LIST` command was designed after FTP protocol.
We might need to come with something else for other protocols or revise whatever we do in the `SmbSession.list()` (and maybe `SftpSession.list()`)

**Comment by artembilan** [comment]
Taking that back.
Looks like it works for SFTP:
```
		IntegrationFlow flow = IntegrationFlow
				.from(Sftp.inboundAdapter(sessionFactory())
								.preserveTimestamp(true)
								.remoteDirectory("/sftpSource/subSftpSource")
								.regexFilter(".*\\.txt$")
								.localFilenameExpression("#this.toUpperCase() + '.a'")
								.localDirectory(getTargetLocalDirectory())
								.remoteComparator(Comparator.comparing(SftpClient.DirEntry::getFilename)),
						e -> e.id("sftpInboundAdapter").poller(Pollers.fixedDelay(100)))
				.channel(out)
				.get();
```
And my test fails as expected:
```
Expected :" SFTPSOURCE1.TXT.a"
Actual   :"SUBSFTPSOURCE1.TXT.a"
```

Anyway we need a new issue for new milestone(s).
Thanks
