### ISSUE TITLE
ZeroMQ: ZeroMQMessageHandler with bind capability

### ISSUE THREAD

**Issue by alessiomatricardi** [spring-projects/spring-integration#9228]
**Expected Behavior**

The expected behaviour is that the ZeroMqMessageHandler could bind a port when the other part (a ZeroMqMessageProducer or whatever out of Spring world) connects to that port.

**Current Behavior**

As for now, the ZeroMqMessageHandler can only connect to a specific URL, while [no binding is allowed](https://github.com/spring-projects/spring-integration/blob/afb87d45e82cd6ad3ea02a87758701310b08e473/spring-integration-zeromq/src/main/java/org/springframework/integration/zeromq/outbound/ZeroMqMessageHandler.java#L53).

**Context**

As per ZeroMQ philosophy, binding or connecting to a socket is completely decoupled from sender/receiver abstraction.

My question is: Is there any reason behind the current limitation? Something I'm missing out?
If you agree, I could make a PR to add this functionality

**Comment by artembilan** [comment]
Well, we even mention that in the doc: https://docs.spring.io/spring-integration/reference/zeromq.html#zeromq-outbound-channel-adapter.

I cannot recall why, but I believe it is just because the `ZeroMqMessageHandler` is passive and does its stuff only when we send a message into this handler.
Therefore it feels a bit awkward to make this component as a server side.
The workaround is very easy if intention is exactly to have a server in the producer application:
```
private String socketAddress = "inproc://messageHandler.test";

@Bean
ZContext context() {
	return new ZContext();
}

@Bean
ZMQ.Socket mySocket(ZContext context) {
	ZMQ.Socket socket = context.createSocket(SocketType.PAIR);
	socket.bind(this.socketAddress);
        return socket;
}

@Bean
ZeroMqMessageHandler myMessageHandler(ZContext context) {
     return new ZeroMqMessageHandler(context, this.socketAddress);
} 
```

Sorry, the `SocketType.PAIR` is in-memory, but you got a gist.

**Comment by alessiomatricardi** [comment]
Yes, I read the docs and also got your point.

My point is that if we provide the instruments for binding of the message producer (inbound) we could provide this capability also on outbound.

A classical scenario could be this one:
My application has a publisher which publish on port 9090 => it will bind `tcp://*:9090`.

Over the network, there are many subscribers (eterogeneus for programming language and/or ZMQ library) who connect on `tcp://publisher_ip:9090` and wait for messages.

My application send messages over a MessageChannel, and are automatically redirect to the ZMQ.Socket bound by the publisher.

As for now, this approach is not applicable. Let me know if I’m avoiding some details or crucial points.

**Comment by artembilan** [comment]
Ok. If that is the use-case which requires such a convenience, then let’s do that! Consider to implement that logic in the `Lifecylce.start()`. However this also could be done only for the current `6.4`. As we have a reasonable workaround .
