### ISSUE TITLE
Refactor to Eliminate Repetitive Mock Object Creation in TcpMessageMapperTests.java

### ISSUE THREAD

**Issue by gzhao9** [spring-projects/spring-integration#9271]
Hi there!

While working with the `TcpMessageMapperTests` class, I noticed two mock variables repeatedly created across various tests. To simplify the code, I propose a small refactor to eliminate these redundancies, which could reduce the code by 41 lines.

1. **Repetitive Mock TcpConnection Creation**: The creation of a mock `TcpConnection` object repeated in 7 test cases.

2. **Repetitive Mock Socket Creation**: The creation of a mock `Socket` object repeated in 3 test cases.

Specifically, here is the refactoring method I propose:

Creating a mock for `TcpConnection` currently looks like this:

```java
TcpConnection connection = mock(TcpConnection.class);
//other code...
when(connection.getPayload()).thenReturn(TEST_PAYLOAD.getBytes());
when(connection.getHostName()).thenReturn("MyHost");
when(connection.getHostAddress()).thenReturn("1.1.1.1");
when(connection.getPort()).thenReturn(1234);
```

I introduced a method, `CreatMockTcpConnection`:

```java
public TcpConnection CreatMockTcpConnection(Object bytes, String hostName, String ipAdress, int port){
    TcpConnection connection = mock(TcpConnection.class);
    when(connection.getPayload()).thenReturn(bytes);
    when(connection.getHostName()).thenReturn(hostName);
    when(connection.getHostAddress()).thenReturn(ipAdress);
    when(connection.getPort()).thenReturn(port);
    return connection;
}
```

With this method, creating a mock `TcpConnection` becomes:

```java
TcpConnection connection = CreatMockTcpConnection(map, "someHost", "1.1.1.1", 1234);
```

Similarly, for `Socket`, I introduced a method, `creatMockSocket` as follows:

```java
public Socket creatMockSocket(InetAddress local){
    Socket socket = mock(Socket.class);
    when(socket.getLocalAddress()).thenReturn(local);
    return socket;
}
```

This allows us to create mocks on one line as well：

```java
Socket socket = creatMockSocket(local);
```

I created a draft of the PR, you can see the details file changes  [here](https://github.com/gzhao9/spring-integration/pull/1/files).

---

The refactor reduced the test cases by 41 lines of code, and I believe these changes will improve code readability.

**Comment by artembilan** [comment]
Thank you for looking into that!
Please, consider to raise a PR and we will review it shortly: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

**Comment by gzhao9** [comment]
> Thank you for looking into that! Please, consider to raise a PR and we will review it shortly: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

@artembilan Thank you very much for your prompt reply. I have submitted PR #9277. If there are any modifications needed, please feel free to let me know in the PR.
