### ISSUE TITLE
DefaultSftpSessionFactory  Session.close ssh tcpconnection still open

### ISSUE THREAD

**Issue by hellojiange** [spring-projects/spring-integration#9281]
DefaultSftpSessionFactory factory = new DefaultSftpSessionFactory(false);
        factory.setHost(host);
        factory.setPort(port);
        factory.setUser(userName);
        factory.setPassword(password);
        factory.setAllowUnknownKeys(true);

        Session session =factory.getSession();
        Thread.sleep(10000);
        session.close();

session.close() ，but ssh tcp connetion still established,how i can close the ssh tcp connection

**Comment by artembilan** [comment]
Duplication of https://github.com/spring-projects/spring-integration/issues/9272
