### ISSUE TITLE
Refactor to Eliminate Repetitive Mock Object Creation(more exmple with #9271)

### ISSUE THREAD

**Issue by gzhao9** [spring-projects/spring-integration#9283]
Hi there!

This PR essentially does the same thing as issue #9271, I also have already created PR #9282 You can look directly at the PR if you are interested.

I found another two mock variables repeatedly created across various tests. To simplify the code, I propose a small refactor to eliminate these redundancies, which could reduce the code by 76 lines.

1. **Repetitive Mock AbstractClientConnectionFactory Creation**: The creation of a mock `AbstractClientConnectionFactory` object repeated in 8 test cases.

2. **Repetitive Mock BeanFactory Creation**: The creation of a mock `BeanFactory` object repeated in 10 test cases.

Specifically, here is the refactoring method I propose:

With the example from `testOkAgainAfterCompleteFailure`, Creating a mock for `AbstractClientConnectionFactory` currently looks like this:

```java
AbstractClientConnectionFactory factory1 = mock(AbstractClientConnectionFactory.class);
AbstractClientConnectionFactory factory2 = mock(AbstractClientConnectionFactory.class);
List<AbstractClientConnectionFactory> factories = new ArrayList<>();
factories.add(factory1);
factories.add(factory2);
TcpConnectionSupport mockConn1 = makeMockConnection();
TcpConnectionSupport mockConn2 = makeMockConnection();
when(factory1.getConnection()).thenReturn(mockConn1);
when(factory2.getConnection()).thenReturn(mockConn2);
when(factory1.isActive()).thenReturn(true);
when(factory2.isActive()).thenReturn(true);
```

I introduced a method, `makeMockactory`:

```java
public static AbstractClientConnectionFactory makeMockactory(TcpConnectionSupport mockConn) throws Exception {
        AbstractClientConnectionFactory factory = mock(AbstractClientConnectionFactory.class);
        when(factory.getConnection()).thenReturn(mockConn);
        when(factory.isActive()).thenReturn(true);
        return factory;
}
```

With this method, creating a mock `AbstractClientConnectionFactory` becomes:

```java
AbstractClientConnectionFactory factory1 = makeMockactory(conn1);
AbstractClientConnectionFactory factory2 = makeMockactory(conn2);
```

Similarly, for `BeanFactory`, I introduced a method, `createMockBeanFactory` as follows:

```java
public static BeanFactory createMockBeanFactory(ThreadPoolTaskScheduler scheduler) {
        BeanFactory beanFactory = mock(BeanFactory.class);
        when(beanFactory.containsBean(IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)).thenReturn(true);
        when(beanFactory.getBean(IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME, TaskScheduler.class))
                        .thenReturn(scheduler);
        return beanFactory;
}
```

This allows us to create mocks on one line：

```java
BeanFactory beanFactory = createMockBeanFactory(scheduler);
```

I created the PR, you can see the details of file changes from PR #9282 .

---

The refactor reduced the test cases by 76 lines of code, and I believe these changes will improve code readability.

**Comment by artembilan** [comment]
@gzhao9 ,

thank you for looking into this!

Please, consider in the future to not create an issue if you have a PR in hands.
From GitHub perspective they are essentially the same and we always can assign milestone directly to PR.

Closed in favor of PR #9282
