### ISSUE TITLE
Broken documentation link for version 5.5.20

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-integration#9346]
On https://spring.io/projects/spring-integration#learn the link for 5.5.20 points to https://docs.spring.io/spring-integration/docs/5.5.20/reference/html/, which returns 404 Not Found.

**Comment by artembilan** [comment]
Has been fixed.
Thank you for the report!
For reference this is what happened in that version: https://github.com/spring-projects/spring-integration/commit/89791c63a9a0864f91f01deb1c9bd91bffbaa6d4
