### ISSUE TITLE
Allow configuring SFTP max packet size

### ISSUE THREAD

**Issue by gbaso** [spring-projects/spring-integration#9380]
**Expected Behavior**

Provide a property on the `DefaultSftpSessionFactory` that allows to configure the max packet size:

```java
DefaultSftpSessionFactory factory = new DefaultSftpSessionFactory()
factory.setMaxPacketSize(maxPacketSize);
```

**Current Behavior**

Max packet size is not configurable via `DefaultSftpSessionFactory`. It defaults to 32KB according to `org.apache.sshd.core.CoreModuleProperties#DEFAULT_MAX_PACKET_SIZE`. To change it, you must create your own SshClient and update the property:

```java
SshClient sshClient = SshClient.setUpDefaultClient();
PropertyResolverUtils.updateProperty(sshClient, "packet-size", <value>);
```

however this prevents the `DefaultSftpSessionFactory` to initialize the client via `doInitInnerClient()`, therefore the `ServerKeyVerifier`, `PasswordIdentityProvider`, `KeyIdentityProvider` and `UserInteraction` must also be configured on the client instead of relying on the cleaner API from the `DefaultSftpSessionFactory`.

**Context**

I need to change the max packet size in order to reduce the amount of remote calls for more data in my `Sftp.inboundStreamingAdapter` integration flow, due to complaints from our SFTP server maintainer. Alternatively, we could reduce the rate at which we read from the remote `InputStream`, but that would slow down and add complexity to the integration flow

**Comment by artembilan** [comment]
Well, that's exactly why we have introduced that ctor:
```
	/**
	 * Instantiate based on the provided {@link SshClient}, e.g. some extension for HTTP/SOCKS.
	 * @param sshClient the {@link SshClient} instance.
	 * @param isSharedSession true if the session is to be shared.
	 */
	public DefaultSftpSessionFactory(SshClient sshClient, boolean isSharedSession) {
```
So, you can provide any custom `SshClient`.

However I see you pain for the `ServerKeyVerifier`, `PasswordIdentityProvider`, `KeyIdentityProvider` and `UserInteraction`.
I think we will go ahead and introduce something like:
```
setSshClientConfigurer(Consumer<SshClient> sshClientConfigurer)
```
So, you can continue to use that default internal behavior, but will be able to customize it with required properties  or so.
New feature for the current in-progress `6.4` version.
For those previous versions a workaround via mentioned ctor should be enough.

Thanks
