### ISSUE TITLE
Provide first-class configuration support for SpEL `IndexAccessor`

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-integration#9436]
## Overview

As mentioned in https://github.com/spring-projects/spring-integration/pull/9429#issuecomment-2322883447, Spring Integration currently provides first-class support for registering a `PropertyAccessor` but not yet for an `IndexAccessor` (new SpEL API introduced in Spring Framework 6.2).

For example, one can currently register a `PropertyAccessor` for use with Spring Integration via the following.

1. `IntegrationEvaluationContextFactoryBean` and `IntegrationSimpleEvaluationContextFactoryBean`
2. the `<spel-property-accessors>` XML namespace element
3. a `SpelPropertyAccessorRegistrar` bean in the `ApplicationContext`.

However, there is currently no easy way for Spring Integration users to register an `IndexAccessor` (either a custom one of their own or the `JsonIndexAccessor` proposed in #9429).

Thus, the Spring Integration team should decide if it wants to provide similar configuration support for registering an `IndexAccessor`:

- via `AbstractEvaluationContextFactoryBean` and its subclasses
- via an XML namespace element
- via an auto-detected bean in the `ApplicationContext` -- `SpelPropertyAccessorRegistrar` or a separate `SpelIndexAccessorRegistrar`

## Side Note

`IntegrationSimpleEvaluationContextFactoryBean` is not currently documented in the reference manual. If that warrants documentation, a new issue can be created to address that.

## Related Issues

- #9383
- #9429

**Comment by artembilan** [comment]
Hi @sbrannen !
FYI: https://github.com/spring-projects/spring-integration/pull/9451
Thanks
