### ISSUE TITLE
Spring Integration Smb upload fails to create missing remote directory when running on Windows

### ISSUE THREAD

**Issue by pfosser** [spring-projects/spring-integration#9453]
https://github.com/spring-projects/spring-integration/blob/775bfd6168925c8fee94a22deec11ca84926550e/spring-integration-smb/src/main/java/org/springframework/integration/smb/session/SmbSession.java#L341

Hi, the method linked above checks the remote path (which is a smb path) for `FILE_SEPARATOR` which is initialized as
```
private static final String FILE_SEPARATOR = FileSystems.getDefault().getSeparator();
```
Clearly on Windows that is "\\" which is never found in a smb path. So the need to create possibly missing remote dirs is never detected.

**Comment by artembilan** [comment]
Yeah... 
I don't see a reason in that `FILE_SEPARATOR` constant at all.
We really deal with remote SMB paths over there, so, the separator is supposed to be that simple `/`.

Feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc!
