### ISSUE TITLE
Flagging of messages should be optional.

### ISSUE THREAD

**Issue by alexandru-mng** [spring-projects/spring-integration#9613]
**Expected Behavior**
Flagging of messages should be optional similar with [SearchTermStrategy](https://docs.spring.io/spring-integration/reference/mail.html#search-term)

It would be ideal to simply bypass the [default behaviour](https://docs.spring.io/spring-integration/reference/mail.html#imap-seen) when a custom SearchTermStrategy is used.

**Current Behavior**
Messages are always flagged when the email server does not support \Recent or user flags even when that flag is not used when searching for new new messages.

***How has this issue affected you?***
Microsoft Exchange does not support \Recent or user flags, thus ImapMailReceiver always flags the read messages. 
![Screenshot from 2024-10-29 22-14-28](https://github.com/user-attachments/assets/46892817-b255-4500-bee8-6aa94cb1b8c3)

***Are you aware of any workarounds?***
I am not sure if this even works, but it may be a workaround.
https://stackoverflow.com/questions/62214324/java-mail-listner-this-email-server-does-not-support-recent-or-user-flags

***What other alternatives have you considered?***
Override ImapMailReceiver.setAdditionalFlags in order to remove the 'FLAGGED' flag, but this is not a viable solution because it may remove a "real" Follow-up flag.

**Comment by artembilan** [comment]
@alexandru-mng ,

if you see what can be done from the framework perspective, feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc.

I'm not sure yet what is going on, but will be happy to review PR.

Thanks

**Comment by artembilan** [comment]
Please, find the fix in the linked commit.

Thank you for the report anyway!
