### ISSUE TITLE
SFTP: Failed to transfer file if temporary remote directory doesn't exist

### ISSUE THREAD

**Issue by sottaviani2** [spring-projects/spring-integration#9684]
5.5.20

**Describe the bug**
I use SftpMessageHandler to send files to a remote SFTP server.
I want to transfer files using a temporary remote directory. Transfer is aborted if the temporary remote doesn't exist, otherwise it works fine.

**To Reproduce**
Transfer file test.txt to /remote setting /remote_temp as temporary directory. /remote_temp doesn't exist on target server

**Expected behavior**
If /remote_temp doesn't exist on remote server and autoCreateDirectory is true, the file is sent to /remote and /remote_temp is created to store the file before moving to final destination.

**Sample**
    SftpMessageHandler handler = new SftpMessageHandler(sftpSessionFactory) ;
     handler.setRemoteDirectoryExpressionString("headers['remoteDirectory']");
     handler.setTemporaryRemoteDirectoryExpressionString("headers['remoteTempDirectory']");
     handler.setAutoCreateDirectory(true);

**Comment by artembilan** [comment]
That version is out of support for a while. Any chances to check your solution with much newer one: https://spring.io/projects/spring-integration#learn ?

**Comment by sottaviani2** [comment]
> That version is out of support for a while. Any chances to check your solution with much newer one: https://spring.io/projects/spring-integration#learn ?

I think 6.4.0 has the same problem. I check source code and find out that the bug is in org.springframework.integration.file.remote.RemoteFileTemplate on method sendFileToRemoteDirectory
It tries to create only remoteDirectory. I suppose that you must check for existence of the temporary directory 
and create it.

**Comment by artembilan** [comment]
Ok. I’m out for vacation until next week. So, if you have some idea how to fix, feel free to open PR and I’ll look shortly when I’m back .
Thank you!

**Comment by artembilan** [comment]
Essentially, the `RemoteFileTemplate` is missing to create that temporary directory here:
```
		String remoteDirectory = normalizeDirectoryPath(remoteDirectoryArg);
		String temporaryRemoteDirectory = normalizeDirectoryPath(temporaryRemoteDirectoryArg);

		String remoteFilePath = remoteDirectory + fileName;
		String tempRemoteFilePath = temporaryRemoteDirectory + fileName;
		// write remote file first with temporary file extension if enabled

		String tempFilePath = tempRemoteFilePath + (this.useTemporaryFileName ? this.temporaryFileSuffix : "");

		if (this.autoCreateDirectory) {
			try {
				RemoteFileUtils.makeDirectories(remoteDirectory, session, this.remoteFileSeparator, this.logger);
			}
			catch (@SuppressWarnings("unused") IllegalStateException e) {
				// Revert to old FTP behavior if recursive mkdir fails, for backwards compatibility
				session.mkdir(remoteDirectory);
			}
		}
```

**Comment by sottaviani2** [comment]
Correct. I used this code as a workaround for my project
`RemoteFileUtils.makeDirectories(temporaryRemoteDirectory, session, this.remoteFileSeparator, this.logger);`
only when temporaryRemoteDirectory is specifed
